### ISSUE TITLE
Socket Closed with remote peer error with Android POST _changes

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/couchbase-lite-android#1010]
This is possibly due to a bug in Android. We are not sure yet. @pasin and I have been pair debugging this issue. Tracking ticket - https://github.com/couchbase/couchbase-lite-ios/issues/1447

**Comment by sethrosetter** [comment]
This seems to be related to POST _changes

This succeeds 
```
## Request
curl -X "GET" "http://192.168.59.101:5984/ls_db2/_changes?feed=normal&heartbeat=300000&style=all_docs&active_only=true&since=0" \
     -H "Content-Type: application/json; charset=utf-8" \
     -d "{\"active_only\":true,\"feed\":\"normal\",\"style\":\"all_docs\",\"heartbeat\":300000,\"since\":0}"
```

where 192.168.59.101:5984 is the running Android LiteServ. This does not. 

This fails
```
## Request
curl -X "POST" "http://192.168.59.101:5984/ls_db2/_changes?feed=normal&heartbeat=300000&style=all_docs&active_only=true&since=0" \
     -H "Content-Type: application/json; charset=utf-8" \
     -d "{\"active_only\":true,\"feed\":\"normal\",\"style\":\"all_docs\",\"heartbeat\":300000,\"since\":0}"
```

with `Socket Closed with remote peer`

**Comment by sethrosetter** [comment]
Using Android (1.3.1-30)

**Comment by hideki** [comment]
Hi @sethrosetter,
Issue could be same with https://github.com/couchbase/couchbase-lite-android/issues/989 . Fix is already in master.
Don't you mind to retest with [`1.3.1-52`](http://files.couchbase.com/maven2/com/couchbase/lite/couchbase-lite-android/1.3.1-52/) ?
Thanks!

**Comment by sethrosetter** [comment]
I am still hitting the issue with `1.3.1-32`

**Comment by hideki** [comment]
@sethrosetter Thank you for your update.

Dod this issue block you? If so, we can put higher priority.

**Comment by hideki** [comment]
Note to self: 
- It seems REST API handler does not meet the recent POST /_changes API changes.

**Comment by sethrosetter** [comment]
It is causing test failures but besides that is non blocking.
