### ISSUE TITLE
html <img> tag could not access attachment directly 

### ISSUE THREAD

**Issue by tjayesh** [couchbase/couchbase-lite-android#1015]
Hi,

I am working on a hybrid HTML android application.
I am trying to display image using HTML **img** tag by passing following urls.

**http://localhost:5984/db_name/doc_id/file_name.jpg** 
This returns "406 (Not Acceptable)"

**http://127.0.0.1:5984/db_name/doc_id/file_name.jpg**
 This  returns "404 (Not Found)"

However, Ajax GET request for **http://localhost:5984/db_name/doc_id/file_name.jpg** returns blob.

Also, similar URL workes well in iOS;
**http://lite.couchbase./db_name/doc_id/file_name.jpg**

Please, suggest me a correct way of accessing image attachments from CBL by directly passing URL to HTML image tag. 

-Thanks

**Comment by jamiltz** [comment]
Application development questions are preferably asked on the forum https://forums.couchbase.com/c/mobile. Could you create a new thread there with what you provided here and also the name of the hybrid framework so we can try it too. I'll close this issue for now. Thanks

**Comment by jamiltz** [comment]
Discussed at https://github.com/couchbase/couchbase-lite-java-core/issues/1474
