### ISSUE TITLE
Where is com.couchbase.lite:couchbase-lite-android:1.1.0-17??

### ISSUE THREAD

**Issue by breakline87** [couchbase/couchbase-lite-android#1021]
Hi,

there is a mention of "com.couchbase.lite:couchbase-lite-android:1.1.0-17" in the doc/tutorial on github.

But this version is not in the couchbase maven repo:

http://files.couchbase.com/maven2/com/couchbase/lite/couchbase-lite-android/

But then mvrepository has it:

https://mvnrepository.com/artifact/com.couchbase.lite/couchbase-lite-android/1.1.0-17

Where can I get this particular version? I have some legacy code I just inherited, but the build fails because of this missing version. I'm not familiar with Couchbase enough to just upgrade it because I dont know if its backward compatible.

**Comment by hideki** [comment]
Hi @breakline87,

Any android builds with x.x.x-<build number> are kind of developer build which is not production build. Recommend to use `1.3.1` which is latest production build.

Thanks!

**Comment by hideki** [comment]
Hi @breakline87,
Where did you see the version number `1.1.0-17`?

**Comment by breakline87** [comment]
Thanks for the quick reply. On this page this version is explicitly mentioned:

https://github.com/couchbase/couchbase-lite-android/releases

I'm working on a code done by another developer. Can I update couchbase without problems to the current version or are there issues with compatibility?

**Comment by hideki** [comment]
> I'm working on a code done by another developer. Can I update couchbase without problems to the current version or are there issues with compatibility?

If application uses only public API, migration should be smooth.

**Comment by hideki** [comment]
I will close this ticket.
