### ISSUE TITLE
Wrong winning revision when try to delete document

### ISSUE THREAD

**Issue by mtrakal** [couchbase/couchbase-lite-android#1035]
Tested on `1.3.1` and `1.3.1-89`

- have old app with CBL 1.3.1
- upgrade to our new app (with 1.3.1-89)
- after upgrade app all records was updated (added envelopeId to record)
- try to delete object created in old app with 1.3.1 (I tried to uninstall new app and install new app again with replication from server, for exclude upgrade CBL process, same result)

Tested with CBL SQLite and CBL Forest, both have same result. Not deleted object.

`com.couchbase.lite.store > SQLiteStore > winningRevIDOfDocNumericID` returns wrong revID.

`com.couchbase.lite.store > SQLiteStore > winner`

```
docNumericID = 1056
oldWinningRevID = "6-8c6f538b0517a7b7d75e246e3e596c4d"
oldWinnerWasDeletion = false
newRev = {RevisionInternal@8111} "{-Category_bf1c14ad-d6a5-4457-9609-ff91d0e973c0 #7-d33410b6da60ee83a49e5feae726ff58 @1726 DEL}"
newRevID = "7-d33410b6da60ee83a49e5feae726ff58"
outIsDeleted = {AtomicBoolean@8135} "false"
```

returning revision is: `revID = "5-0274f5bcd70851e493292992e2167459"`

But, it's older than current revision. And 2 version back than version which should win!
What happens:

Current revision: 
`{"seq":1408,"id":"-Category_bf1c14ad-d6a5-4457-9609-ff91d0e973c0","changes":[{"rev":"6-8c6f538b0517a7b7d75e246e3e596c4d"}],"doc":{"_id":"-Category_bf1c14ad-d6a5-4457-9609-ff91d0e973c0","_rev":"6-8c6f538b0517a7b7d75e246e3e596c4d","reservedCreatedAt":"2016-11-01T10:27:25.589Z","icon":49,"reservedModelType":"Category","position":12000,"reservedOwnerId":"76544ded-2920-471d-9713-364711cb2f94","reservedSource":"android","envelopeId":3002,"color":"#AD1457","customCategory":true,"name":"Domácnost, služby","defaultType":1,"reservedUpdatedAt":"2016-11-01T10:31:36.433Z"}},`

new revision how should looks like, what I expect:
`{"seq":1729,"id":"-Category_bf1c14ad-d6a5-4457-9609-ff91d0e973c0","changes":[{"rev":"7-d33410b6da60ee83a49e5feae726ff58"}],"deleted":true,"doc":{"_id":"-Category_bf1c14ad-d6a5-4457-9609-ff91d0e973c0","_rev":"7-d33410b6da60ee83a49e5feae726ff58","reservedCreatedAt":"2016-11-01T10:27:25.589Z","icon":49,"reservedModelType":"Category","position":12000,"reservedOwnerId":"76544ded-2920-471d-9713-364711cb2f94","reservedSource":"android","envelopeId":3002,"color":"#AD1457","customCategory":true,"name":"Domácnost, služby","defaultType":1,"reservedUpdatedAt":"2016-11-01T11:20:22.433Z","_deleted":true}}`

What I really get:
`{"seq":1729,"id":"-Category_bf1c14ad-d6a5-4457-9609-ff91d0e973c0","changes":[{"rev":"5-0274f5bcd70851e493292992e2167459"}],"doc":{"_id":"-Category_bf1c14ad-d6a5-4457-9609-ff91d0e973c0","_rev":"5-0274f5bcd70851e493292992e2167459","reservedCreatedAt":"2016-11-01T10:27:25.589Z","icon":49,"enabled":true,"reservedModelType":"Category","position":12000,"reservedOwnerId":"76544ded-2920-471d-9713-364711cb2f94","reservedSource":"android","color":"#AD1457","name":"Domácnost, služby","defaultType":1,"reservedUpdatedAt":"2016-11-01T10:27:56.443Z"}}`

How you can look, winning revision is older than previous current (current is revision 6, with some date, new winning is older and with revision 5)

----------
```
public synchronized boolean delete(String id) {
        Document doc = getDatabase().getDocument(id);
        try {
            doc.update(new Document.DocumentUpdater() {
                @Override
                public boolean update(UnsavedRevision newRevision) {
                    newRevision.setIsDeletion(true);
                    Map<String, Object> properties = newRevision.getUserProperties();
                    properties.put("deletedAt", DateTime.now(DateTimeZone.UTC).toString());
                    newRevision.setUserProperties(properties);
                    return true;
                }
            });
        } catch (CouchbaseLiteException e) {
...
        }
        return true;
    }
```
From `doc.update` > 
- com.couchbase.lite/couchbase-lite-java-core/1.3.1-89/f3934ba1c881792b808a269713bceeca70d09fdf/couchbase-lite-java-core-1.3.1-89-sources.jar!/com/couchbase/lite/Document.java:380

- com.couchbase.lite/couchbase-lite-java-core/1.3.1-89/f3934ba1c881792b808a269713bceeca70d09fdf/couchbase-lite-java-core-1.3.1-89-sources.jar!/com/couchbase/lite/UnsavedRevision.java:118
```

```
- com.couchbase.lite/couchbase-lite-java-core/1.3.1-89/f3934ba1c881792b808a269713bceeca70d09fdf/couchbase-lite-java-core-1.3.1-89-sources.jar!/com/couchbase/lite/Document.java:525
```
properties = {HashMap@7333}  size = 16
 0 = {HashMap$HashMapEntry@7344} "reservedCreatedAt" -> "2016-11-01T10:27:25.600Z"
 1 = {HashMap$HashMapEntry@7345} "_rev" -> "6-edea31ae699bc6553c0846d19816198d"
 2 = {HashMap$HashMapEntry@7346} "icon" -> "70"
 3 = {HashMap$HashMapEntry@7347} "deletedAt" -> "2016-11-01T13:55:47.204Z"
 4 = {HashMap$HashMapEntry@7348} "reservedModelType" -> "Category"
 5 = {HashMap$HashMapEntry@7349} "position" -> "18000"
 6 = {HashMap$HashMapEntry@7350} "reservedOwnerId" -> "76544ded-2920-471d-9713-364711cb2f94"
 7 = {HashMap$HashMapEntry@7351} "reservedSource" -> "android"
 8 = {HashMap$HashMapEntry@7352} "envelopeId" -> "11000"
 9 = {HashMap$HashMapEntry@7353} "color" -> "#64dd17"
 10 = {HashMap$HashMapEntry@7354} "customCategory" -> "true"
 11 = {HashMap$HashMapEntry@7355} "name" -> "Ostatní"
 12 = {HashMap$HashMapEntry@7356} "defaultType" -> "1"
 13 = {HashMap$HashMapEntry@7357} "_deleted" -> "true"
 14 = {HashMap$HashMapEntry@7358} "_id" -> "-Category_472621e1-6753-4bbd-af5d-136caef1e0bf"
 15 = {HashMap$HashMapEntry@7359} "reservedUpdatedAt" -> "2016-11-01T10:31:36.463Z"
prevID = "6-edea31ae699bc6553c0846d19816198d"
allowConflict = false
hasTrueDeletedProperty = true
deleted = true
rev = {RevisionInternal@7335} "{-Category_472621e1-6753-4bbd-af5d-136caef1e0bf #null @0 DEL}"
```
- com.couchbase.lite/couchbase-lite-java-core/1.3.1-89/f3934ba1c881792b808a269713bceeca70d09fdf/couchbase-lite-java-core-1.3.1-89-sources.jar!/com/couchbase/lite/Database.java:1913

- com.couchbase.lite/couchbase-lite-java-core/1.3.1-89/f3934ba1c881792b808a269713bceeca70d09fdf/couchbase-lite-java-core-1.3.1-89-sources.jar!/com/couchbase/lite/Database.java:1975
```
docID = "-Category_472621e1-6753-4bbd-af5d-136caef1e0bf"
properties = {HashMap@7385}  size = 16
 0 = {HashMap$HashMapEntry@7396} "reservedCreatedAt" -> "2016-11-01T10:27:25.600Z"
 1 = {HashMap$HashMapEntry@7397} "_rev" -> "6-edea31ae699bc6553c0846d19816198d"
 2 = {HashMap$HashMapEntry@7398} "icon" -> "70"
 3 = {HashMap$HashMapEntry@7399} "deletedAt" -> "2016-11-01T13:55:47.204Z"
 4 = {HashMap$HashMapEntry@7400} "reservedModelType" -> "Category"
 5 = {HashMap$HashMapEntry@7401} "position" -> "18000"
 6 = {HashMap$HashMapEntry@7402} "reservedOwnerId" -> "76544ded-2920-471d-9713-364711cb2f94"
 7 = {HashMap$HashMapEntry@7403} "reservedSource" -> "android"
 8 = {HashMap$HashMapEntry@7404} "envelopeId" -> "11000"
 9 = {HashMap$HashMapEntry@7405} "color" -> "#64dd17"
 10 = {HashMap$HashMapEntry@7406} "customCategory" -> "true"
 11 = {HashMap$HashMapEntry@7407} "name" -> "Ostatní"
 12 = {HashMap$HashMapEntry@7408} "defaultType" -> "1"
 13 = {HashMap$HashMapEntry@7409} "_deleted" -> "true"
 14 = {HashMap$HashMapEntry@7410} "_id" -> "-Category_472621e1-6753-4bbd-af5d-136caef1e0bf"
 15 = {HashMap$HashMapEntry@7411} "reservedUpdatedAt" -> "2016-11-01T10:31:36.463Z"
prevRevID = "6-edea31ae699bc6553c0846d19816198d"
allowConflict = false
source = null
outStatus = {Status@7378} "Status: 200 (HTTP 200 OK)"
deleting = true
validationBlock = null
```

- com.couchbase.lite/couchbase-lite-java-core/1.3.1-89/f3934ba1c881792b808a269713bceeca70d09fdf/couchbase-lite-java-core-1.3.1-89-sources.jar!/com/couchbase/lite/store/SQLiteStore.java:1623
`winner(docNumericID, oldWinningRevID, oldWinnerWasDeletion.get(), newRev, deleting ? wasConflicted : null);`
```
docID = "-Category_472621e1-6753-4bbd-af5d-136caef1e0bf"
prevRevID = "6-edea31ae699bc6553c0846d19816198d"
properties = {HashMap@7385}  size = 16
deleting = true
allowConflict = false
validationBlock = null
outStatus = {Status@7378} "Status: 200 (HTTP 200 OK)"
json = {byte[369]@7416} 
winningRevID = null
inConflict = true
docNumericID = 1049
isNewDoc = {AtomicBoolean@7423} "false"
oldWinnerWasDeletion = {AtomicBoolean@7430} "false"
wasConflicted = {AtomicBoolean@7432} "true"
oldWinningRevID = "6-edea31ae699bc6553c0846d19816198d"
parentSequence = 1052
newRevId = "7-f43dd6c1875202a805dd9744b6c878de"
newRev = {RevisionInternal@7456} "{-Category_472621e1-6753-4bbd-af5d-136caef1e0bf #7-f43dd6c1875202a805dd9744b6c878de @1732 DEL}"
 body = {Body@7470} 
 deleted = true
 docID = "-Category_472621e1-6753-4bbd-af5d-136caef1e0bf"
 missing = false
 revID = "7-f43dd6c1875202a805dd9744b6c878de"
 sequence = 1732
 shadow$_klass_ = {Class@1690} "class com.couchbase.lite.internal.RevisionInternal"
 shadow$_monitor_ = -1902962516
hasAttachments = false
docType = null
sequence = 1732
minGenToKeep = -12
```

**UNDER IS WRONG RETURNING WINNING REVISION**

- com.couchbase.lite/couchbase-lite-java-core/1.3.1-89/f3934ba1c881792b808a269713bceeca70d09fdf/couchbase-lite-java-core-1.3.1-89-sources.jar!/com/couchbase/lite/store/SQLiteStore.java:2274
```
docNumericId = 1049
outIsDeleted = {AtomicBoolean@7548} "false"
outIsConflict = {AtomicBoolean@7432} "true"
cursor = {SQLiteStorageEngineBase$SQLiteCursor@7561} 
sql = "SELECT revid, deleted FROM revs WHERE doc_id=? and current=1 ORDER BY deleted asc, revid desc LIMIT ?"
limit = 2
args = {String[2]@7558} 
revID = "5-7341df900fa7ad7904eca10336303862"
```

**Returning revision is 5, not 7!**

- com.couchbase.lite/couchbase-lite-java-core/1.3.1-89/f3934ba1c881792b808a269713bceeca70d09fdf/couchbase-lite-java-core-1.3.1-89-sources.jar!/com/couchbase/lite/store/SQLiteStore.java:2292
`revID = "5-7341df900fa7ad7904eca10336303862"`

- com.couchbase.lite/couchbase-lite-java-core/1.3.1-89/f3934ba1c881792b808a269713bceeca70d09fdf/couchbase-lite-java-core-1.3.1-89-sources.jar!/com/couchbase/lite/store/SQLiteStore.java:2795
```
docNumericID = 1049
oldWinningRevID = "6-edea31ae699bc6553c0846d19816198d"
oldWinnerWasDeletion = false
newRev = {RevisionInternal@7456} "{-Category_472621e1-6753-4bbd-af5d-136caef1e0bf #7-f43dd6c1875202a805dd9744b6c878de @1732 DEL}"
outIsConflict = {AtomicBoolean@7432} "false"
newRevID = "5-7341df900fa7ad7904eca10336303862"
outIsDeleted = {AtomicBoolean@7548} "false"
winningRevID = "5-7341df900fa7ad7904eca10336303862"
```

**Comment by hideki** [comment]
Hi @mtrakal,

I tried to reproduce the issue. So far, I can not.

Can you debug `winningRevIDOfDocNumericID()`. 
- What is query result of SQL. This method returns only first entry. Can you modify the code, and iterate?

```java
    protected String winningRevIDOfDocNumericID(long docNumericId,
                                                AtomicBoolean outIsDeleted,
                                                AtomicBoolean outIsConflict) // optional
            throws CouchbaseLiteException {
        assert (docNumericId > 0);
        Cursor cursor = null;
        String sql = "SELECT revid, deleted FROM revs" +
                " WHERE doc_id=? and current=1" +
                " ORDER BY deleted asc, revid desc LIMIT ?";

        long limit = outIsConflict != null ? 2 : 1;
        String[] args = {Long.toString(docNumericId), Long.toString(limit)};
        String revID = null;
        try {
            cursor = storageEngine.rawQuery(sql, args);
            if (cursor.moveToNext()) {
                revID = cursor.getString(0);
                outIsDeleted.set(cursor.getInt(1) > 0);
                // The document is in conflict if there are two+ result rows that are not deletions.
                if (outIsConflict != null)
                    outIsConflict.set(!outIsDeleted.get() && cursor.moveToNext() && !(cursor.getInt(1) > 0));
            } else {
                outIsDeleted.set(false);
                if (outIsConflict != null)
                    outIsConflict.set(false);
            }
        } catch (SQLException e) {
            Log.e(TAG, "Error", e);
            throw new CouchbaseLiteException("Error", e, new Status(Status.INTERNAL_SERVER_ERROR));
        } finally {
            if (cursor != null) {
                cursor.close();
            }
        }
        return revID;
    }
```

**Comment by hideki** [comment]
Hi @mtrakal,

From the information you provided, this document has conflicts. One of branch is with `6-edea31ae699bc6553c0846d19816198d`. Another one is `5-7341df900fa7ad7904eca10336303862`. (I believe `5-7341df900fa7ad7904eca10336303862` is not ancestor of `6-edea31ae699bc6553c0846d19816198d`. )
Before deleting branch of `6-edea31ae699bc6553c0846d19816198d`, both `6-edea31ae699bc6553c0846d19816198d` and `5-7341df900fa7ad7904eca10336303862` are a current revision.
By deleting branch of `6-edea31ae699bc6553c0846d19816198d` with `7-f43dd6c1875202a805dd9744b6c878de`, other branch `5-7341df900fa7ad7904eca10336303862` becomes winning revision. This is expected behavior.

I will close this ticket. If my assumption is not correct, please reopen the ticket.

Thanks!

**Comment by mtrakal** [comment]
There is no reason for conflicts on this document. I'm using just one device and make linear changes.

- old app: create document
- upgrade to new app version (newer CBL, but not important, because it's caused after delete app and install again with initial replication)
- after run new app data migration start (add to document with rev 5 just next one column (envelopeId))
- it's created new revision 6 (actual object), no reason for conflict here.

- Now when try to delete document (internally created rev7 with flag deleted)
- but new revision is 5 
- code didn't go through our code for resolving conflicts. 'New' old 5 revision comes to app without conflict from CBL as a non-conflicted.

**Comment by mtrakal** [comment]
Hi @hideki,

you are right. We have documents in conflict, but don't know reason :(. I must check why conflict is created.

**Comment by mtrakal** [comment]
```java
private Database.ChangeListener getChangeListener() {
        return new Database.ChangeListener() {
            @Override
            public void changed(Database.ChangeEvent changeEvent) {
                for (DocumentChange documentChange : changeEvent.getChanges()) {
                  if (documentChange.isConflict()) { // everytime is false
...
```

**Comment by mtrakal** [comment]
We didn't found where is problem with created conflicted records, but have a solution for it :). 
Thanks for help.
