### ISSUE TITLE
2.1 GB sparse db.forest.4 file created with ForestDB

### ISSUE THREAD

**Issue by svenfrauen** [couchbase/couchbase-lite-android#1040]
I used the newest Couchbase Lite for Android with version 1.3.1 and forestdb 1.3.1 to store and push a lot of sensor data from Android devices. At some point the storage usage of the app takes a huge leap of about 2.1 GB. After some investigation I found out that Couchbase / forestdb creates another sparse / "empty" db file "db.forest.4" with the size of 2.1 GB (which might be the maximum file size on my Android device). Apparently the file does not contain real data (I cannot read it with any Coubase tool) and if it is zipped the file size drops to just 18 MB so it looks like it is just a sparse dummy file.

I am not quite sure what triggers the creation of this file. Maybe an exception or an error was thrown during my app process but I could not reproduce it with any exception. But the sparse file was created on several occasions and sometimes even more than once. Furthermore, you can delete this file and new documents will still be stored in the "db.forest.3" file which grows continually with document numbers.

I also used push replication (with a filter) to upload documents to Couchbase Server via Sync Gateway (version 4.1 and 1.3.1) if that is of any help. For now I switched back sqlite which does not create sparse files but has slower performance.

Have you guys seen this behavior before or any idea what might be wrong? I would appreciate any help. Thank you!

Here is a zipped "db.forest.4" file:
[db.forest.4.zip](https://github.com/couchbase/couchbase-lite-android/files/576976/db.forest.4.zip)

**Comment by dbauduin** [comment]
I had the same problem (and other too: https://github.com/couchbase/couchbase-lite-ios/issues/1413) and I was forced to temporarily use SQLite storage type.
It seems that the next release will fix this bug: https://github.com/couchbase/couchbase-lite-android/issues/685#issuecomment-255820961.

**Comment by kumar1773** [comment]
I am facing the same issue, so switched back to SQLite.

**Comment by svenfrauen** [comment]
Thanks a lot for the input! I will wait for the next release and see if the problem is fixed.

**Comment by hideki** [comment]
Hi @svenfrauen,

Thank you for reporting the issue.

Can you test with CBL Android ForestDB jar version `1.3.1-90` which was built from the master branch? 
http://files.couchbase.com/maven2/com/couchbase/lite/couchbase-lite-android-forestdb/1.3.1-90/

Thank you!
Hideki

**Comment by hideki** [comment]
FYI:
I heard forestdb version that CBL Android uses still has the compaction issue. The forestdb team is investigating this.
Thanks!

**Comment by hideki** [comment]
This issue should be fixed by https://github.com/couchbaselabs/cbforest/commit/993f219bf3a95f2180257e6ff67db07d4dd4489f

**Comment by dbauduin** [comment]
In the [1.4 release notes](https://developer.couchbase.com/documentation/mobile/1.4/references/couchbase-lite/release-notes/Java.html), it is mentioned:

> The following features are being deprecated in Couchbase Mobile 1.4 and will be unsupported in 2.0.
> • ForestDB

Sad news...

**Comment by vbenso** [comment]
That is really, really bad.
@hideki do you have any comment on this deprecation?
