### ISSUE TITLE
Issue with cordova couchbase lite 1.3.0 - Router unable to route request to do_GET_Database

### ISSUE THREAD

**Issue by PrabhuKathiresan** [couchbase/couchbase-lite-android#1047]
Hi,
   Could anyone help me with an issue that corresponds to cordova couchbase lite v-1.3.0
I am new to mobile development and I am using couchbase lite for my offline capabilities. 
Initially i was using cordova couchbase lite v-1.0.1 and it all worked fine for me. But right now I want my app to be working in Android 7. So i need to update my couchbase lite from v-1.0.1 to v-1.3.0.

But, now I am facing a issue as soon as I start running my app.

"error-xhr: {"readyState":4,"responseText":"{\"error\":\"not_found\",\"status\":404,\"reason\":\"Router unable to route request to do_GET_Databasejava.lang.reflect.InvocationTargetException\"}","responseJSON":{"error":"not_found","status":404,"reason":"Router unable to route request to do_GET_Databasejava.lang.reflect.InvocationTargetException"},"status":404,"statusText":"Not found"}"

and the java error
![error](https://cloud.githubusercontent.com/assets/24243049/20701033/cfcd66fe-b636-11e6-8f66-8040ffe296d0.PNG)

could anyone help me how to sort out this issue??? 

Thanks in advance!

**Comment by hideki** [comment]
Hi @PrabhuKathiresan,

Error message indicates CBL can not open the database file. It seems like migrating database from 1.0.1 to 1.3.x failed with your environment.

**Comment by PrabhuKathiresan** [comment]
Hi @hideki 

Thanks for the reply,

Is there any workaround to setup the environment that help CBL to work??

**Comment by PrabhuKathiresan** [comment]
Can you help me understand what are things that need to be taken care before migrating to CBL v-1.3.0???

**Comment by hideki** [comment]
We need to reproduce the issue first. If you could provide detailed information, it could help us to debug it. Ideally, the CBL v1.0.1 sample sqlite file which can be extracted from emulator helps us a lot.

**Comment by PrabhuKathiresan** [comment]
Thank you for this help, I am listing out the steps that leads to the issue below. Please let me know if you need more information. 

1. This is the javascript code which I am using to connect with my couchbase v-1.0.1

        var coax = require("coax");
        var appDbName = "todos";

        document.addEventListener("deviceready", onDeviceReady, false);
        function onDeviceReady() {
            setupConfig(function(err) {
                if (err) {
                    alert(err)
                    return console.log("err "+JSON.stringify(err))
                }
            });
        };

        function setupConfig(done) {
            // get CBL url
            if (!window.cblite) {
                return done('Couchbase Lite not installed')
            }

        cblite.getURL(function(err, url) {
            console.log("getURL: " + JSON.stringify([err, url]))
            if (err) {return done(err)}

        if (!/Apple/.test(navigator.userAgent)) {
            // this helps on Android < 4.4
            // otherwise basic auth doesn't work
            var xmlHttp = new XMLHttpRequest()
            xmlHttp.open( 'GET', url, false )
            xmlHttp.send( null )
            console.log( 'XMLHttpRequest get: ' +  xmlHttp.responseText )
        }

        window.server = coax(url);
        var db = coax([url, appDbName]);
        setupDb(db, function(err, info){
            if (err) {return done(err)}
            setupViews(db, function(err, views){
                if (err) {return done(err)}
                getUser(db, function(err, user) {
                    if (err) {return done(err)}
                    window.config = {
                        site : {
                            syncUrl : REMOTE_SYNC_URL
                        },
                        user : user,
                        setUser : function(newUser, cb) {
                            if (window.config.user) {
                                if (config.user.user_id !== newUser.email) {
                                    return cb("already logged in as "+config.user.user_id)
                                } else {
                                    // we got a new facebook token
                                    config.user.access_token = newUser.access_token
                                    db.put("_local/user", config.user, function(err, ok){
                                        if (err) {return cb(err)}
                                        log("updateUser ok")
                                        config.user._rev = ok.rev
                                        cb()
                                    })
                                }
                            } else {
                                newUser.user_id = newUser.email
                                log("setUser "+JSON.stringify(newUser))
                                db.put("_local/user", newUser, function(err, ok){
                                    if (err) {return cb(err)}
                                    log("setUser ok")
                                    window.config.user = newUser
                                    cb()
                                })
                            }
                        },
                        db : db,
                        s : coax(url),
                        info : info,
                        views : views,
                        server : url
                    }
                    if (window.config.user) {
                        registerFacebookToken(done)
                    } else {
                        done(false)
                    }
                })
            })
        })
        })
        **This is the function from where the issue is throwed from CBL v-1.3.0**
        function setupDb(db, cb) {
        db.get(function(err, res, body){
            console.log(JSON.stringify(["before create db put", err, res, body]))
            db.put(function(err, res, body){
                db.get(cb)
            })
        })
        }
        function setupViews(db, cb) {
        var design = "_design/todo-view"
        db.put(design, {
            views : {
                lists : {
                    map : function(doc) {
                        if (doc.type == "list" && doc.created_at && doc.title) {
                            emit(doc.created_at, doc.title)
                        }
                    }.toString()
                },
                tasks : {
                    map : function(doc) {
                        if (doc.type == "task" && doc.created_at && doc.title && doc.list_id) {
                            emit([doc.list_id, doc.created_at],
                                {
                                    checked : doc.checked ? "checked" : "",
                                    title : doc.title
                                })
                        }
                    }.toString()
                },
                profiles : {
                    map : function(doc){
                        if (doc.type == "profile" && doc.user_id && doc.name) {
                            emit(doc.name)
                        }
                    }.toString()
                }
            }
        }, function(){
            cb(false, db([design, "_view"]))
        })
        }

        function getUser(db, cb) {
        db.get("_local/user", function(err, doc) {
            var user = false;
            if (!err) {
                user = doc;
            }
            cb(false, user)
        })
        };
        }

jar available in CBL v-1.0.1
![1 0 1](https://cloud.githubusercontent.com/assets/24243049/20745312/cee61a6c-b706-11e6-853a-98a75ec95003.PNG)

jar available in CBL v-1.3.0
![1 3 0](https://cloud.githubusercontent.com/assets/24243049/20745324/dc9af6dc-b706-11e6-968a-d14acb994ebc.PNG)

**Comment by hideki** [comment]
@PrabhuKathiresan,
You closed this ticket. Could you solve this?
