### ISSUE TITLE
Add Full-Text search capability

### ISSUE THREAD

**Issue by tleyden** [couchbase/couchbase-lite-android#105]
See https://github.com/couchbase/couchbase-lite-ios/issues/131

From http://www.sqlite.org/fts3.html#section_1_1

" FTS3 has been available since SQLite version 3.5.0 in 2007-09-04. The enhancements for FTS4 were added with SQLite version 3.7.4 on 2010-12-08."

FTS situation on android: http://stackoverflow.com/questions/6339022/sqlite3-fts4-match-and-android

The _current_ minimum android version for CBLite is 11-3.0-Honeycomb, which has FTS4.

**Comment by beilharz** [comment]
Hi @tleyden,

Did you share these details somewhere? 

Thanks

**Comment by tleyden** [comment]
@zgramana want to chime in on the roadmap here?

**Comment by fakeh** [comment]
Hi again,
Do the above comments mean some decision has been reached or progress made concerning this feature?
Thanks, Dan.

**Comment by tleyden** [comment]
@fakeh It's on our roadmap, but I just don't know which future release we have this planned for.  I know its a high priority, along with encryption (and these are the two features I'm pushing for the most).

If you or anyone you know is interested, we are hiring for a software developer role, which would help speed this along.  Also, third party community contributions would be welcome, but it's best to at least discuss the feature before starting to implement.

**Comment by fakeh** [comment]
@tleyden Thanks. Those two features are very important for applications, especially in the enterprise world.

**Comment by alexustinovsm** [comment]
+1
I have to write wrapper for search in QueryEnumerator T_T.
Please add full text search

**Comment by skhaz** [comment]
bump

**Comment by morphine9** [comment]
bump

**Comment by cpoopc** [comment]
+10086

**Comment by vitoller** [comment]
It would be very useful to have a full text search capability in the android version of couchbase lite. I am looking forward to the feature being available.

**Comment by iCRG** [comment]
It would be good if we have a full text search in the android, there is a lot of challenges for the lot apps because we do not a have FTS for android.

**Comment by morphine9** [comment]
+1 (bump)

**Comment by atom992** [comment]
+1

**Comment by hugofreire** [comment]
+1

**Comment by yan-oreshchenkov** [comment]
+1

**Comment by Abhilash-D** [comment]
+1

**Comment by zlymeda** [comment]
+1

**Comment by rockandbit** [comment]
+1
Is there any idea for when it may be available?
Thanx!

**Comment by prasannakumark** [comment]
+1

**Comment by maheswaranapk** [comment]
+1

**Comment by beilharz** [comment]
@hideki can you comment on this?

**Comment by hideki** [comment]
We understand many users are looking for full text search. But we have priority for new feature implementation and bug fixes.

**Comment by jblejder** [comment]
Full text search would be an awesome new feature.

**Comment by pgeyman** [comment]
+1

Until this is implemented, what is the work around for doing a search for documents where property "name" starts with a value a user enters? I can't find any examples of this.

**Comment by zcsongor** [comment]
+1

**Comment by lepinay** [comment]
+1

**Comment by EvenModiguy** [comment]
+1

**Comment by hideki** [comment]
We have planned to implement full-text search with CBL v2.x
https://github.com/couchbase/couchbase-lite-core/blob/master/README.md

**Comment by hitesh-dhamshaniya** [comment]
https://stackoverflow.com/questions/44604264/couchbase-light-filter-data-implement-search-in-android

Above issue can be solved from Full-Text search?

**Comment by jamiltz** [comment]
For a filter behaviour with 1.x you can use the prefixMatchLevel operator https://developer.couchbase.com/documentation/mobile/1.4/guides/couchbase-lite/native-api/query/index.html#creating-and-configuring-queries

**Comment by fernandocamargoti** [comment]
Soon this issue will complete 4 years old. Isn't there any news about it?

**Comment by hideki** [comment]
We will support FTS with 2.x. See https://developer.couchbase.com/documentation/mobile/2.0/guides/couchbase-lite/native-api/full-text-search/index.html

But currently no plan for 1.x.

**Comment by hideki** [comment]
We implemented FTS with 2.0.0
