### ISSUE TITLE
Change tracker stopped during continuous replication when using setDocIds filter

### ISSUE THREAD

**Issue by sureshjoshi** [couchbase/couchbase-lite-android#1050]
For my PullReplication, I use mPullReplication.setDocIds(createDocIdFilter()) - when doing this, I very quickly end up with the following set of errors (however, this does not happen when I remove the 'setDocIds').

Note: I'm also using continuous mode.

Has anyone seen this before?

```
12-13 01:53:27.759 24671-24743/com.example E/Datastore: PullReplication ChangeEventListener error: null
12-13 01:53:27.760 24671-24743/com.example E/Datastore: PullReplication ChangeEventListener lastError: java.lang.Exception: Change tracker stopped during continuous replication
12-13 01:53:27.762 24671-24743/com.example D/Datastore: PullReplication totalChanges: 5 completedChanges: 0 with status: REPLICATION_IDLE
12-13 01:53:27.763 24671-24743/com.example E/Datastore: PullReplication ChangeEventListener error: null
12-13 01:53:27.770 24671-24743/com.example E/Datastore: PullReplication ChangeEventListener lastError: java.lang.Exception: Change tracker stopped during continuous replication
12-13 01:53:27.772 24671-24743/com.example D/Datastore: PullReplication totalChanges: 5 completedChanges: 0 with status: REPLICATION_IDLE
12-13 01:53:27.774 24671-24743/com.example E/Datastore: PullReplication ChangeEventListener error: null
12-13 01:53:27.776 24671-24743/com.example E/Datastore: PullReplication ChangeEventListener lastError: java.lang.Exception: Change tracker stopped during continuous replication
12-13 01:53:27.777 24671-24743/com.example D/Datastore: PullReplication totalChanges: 5 completedChanges: 0 with status: REPLICATION_IDLE
12-13 01:53:27.779 24671-24743/com.example E/Datastore: PullReplication ChangeEventListener error: null
12-13 01:53:27.780 24671-24743/com.example E/Datastore: PullReplication ChangeEventListener lastError: java.lang.Exception: Change tracker stopped during continuous replication
12-13 01:53:27.782 24671-24743/com.example D/Datastore: PullReplication totalChanges: 5 completedChanges: 0 with status: REPLICATION_IDLE
12-13 01:53:27.785 24671-24743/com.example E/Datastore: PullReplication ChangeEventListener error: null
12-13 01:53:27.787 24671-24743/com.example E/Datastore: PullReplication ChangeEventListener lastError: java.lang.Exception: Change tracker stopped during continuous replication
12-13 01:53:27.789 24671-24743/com.example D/Datastore: PullReplication totalChanges: 5 completedChanges: 0 with status: REPLICATION_IDLE
12-13 01:53:27.862 24671-26008/com.example W/ChangeTracker: ChangeTracker{https://example.com/sync/, LongPoll, @ac9ef07}: Change tracker got error 400
12-13 01:53:27.862 24671-24743/com.example W/Sync: Change tracker stopped during continuous replication
12-13 01:53:28.264 24671-24743/com.example E/Datastore: PullReplication ChangeEventListener error: null
12-13 01:53:28.276 24671-24743/com.example E/Datastore: PullReplication ChangeEventListener lastError: java.lang.Exception: Change tracker stopped during continuous replication
12-13 01:53:28.277 24671-24743/com.example D/Datastore: PullReplication totalChanges: 0 completedChanges: 0 with status: REPLICATION_IDLE
12-13 01:53:29.404 24671-24744/com.example D/Datastore: PushReplication totalChanges: 2 completedChanges: 2 with status: REPLICATION_ACTIVE
12-13 01:53:29.905 24671-24744/com.example D/Datastore: PushReplication totalChanges: 2 completedChanges: 2 with status: REPLICATION_IDLE
12-13 01:53:33.264 24671-24743/com.example E/Datastore: PullReplication ChangeEventListener error: null
12-13 01:53:33.269 24671-24743/com.example E/Datastore: PullReplication ChangeEventListener lastError: java.lang.Exception: Change tracker stopped during continuous replication
12-13 01:53:33.271 24671-24743/com.example D/Datastore: PullReplication totalChanges: 0 completedChanges: 0 with status: REPLICATION_ACTIVE
12-13 01:53:34.019 24671-24743/com.example E/Datastore: PullReplication ChangeEventListener error: null
12-13 01:53:34.024 24671-24743/com.example E/Datastore: PullReplication ChangeEventListener lastError: java.lang.Exception: Change tracker stopped during continuous
```

**Comment by hideki** [comment]
It seems ChangeTracker sent a bad request to sync_gateway.  Do you have log message from sync_gateway, and detailed log from CBL?

**Comment by sureshjoshi** [comment]
Hey @hideki I can get those. Using default logging options, what you see is all I get from CBL. 

I'll work on getting some SG logs.

**Comment by pasin** [comment]
SGW doesn't currently support docIDs filter for continuous replication.

https://github.com/couchbase/sync_gateway/issues/1703

**Comment by sureshjoshi** [comment]
@pasin In that case, it works, but it shouldn't  :) 

I have an account with 1500 revisions (of maybe 100 docs). When I set the docId filter and open my app, only the 30 docs I'm interested in are there, and my total changes drops from 1500 to 350. The other 70 docs never come down, and there are no more revisions added.

So, whether it's supposed to be working or not - it seems to be.

However, maybe when Couchbase opens, it starts with an internal one-shot, and then it's the continuous replication afterwards (which is causing these errors)? 

I'm not sure, all I can guarantee is that my filtered docs are the only ones appearing in my local DB, and that I have continuous replication on.

**Comment by hideki** [comment]
@sureshjoshi, I recommend `sync function` to achieve this requirement. http://developer.couchbase.com/documentation/mobile/1.3/guides/sync-gateway/sync-function-api-guide/index.html

**Comment by sureshjoshi** [comment]
Thanks @hideki, is there an example of doing this anywhere? The documents operate per day on the pull replication. As in, every day, it's a different set of (deterministic) documents

**Comment by pasin** [comment]
> However, maybe when Couchbase opens, it starts with an internal one-shot, and then it's the continuous replication afterwards (which is causing these errors)?

Yes, that's why it seems to (partially) work.

**Comment by sureshjoshi** [comment]
@hideki Any thoughts on examples of how to achieve this functionality from the sync gateway? I can't use channel replication in this case, I just need to filter per user on certain docs (by date).

Alternatively, is there a good pattern for using a one-shot filter, followed by continuous? I know that will eventually pull all docs, but at least the ones I'm interested should be pulled first.

**Comment by sureshjoshi** [comment]
Actual, just for posterity's sake, what I went with was an observable sitting on the replication change event.

        mCompositeSubscription.add(getOneShotPullReplicationChangeEventObservable()
                .distinct()
                .filter(changeEvent -> changeEvent.getSource().getStatus() == Replication.ReplicationStatus.REPLICATION_STOPPED)
                .subscribe(changeEvent -> {
                    startContinuousPullReplication();
                }));

**Comment by sureshjoshi** [comment]
@hideki Is there some mechanism to directly download documents through SyncGateway, and then get them into Couchbase Lite so that they don't conflict with the replicator? Basically, I just need 30 documents out of hundreds before I can start my app, and even with continuous replication and a doc ID filter, it can take a while.

I know the names of the files, so I'm wondering if I could explicitly grab them, let my app start, and then let the replicators run in the background?

**Comment by hideki** [comment]
Hi @sureshjoshi,

If you know document IDs, you could start replicator with specifying the document IDs. 
https://developer.couchbase.com/documentation/mobile/1.3/references/couchbase-lite/couchbase-lite/replication/replication/index.html

**Comment by hideki** [comment]
@sureshjoshi Do you have enough information to solve this?

**Comment by sureshjoshi** [comment]
Hey @hideki what I've done is I start the app with one-shot mode with my document filter, and then after login, I turn on continuous replication without the doc filter, which (unfortunately) pulls all the documents down in the background.

Can't use continuous replication AND a doc ID filter.

I haven't figured out a way to bypass replication for login (e.g. by directly pulling the 30 documents I need from SG) though.

**Comment by hideki** [comment]
If you know the doc IDs, you could use `Replication.setDocIds(List<String> docIds)` to replicate only specified documents. Or you could write sync function on Sync Gateway side.

**Comment by sureshjoshi** [comment]
Going back to the first few comments on this issue, continuous replication with document IDs doesn't actually work (couchbase/sync_gateway#1703).

And, as I asked earlier - how would I write a sync function on Sync Gateway to always pull the last 7 days of documents (for example). I have deterministic document IDs, I just don't know how I could enforce pull replication by date.

**Comment by hideki** [comment]
As I am not an expert of sync gateway, I recommend you to post a question on Couchbase forum with mobile / sync gateway tag. https://forums.couchbase.com/

**Comment by sureshjoshi** [comment]
@hideki I wrote a script which pulls the 30 documents I care about from SG directly using HTTP GETs... Is there some way to then 'inject' those into CB Lite databases without running into a huge set of conflict issues?

Basically, this would let me 'preload' the database with the most important documents first, and lazy load the rest.... Thoughts?

**Comment by hideki** [comment]
Hi @sureshjoshi,

It seems you already tried the combination of one-shot and continuous replication. I believe following approach is simpler and should work.

- Run one-shot (non-continuous) pull replication with docIDs filter. This process, you could replicate specific documents you need.
- After one-shot replication finished, start continuous pull replication.

**Comment by sureshjoshi** [comment]
Hey @hideki, I already do this - but it doesn't work for iOS... It can also be a bit slow. The direct HTTP GET requests from Sync Gateway, on the other hand, are very fast. And I can also download documents in my specified order (e.g. a user profile comes down first).

**Comment by hideki** [comment]
@sureshjoshi 
If you could get all information from SG, you could insert document/Revision with using`Document.putExistingRevision()`
https://github.com/couchbase/couchbase-lite-java-core/blob/a700e5183e50d059c7bc56459f923658a45416ed/src/main/java/com/couchbase/lite/Document.java#L418
Thanks!
Hideki

**Comment by sureshjoshi** [comment]
Amazing!!! I will test this out and let you know!
