### ISSUE TITLE
How to listen to change tracker errors.

### ISSUE THREAD

**Issue by victordigio** [couchbase/couchbase-lite-android#1052]
Hi, I need to listen to change tracker errors, because in my project, the server can close the client session anytime. When It happens, I see in LogCat: "Change tracker got error 401", but I need to be inform of this situation. I have set a ChangeListener to my pull replicator with addChangeListener(...). Sometimes, when my client loose the server session, this listener is invoked with an RemoteRequestResponseException, but most of the time is not invoked, and I keep seeing in the LogCat "Change tracker got error 401" without being able to do nothing.

**Comment by hideki** [comment]
Hi @victordigio,

I believe Replicator should stop with setting Exception if the application prints `Change tracker got error 401`. Can you please provide a detailed scenario in case Replicator stops without setting an exception.
Thanks!

**Comment by hideki** [comment]
Hi @victordigio,
Do you have additional information about this issue?

**Comment by hideki** [comment]
as we don't have detailed information. I will close this ticket. If you are still facing this issue. please reopen the ticket.
