### ISSUE TITLE
Nested documents unexpected behavior

### ISSUE THREAD

**Issue by ramden** [couchbase/couchbase-lite-android#1053]
Hello, I wrote the question already on stackoverflow:

http://stackoverflow.com/questions/41353024/couchbase-lite-android-unexpected-behavior

Basically :
1. Query all records, I get all documents with nested objects
2. Change condition, execute same query, no results (expected)
3. Do first query again (query all records) with working condition, I get all documents **WITHOUT** nested objects

What could cause such behavior?

Is this expected or a major bug?

**Comment by hideki** [comment]
It seems that question is handled on stackoverflow.
