### ISSUE TITLE
Couchbase lite latest version 1.4-x

### ISSUE THREAD

**Issue by orenyodfat** [couchbase/couchbase-lite-android#1064]
What is the latest  stable version of couchbase lite?
Does 1.3.1 is the latest official one? Though it has some issues..

I am seeing at http://files.couchbase.com/maven2/com/couchbase/lite/couchbase-lite-android/
version 1.4-25.  so I guess this is still under development ?

When is the plan to official release the 1.4?

**Comment by hideki** [comment]
> Does 1.3.1 is the latest official one?

Yes

> so I guess this is still under development?

Yes

> When is the plan to official release the 1.4?

It could be during next month (Feb 2017).

Note:
At this moment, we only fix the critical issues for 1.4.0.
