### ISSUE TITLE
Saving JSON in Compressed format in Local CouchLite DB

### ISSUE THREAD

**Issue by BharathMG** [couchbase/couchbase-lite-android#1072]
Hi,

I understand couchbase lite supports sending compressed gzip data to server. But is it possible to store entire data in compressed manner inside local database to reduce the document size? 

Thanks,
Bharath MG

**Comment by hideki** [comment]
Couchbase Lite does not support the compressed data storing. If you could extract the part of data as an attachment, you can compress the attachment, and I believe you could save storage space.
