### ISSUE TITLE
2.0: Figure out best project structure for both CBL Android and Java

### ISSUE THREAD

**Issue by hideki** [couchbase/couchbase-lite-android#1083]
* Problems of CBL Android/Java v1.x is too many submodules and separated git repositories for CBL Android and Java.
* For 2.x, One git repository should contain both CBL Android and Java projects, and one submodule dependency to LiteCore. LiteCore could have nested submodules.

**Comment by hideki** [comment]
Links
- https://developer.android.com/studio/projects/android-library.html
- http://stackoverflow.com/questions/33961368/create-standalone-android-studio-1-5-library-project
- https://gist.github.com/daniellevass/2c46cf33e3814e685b47

**Comment by hideki** [comment]
### Approach 1
```
/root dir
   /android project dir
      - android project files
   /java project dir
      - java project files
   /src
      /shared
      /android
      /java
   /test
      /shared
      /android
      /java
   /libs (or /libraries)
      /LiteCore
```

NOTES:
Pros:
- Clear project isolation between android and java
Cons:
- From the project file, the source codes should be specified by `..`. I am not sure if this works.

### Approach 2
```
/root dir
   - build.gradle
   - android project files (cbl-android.gradle)
   - java project files (cbl-java.gradle)
   /src
      /shared
      /android
      /java
   /test
      /shared
      /android
      /java
   /libs (or /libraries)
      /LiteCore
```
NOTES:
Pros:
- In general, Android Studio/Project works well if it is on parent/root directly.
Cons:
- Higher chance, we can not use the same version of gradle.

**Comment by jamiltz** [comment]
It would be tremendously helpful to have everything in a single repository. Was this ticket closed because it turns out it can't be done or maybe because the extra work to do it isn't worth it?

**Comment by hideki** [comment]
Hi @jamiltz 
From 2.0, couchbase-lite-android repo contains two projects CBL Android and CBL Java. A submodule is only one which is couchbase-lite-core. Repo's directory structure is like Approach 1.
