### ISSUE TITLE
Cant find Databases after updating app

### ISSUE THREAD

**Issue by konbernu** [couchbase/couchbase-lite-android#1093]
I experienced the following behavior:

I have some Databases in my App. After I update my Application (I have a new .apk file and i install it from sd card) I cant find the Databases again. I dont override AndroidContext class. I checked the path for getFilesDir(), and it is the same before and after. I use the getAllDatabaseNames() function to check the Databases. I am wondering if it is CBL s fault or i have some other problems. Does CBL clear off its Databases at update?

Thank you for your answer.

**Comment by hideki** [comment]
Hi @konbernu,
I don't know what causes the upgrade problem. Can you observe any Exceptions or error messages in the logcat? It might gives you the hints.
Thanks!
Hideki

**Comment by djpongh** [comment]
Without more info, not much we can do to figure out what happened
