### ISSUE TITLE
2.0: JNI Binding for Query API

### ISSUE THREAD

**Issue by hideki** [couchbase/couchbase-lite-android#1118]

**Comment by pasin** [comment]
Here are the bindings that we need:

* C4Query* c4query_new(C4Database *database, C4String expression, C4Error *error) C4API;
C4StringResult c4query_explain(C4Query *query) C4API;
* void c4query_free(C4Query*) C4API;
* C4SliceResult c4queryenum_customColumns(C4QueryEnumerator *e) C4API;
* C4StringResult c4queryenum_fullTextMatched(C4QueryEnumerator *e, C4Error *outError) C4API;
* C4StringResult c4query_fullTextMatched(C4Query *query, C4String docID, C4SequenceNumber seq, C4Error *outError) C4API;
* bool c4queryenum_next(C4QueryEnumerator *e, C4Error *outError) C4API;
* void c4queryenum_close(C4QueryEnumerator *e) C4API;
* void c4queryenum_free(C4QueryEnumerator *e) C4API;
* bool c4db_createIndex(C4Database *database, C4String expressionsJSON, C4IndexType * indexType, const C4IndexOptions *indexOptions, C4Error *outError) C4API;
*bool c4db_deleteIndex(C4Database *database, C4String expressionsJSON,  C4IndexType indexType, C4Error *outError) C4API;
