### ISSUE TITLE
Java REST API, updating a View documents map function will not take effect for falling queries

### ISSUE THREAD

**Issue by erikm-couchbase** [couchbase/couchbase-lite-android#1139]
Problem:
REST API does support View version, but CBL Android always sets "1" for the version. By using same version number, re-indexing does not happen

**Comment by hideki** [comment]
### Problem:
- REST API does support View version - https://developer.couchbase.com/documentation/mobile/1.3/references/couchbase-lite/rest-api/index.html#!/query/post_db_design_ddoc_view_view
- CBL Android always set "1" for version. By using same version number, re-indexing not happen - https://github.com/couchbase/couchbase-lite-java-core/blob/master/src/main/java/com/couchbase/lite/router/Router.java#L2484
 
### Solution:
- Like iOS implementation, CBL Java need to set the hash value from content https://github.com/couchbase/couchbase-lite-ios/blob/66133e2ec76851ed16828f3b05476de0671ced3e/Source/CBLView%2BREST.m#L59

**Comment by sethrosetter** [comment]
@hideki Were you able to add a test for this or do we need to add a functional test?

**Comment by hideki** [comment]
Hi @sethrosetter,

I added the unit test for this. https://github.com/couchbase/couchbase-lite-android/pull/1145/files
