### ISSUE TITLE
Feature Request in 2.0: Reset Property in Replication to re-sync purged docs

### ISSUE THREAD

**Issue by pradipvaghasiya** [couchbase/couchbase-lite-android#1195]
Hello,
Can we have **reset** property added into Replication for Couchbase Lite Android 2.0 ?

If All docs of particular channel are purged then there is currently no way to re-sync all of them without knowing doc ids in Android.

In iOS it is possible, simply by adding reset parameter in Replication custom properties. Link below.
[iOS Replication Custom Properties](https://github.com/couchbase/couchbase-lite-ios/wiki/Replication-Custom-Properties)

**Comment by hideki** [comment]
Hi @pradipvaghasiya,

Thank you very much for your feedback to 2.0.

I submitted your request to internal 2.0 API spec repo.
https://github.com/couchbaselabs/couchbase-lite-apiv2/issues/104
