### ISSUE TITLE
2.0: Thread Safe (Database)

### ISSUE THREAD

**Issue by hideki** [couchbase/couchbase-lite-android#1201]

**Comment by NitzDKoder** [comment]
@hideki can you Please elaborate on this bug?

**Comment by hideki** [comment]
Hi @NitzDKoder,
CBL 2.x should be thread-safe. But we did not start to work for it yet. It should be done in few weeks.

**Comment by NitzDKoder** [comment]
@hideki Can you please expalin current behavior 1.4..

database.addChangeListener{//Android Main/UI thread Registering
changed(){//callback on which thread?
//Any operation here inside changed runs on which thread?
}
}
