### ISSUE TITLE
com.couchbase.lite.CouchbaseLiteException: Cannot index view student_view: no map block registered, Status: 400 (HTTP 400 bad_request)

### ISSUE THREAD

**Issue by kundan7560** [couchbase/couchbase-lite-android#1213]
```
 public void generateViewForMiltipleFilter(final String keyDocumentType, final String valueDocumentType, final List<Object> keys, String viewName, String viewVersionNo) {
        View view = null;
        if (database != null) {
            view = database.getExistingView(viewName);
        } else {
            Log.d(TAG, "Database does not exist.");
        }
        if (view == null) {
            view = database.getView(viewName);
            view.setMap(new Mapper() {
                @Override
                public void map(Map<String, Object> document, Emitter emitter) {
                    Object docType = document.get(keyDocumentType);
                    List<Object> keysList = new ArrayList<Object>();
                    for (Object mKey : keys) {
                        keysList.add(document.get(mKey));
                    }
                        emitter.emit(keysList, document);
                }
            }, viewVersionNo);
        }
    }
```

**Comment by hideki** [comment]
Hi @kundan7560,

Your codes look fine. Can you provide more information? or Can you debug further by yourself?

**Comment by kundan7560** [comment]
Hi @hideki At first run its working fine . now i close the app again open it . insert some records. now on run the query its not showing results ,showing exception mentioned above.

**Comment by hideki** [comment]
@kundan7560,
After reopening the app, does the app set the map function again?

**Comment by kundan7560** [comment]
@hideki No I get the existing view that is already exist.

**Comment by hideki** [comment]
@kundan7560,
Can you write an unit-test or a simple sample app to reproduce the issue?

**Comment by kundan7560** [comment]
@hideki After calling the map function every time its working. but why not with existing map function that has been already exist. why i am getting no map block registered exception?

**Comment by hideki** [comment]
Once registered the map function, the indexing should use the registered map function. Currently, I don't know how you encounter the problem. We need more information.

**Comment by kundan7560** [comment]
@hideki Hi how to register map function is there any method to register map function in couchbase lite?

**Comment by kundan7560** [comment]
@hideki Hi When i remove the below line its working...
  if (database != null) {
            view = database.getExistingView(viewName);
        } else {
            Log.d(TAG, "Database does not exist.");
        }

**Comment by hideki** [comment]
Hi @kundan7560,

Here is a guide for View. If the app follows it, the app should not have the problem.
https://developer.couchbase.com/documentation/mobile/1.4/guides/couchbase-lite/native-api/view/index.html

However, CBL could have the bug in the code. To investigate the problem, we need more info.

**Comment by kundan7560** [comment]
Hi@hideki thanks lot for support. i have figured out the problem.
