### ISSUE TITLE
JSON Mapping in Couchbase lite 2.0 

### ISSUE THREAD

**Issue by BharathMG** [couchbase/couchbase-lite-android#1215]
Hi,
Thanks for this wonderful library. 

I'm migrating the existing couchbase lite 1.4 database changes to use 2.0. So, `properties` map is not anymore in 2.0. We've been using Jackson library to do JSON Serialisation/Deserialisation Document Properties map. 

Now it looks like there is no way I can get the 'Properties Map' to do this JSON Mapping. 
Should I just create and use my own "Properties" Map inside the Document?

What is the recommended way to do JSON to Object Mapping in Couchbase 2.0?

Any help will be much appreciated!

**Comment by hideki** [comment]
Hi @BharathMG,

Thank you very much for using CBL 2.0.

CBL v2.x does not provide JSON serialization. The app can use Jackson, GSON, or own codes to serialize between JSON string and Map. Then by using [`Document(Map)`](http://docs.couchbase.com/mobile/2.0/couchbase-lite-java/db009/com/couchbase/lite/Document.html), `Document.set(Map)` or `Document.set(String key, Object value)`, then the app stores Map in the database. Note:  Object could be Map.

NOTE: From CBL Android v2.x does not depend on Jackson.

I hope this info helps.

**Comment by snej** [comment]
It sounds like you want to get the contents of a Document as a JSON string? What's the use case for this? Maybe we can provide a more direct API for what it is you want to do.

**Comment by BharathMG** [comment]
@hideki Thank you! It looks like `toMap()` will be the right candidate for my use case.

@snej So I want to convert my custom objects to map structure to store it in the CB Document. With the `toMap()` method suggested by @hideki , I can convert Map to custom Object using my Jackson adapter.

Thanks for answering my query in very short time!

**Comment by sytolk** [comment]
> It sounds like you want to get the contents of a Document as a JSON string? What's the use case for this? Maybe we can provide a more direct API for what it is you want to do.

@snej exactly this is the right usage of Couchbase Document sending to React Native Bridge. 
FB have this issue with the bridge: https://github.com/facebook/react-native/issues/10504
And its need to serialize couchbase Document to JSON to send it with native RN bridge to be accessible from React Native JS.
On the native Java side I have: 
```
Document trip = getDatabase().getDocument(tripId);
new JSONObject(trip.toMap()).toString())
```
can we optimize this conversions to: `trip .toJSON()` ?

**Comment by snej** [comment]
We can consider adding API for this in future releases; I'll file an internal ticket. This will just be for performance and simplicity; you can pretty easily write code to do the conversion yourself using the 2.0 API.

**Comment by sytolk** [comment]
Yes this is just a performance issue. Thanks!
