### ISSUE TITLE
1.x: CBL 1.4 and 1.3.1, replication of 200k docs : linear consumption of memory

### ISSUE THREAD

**Issue by nicolas-albert** [couchbase/couchbase-lite-android#1229]
I do a sample project to reproduce this issue : https://github.com/nicolas-albert/couchbase-lite-replication-memory

I try a trick that *cancel / create* the replicator each 20k docs and the consumption doesn't increase.

![chart](https://github.com/nicolas-albert/couchbase-lite-replication-memory/raw/master/cbl-replication-chart.png)

**Comment by tikimcfee** [comment]
@nicolas-albert Interesting stats. We see something very similar in our usage as well, and saw it way back in 1.1 and 1.2. I'm curious - what sort of increase in total amount of time to synchronize do you see when restarting the replicators every 20K or so documents?

**Comment by nicolas-albert** [comment]
I didn't check the time taken between the 2 runs, sorry.

**Comment by tikimcfee** [comment]
Ah, no worries. If you ever feel like testing this again, we'd be quite interested in seeing the numbers. Cheers!

**Comment by nicolas-albert** [comment]
Someone get the same behavior ?

**Comment by hideki** [comment]
Notes to self:
- The issue that memory is not released after replication completed is fixed by [PR](https://github.com/couchbase/couchbase-lite-java-core/pull/1661/files). `allReplicators` variable holds all references to replicators.
