### ISSUE TITLE
2.0 : Saving newly created document with existing ID should fail with conflict, instead of NPE.

### ISSUE THREAD

**Issue by AlBlanc** [couchbase/couchbase-lite-android#1231]
Hello,

I am not sure if it is a bug or a desired behaviour: First time i save a Document that I instanciated with a custom ID everything works fine. But the second time I instanciate a document using the same ID (in order to overwrite the previously created Document), it crashes and produces the following traceback.

```
06-26 18:10:18.045 10872-10872/io.sportner.client E/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.sportner.client, PID: 10872
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.couchbase.lite.CBLC4Doc.getRevID()' on a null object reference
        at com.couchbase.lite.ReadOnlyDocument.generation(ReadOnlyDocument.java:85)
        at com.couchbase.lite.Document.merge(Document.java:533)
        at com.couchbase.lite.Document.save(Document.java:470)
        at com.couchbase.lite.Document.save(Document.java:363)
        at com.couchbase.lite.Database.save(Database.java:192)
```

Version 
--------
Couchbase Lite Android 2.0-DB010

Desired behaviour
--------
On `Database.save(Document document)`, it should create or update the document properly.

**Comment by hideki** [comment]
@AlBlanc,  Thank you very much for trying to use 2.0.
Could you please paste code snippet?

**Comment by AlBlanc** [comment]
Basycally I am doing:
```
DatabaseConfiguration options = new DatabaseConfiguration(context);
Database db = new Database("some_db", options);
Document doc = new Document("abc");
doc.set("someKey", "someVar");
db.save(doc); // It works
Document doc2 = new Document("abc");
doc.set("someKey", "newVar");
db.save(doc2); // It crashes here
 ```

but the following code works:
```
DatabaseConfiguration options = new DatabaseConfiguration(context);
Database db = new Database("some_db", options);
Document doc = new Document("abc");
doc.set("someKey", "someVar");
db.save(doc);

Document doc2 = new Document("abc");
doc.set("someKey", "newVar");

Document existingDoc = db.getDocument("abc");
existingDoc.set(doc2.toMap());
db.save(existingDoc);
 ```

**Comment by hideki** [comment]
Hi @AlBlanc,

Thank you for the code snippet.

In case 1, I will clarify how it should work.

In case 2, updating `existingDoc` instance directly instead of creating `doc2` instance could be efficent.
```java
Document existingDoc = db.getDocument("abc");
existingDoc.set("someKey", "newVar");
db.save(existingDoc);
```
or
```java
Document existingDoc = db.getDocument("abc");
Map<String, Object> data = new HashMap();
data.put("someKey", "newVar");
...
existingDoc.set(data);
db.save(existingDoc);
```

**Comment by hideki** [comment]
Hi @AlBlanc,

Following codes should cause the conflict error instead of NullPointerException.

With `new Document(<id>)`, the document instance is not associated with Database instance. It is not possible to load the data from the database. So, calling `db.save(doc2);` should fail with conflict error. We will fix NullPointerException.

```
DatabaseConfiguration options = new DatabaseConfiguration(context);
Database db = new Database("some_db", options);
Document doc = new Document("abc");
doc.set("someKey", "someVar");
db.save(doc); // It works
Document doc2 = new Document("abc");
doc2.set("someKey", "newVar");
db.save(doc2); // It crashes here
```

**Comment by AlBlanc** [comment]
@hideki I agree but this is data i obtained from my API which is converted using GSON straight into a model class. Then I convert it into a Document for cache purpose.

**Comment by hideki** [comment]
With above scenario, NPE should not occur. It was a bug.

With current implementation, [DefaultConflictResolver](https://github.com/couchbase/couchbase-lite-android/blob/feature/2.0/shared/src/main/java/com/couchbase/lite/DefaultConflictResolver.java) should be applied. In above scenario, newly save doc should win.
