### ISSUE TITLE
2.0 : Exception when trying to open DB with prebuilt DB (v1.x)

### ISSUE THREAD

**Issue by rajagp** [couchbase/couchbase-lite-android#1237]
Used the following code snippet to load a prebuilt DB from assets folder
```
if (Database.exists(“quizzdroid”,context.getFilesDir()) == false) {
    try {
        // Copy the prebuilt database into specified location
        DataManager.unzip(context.getAssets().open("quizzdroid.cblite2.zip"), context.getFilesDir());

    }
    catch (IOException e) {
        e.printStackTrace();
    }
    catch (CouchbaseLiteException e) {
        e.printStackTrace();
    }

}
// Set database configuration
DatabaseConfiguration config = new DatabaseConfiguration(context);
// Create a new database with specified name and configuration . It should open existing one if present 
database = new Database("quizzdroid", config);
```
The files do get unzipped into the fileDir
```
/data/data/com.couchbase.quizzdroid_cbl/files/quizzdroid.cblite2 # ls -l
total 136
drwx------ 2 u0_a81 u0_a81  4096 2017-06-30 03:37 attachments
-rw------- 1 u0_a81 u0_a81 31744 2017-06-30 03:37 db.sqlite3
-rw------- 1 u0_a81 u0_a81 32768 2017-06-30 03:37 db.sqlite3-shm
-rw------- 1 u0_a81 u0_a81     0 2017-06-30 03:37 db.sqlite3-wal
```

**Exception raised when running this**
```
c4db = new com.couchbase.litecore.Database(
        dbFile.getPath(),
        databaseFlags,
        encryptionAlgorithm,
        encryptionKey);
```
**Exception :**
com.couchbase.litecore.LiteCoreException: No such file or directory

Note: The cblite2 was generated from V1 . Assumption that it will be migrated for 2.0 automatically. See attached
[quizzdroid.cblite2.zip](https://github.com/couchbase/couchbase-lite-android/files/1115723/quizzdroid.cblite2.zip)

**Comment by jamiltz** [comment]
It might be because the prebuilt database was built with CBL 1.2. But the database upgrader in 2.0 doesn't go that far back. Could you try opening the 1.2 with CBL 1.4 and then that database with CBL 2.0?

**Comment by jamiltz** [comment]
https://developer.couchbase.com/documentation/mobile/2.0/guides/couchbase-lite/native-api/database/index.html#opening-1.x-databases

Or it could be that the default database path when opening the database has changed. I'll try it in the examples project.

**Comment by rajagp** [comment]
I get the same exception even when I opened the todo.zip which was bundled with the 1.4 version of todo sample app.

**Comment by jamiltz** [comment]
Same here actually, I thought the database upgrader was automatically enabled in LiteCore but maybe not.

**Comment by hideki** [comment]
Note To Self:

litecore supports migration from 1.x DB.

**Comment by hideki** [comment]
Opening CBL v1.x Database by CBL 2.0 fails.
UnitTest: https://github.com/couchbase/couchbase-lite-android/commit/65365f2f3b01e188bbc8da3e7c65aea0d6c387ad

Need to talk during next cross-platform meeting.

**Comment by hideki** [comment]
Note to Self:

Lite core has [Upgrader](https://github.com/couchbase/couchbase-lite-core/blob/master/LiteCore/Database/Upgrader.cc) class. However, CBL layer does not have the implementation for the upgrade for 1.x DB. We need to work.

**Comment by hideki** [comment]
Note to Self: It seems CBL Android has bug.

**Comment by hideki** [comment]
With Android, mkTempDir() fails with the permission error.

In Upgrader.cc
```c++
    bool UpgradeDatabaseInPlace(const FilePath &path, C4DatabaseConfig config) {
        if (!(config.flags & kC4DB_Bundled) || (config.flags & (kC4DB_NoUpgrade | kC4DB_ReadOnly))) return false;

        string p = path.path();
        chomp(p, '/');
        chomp(p, '\\');
        FilePath newTempPath(p + "_TEMP/");
        auto trashPath(FilePath::tempDirectory()["CBL_Obsolete_DB-"].mkTempDir());
```

**Comment by hideki** [comment]
It seems Android app does not have access write to `"/tmp/CBL_Obsolete_DB-g3GE5y"`.
