### ISSUE TITLE
2.0: Push Replication  Causing Errors

### ISSUE THREAD

**Issue by rajagp** [couchbase/couchbase-lite-android#1247]
Version :  DB11
The following code snippet is used to create a document. Here `props` is a map. (Tried with `id` as null and providing a value for `id`
 
`Document document = new Document(id,props);
` 
This is the screenshot of debug view of my document
![image001](https://user-images.githubusercontent.com/645251/27880056-a7a09690-6191-11e7-8223-09fc62d8872c.png)

The SG Returns error :-
```
MSG#3! "changes"
2017-07-02T14:47:35.658-04:00 Sync: Received 1 changes from client
2017-07-02T14:47:35.658-04:00 Sync+: MSG#3!    --> OK
2017-07-02T14:47:35.664-04:00 Sync: MSG#4 "rev"
2017-07-02T14:47:35.664-04:00 Sync: MSG#4    --> 400 Missing doc _id or _rev
```

**Comment by hideki** [comment]
Hi @rajagp,
Do you have the code snippet to reproduce this problem?

**Comment by hideki** [comment]
Note To Self: 
test code is sent through email.

**Comment by rajagp** [comment]
Seems to be resolved with latest DB12 drop

**Comment by hideki** [comment]
@rajagp 
I will close this ticket. If you see this problem again, please re-open the ticket.
