### ISSUE TITLE
Pusher/Puller Replication Error Listener

### ISSUE THREAD

**Issue by BharathMG** [couchbase/couchbase-lite-android#1253]
Hi,

When Pusher replication is running, I'm seeing these logs for some documents,

       W/Sync: error=forbidden, id=332444fa-0e81-4896-a171-8e1510ffc938, reason=Unknown document type, status=403}: _bulk_docs got an error: com.couchbase.lite.replicator.PusherInternal

Is there any listener to get these as callback? So that I can remove those failed documents from local db. I can see `addChangeListener` and `lastError` but there is no Error Listener.

Thanks!

**Comment by hideki** [comment]
Hi @BharathMG,

you could set ChangeListener to the replicator, and check the value of `ChangeEvent.getError()`.
https://github.com/couchbase/couchbase-lite-java-core/blob/master/src/main/java/com/couchbase/lite/replicator/Replication.java#L676-L678

**Comment by djpongh** [comment]
This looks more appropriate for the forums but hopefully Hideki's answer helped.
