### ISSUE TITLE
2.0: Why library force my app manifest to use `android:allowBackup="true"`

### ISSUE THREAD

**Issue by AlBlanc** [couchbase/couchbase-lite-android#1254]
Hello,

I don't want my app to use the auto backup feature provided by Android M, but when I disable this feature I got this error:

![image](https://user-images.githubusercontent.com/5583672/27911816-c19639d2-625a-11e7-80a0-22dc56ed7070.png)

**Comment by hideki** [comment]
Hi @AlBlanc 
Thank you for reporting this.
