### ISSUE TITLE
2.0 migration from Forest back to SQlite

### ISSUE THREAD

**Issue by mtrakal** [couchbase/couchbase-lite-android#1264]
Hi, I'm trying to upgrade to 2.0 and testing.
ForestDB is removed, but is somewhere some tutorial solution how to migrate current users back to SQLite? 
Because we have about few thousands users still on ForestDB. We disable forest for new users when deprecation was announced, but still we have too much old users on forest and need to migrate them with 2.0 back to SQLite.

Thanks
We can do it before migrate to 2.0 (until we have time now), but I have no idea how, because I know, that somewhere was written that migration is possible only from SQLite to ForestDB :'(

**Comment by hideki** [comment]
Hi @mtrakal,

Currently, CBL does not provide migration from ForestDB to SQLite.

FYI: I believe your product uses CouchDB as a backend. Honestly speaking, CBL 2.x supports only new replication protocol. New replication protocol is not compatible with CouchDB.

Thanks,
Hideki

**Comment by mtrakal** [comment]
Oh, thanks for info.

Do you plan to support older 1.4.x for maintainance for some time when will be found some major bugs?

Thanks again for info.

**Comment by hideki** [comment]
Hi @mtrakal,

We will keep maintaining CBL v1.x.

**Comment by hideki** [comment]
REF: https://docs.google.com/document/d/1U1ZxM30e1cRMzpLluBDdcVh3v_CmLpw9ItDcYy1Gcfk/edit
