### ISSUE TITLE
2.0 Failed to resolve conflict while trying to delete the document

### ISSUE THREAD

**Issue by sridevi-15** [couchbase/couchbase-lite-android#1279]
Steps to reproduce:
1. Create documents.
2. Update documents which creates some revisions and updates the document.
3. Now delete the document
Result : 
   Document gets deleted in local database , but not get deleted in sync-gateway and server.
   When I check the count after deletion , I can see that count has reduced.
   When replicator tries to delete the document on sync-gateway and server, it throws this error on client

Expected behavior : 
   2.0 should handle conflicts and should delete without any revisions 

Logs on client: 
https://gist.github.com/sridevi-15/7d4932516fbf6d17b9fe914d522d593f

**Comment by hideki** [comment]
@sridevi-15 Can you write unit test or code snipet for this issue?

**Comment by djpongh** [comment]
This is a sync gateway issue. Filed https://github.com/couchbase/sync_gateway/issues/2713

**Comment by sridevi-15** [comment]
Hi Hideki,
        I heard unit test coverage is done by developers.

**Comment by hideki** [comment]
Hi @sridevi-15,
developers measure the test coverage.

DB013 test coverage
http://uberjenkins.sc.couchbase.com/view/Build/job/couchbase-lite-android/138/artifact/android/CouchbaseLite/build/reports/coverage/debug/index.html

**Comment by snej** [comment]
@djpongh There's an exception being thrown in CBL, according to the logs shown above; that looks unrelated to SG.
