### ISSUE TITLE
2.0 Attachments in auto upgraded DB from 1.x is not accessible through getBlob()

### ISSUE THREAD

**Issue by hideki** [couchbase/couchbase-lite-android#1286]
Attachment data from 1.x does not contain "@type" with "blob". So getBlob() does not work.
```json
    {attach1={digest=sha1-P1i5kI/sosq745/9BDR7kEghKps=, length=7, stub=true, revpos=2, content_type=text/plain}}
```

from Jens:
> The new plan is that CBL will recognize an `_attachments` property and treat dictionaries inside it as blobs. For compatibility with pre-existing documents, and docs replicated (via SG) from 1.x or CouchDB/PouchDB.

Ref: https://github.com/couchbase/couchbase-lite-android/blob/feature/2.0/android/CouchbaseLite/src/androidTest/java/com/couchbase/lite/MigrationTest.java#L81-L87

**Comment by hideki** [comment]
I believe this should be fixed in lite-core.

**Comment by hideki** [comment]
from jens
> This is intentional. We can't insert the "@type" property because it would modify the revision -- but revisions are immutable.
You'll need to modify Couchbase Lite to recognize this as a blob even without that property.

**Comment by hideki** [comment]
@borrrden and @pasin Can we discuss the solution when Jim is back?

**Comment by hideki** [comment]
Everything under `_attachments` are a blob.

1.x -> `/_attachments/photo.png`
2.0 -> `Docoument.getDictionary("_attachments").getBlob("photo.png")`

**Comment by snej** [comment]
What needs to be fixed in CBL is that getting a sub-property of "_attachments" should return a Blob object.
@pasin says he doesn't think this is implemented in iOS either.
