### ISSUE TITLE
2.0: Conflict Resolver: conflict.base does not seem valid (missing data)

### ISSUE THREAD

**Issue by rajagp** [couchbase/couchbase-lite-android#1293]
Tried on Android. Not sure if its an issue on iOS as well.
Assumption is the conflict.base is the common ancestor of mine and theirs revision. So tried this exercise: 
A custom conflict resolver is registered during database creation that just returns "base". 
```
  @Override
    public ReadOnlyDocument resolve(Conflict conflict) {
        // Get revisions in conflict
        ReadOnlyDocument base = conflict.getBase();
        ReadOnlyDocument mine  = conflict.getMine();
        ReadOnlyDocument theirs = conflict.getTheirs();

        return base;
    }
```

Steps:
**STEP 1:  Created a new document with id = "test123"**
```
 document = new Document(id, props);
 database.save(document);
```
Sync Gateway GET response (as expected):
```
{{adminurl}}/quizzdroid/test123?revs=true
{
    "_id": "test123",
    "_rev": "1-0854104c076ade28fa28191b03b1f086405445ac",
    "_revisions": {
        "ids": [
            "0854104c076ade28fa28191b03b1f086405445ac"
        ],
        "start": 1
    },
    "question_id": "35b4f94808f542b67de6996a53d404c3",
    "type": "answer",
    "user_answer": "elephant"
```

**STEP 2: Added a revision to the document**
```
 Document document = database.getDocument(id);
 document.set(props);
 document.set("university", "1");
 database.save(document);
```
Sync Gateway GET response (as expected):
```
{
    "_id": "test123",
    "_rev": "2-641504fc48ac122aad11324924e351dcd3ce2c94",
    "_revisions": {
        "ids": [
            "641504fc48ac122aad11324924e351dcd3ce2c94"
        ],
        "start": 2
    },
    "question_id": "35b4f94808f542b67de6996a53d404c3",
    "type": "answer",
    "university": "1",
    "user_answer": "t-rex"
}
```
**STEP3: Create Conflict as follows**
I do this by creating a new document with a docID of an existing document
```
 document = new Document("test123", props);
document.set("university", "2");
 database.save(document);
```
Conflict occurs and custom conflict resolver is called 
These are screenshots from debugger (Note "base")

**base **
Notice empty body
<img width="922" alt="screen shot 2017-07-24 at 1 30 05 pm" src="https://user-images.githubusercontent.com/645251/28536436-93791d84-7075-11e7-969c-54f1e1fc5d90.png">

**Mine**
<img width="921" alt="screen shot 2017-07-24 at 1 27 48 pm" src="https://user-images.githubusercontent.com/645251/28536379-6d158ec0-7075-11e7-969a-4b64df3e86a9.png">

**Theirs**
<img width="919" alt="screen shot 2017-07-24 at 1 29 22 pm" src="https://user-images.githubusercontent.com/645251/28536409-803800f0-7075-11e7-9480-21200bff5789.png">

I return "base" from my conflict resolver => this is new winning revision.

Sync Gateway GET response( this is the base revision that's returned from conflict resolver)
```
{{adminurl}}/quizzdroid/test123?revs=true

{
    "_id": "test123",
    "_rev": "3-9179197b323e7ce05b10d4e939164448133872bc",
    "_revisions": {
        "ids": [
            "9179197b323e7ce05b10d4e939164448133872bc"
        ],
        "start": 3
    }
}

```

Issues:
1) There is no body in base
2)Based on conflict resolver, I would have expected a revision with generation Id 1 to be returned.

**Comment by hideki** [comment]
Hi @rajagp,

The document which is created by Step 3 does not have parent revision. It means revision ID is 1-xxx.  So no common ancestor for this case. Currently, I don't know why return `base` which is `null` creates revision `3-xxxx`

**Comment by hideki** [comment]
Expected behavior:
1. If no common ancestor of conflicted revisions, `Conflict.base` should be `null`.
2. If `ConflictResolver.resolve(Conflict)` returns `null`, `Database.save()` should fail with `409`.

**Comment by rajagp** [comment]
@hideki  : 
1) If 409 is returned if the conflict resolver returns null, then won't the conflict resolver be called again (infinite loop)?
2) W.r.t 

> The document which is created by Step 3 does not have parent revision. It means revision ID is 1-xxx. 


Hmm. a document with this id "test123" already exists . For my clarification, what exactly is happening behind the scenes when I create a new document with same Id?

**Comment by hideki** [comment]
@rajagp 
1. `Database.save(Document)` should fail instead of keeping to solve conflict.
2. `new Document(String docID)` instance is not associated with Database. So it is treated as new Document. It seems `Document(String)` constructor makes confusion. We should discuss with API repo.

NOTE: current implementation does not return 409. Instead it return 14 (LiteCore error code). this could be changed.

**Comment by rajagp** [comment]
Thanks.  Would be great if the API documentation can clarify exactly the behavior if a user creates a new document with an Id that belongs to an existing document. (both Android and iOS) (CC @pasin )
