### ISSUE TITLE
2.0: DB14 Getting Document From Result

### ISSUE THREAD

**Issue by eljefe6a** [couchbase/couchbase-lite-android#1357]
In DB14, the `getDocument` method was removed. In the iOS API, the `document` property is still there. Was this removed by mistake or is this a new way of accessing the `Document`?

**Comment by hideki** [comment]
Hi @eljefe6a,
It is current spec.
https://github.com/couchbaselabs/couchbase-lite-apiv2/blob/master/query/java/couchbase/lite/query/Result.java
To access entire data, please use [SelectResult.all()](https://github.com/couchbaselabs/couchbase-lite-apiv2/blob/master/query/java/couchbase/lite/query/SelectResult.java#L11)

sample code:
https://github.com/couchbase/couchbase-lite-android/blob/feature/2.0/android/CouchbaseLite/src/androidTest/java/com/couchbase/lite/QueryTest.java#L1077

Thanks!

**Comment by eljefe6a** [comment]
So you're saying the iOS API isn't up to spec? Otherwise, this is a really big difference between the Android and iOS APIs. iOS has `CBLDocument *doc = row.document;` The Java `Result` object has no way to access the `Document`.

**Comment by hideki** [comment]
Hi @eljefe6a,

cc: @pasin 

CBL iOS v2.0 DB14 might not implement Result instead of QueryRow yet.
All platforms should follow API spec.
