### ISSUE TITLE
2.0: IDLE Still Says It Can Be Offline

### ISSUE THREAD

**Issue by eljefe6a** [couchbase/couchbase-lite-android#1380]
The JavaDoc says:
```
IDLE
The replication is inactive; either waiting for changes or offline as the remote host is unreachable.
--
OFFLINE
The replicator is offline as the remote host is unreachable.
```

Does `IDLE` still have offline as a possibility or was that taken by `OFFLINE` and the JavaDoc wasn't updated?

**Comment by hideki** [comment]
CBL 2.0 activity level is different from 1.x.
1.x OFFLINE also could be IDLE
2.x OFFLINE and IDLE are exclusive.
