### ISSUE TITLE
2.0: Query issues

### ISSUE THREAD

**Issue by JustSayBien** [couchbase/couchbase-lite-android#1387]
I have two questions:

1. Some Query-APIs are package-private for now, e.g. `in`:

   `Expression.any("LIKE").in("likes") ...`

    Is this intended?

2. How would one query items with a specific field contained in some array, e.g.:

This is not working:
```
List<String> listOfAllowedFieldValues;
Query query = Query.select(SelectResult.expression("someField")).from(DataSource.database(mDatabase)).where(Expression.property("someField").in(listOfAllowedFields));
```

 I tried to build this with `or` clauses, i.e 
```
.where(Expression.property("someField").equalTo(listOfAllowedFields.get(0)).or(Expression.property("someField").equalTo(listOfAllowedFields.get(1)) ...
```

But this does not work if `listOfAllowedFields` has lots of entries ( 200+)

**Comment by hideki** [comment]
@JustSayBien,

> Is this intended?

It is a bug. It should be a public method. 

> How would one query items with a specific field contained in some array, e.g.:

I found there is a bug in `Expression.in(Object...)`.  It will be fixed by DB017 release.

**Comment by hideki** [comment]
@JustSayBien,

Thank you again reporting the bug. Fixed codes are in  `feature/2.0` branch. DB017 release contains the fix for this issue.

Following is sample code for how to use `Expression.in(...)` method
https://github.com/couchbase/couchbase-lite-android/blob/feature/2.0/android/CouchbaseLite/src/androidTest/java/com/couchbase/lite/QueryTest.java#L306-L329

**Comment by JustSayBien** [comment]
You're welcome. Thanks for the response and quick fixes, looking foward to DB17.

**Comment by JustSayBien** [comment]
Hi. I'm still seeing some problems:

```java
Expression.any("ITEM").in("json.items").satifies(Expression.variable("ITEM.id")
```

`in()` is still not accessible from outside since `In` class is package-private:

```java
    static final class In {
        QuantifiesType type;
        String variable;

        In(QuantifiesType type, String variable) {
            this.type = type;
            this.variable = variable;
        }

        public Satisfies in(Object expression) {
            return new Satisfies(type, variable, expression);
        }
    }

```

**Comment by hideki** [comment]
Hi @JustSayBien,
Sorry for causing this issue.
I should re-write unit test with a different package to catch the access level problems.
