### ISSUE TITLE
Maven central issue Android gradle

### ISSUE THREAD

**Issue by srikarreddy** [couchbase/couchbase-lite-android#1399]
Followed maven instructions provided [here](https://developer.couchbase.com/documentation/mobile/2.0/guides/couchbase-lite/index.html?language=java)

Getting following error:
Error:Failed to resolve: com.couchbase.lite:couchbase-lite-android:2.0.0-DB016

Please provide me a prebuild(.aar) link for the 2.0.0_DB016 version.

Regards,
Srikar

**Comment by hideki** [comment]
Hi @srikarreddy,

Thank you for reporting this. It seems Maven Repo has a problem now. We will let you know as soon as maven repo is recovered.

**Comment by djpongh** [comment]
This should be working again. Let us know if you can't get DB16.
