### ISSUE TITLE
2.0: C4ReplicatorStatus progressCompleted is never updating

### ISSUE THREAD

**Issue by ascendancy05** [couchbase/couchbase-lite-android#1401]
couchbase-lite-android 2.0.0-DB016

We are observing very odd behavior where when we want to wait for an explicit completion of a sync, we are receiving this message back:

```
statusChanged() c4Status -> C4ReplicatorStatus{activityLevel=0, progressCompleted=0, progressTotal=348635, errorDomain=0, errorCode=0, errorInternalInfo=0}             Got this at the end of a sync.  FOr your bug report, so they see the progressCompleted is never updating
```

Here is the logic where we are implementing this in our app:

```
ReplicatorConfiguration replConfig = new ReplicatorConfiguration(database, uri);
            replConfig.setAuthenticator(new SessionAuthenticator(sessionInfo.cookieValue, sessionInfo.cookieDate, sessionInfo.cookieName));
            replConfig.setContinuous(false);
            replConfig.setReplicatorType(ReplicatorConfiguration.ReplicatorType.PULL);
            replicator = new Replicator(replConfig);
            replicator.addChangeListener(new ReplicatorChangeListener() {
                @Override
                public void changed(Replicator replicator, Replicator.Status status, CouchbaseLiteException error) {
```

```sessionInfo``` is an instance of an internal class we have that contains the pertinent information to instantiate the ```SessionAuthenticator```

inside ```changed``` we are never seeing the ```progressCompleted``` value increment from the ```status``` variable. As a result, we can never know when the sync is completed, and have to just "guess" from inactivity from the sync gateway.

**Comment by ascendancy05** [comment]
Also worth noting we do eventually see a ```LiteCore [Sync]: {3} Caught up with remote changes``` log message when sync_gateway seems to finish sending changes down but it doesn't appear this completed state ever gets cascaded up/isn't available via the android library from the C++ core code

**Comment by ascendancy05** [comment]
Is there currently any ETA on DB017 being released? I would imagine that since the version has not been cut yet, I am curious if the changes to the Pusher from the issue above in the core submodule would get us unstuck here. Also bumping as its been close to 3 weeks now

**Comment by hideki** [comment]
Hi @ascendancy05,

DB017 and DB018 are on the couchbase maven repo. http://mobile.maven.couchbase.com/feeds/dev

This ticket is still in the backlog queue.

**Comment by ascendancy05** [comment]
Thanks @hideki. Unfortunately I am not able to access that link, it shows up as Forbidden to me.

**Comment by hideki** [comment]
Hi @ascendancy05 
Can you just replace `DB016` with `DB017` or `DB018`?
https://developer.couchbase.com/documentation/mobile/2.0/guides/couchbase-lite/index.html?language=java
Thanks,
Hideki

**Comment by ascendancy05** [comment]
Ok great, thanks. We will check it out for DB018 tomorrow and retest

**Comment by ascendancy05** [comment]
DB018 fails to resolve during gradle sync. DB017 works

**Comment by hideki** [comment]
POM file for DB018 contained the inappropriate version number. This issue is already addressed.
