### ISSUE TITLE
Accessing attachments created in 2.x from a 1.x client

### ISSUE THREAD

**Issue by ssmotra** [couchbase/couchbase-lite-android#1415]
As a user I would like to attachments created via a 2.0 client to be replicated to any 1.x clients connected to the cluster. 

Need to verify that 2.0 apps that need backward compatibility can create blobs in an “_attachments” property so that they are recognized by older versions.

**Comment by djpongh** [comment]
Moved to: https://github.com/couchbaselabs/mobile-testkit/issues/1472
