### ISSUE TITLE
Immutable API

### ISSUE THREAD

**Issue by djpongh** [couchbase/couchbase-lite-android#1436]
https://github.com/couchbaselabs/couchbase-lite-apiv2/commit/b663385e73f4dd4f4db44ca48dca35e97f6311ee

**Comment by hideki** [comment]
TODOs
- [ ] Update class names, Document, MutableDocument, Array, MutableArray, Dictionary, MutableDictionary, DictionaryInterface, MutableDictionaryInterface, ArrayInterface, MutableArrayInterface.
- [ ] Check updated class's method names
- [ ] `Document Database.save(MutableDocument doc)`.
