### ISSUE TITLE
2.0 Question regarding data-format

### ISSUE THREAD

**Issue by JustSayBien** [couchbase/couchbase-lite-android#1439]
Question:

Is the core data-format stable already? Which means we can simply upgrade to the stable version of couchbase-lite 2.0 once it's ready? Or do we have to expect changes in the data-format which will require additional data-migration? If so, will you provide a way to upgrade from e.g couchbase-lite-android DB 19 to couchbase-lite-android BETA or couchbase-lite-android stable?

**Comment by hideki** [comment]
@JustSayBien We don't have the plan to change the data format near future. If you are considering to use CBL 2.0 for the production, I recommend you to wait for official release of CBL 2.0.

**Comment by JustSayBien** [comment]
Thanks for your answer. Unfortunately we have some due dates, which likely won't allow us to wait for the stable release. 
At the moment we are using CBL (2.0 DB) as local database/document store only (without any replication) and it is working stable enough for us to use it in production. The only deal-breaker would be an incompatible change in the current database-format, but if this is unlikely to happen, we can stay with the current version, "sit it out" and then simply upgrade to the stable CBL release once it's ready.
