### ISSUE TITLE
Discrepancy between the Database class constructor doc and its implementation.

### ISSUE THREAD

**Issue by hrajput89** [couchbase/couchbase-lite-android#1440]
There is discrepancy between class constructor and its implementation of Database class. The constructor says, that we can pass null to "config" argument, however, the implementation explicitly raises IllegalArgumentException for null value.

>  /**
>      * Construct a  Database with a given name and database config.
>      * If the database does not yet exist, it will be created, unless the `readOnly` option is used.
>      *
>      * @param name   The name of the database. May NOT contain capital letters!
>      * @param config The database config, or null for the default config.
>      * @throws CouchbaseLiteException Throws an exception if any error occurs during the open operation.
>      */
>     public Database(String name, DatabaseConfiguration config) throws CouchbaseLiteException {
>         if (name == null || name.length() == 0)
>             throw new IllegalArgumentException("name should not be empty.");
>         **if (config == null)**
>             **throw new IllegalArgumentException("DatabaseConfiguration should not be null.");**

**Comment by hideki** [comment]
Fixed with https://github.com/couchbase/couchbase-lite-android/commit/82f7ffc429043525f8a87b9522019753ea1f7b11
