### ISSUE TITLE
getDocument() of database class, doesn't return Null for a non-existent document.

### ISSUE THREAD

**Issue by hrajput89** [couchbase/couchbase-lite-android#1450]
1. Created a DB object.
2. Requested for a non-existent document with doc_id (String) equals to "boo".
3. Got a reference object of ReadOnlyDocument - "boo".

**Comment by hideki** [comment]
Issue is not reproducible with master branch
Following test covers this scenario.
https://github.com/couchbase/couchbase-lite-android/commit/7a751c206ec78e5cedf3ddf3f4ba5c002a1f491c
