### ISSUE TITLE
2.0: Improve code coverage rate to 80%.

### ISSUE THREAD

**Issue by hideki** [couchbase/couchbase-lite-android#1457]
With Build 168, Coverage is 52%. 
http://mobile.jenkins.couchbase.com/view/Core_Based_Builds/job/couchbase-lite-android/168/artifact/reports/reports-android-24/coverage/debug/index.html

**Comment by hideki** [comment]
## Notes

#### Unavoidable miss-coverage
- private constructor
```java
public class LiteCoreBridge {
    private LiteCoreBridge(){}
}
```

**Comment by hideki** [comment]
60% - 12/13/2017
http://mobile.jenkins.couchbase.com/job/couchbase-lite-android/179/artifact/reports/reports-android-24/coverage/debug/index.html

**Comment by jayahariv** [comment]
Reached 79% for EE 
Reached 76% for CE 

## EE
<img width="1169" alt="ee" src="https://user-images.githubusercontent.com/10448770/52880698-7e086900-3117-11e9-8f86-8d089faea308.png">

## CE
<img width="1139" alt="ce" src="https://user-images.githubusercontent.com/10448770/52880836-f111df80-3117-11e9-8819-38c49cc9c938.png">

Hence closing this for now.
