### ISSUE TITLE
CBL 2.0: It is possible to know results counts of a query?

### ISSUE THREAD

**Issue by AlBlanc** [couchbase/couchbase-lite-android#1463]
Everything is in the title!

It would be great to have query results count, this information is mandatory in a `RecyclerView`. Then we would use the query result as a cursor in order to write beautiful recycler which can handle tons of results.

**Comment by hideki** [comment]
With the current design, ResultSet does not support the count.
https://github.com/couchbase/couchbase-lite-android/blob/feature/2.0/shared/src/main/java/com/couchbase/lite/ResultSet.java

I will propose `count()` method for `ResultSet` to our team.

**Comment by hideki** [comment]
REF: https://github.com/couchbaselabs/couchbase-lite-apiv2/issues/186

**Comment by pasin** [comment]
Thanks for the feedback and recommendation. We have thought about this through and have decided not to change the API at this point. We would like to keep the ResultSet as an enumerator or iterator for performance and memory optimization.

In order to being able to access the ResultSet as an array, developers could load all of the result into an array or list.

**Comment by AlBlanc** [comment]
By doing this way we can't deal with a large data set in a `RecyclerView` which is a huge issue for us, and I believe for many other apps.

Reactivity matters for the user experience and right now there is a significative latency when we load all of the query results in a list even with a Galaxy S8 (I am scared to try on a low-end smartphone).

If you can't provide any workaround, we'll have to think about to drop couchbase lite, we really have to provide a smooth experience to our users.

**Comment by pasin** [comment]
@AlBlanc Thanks for the feedbacks. We are revising the API and will provide some support on this.

**Comment by AlBlanc** [comment]
Great! Please keep us in touch when you'll have any insight about the availability of this feature

**Comment by AlBlanc** [comment]
Hello, Any news about this topic?

**Comment by AlBlanc** [comment]
The result set is not really large (~1.5k items maximum), but the user experience is not the same. 
The list could have been displayed instantly like I was used to do it with a `CursorAdapter`.

Ok, well, we'll do it this way.
