### ISSUE TITLE
Dictionary contains method returning false for a key when dictionary content is generated by set method

### ISSUE THREAD

**Issue by hrajput89** [couchbase/couchbase-lite-android#1466]
When I'm setting the dictionary content from set method (passing a hash map ), I can see all the keys that I've provided in hash map from getKeys method. However, when I check the key in dictionary using contains method, I'm getting False.

**Comment by hideki** [comment]
Hi @hrajput89,
Could you please specify the version number. And could you please provide the code snippet?

**Comment by djpongh** [comment]
Could you point us at the test that's failing?

**Comment by djpongh** [comment]
@hrajput89 , please update!

**Comment by hrajput89** [comment]
the method for which I logged the issue is no longer available in Document API.  Hence closing the ticket
