### ISSUE TITLE
2.0: In My App with CB Lite DB020(Android), ConflictResolver is called endless loop during three device or much more!

### ISSUE THREAD

**Issue by hideki** [couchbase/couchbase-lite-android#1470]
https://forums.couchbase.com/t/in-my-app-with-cb-lite-db020-android-conflictresolver-is-called-endless-loop-during-three-device-or-much-more/15113

Three or much more devices are running my app, i set ConflictResolver with ::
```java
ConflictResolver getConflictResolver(){
/**
* Example: Conflict resolver that merges Mine and Their document.
*/
return new ConflictResolver() {
@Override
public ReadOnlyDocument resolve(Conflict conflict) {
ReadOnlyDocument mine = conflict.getMine();
ReadOnlyDocument theirs = conflict.getTheirs();

    Document resolved = new Document();
    Set<String> changed = new HashSet<>();

    // copy all data from theirs document
    for (String key : theirs)
    {
      resolved.setObject(key, theirs.getObject(key));
      changed.add(key);
    }

    // copy all data from mine which are not in mine document
    for (String key : mine)
    {
      if (!changed.contains(key))
        resolved.setObject(key, mine.getObject(key));
    }

    return resolved;
  }
};

```
but when Documents conflict, this ConflictResolver function is called endless loop during
these devices. this bug happens in the todo Demo also!

**Comment by loongsun** [comment]
the exact steps are :1. run todo app on three devices and add one document  2.update that document  at same time on two devices.   this issue will happen.

**Comment by hideki** [comment]
https://gist.github.com/raghusarangapani/4d0a93fea4bcd53400dda5ca963b7669
