### ISSUE TITLE
make List<QueryRow> public or a way to merge QueryEnumerators

### ISSUE THREAD

**Issue by nishantpardamwar** [couchbase/couchbase-lite-android#1479]
Couchbase Lite version : 1.4.0 (Android)

I was loading around 20k+ of rows into recyclerview and iterating over QueryEnumerator to make List of queryrow is very slow, so i checked the QueryEnumerator code and there is already List<QueryRow> field, so is it possible to get that list direct and also merging different QueryEnumerators ?
Because seriously queryrow list is already there so why create new list by iterating over QueryEnumerator.

**Comment by hideki** [comment]
Hi @nishantpardamwar 
API change is not only for Android platform, also other platforms. Not easy for us.
Could you compile CBL Android by yourself with customizing QueryEnumerator?
