### ISSUE TITLE
Does Push and pull replication replicates revisions of a document?

### ISSUE THREAD

**Issue by shwetankb11** [couchbase/couchbase-lite-android#1490]
Hi,

Current Network condition: No Internet Connection
In a freshly installed application If I create a document and update it 10 times then I will have 10 revisions of a particular document. (There is a property which I added when I was updating the document 5th time and then removed it later).

Switch on our network and sync it on the server.

Now,
if I run a fresh application on another device and try to get
document.getRevision(5);
Will I get the property i added to that specific revision or properties of the Latest revision is returned?

**Comment by hideki** [comment]
@shwetankb11 
With your scenario, the revision's property should be replicated.
In case a document is compacted or revision history is longer than maximum, the particular revision is not replicated.
