### ISSUE TITLE
Document id is stored as _id in CBL android

### ISSUE THREAD

**Issue by hrajput89** [couchbase/couchbase-lite-android#1496]
I found that document store, id value as "_id" key only for android. At CBS it is stored as "id" and also same is true for CBL iOS.

from cbl - {'_id': u'airport_1360', 'type': u'airport', 'name': None}
from n1ql query on CBS - {u'type': u'airline', u'id': u'airline_1191', u'name': u'Air Austral'}

**Comment by hideki** [comment]
I believe @hrajput89 mentions the property name of query result for Meta.id.

This issue is fixed by the https://github.com/couchbase/couchbase-lite-android/commit/340985bb378fed3973c5e6f59fa90bf3ff0ba5b5

**Comment by snej** [comment]
I don't think this is about Meta.id. @hrajput89, could you please give more detail? The meta-properties `_id` and `id` aren't used anywhere in CBL 2.0.
