### ISSUE TITLE
1.4 : Continuous Replication with wrong status (Replication_stopped)

### ISSUE THREAD

**Issue by pkjvit** [couchbase/couchbase-lite-android#1505]
As per replication document, Continuous replication never stopped. 
here is the link [CoucbaseLite-Replication](https://developer.couchbase.com/documentation/mobile/current/guides/couchbase-lite/native-api/replication/index.html)

In my case **Continuous** replication running and I found the pull replication url gives me "404 not found" error and replication goes in **Stopped** state instead of **Offline**.
Is it right or It should goes in Offline state?

**Comment by hideki** [comment]
@pkjvit 
Continuous replicator stops if it encounters permanent error.

**Comment by pkjvit** [comment]
@hideki 
Thank you
