### ISSUE TITLE
2.0: Request changes based on API Review

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-android#1507]
## Request changes based on API review:

Database
* [x] Shouldn’t expose or implement C4Constants.
* [x] getActiveLiveQueries should not be public.
* [x] Change getDocument(documentID) to getDocument(id)
* [x] Change contains(documentID) to contains(id)
* [x] Change inBatch(Runnable action) to inBatch(runnable)
* [x] Change addDocumentChangeListener(docID, …) to addDocumentChangeListener(id, …)

Array (including MutableArray, ArrayInterface and MutableArrayInterface)
* [ ] encodeTo shouldn’t be public. (NOTE: Not avoidalble with current implementation. Write in javadoc)
* [ ] ~~FLEncodable shouldn’t be as public. (TODO: called from litecore.fleece.Encoder)~~
* [x] set/insert/addArray() should allow Array not just MutableArray
* [x] set/insert/addDictionary() should allow Dictionary not just MutableDictionary

Dictionary( including MutableDictionary, DictionaryInterface and MutableDictionaryInterface)
* [ ] encodeTo shouldn’t be public. (NOTE: Not avoidalble with current implementation. Write in javadoc)
* [ ] ~~FLEncodable shouldn’t be public. (TODO: called from litecore.fleece.Encoder)~~
MutableArray
* [x] set/insert/addArray() should allow Array not just MutableArray
* [x] set/insert/addDictionary() should allow Dictionary not just MutableDictionary

CBLConverter
* [x] Shouldn’t be public.

Query classes
* [x] Moved everything at root for consistency.

Replicator
* [x] networkReachable() shouldn’t be public. (TODO: NetworkReachabilityListener is interface)
* [x] networkUnreachable() shouldn’t be public. (TODO: NetworkReachabilityListener is interface)

ReplicatorConfiguration
* [x] ReplicatorConfigurator(Database, Object, ReplicatorType ….) should not be public.
* [x] copy() shouldn’t be public or should be removed if no use.

ArrayExpression
* [x] Expression.variable(name) should be moved to ArrayExpression.

Collation
* [x] For unicode collation, if the locale is not set, use the current device locale or default platform locale.
* [x] CollationExpression shouldn’t be public.

DataSource
* [x] Remove query()

Expression
* [x] asJson() shouldn’t be public.
* [ ] ~~Implement concat~~

Function
* [x] Change atan2(y, x) to atan2(x, y)

MetaExpression
* [x] Should extend Expression instead of PropertyExpression and include from(alias) method in it.

ValueIndex
* [x] Should be public

PropertyExpression
* [x] Need to move from internal to public.
* [x] PropertyExpression constructor shouldn’t be public.
* [x] Only from(alias) is public, the rest methods and kCBLAllPropertiesName are not.

Query
* [x] Missing addChangeListener(queue, listener).
* [x] getDatabase() shouldn’t be public.

QueryChange
* [x] Change getRows() to getResult()

ResultContext
* [x] Shouldn’t be public.

ResultSet
* [x] Make only next() and iterator() public. The rest shouldn’t be public.

SelectResult
* [x] from(alias) should return SelectResult.

NetworkReachabilityListener
* [x] Shouldn’t be public  (TODO: NetworkReachabilityListener is interface)

NetworkReachabilityManager
* [x] Shouldn’t be public

Log
* [x] Shouldn’t be public (TODO: two options - make package level, or move to internal)

## Request changes based on API Spec update

See: 
https://github.com/couchbaselabs/couchbase-lite-apiv2/commit/df94b46e0e5aa9e7eac2da006964553662cb76b2
https://github.com/couchbaselabs/couchbase-lite-apiv2/commit/ad7a29ae1872da9d41d4f1dfce71aeb28d26c7e3
https://github.com/couchbaselabs/couchbase-lite-apiv2/commit/4b501559f67f9e9f2e131ccbda85e65b244ab4d5

DatabaseConfiguration
* [x] getConflictResolver() returns the default one by default.
* [x] setConflictResolver(resolver) doesn’t allow to set null.
* [x] getDirectory() returns the default one by default.
* [x] setDirectory(directory) doesn’t allow to set null.
* [x] Use builder pattern.

Database
* [x] Remove contains(id: String) -> Bool as the redundant function with checking null from calling getDocument(id)
* [x] delete(document) : No-ops when the document doesn’t exists or has already been deleted in the database.
* [x] delete(document) : Throws not allow exception if deleting a newly created document.
* [x] purge(document): No-ops when the document doesn’t exists in the database.
* [x] purge(document):Throws not allow exception if purging a newly created document.

ReplicatorConfiguration
* [x] getConflictResolver() returns the default one by default.
* [x] setConflictResolver(resolver) doesn’t allow to set null.
* [x] New Endpoint interface, NetworkEndpoint class, and DatabaseEndpoint class.
* [x] Use builder pattern.

DocumentChange 
* [x] Add getDatabase().

Parameters
* [x] Add getValue().
* [x] Use builder pattern.

Expression
* [x] Add all() to express * (star). This can be used to express count(*) and select *.

FullTextExpression
* [x] Change index(indexName) to index(name).

Function
* [x] Remove all type check functions.

ResultSet
* [x] Add toList() (NOTE: Implement UnmodifilableList and return it)

**Comment by pasin** [comment]
Update to Configuration and Parameters's Builder: https://github.com/couchbaselabs/couchbase-lite-apiv2/commit/ad7a29ae1872da9d41d4f1dfce71aeb28d26c7e3

**Comment by pasin** [comment]
I have just updated the Endpoint classes. Could you please make changes accordingly? Sorry for the immediate changes.

couchbaselabs/couchbase-lite-apiv2@49ac079

**Comment by hideki** [comment]
### save(doc) and delete(doc)
- [ ] Lock down the MutableDocument() after the save or delete operation is successful. Re-saving / deleting the old MutableDocument should throw not-allow error. The exact error message is TBD.

### ResultSet.toList() / toArray()
- [ ] In 2.0, we will iterate through the enumerator to create and return the Array of the result. The cursor should also be reset to the current cursor position (we could keep track of the current position when the next() is called) after returning the array. This is not the most efficient implementation which we may improve later. We don’t provide count() or move/seek(index) to the API, because they prevent us from changes or optimization at the LiteCore level in the future.

### SessionAuthenticator
- [ ] Remove expires as not used.
- [ ] Have two constructors, one with cookie name and one without. When the cookie name is not specified, use the default SGW session cookie name which is “SyncGatewaySession”.

### crossJOIN
- [ ] Remove ON expression.
