### ISSUE TITLE
addDocumentChangeListener behaviour issues

### ISSUE THREAD

**Issue by kuscsik** [couchbase/couchbase-lite-android#1545]
There is a strange behavior of the listener. If a listener is registered for a document ID, the document update is not propagated to the sync server.
Reproduced on: 2.0.0-DB021

For example:

If listener is set:

`database.addDocumentChangeListener("testId", listener);
`

The document update never hits the server:

```
        Document doc = database.getDocument("testId");
        MutableDocument mutableDocument;
        if(doc == null) {
            mutableDocument = new MutableDocument("testId");
        } else {
            mutableDocument = doc.toMutable();
        }
        mutableDocument.setValue("brand",  brand);
        try {
            database.save(mutableDocument);
        } catch (CouchbaseLiteException e) {
            e.printStackTrace();
         }
```

With logging enabled, I verified the document update is not detected by cauchbase lite, however, the document change listener callback is executed.

**Comment by hideki** [comment]
Hi @kuscsik,

Thank you for your report.
I have some clarification questions:
1. `the document update is not propagated to the sync server.` <-- Push replicate does not happen?
1. `the document update is not detected by cauchbase lite` What does this mean?
1. Do you setup replication with continuous mode?

Thanks!
Hideki

**Comment by kuscsik** [comment]
Hi @hideki 


1. Push replicate doesn't happen. The sync server not reporting any new lines when addDocumentChangeListener.

2. If no document changer listener set, I can see in the logs from
Replicator/DBWorker.cpp and prints the log  message **"Notified of1 db changes"** . If addDocumentChangeListener is set, this log message is not visible.

3. Replicator is set in continuous mode

This is my sample:
https://github.com/kuscsik/couchbase_android_lite_2.0_test/blob/master/app/src/main/java/com/example/couchbase_test/DbAdapter.java#L52

**Comment by hideki** [comment]
Hi @kuscsik,
Thank you very much for detail information and sample code.
It is a critical issue. We will look into this.
Thanks!

**Comment by hideki** [comment]
Hi @kuscsik,
Thank you again for sample codes. It helps us a lot. I could reproduce this issue with DB021. However, with latest build 2.0.0-288 which is DB022 candidate. Our engineer fixed other push replication issue, it seems that fix also solved this issue too.

We plan to release DB022 soon. If you can wait for it, please wait few more days.
In case you would' like to try the latest build, please used `2.0.0-288`. We changed some API between DB021 and DB022. You would face compilation error. To solve the problem can you refer unit test as sample codes?
```
compile 'com.couchbase.lite:couchbase-lite-android:2.0.0-288'
```
2.0.0-288 requires latest Sync Gateway. I used SG build `2.0.0-749`. you could download from the following link.
http://latestbuilds.service.couchbase.com/builds/latestbuilds/sync_gateway/2.0.0/749/

**Comment by kuscsik** [comment]
Thanks @hideki, looking forward test the fix.
