### ISSUE TITLE
1.4 Attachments: Bandwidth usage 5x more than it should be upon attachment upload

### ISSUE THREAD

**Issue by ancientmethods** [couchbase/couchbase-lite-android#1556]
Hello

We've had clients complain about the mobile data usage the app is consuming. Luckily Android studio has a great profiling tool so after digging in I realised that uploading attachments are causing 5x-6x more bandwidth usage than they should. 

In the graph below you can see the network consumption right after the attachment file PUT call.  You can see the upload finished after 10 seconds and if you take the median of the network axis at around 1.3mb/sec, this equates to roughly 13mb of data uploaded. The attachment file itself is only 2.2mb, and this rate is consistent with all file sizes and types (pds,mp3 etc..). I uploaded a 20mb mp3 file, and my data usage of my app on my mobile spiked by 100mb. 

<img width="979" alt="screen shot 2018-01-26 at 10 21 55" src="https://user-images.githubusercontent.com/8930383/35436791-b81ab9e6-0287-11e8-9e42-875baa8a2819.png">

I'm using couchbase lite 1.4 and using the standard method for uploading attachments. 

` 
UnsavedRevision newRev = doc1.getCurrentRevision().createRevision();
newRev.setAttachment(file_name, mime_type, stream);
newRev.save();`
`
The weird thing is that the PUT request itself seems fine in terms of the content size, but when that call executes, I've setup a breakpoint on the  'response = call.execute()' line in the sdk and I can see those results in the graph. At that moment, the profiler in Android studio can show you all active http requests, and the only active call is this PUT attachment file call, so it really can't be anything else. 

<img width="1365" alt="screen shot 2018-01-26 at 10 44 47" src="https://user-images.githubusercontent.com/8930383/35436758-9a3f0a12-0287-11e8-9e91-6b296444743c.png">

Thanks for your time.

**Comment by hideki** [comment]
Hi @ancientmethods,

Thank you for your report.

As CBL set the `InputStream` of attachment to `OkHttp`, CBL does not do anything special like base64 encoding or etc.

In second screen capture image, you highlighted `declaredLength` property. It is Couchbase module, its value is set by CBL.

https://github.com/couchbase/couchbase-lite-java-core/blob/1ae4c0d1873d1287c725406ceaf8035014fb4927/src/main/java/com/couchbase/lite/replicator/BlobRequestBody.java#L78-L91

**Comment by hideki** [comment]
TODOs:

- Measure data usage by a simple single document with an attachment which is around 2MB.
- Measure OkHttp's PUT command data usage with a 2MB image file.

**Comment by ancientmethods** [comment]
@hideki 

I discovered that I had multiple push replications running at the same time, which is awkard itself as each replication was created with the same url, hence should have the same checkpoint id. So I usually would do this upon application startup : 


```
 Replication pushReplication;
 pushReplication = App.getDatabase().createPushReplication(syncUrl);
 pushReplication.setContinuous(true);
 pushReplication.start();
```
This was creating a new replication instance that was running alongside the others, and hence the file upload was happening on each replication. I will make the necessary checks and make sure only one push replication runs all the time. Is it normal that a new push replication instance gets created? 

Thanks for your time.
