### ISSUE TITLE
2.0 DB21 Duplicate MutuableDocument Exception Handling

### ISSUE THREAD

**Issue by natgross** [couchbase/couchbase-lite-android#1591]
[Android] Two  problems when creating duplicate (id's) documents. (Might be different issues but same code snippet illustrates both.) 
1. If you call db.save() with the same id consecutively -twice-, NO ERROR is reported and an exception is NOT thrown. The second attempt is rejected in the db, but code flows as if all is ok.
This happens ONLY on the second attempt -of the same id-. and it happens every time.

2. After the second db.save(), an exception is reported in the log, but is consumed in the root class somewhere and NOT thrown in my code, again allowing the code flow to continue as if nothing wrong happened.

Code snippet with simple instructions follows.
```java
private void newMutableDocTest(Database db, String id) {

        if (id == null || id.isEmpty()) return;
        final MutableDocument doc = new MutableDocument(id);
        //any test data - whatever
        doc.setString("s1", "s1 " + id);
        doc.setString("s2", "s2 " + id);
        doc.setDate("Date1", new Date());
        doc.setDate("Date2", new Date());
        doc.setBoolean("Bool1", true);
        doc.setLong("Long1", System.currentTimeMillis());
        try {
            db.save(doc); 
            System.out.println("TEST NEW DOCUMENT. ID = " + doc.getId());
        } catch (CouchbaseLiteException e) {
            e.printStackTrace();
        }
    }
```
Calling this method consecutively with the same id  will ALWAYS println the line after the save. From the 3rd time and beyond the log will produce "I/LiteCore [DB]: DataFile: abort transaction" error, but in the log only.  Code flow continues as if everything is ok.

**Comment by hideki** [comment]
1. Default Conflict resolver is used. https://github.com/couchbase/couchbase-lite-android/blob/feature/2.0/shared/src/main/java/com/couchbase/lite/DefaultConflictResolver.java
Both are same Doc ID and same generation. Winner depends on revision ID. 

2. With the latest code, I can not observe this exception. I guess printing stack trace is removed from the latest code.

> Calling this method consecutively with the same id will ALWAYS println the line after the save. From the 3rd time and beyond the log will produce "I/LiteCore [DB]: DataFile: abort transaction" error, but in the log only. Code flow continues as if everything is ok.

Because of documents are conflicting by same docID and same generation. the second save operation aborts from a transaction. It is INFORMATION level logging.

I hope this helps.

**Comment by natgross** [comment]
@hideki I don't think you read my post.
The second save is not aborting the transaction.
Why is the second save() different than the third?
Also, are you saying that the db simply allows creation of NEW documents with the same ID without an exception? Note. This method is NOT saving the same document twice, a new document with the same id is being created.

**Comment by hideki** [comment]
> The second save is not aborting the transaction.
> Why is the second save() different than the third?

can you post the log file. It seems I misunderstand the your problem.

> Also, are you saying that the db simply allows creation of NEW documents with the same ID without an exception? Note. This method is NOT saving the same document twice, a new document with the same id is being created.

CBL 2.0 treats that saving **new** document with existing docID is a **conflicted** document. So conflict resolver is kicked in.

To overwrite the document, need to obtain the document from the database first. then save.
```java
// second save
Document doc = db.getDocument(id);
MutableDocument mdoc = doc.toMutable();
mdoc.setValue(....);
db.save(mdoc);
```

**Comment by natgross** [comment]
Following method makes it clearer:

`
for (int i = 1; i < 5; i++) {

            System.out.println("Iteration: " + i + " START");
            final MutableDocument doc = new MutableDocument("100"); //New document with same id used in every iteration.
            doc.setString("property1", "This is property1");
            try {
                db.save(doc); //if duplicate new doc, an exception needs to abort the try block and NOT continue to the Sustem.out.println's
                System.out.println("SAVED NEW DOCUMENT. ID = " + doc.getId());
                System.out.println("Iteration: " + i + " END ");
            } catch (CouchbaseLiteException e) {
                e.printStackTrace();
            }
        }
`

And following is the log of the aforementioned loop. (Note the second iteration is the same as the 1st while the 3rd, 4th... differ from the second. But they are all doing exactly the same thing in the same loop!)

I/System.out: Iteration: 1 START
I/System.out: SAVED NEW DOCUMENT. ID = 100
I/System.out: Iteration: 1 END 

I/System.out: Iteration: 2 START
I/System.out: SAVED NEW DOCUMENT. ID = 100
I/System.out: Iteration: 2 END 

I/System.out: Iteration: 3 START
I/LiteCore [DB]: DataFile: abort transaction
I/System.out: SAVED NEW DOCUMENT. ID = 100
I/System.out: Iteration: 3 END 

I/System.out: Iteration: 4 START
I/LiteCore [DB]: DataFile: abort transaction
I/System.out: SAVED NEW DOCUMENT. ID = 100
I/System.out: Iteration: 4 END

**Comment by natgross** [comment]
continued... The error message from cblite "/LiteCore [DB]: DataFile: abort transaction" does NOT happen the second time.
But the real problem is that an exception needs to be thrown to disallow the save()! This is NOT a conflict! This is basic database, any db.

**Comment by natgross** [comment]
@hideki Would issue #1577 fix this problem? (Since CouchBaseLite Exception) would be thrown.)

**Comment by natgross** [comment]
@hideki I **rewrote** the little test yet again, and have discovered the answer - _and a far more serious problem_.  The second save (NEW DOCUMENT) OVERWRITES the first! And the other saves do not.
Here is a new code snippet (1 method) that you can run. 
<
    
    private void duplicateMutableDocTest(Database db) {
        System.out.println("duplicateMutableDocTest - START -");
        final Long randomID = System.currentTimeMillis();
        final String aNewID = randomID.toString();
        final String IterationNumberKey = "IterationNum";
        for (int i = 1; i < 5; i++) {
            System.out.println("Iteration: " + i + " START");
            final MutableDocument doc = new MutableDocument(aNewID); //New document with same id used in every iteration.
            final String iterationNumberValue = "This is iteration # " + i;
            doc.setString(IterationNumberKey, iterationNumberValue);
            System.out.println("iterationNumberValue stored in document = " + iterationNumberValue);
            try {
                db.save(doc);
                System.out.println("SAVED NEW DOCUMENT. ID = " + doc.getId());
                System.out.println("Iteration: " + i + " END\n");
            } catch (CouchbaseLiteException e) {
                e.printStackTrace();
            }
        }
        System.out.println("After the loop, let's find the document and ascertain that only the first iteration was actually saved.");
        final Document doc = db.getDocument(aNewID); //if for some unseen reason, doc is not found, the following println will npe, so that we know we have a new real problem.
        System.out.println("Document with ID: " + doc.getId() + " fetched ok. The IterationNum String stored within is: " + doc.getString(IterationNumberKey));
        System.out.println("duplicateMutableDocTest - END -\n");
    }

>
The simple solution to this is NOT to treat NEW documents with the same id as a conflict. Simply disallow the duplicate save. This is expected behavior from any database - including Couchbase Server (as well as cbl 1.x).
nat

**Comment by natgross** [comment]
@hideki Good news is that DB22 has fixed the inconsistent part, and now all saves after the first behave consistently, and do not overwrite the first save.
So the remaining question is: how do I know if a save caused a **I/LiteCore [DB]: DataFile: abort transaction** due to a duplicate id? (Without having to manually find and check for null document) since this error/exception is not thrown back to my code.
Thanks

**Comment by pasin** [comment]
@natgross doe you mean the above code snippet causes the null document returned with "I/LiteCore [DB]: DataFile: abort transaction" message in the log when saving the second doc that has the same ID as the previous one?

**Comment by natgross** [comment]
I put up a new Gist with a little more elaborate test (and with the log results! so you need not run the test) here. 
https://gist.github.com/natgross/53d5c0e0d20b6f3a2e8ef40395fc2039#file-duplicatedoctest_cbl-java

Please see the comment(s) on the Gist for a link to another Gist containing the log.
1. null document is NOT returned. So that might be ok. 
2. The successive saves are aborted and not saved, but a CBLException is not thrown.
Please have a look at this Gist and if no time to run it, the output link is in the comments there.

**Comment by hideki** [comment]
Hi @natgross,
Thanks for providing the test case, and sorry for taking a time to reply. 

The test case you provided causes a conflict when `Database.save(MutableDocument)` method is called since the second iteration as document ID is same and parent revision is not known (new document, but document already exists). When conflict happens, CBL calls [`DefaultConflictResolver`](https://github.com/couchbase/couchbase-lite-android/blob/dbd0a80ce303d89935429fe4aef8e2fe6a5230de/shared/src/main/java/com/couchbase/lite/DefaultConflictResolver.java) which solve the conflict. Because new document's generation is 1 and revision id is null, so always existing document wins.

Please check additional logging message and DefaultConflictResolver implementation.
```
   @Test
    public void duplicateMutableDocTest() {
        duplicateMutableDocTest(db);
    }

    private void duplicateMutableDocTest(Database db) {
        System.out.println("duplicateMutableDocTest - START -");
        final Long randomID = System.currentTimeMillis();
        final String aNewID = randomID.toString();
        final String IterationNumberKey = "IterationNum";
        for (int i = 1; i < 5; i++) {
            System.out.println("Iteration: " + i + " START");
            final MutableDocument doc = new MutableDocument(aNewID); //New document with same id used in every iteration.
            final String iterationNumberValue = "This is iteration # " + i;
            doc.setString(IterationNumberKey, iterationNumberValue);
            System.out.println("iterationNumberValue stored in document = " + iterationNumberValue);
            try {
                final Document docReturned = db.save(doc);
                System.out.println("SAVED NEW DOCUMENT. ID = " + doc.getId());
                System.out.println("DOCUMENT GENERATION =   = " + doc.generation());
                System.out.println("DOCUMENT REV ID =   = " + doc.getRevID());
                System.out.println("DOCUMENT SEQUENCE = " + doc.getSequence());
                System.out.println("DOCUMENT RETURNED ID = " + docReturned.getId());
                System.out.println("RETURNED GENERATION =   = " + docReturned.generation());
                System.out.println("RETURNED REV ID =   = " + docReturned.getRevID());
                System.out.println("RETURNED SEQUENCE = " + docReturned.getSequence());
                System.out.println("RETURNED DOCUMENT IterationNum String stored within is: " + docReturned.getString(IterationNumberKey));
                System.out.println("Iteration: " + i + " END\n");
            } catch (CouchbaseLiteException e) {
                e.printStackTrace();
            }
        }
        System.out.println("After the loop, let's find the document and ascertain that only the first iteration was actually saved.");
        final Document doc = db.getDocument(aNewID); //if for some unseen reason, doc is not found, the following println will npe, so that we know we have a new real problem.
        System.out.println("Document with ID: " + doc.getId() + " fetched ok. The IterationNum String stored within is: " + doc.getString(IterationNumberKey));
        System.out.println("DOCUMENT SEQUENCE = " + doc.getSequence());
        System.out.println("duplicateMutableDocTest - END -\n");
    }
```

Current CBL behavior is expected. 

If you have a suggestion, please let us know. For example, throw Exception instead of solving the conflict, etc.

As this is not issue, I will close this ticket now.
