### ISSUE TITLE
Expression.in() is not working! DB021 version

### ISSUE THREAD

**Issue by itaishalom** [couchbase/couchbase-lite-android#1592]
Hi all.
Apparently, I'm unable to use operator in().
I wish to look inside arraylist inside hashmap inside document.
This is the test code:

```
    private void test3() {
DBHandler dbHand = DBHandler.getInstance(this);
        MutableDocument newDoc = new MutableDocument();
        HashMap map = new HashMap();
        ArrayList<String> values = new ArrayList<>();
        values.add("first");
        values.add("second");
        map.put("name", "map");
        map.put("array", values);
        newDoc.setValue(HASH_MAP, map);
        try {
            lock.lock();
            dbHand.mDb.save(newDoc);

        } catch (CouchbaseLiteException e) {
            e.printStackTrace();
        } finally {
            if (lock.isLocked()) {
                lock.unlock();
            }
        }
        Expression where1 = Expression.property(HASH_MAP+"."+"array").in("first");
        Expression where1_working = Expression.property(HASH_MAP+"."+"array[0]").in("first"); //The only one is working
        Expression where2 = Expression.property("first").in(HASH_MAP+"."+"array");
        queryTest3(where1);
        queryTest3(where1_working);
        queryTest3(where2);
    }


  private void queryTest3(Expression where) {
        Query query = Query.select(SelectResult.all()).from(DataSource.database(DBHandler.getInstance().mDb)).where(where);
        lock.lock();
        ResultSet resultSet = null;
        try {
            resultSet = query.execute();
        } catch (CouchbaseLiteException e) {
            e.printStackTrace();
        }
        lock.unlock();
        if (resultSet != null) {
            Result row;
            while ((row = resultSet.next()) != null) {
                Dictionary dictionary = (Dictionary) row.getValue(HASH_MAP);
                HashMap map = new HashMap(dictionary.toMap());
                Log.d("MainActivity", "queryTest3: " + map.get("name"));
            }
        }
    }

```
For some reason, only where1_working expression is working. The desired behavior is that the where1 will work because if I wish to look for "second", array[0] is incorrect. in() should look inside all the arraylist.

for testing check my git:
https://github.com/itaishalom/CouchBase

test number 3

**Comment by rajagp** [comment]
> Expression where1 = Expression.property(HASH_MAP+"."+"array").in("first");
        
The `in` expression is used to look for matches in an array. It looks like you are passing a string value. So can you try
Expression where1 = Expression.property(HASH_MAP+"."+"array").in(["first"]);

In DB022/ future releases, this would be an Expression type, so trying to pass a raw string would fail

**Comment by itaishalom** [comment]
I'm not sure I understand you.
How can I query the db in order to get the documents? If I wish to look for any hashmap that contains "second" inside the array, how do I do it? In this release and in future release?

**Comment by rajagp** [comment]
From ` Expression where1 = Expression.property(HASH_MAP+"."+"array").in("first");` 

 It seems  like you are looking for the string "first" within  the nested `array` member of HASH_MAP property (HASH_MAP.array).  Isn't that what you are trying to do ? 

if so, there are couple of ways to do it :- 
This is in DB022 syntax  ..but you can do the equivalent in db021 as well with some syntactical tweaks. 

- use `ArrayFunction`. 
```
      Expression exArrayContains1 = ArrayFunction.contains(Expression.property(HASH_MAP+"."+"array"), Expression.string("first"));
```

- If you are using `in` clause, then your in expression would have to specify an array . The issue that you are sending in a string value ..

```
 Expression where = Expression.parameter("value").in(Expression.property(HASH_MAP+"."+"array"));
 Parameters params = new Parameters(myQuery.getParameters()).setValue("value", "first);
       myQuery.setParameters(params);
```

There are probably other ways as well...

**Comment by pasin** [comment]
That should work with ArrayFunction or ArrayExpression as @rajagp described. Using IN([Expression]) will not work for this case because IN expression takes an array of expressions. If using ArrayFunction or ArrayExpressions don't work, please let us know.

**Comment by itaishalom** [comment]
Thanks, that was it.

**Comment by rajagp** [comment]
@itaishalom Again, as mentioned in other topic, in future please use the Developer Forums for questions and clarifications.
