### ISSUE TITLE
Error:Could not find jai_core.jar - DB22

### ISSUE THREAD

**Issue by itaishalom** [couchbase/couchbase-lite-android#1593]
I tried to pull version 22 this morning and I got this:

Error:Could not find jai_core.jar (javax.media:jai_core:1.1.3).
Searched in the following locations:
    https://jcenter.bintray.com/javax/media/jai_core/1.1.3/jai_core-1.1.3.jar

My gradle file:

```
allprojects {
    repositories {
        jcenter()
        maven {
            url "http://mobile.maven.couchbase.com/maven2/dev/"
        }
```

And the second:
```
dependencies {
  compile 'com.couchbase.lite:couchbase-lite-android:2.0.0-DB022'
```

**Comment by itaishalom** [comment]
Worked from another env.

**Comment by rajagp** [comment]
@itaishalom  In future, please use the Developer Forums for such questions/issues. If there is in fact a bug, we will open one here accordingly.
