### ISSUE TITLE
liveQuery remains alive

### ISSUE THREAD

**Issue by itaishalom** [couchbase/couchbase-lite-android#1595]
Hi, I'm trying to create a live query that will be updated each time the changed() is called.
For example, every time the changed() is called, update the where expression to bring new documents that were added from now on (To avoid brining documents from last time).
My solution was to remove the query listner and add a new one but I see on the logs that the query remains alive and after each insertetion there is new line, so after 5 insertion I'll get 

```
I/LiteCore [SQL]: Created prerecorded query enum with 1 rows (Y bytes) in Xms

I/LiteCore [SQL]: Created prerecorded query enum with 2 rows (Y bytes) in Xms

I/LiteCore [SQL]: Created prerecorded query enum with 3 rows (Y bytes) in Xms

I/LiteCore [SQL]: Created prerecorded query enum with 4 rows (Y bytes) in Xms
```

Although the changed() function is called only once with the latestet document.

So, I tried only removing the old listneres but the query still runs (See it on logs) but no new lines are added.
This is a test code :

 ```
 private void startliveQuery() {
        Expression whereExp = Expression.property(DB_UPDATE_TIME_COLUMN_NAME).greaterThan(Expression.longValue(lastSelectedTime));
        mQuery = QueryBuilder.select(SelectResult.all())
                        .from(DataSource.database(mDatabase))
                        .where(whereExp );
        mQueryListener = new myListener();
        mToken = mQuery.addChangeListener(mQueryListener);
    }
	
	 public class myListener implements QueryChangeListener {

        String mUri;

        ReactiveLayerListener() {
            mUri = uriToBroadcast;
        }

        @Override
        public void changed(QueryChange queryChange) {

            ResultSet rows = queryChange.getResults();
            Result row;
			//Do something with the results();
			  mQuery.removeChangeListener(mToken);
			mQueryListener = null;
			lastSelectedTime = System.currentTimeMillis();
Expression where = Expression.property(DB_UPDATE_TIME_COLUMN_NAME).greaterThan(Expression.longValue(lastSelectedTime));
mQuery = somefunction(where ); //Using queryBuilder creates Query object
mToken = mQuery.addChangeListener(mQueryListener);
		}
	}


```

My question is, how do I do it properly? 
How do I create only one listener that will be updated and I won't see old queries running on logs?

**Comment by itaishalom** [comment]
So, I tried only removing the old listneres but the query still runs (See it on logs) but no new lines are added.
This is a test code :
``
  private void startliveQuery() {
        Expression where = Expression.property(DB_UPDATE_TIME_COLUMN_NAME).greaterThan(Expression.longValue(lastSelectedTime));
        mQuery = somefunction(); //Using queryBuilder creates Query object
        mQueryListener = new myListener();
        mToken = mQuery.addChangeListener(mQueryListener);
    }
	
	 public class myListener implements QueryChangeListener {

        String mUri;

        ReactiveLayerListener() {
            mUri = uriToBroadcast;
        }

        @Override
        public void changed(QueryChange queryChange) {

            ResultSet rows = queryChange.getResults();
            Result row;
			//Do something with the results();
			  mQuery.removeChangeListener(mToken);
			mQueryListener = null;
			lastSelectedTime = System.currentTimeMillis();
		}
	}
``

**Comment by rajagp** [comment]
@itaishalom  Please move this question to the Forums so we can track it there . If there is in fact a bug or feature request, we will raise one accordingly.

**Comment by itaishalom** [comment]
Ok but note that you do not respond to threads I opened before like this one
https://forums.couchbase.com/t/requests-for-build-2-0-0-db022-android/15599/3

I found out that you only response here.
Anyway I opened a new thread for this issue:
https://forums.couchbase.com/t/livequery-remains-alive/15786
