### ISSUE TITLE
BLIP message invalid checksum

### ISSUE THREAD

**Issue by ascendancy05** [couchbase/couchbase-lite-android#1596]
Couchbase Sync Gateway/1.5.1(4;cb9522c)
com.couchbase.lite:couchbase-lite-android:2.0.0-DB022

Getting the following error when trying to start replication after successful auth:

02-12 17:17:33.737  7081  7205 E LiteCore [BLIP]: {N8litecore4blip6BLIPIOE#2} Caught exception handling incoming BLIP message: BLIP message invalid checksum
02-12 17:17:33.738  7081  7205 E C4Socket: C4Socket.callback.requestClose() socket -> 0xa886956c, status -> 1006, message -> BLIP message invalid checksum
02-12 17:17:33.739  7081  7205 E AndroidRuntime: FATAL EXCEPTION: Thread-24
02-12 17:17:33.739  7081  7205 E AndroidRuntime: Process: com.mypackage.myapp, PID: 7081
02-12 17:17:33.739  7081  7205 E AndroidRuntime: java.lang.IllegalArgumentException: Code 1006 is reserved and may not be used.
02-12 17:17:33.739  7081  7205 E AndroidRuntime: 	at okhttp3.internal.ws.WebSocketProtocol.validateCloseCode(WebSocketProtocol.java:120)
02-12 17:17:33.739  7081  7205 E AndroidRuntime: 	at okhttp3.internal.ws.RealWebSocket.close(RealWebSocket.java:401)
02-12 17:17:33.739  7081  7205 E AndroidRuntime: 	at okhttp3.internal.ws.RealWebSocket.close(RealWebSocket.java:397)
02-12 17:17:33.739  7081  7205 E AndroidRuntime: 	at com.couchbase.lite.internal.replicator.CBLWebSocket.requestClose(CBLWebSocket.java:226)
02-12 17:17:33.739  7081  7205 E AndroidRuntime: 	at com.couchbase.litecore.C4Socket.requestClose(C4Socket.java:155)
02-12 17:17:33.741  1651  1959 W ActivityManager:   Force finishing activity com.mypackage.myapp/com.mypackage.myapp.MyActivity

Not exactly sure where to go from here. The URL being used to sync against is of the format wss://host.name.com:4984/db

**Comment by djpongh** [comment]
With Couchbase Lite 2.0 DB22 you also need to upgrade to Sync Gateway 2.0 Beta (you can find in the pre-release section of the downloads page).

**Comment by djpongh** [comment]
If you still see issues after upgrading, feel free to re-open.

**Comment by ascendancy05** [comment]
@djpongh Is the Sync Gateway 2.0 Beta backwards compatible to earlier versions of the CBL DB? (Example: DB20)
