### ISSUE TITLE
Join query doesn't return any result for CBL app

### ISSUE THREAD

**Issue by hrajput89** [couchbase/couchbase-lite-android#1600]
I'm running a join query on travel-sample bucket data. I'm getting result for the equivalent n1ql query, but not getting any result for cbl query.

Result from CBS for below query - 
```
SELECT DISTINCT airline.name, airline.callsign, route.destinationairport, route.stops, route.airline
FROM `travel-sample` route 
  JOIN `travel-sample` airline 
  ON KEYS route.airlineid 
WHERE route.type = "route" 
  AND airline.type = "airline" 
  AND route.sourceairport = "SFO" 
LIMIT 5;
```
<img width="1406" alt="cbs run for join query" src="https://user-images.githubusercontent.com/18100038/36250058-b6a21902-1262-11e8-9619-308024e6649b.png">

Method for Join query
```
public List<Object> join(Args args) throws CouchbaseLiteException {
        Database db = args.get("database");
        String prop1 = args.get("select_property1");
        String prop2 = args.get("select_property2");
        String prop3 = args.get("select_property3");
        String prop4 = args.get("select_property4");
        String prop5 = args.get("select_property5");
        String joinKey = args.get("join_key");
        String whrKey1 = args.get("whr_key1");
        String whrKey2 = args.get("whr_key2");
        String whrKey3 = args.get("whr_key3");
        Expression limit = Expression.value(args.get("limit"));
        Expression whrVal1 = Expression.value(args.get("whr_val1"));
        Expression whrVal2 = Expression.value(args.get("whr_val2"));
        Expression whrVal3 = Expression.value(args.get("whr_val3"));
        String main = "route";
        String secondary = "airline";

        List<Object> resultArray = new ArrayList<Object>();

        Query query = QueryBuilder
                .selectDistinct(
                        SelectResult.expression(Expression.property(prop1).from(secondary)),
                        SelectResult.expression(Expression.property(prop2).from(secondary)),
                        SelectResult.expression(Expression.property(prop3).from(main)),
                        SelectResult.expression(Expression.property(prop4).from(main)),
                        SelectResult.expression(Expression.property(prop5).from(main)))
                .from(DataSource.database(db).as(main))
                .join(Join.join(DataSource.database(db).as(secondary))
                    .on(Meta.id.from(secondary).equalTo(Expression.property(joinKey).from(main))))
                .where(Expression.property(whrKey1).from(main).equalTo(whrVal1)
                    .and(Expression.property(whrKey2).from(secondary).equalTo(whrVal2))
                    .and(Expression.property(whrKey3).from(main).equalTo(whrVal3)))
                .limit(limit);
        for (Result row : query.execute()){
            resultArray.add(row.toMap());
        }
        return resultArray;
    }
```
Logs from CBL app
[cbl_logs_for_join_query.log](https://github.com/couchbase/couchbase-lite-android/files/1727078/cbl_logs_for_join_query.log)

**Comment by snej** [comment]
What version/build of CBL?

**Comment by hrajput89** [comment]
Android build 2.0.0-299

**Comment by snej** [comment]
The relevant lines from the log:

`I/LiteCore [SQL]: Compiling JSON query: {"WHAT":[[".airline.name"],[".airline.callsign"],[".route.destinationairport"],[".route.stops"],[".route.airline"]],"FROM":[{"AS":"route"},{"AS":"airline","ON":["=",[".airline._id"],[".route.airlineid"]],"JOIN":"INNER"}],"WHERE":["AND",["AND",["=",[".route.type"],"route"],["=",[".airline.type"],"airline"]],["=",[".route.sourceairport"],"SFO"]],"DISTINCT":true,"LIMIT":"5"}`

`I/LiteCore [SQL]: Compiled Query: SELECT DISTINCT fl_result(fl_value("airline".body, 'name')), fl_result(fl_value("airline".body, 'callsign')), fl_result(fl_value("route".body, 'destinationairport')), fl_result(fl_value("route".body, 'stops')), fl_result(fl_value("route".body, 'airline')) FROM kv_default AS "route" INNER JOIN kv_default AS "airline" ON ("airline".key = fl_value("route".body, 'airlineid')) AND ("airline".flags & 1) = 0 WHERE ((fl_value("route".body, 'type') = 'route' AND fl_value("airline".body, 'type') = 'airline') AND fl_value("route".body, 'sourceairport') = 'SFO') AND ("route".flags & 1) = 0 LIMIT MAX(0, '5')`

`I/LiteCore [SQL]: Created prerecorded query enum with 0 rows (2 bytes) in 0.049ms`

**Comment by snej** [comment]
```
SELECT DISTINCT fl_result(fl_value("airline".body, 'name')),
                fl_result(fl_value("airline".body, 'callsign')),
                fl_result(fl_value("route".body, 'destinationairport')),
                fl_result(fl_value("route".body, 'stops')), 
                fl_result(fl_value("route".body, 'airline'))
FROM kv_default AS "route"
INNER JOIN kv_default AS "airline"
        ON ("airline".key = fl_value("route".body, 'airlineid')) 
           AND ("airline".flags & 1) = 0 
WHERE ((fl_value("route".body, 'type') = 'route' 
  AND fl_value("airline".body, 'type') = 'airline')
  AND fl_value("route".body, 'sourceairport') = 'SFO')
  AND ("route".flags & 1) = 0 LIMIT MAX(0, '5')
```

**Comment by snej** [comment]
The only thing that looks weird there is `LIMIT MAX(0, '5')` where the `5` is a string ... I'm not sure if SQLite will coerce that to a number or just treat it as zero or what.

Does the query work correctly if you change `limit` to an integer?

**Comment by snej** [comment]
Looks OK actually:
```
sqlite> select max(0, '5');
max(0, '5') = 5
```

**Comment by snej** [comment]
Oddly, the JSON query works for me in the cblite tool:
```
(cblite) query "{'WHAT':[['.airline.name'],['.airline.callsign'],['.route.destinationairport'],['.route.stops'],['.route.airline']],'FROM':[{'AS':'route'},{'AS':'airline','ON':['=',['.airline._id'],['.route.airlineid']],'JOIN':'INNER'}],'WHERE':['AND',['AND',['=',['.route.type'],'route'],['=',['.airline.type'],'airline']],['=',['.route.sourceairport'],'SFO']],'DISTINCT':true,'LIMIT':'5'}"
["JetBlue Airways", "JETBLUE", "AUS", 0, "B6"]
["JetBlue Airways", "JETBLUE", "BOS", 0, "B6"]
["JetBlue Airways", "JETBLUE", "DXB", 0, "B6"]
["JetBlue Airways", "JETBLUE", "FLL", 0, "B6"]
["JetBlue Airways", "JETBLUE", "JFK", 0, "B6"]
```
(That's not the same set of 5 results as Hemant got, but the query has no ORDER BY clause so the order of results is undefined.)

**Comment by hrajput89** [comment]
@snej, as you have pointed out below, limit should expect a int. I'm able to get result after fixing the issue

> The only thing that looks weird there is LIMIT MAX(0, '5') where the 5 is a string ... I'm not sure if SQLite will coerce that to a number or just treat it as zero or what.
