### ISSUE TITLE
"IS NOT NULL" query doesn't return same result as n1ql

### ISSUE THREAD

**Issue by hrajput89** [couchbase/couchbase-lite-android#1602]
IS NOT NULL returns all the document except when "callsign" is "null". Whereas n1ql return all docs where callsign is there and is not null. I'm using travel-sample default bucket data (31591 docs in both CBS and CBL app). 

- System Info -
 -- CBS 5.5.0-1877 on centos6
 -- CBL app on android 2.0.0-299
 -- SG 2.0.0-773 on Centos6
 

- Query Method 
```
public List<Object> isNot(Args args) throws CouchbaseLiteException {
        //SELECT * FROM `travel-sample` where callsign is not null limit 5
        Database db = args.get("database");
        String prop = args.get("prop");

        List<Object> resultArray = new ArrayList<>();

        Query query = QueryBuilder
                .select(SelectResult.expression(Meta.id),
                        SelectResult.expression(Expression.property("callsign")))
                .from(DataSource.database(db))
                .where(Expression.property(prop).isNot(Expression.value(null)))
                .orderBy(Ordering.expression(Meta.id).ascending());
        for (Result row : query.execute()) {
            resultArray.add(row.toMap());
        }
        return resultArray;
    }

```
- N1Ql query
`select count(*) FROM `travel-sample` WHERE callsign IS NOT NULL`

- Query Result
```
[
  {
    "$1": 166
  }
]
```

- CBL Query
```
I/LiteCore [DB]: Opening DataFile /data/user/0/com.couchbase.TestServerApp/files/test_db.cblite2/db.sqlite3
V/Query: Query encoded as {"WHAT":[["._id"],[".callsign"]],"ORDER_BY":[["._id"]],"WHERE":["IS NOT",[".callsign"],null]}
I/LiteCore [SQL]: Compiling JSON query: {"WHAT":[["._id"],[".callsign"]],"ORDER_BY":[["._id"]],"WHERE":["IS NOT",[".callsign"],null]}
I/LiteCore [SQL]: Compiled Query: SELECT fl_result(key), fl_result(fl_value(body, 'callsign')) FROM kv_default WHERE (fl_value(body, 'callsign') IS NOT x'') AND (flags & 1) = 0 ORDER BY key
I/LiteCore [SQL]: Created prerecorded query enum with 31570 rows (842318 bytes) in 113.068ms
```

**Comment by snej** [comment]
The SQL translation of the `IS NOT NULL` test is `fl_value(body, 'callsign') IS NOT x''` (where `x''` is an empty blob, which is how we represent a JSON `null`.) The discrepancy here is when the result of fl_value is MISSING, which is a SQL NULL.

The SQLite docs say "If one operand is NULL [i.e. MISSING] and the other is not, then the IS operator evaluates to 0 (false) and the IS NOT operator is 1 (true)." Which explains the discrepancy.

**Comment by snej** [comment]
I'm wondering if IS NOT NULL is a special operator in N1QL, or whether IS NOT just behaves differently when its right hand side is NULL?

**Comment by snej** [comment]
Oh, and I just noticed this was filed under Android when it's a LiteCore issue...

**Comment by snej** [comment]
This issue was moved to couchbase/couchbase-lite-core#410
