### ISSUE TITLE
Removing LiveQuery listener does not seem to stop the query 

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-android#1606]
_From @rajagp on February 15, 2018 16:46_

Originally from [forums](https://forums.couchbase.com/t/livequery-remains-alive/15786/8) . Reported on Android but appears to be a lite core issue.

**Issue** 
------
1. Create a live query. 
2. In query listener callback, remove the query listener to stop the query
3. Re-create the query object with new where criteria
4. Reattach the listener

**Expected**
-----------
- Only one query executed (per new where criteria)
- One callback

**Observed**
------------
- One callback (so listeners are managed properly)
- But it seems like old version of query is still executed
After 5 inserts (i.e call back run 5 times so 5 updated queries).  Observing the following messages. Expect to see a single message with 1 row (since only doc matches the updated query).
```
I/LiteCore [SQL]: Created prerecorded query enum with 1 rows (Y bytes) in Xms

I/LiteCore [SQL]: Created prerecorded query enum with 2 rows (Y bytes) in Xms

I/LiteCore [SQL]: Created prerecorded query enum with 3 rows (Y bytes) in Xms

I/LiteCore [SQL]: Created prerecorded query enum with 4 rows (Y bytes) in Xms
```

**Alternative Solution**
-------------------
It was recommended that user parameterized queries (changed parameters to restart query) and that resolved . 

_Copied from original issue: couchbase/couchbase-lite-core#407_

**Comment by snej** [comment]
LiveQuery is implemented in CBL, not LiteCore -- all LiteCore provides is an API call to re-run a C4Query. So I think the investigation should start in CBL-Android.

**Comment by snej** [comment]
_From @rajagp on February 15, 2018 18:49_

Unless this didn't make it into DB022,  equivalent implementation in both Android and iOS
Both call `stop()` to stop the query when listener is removed. Does something more have to be done ?

This is the implementation
```
void removeChangeListener(QueryChangeListenerToken token) {
        synchronized (lock) {
            queryChangeListenerTokens.remove(token);
            if (queryChangeListenerTokens.isEmpty())
                stop(true);
        }
    }
```
And the `stop()` makes a call to remove listener from database
```
   public void removeChangeListener(ListenerToken token) {
        if (token == null)
            throw new IllegalArgumentException("a token parameter is null");

        synchronized (lock) {
            if (token instanceof DocumentChangeListenerToken)
                removeDocumentChangeListener((DocumentChangeListenerToken) token);
            else
                removeDatabaseChangeListener((DatabaseChangeListenerToken) token);
        }
    }
```

(CC @hideki , @pasin )

**Comment by hideki** [comment]
Hi @itaishalom,

I wrote the test to reproduce the daemon LiveQuery issue.
https://github.com/couchbase/couchbase-lite-android/blob/2f0876c92c27a0b30fc0fd4c29361e886bf70f7d/android/CouchbaseLite/src/androidTest/java/com/couchbase/lite/LiveQueryTest.java#L52-L140

However, I can not observe the daemon LiveQuery from log messages. Test updates LiveQuery three times (including initial one). In the log message, I can observe 3 queries. In general, `removeChangeListener(<Token>)` works as expected.

Log
```
02-19 15:28:57.159 24387-24402/com.couchbase.lite.test I/TestRunner: started: testRemovingLiveQuery(com.couchbase.lite.LiveQueryTest)
02-19 15:28:57.167 24387-24387/com.couchbase.lite.test I/MonitoringInstr: Activities that are still in CREATED to STOPPED: 0
02-19 15:28:57.212 24387-24402/com.couchbase.lite.test I/DB: Opening Database@d6f7458{name='testdb'} at path /data/user/0/com.couchbase.lite.test/files/CouchbaseLite/testdb.cblite2
02-19 15:28:57.213 24387-24402/com.couchbase.lite.test I/LiteCore [DB]: Opening DataFile /data/user/0/com.couchbase.lite.test/files/CouchbaseLite/testdb.cblite2/db.sqlite3
02-19 15:28:57.264 24387-24405/com.couchbase.lite.test I/Query: LiveQuery[OrderBy[json={ORDER_BY=[[.number1]], WHAT=[[._id]], WHERE=[>=, [.number1], 1]}]]: Querying...
02-19 15:28:57.274 24387-24405/com.couchbase.lite.test I/LiteCore [SQL]: Compiling JSON query: {"ORDER_BY":[[".number1"]],"WHAT":[["._id"]],"WHERE":[">=",[".number1"],1]}
02-19 15:28:57.276 24387-24405/com.couchbase.lite.test I/LiteCore [SQL]: Compiled Query: SELECT fl_result(key) FROM kv_default WHERE (fl_value(body, 'number1') >= 1) AND (flags & 1) = 0 ORDER BY fl_value(body, 'number1')
02-19 15:28:57.279 24387-24405/com.couchbase.lite.test I/LiteCore [SQL]: Created prerecorded query enum with 1 rows (18 bytes) in 0.390ms
02-19 15:28:57.286 24387-24407/com.couchbase.lite.test E/Test: 1 matched. update query
02-19 15:28:57.294 24387-24405/com.couchbase.lite.test I/Query: LiveQuery[OrderBy[json={ORDER_BY=[[.number1]], WHAT=[[._id]], WHERE=[>=, [.number1], 2]}]]: Querying...
02-19 15:28:57.299 24387-24405/com.couchbase.lite.test I/LiteCore [SQL]: Compiling JSON query: {"ORDER_BY":[[".number1"]],"WHAT":[["._id"]],"WHERE":[">=",[".number1"],2]}
02-19 15:28:57.299 24387-24405/com.couchbase.lite.test I/LiteCore [SQL]: Compiled Query: SELECT fl_result(key) FROM kv_default WHERE (fl_value(body, 'number1') >= 2) AND (flags & 1) = 0 ORDER BY fl_value(body, 'number1')
02-19 15:28:57.301 24387-24405/com.couchbase.lite.test I/LiteCore [SQL]: Created prerecorded query enum with 1 rows (18 bytes) in 0.270ms
02-19 15:28:57.304 24387-24407/com.couchbase.lite.test E/Test: 1 matched. update query
02-19 15:28:57.310 24387-24405/com.couchbase.lite.test I/Query: LiveQuery[OrderBy[json={ORDER_BY=[[.number1]], WHAT=[[._id]], WHERE=[>=, [.number1], 3]}]]: Querying...
02-19 15:28:57.314 24387-24405/com.couchbase.lite.test I/LiteCore [SQL]: Compiling JSON query: {"ORDER_BY":[[".number1"]],"WHAT":[["._id"]],"WHERE":[">=",[".number1"],3]}
02-19 15:28:57.314 24387-24405/com.couchbase.lite.test I/LiteCore [SQL]: Compiled Query: SELECT fl_result(key) FROM kv_default WHERE (fl_value(body, 'number1') >= 3) AND (flags & 1) = 0 ORDER BY fl_value(body, 'number1')
02-19 15:28:57.315 24387-24405/com.couchbase.lite.test I/LiteCore [SQL]: Created prerecorded query enum with 1 rows (18 bytes) in 0.230ms
02-19 15:28:57.317 24387-24407/com.couchbase.lite.test E/Test: 1 matched. update query
02-19 15:28:57.320 24387-24402/com.couchbase.lite.test I/DB: Closing Database@d6f7458{name='testdb'} at path /data/user/0/com.couchbase.lite.test/files/CouchbaseLite/testdb.cblite2/
02-19 15:28:57.320 24387-24402/com.couchbase.lite.test I/LiteCore [DB]: Closing DataFile
02-19 15:28:57.530 24387-24402/com.couchbase.lite.test I/TestRunner: finished: testRemovingLiveQuery(com.couchbase.lite.LiveQueryTest)
```

However, it is possible that there is multi-threading bug in somewhere. If you have time, can you write a simple application that can reproduce this issue? Or, if you can compile CBL from source code, can you debug if `LiveQuery.stop(boolean)` method is called from `LiveQuery.removeChangeListener(QueryChangeListenerToken)`?

**Comment by itaishalom** [comment]
@hideki Hi again. You should pay me for all the QA job I'm doing for you.
Check my latest commit: https://github.com/itaishalom/CouchBase
After pressing 4 times the button "Start test" I see the following log:

`02-20 09:36:19.494 4717-4717/com.example.itai.couchbasetest I/LiteCore [SQL]: Created prerecorded query enum with 1 rows (48 bytes) in 0.118ms
02-20 09:36:20.843 4717-4717/com.example.itai.couchbasetest I/LiteCore [SQL]: Compiling JSON query: {"WHAT":[["."]],"WHERE":[">",[".TIME"],1519112180838]}
02-20 09:36:20.844 4717-4717/com.example.itai.couchbasetest I/LiteCore [SQL]: Compiled Query: SELECT fl_result(fl_root(body)) FROM kv_default WHERE (fl_value(body, 'TIME') > 1519112180838) AND (flags & 1) = 0
02-20 09:36:20.845 4717-4717/com.example.itai.couchbasetest I/LiteCore [SQL]: Created prerecorded query enum with 0 rows (2 bytes) in 0.074ms
02-20 09:36:20.857 4717-4717/com.example.itai.couchbasetest I/Choreographer: Skipped 81 frames!  The application may be doing too much work on its main thread.
02-20 09:36:27.003 4717-4717/com.example.itai.couchbasetest I/LiteCore [SQL]: Created prerecorded query enum with 2 rows (84 bytes) in 0.130ms
02-20 09:36:27.005 4717-4717/com.example.itai.couchbasetest I/LiteCore [SQL]: Created prerecorded query enum with 1 rows (48 bytes) in 0.138ms
02-20 09:36:31.689 4717-4717/com.example.itai.couchbasetest I/LiteCore [SQL]: Compiling JSON query: {"WHAT":[["."]],"WHERE":[">",[".TIME"],1519112191681]}
02-20 09:36:31.690 4717-4717/com.example.itai.couchbasetest I/LiteCore [SQL]: Compiled Query: SELECT fl_result(fl_root(body)) FROM kv_default WHERE (fl_value(body, 'TIME') > 1519112191681) AND (flags & 1) = 0
02-20 09:36:31.691 4717-4717/com.example.itai.couchbasetest I/LiteCore [SQL]: Created prerecorded query enum with 0 rows (2 bytes) in 0.070ms
02-20 09:36:31.693 4717-4717/com.example.itai.couchbasetest I/Choreographer: Skipped 280 frames!  The application may be doing too much work on its main thread.
02-20 09:36:36.757 4717-4717/com.example.itai.couchbasetest I/LiteCore [SQL]: Created prerecorded query enum with 3 rows (120 bytes) in 0.123ms
02-20 09:36:36.758 4717-4717/com.example.itai.couchbasetest I/LiteCore [SQL]: Created prerecorded query enum with 1 rows (48 bytes) in 0.091ms
02-20 09:36:36.759 4717-4717/com.example.itai.couchbasetest I/LiteCore [SQL]: Created prerecorded query enum with 2 rows (84 bytes) in 0.120ms
02-20 09:36:36.764 4717-4717/com.example.itai.couchbasetest I/LiteCore [SQL]: Compiling JSON query: {"WHAT":[["."]],"WHERE":[">",[".TIME"],1519112196760]}
02-20 09:36:36.764 4717-4717/com.example.itai.couchbasetest I/LiteCore [SQL]: Compiled Query: SELECT fl_result(fl_root(body)) FROM kv_default WHERE (fl_value(body, 'TIME') > 1519112196760) AND (flags & 1) = 0
02-20 09:36:36.765 4717-4717/com.example.itai.couchbasetest I/LiteCore [SQL]: Created prerecorded query enum with 0 rows (2 bytes) in 0.052ms
02-20 09:36:41.986 4717-4723/com.example.itai.couchbasetest I/zygote64: Do partial code cache collection, code=30KB, data=22KB
02-20 09:36:41.987 4717-4723/com.example.itai.couchbasetest I/zygote64: After code cache collection, code=30KB, data=22KB
02-20 09:36:41.987 4717-4723/com.example.itai.couchbasetest I/zygote64: Increasing code cache capacity to 128KB
02-20 09:36:42.014 4717-4717/com.example.itai.couchbasetest I/LiteCore [SQL]: Created prerecorded query enum with 4 rows (156 bytes) in 0.195ms
02-20 09:36:42.015 4717-4717/com.example.itai.couchbasetest I/LiteCore [SQL]: Created prerecorded query enum with 1 rows (48 bytes) in 0.132ms
02-20 09:36:42.018 4717-4717/com.example.itai.couchbasetest I/LiteCore [SQL]: Created prerecorded query enum with 2 rows (84 bytes) in 0.114ms
02-20 09:36:42.019 4717-4717/com.example.itai.couchbasetest I/LiteCore [SQL]: Created prerecorded query enum with 3 rows (120 bytes) in 0.206ms
02-20 09:36:42.024 4717-4717/com.example.itai.couchbasetest I/LiteCore [SQL]: Compiling JSON query: {"WHAT":[["."]],"WHERE":[">",[".TIME"],1519112202020]}
02-20 09:36:42.025 4717-4717/com.example.itai.couchbasetest I/LiteCore [SQL]: Compiled Query: SELECT fl_result(fl_root(body)) FROM kv_default WHERE (fl_value(body, 'TIME') > 1519112202020) AND (flags & 1) = 0
02-20 09:36:42.026 4717-4717/com.example.itai.couchbasetest I/LiteCore [SQL]: Created prerecorded query enum with 0 rows (2 bytes) in 0.055ms`

**Comment by hideki** [comment]
@itaishalom Thank you for sample app!

**Comment by hideki** [comment]
With the latest build `2.0.0-333` and build from master branch, this issue is no longer reproducible. It seems the issue was fixed between DB022 and build `2.0.0-333`.

Log with `2.0.0-333` (click START TEST button 5 times)
```
02-21 23:50:28.657 25497-25513/com.example.itai.couchbasetest I/LiteCore [SQL]: Created prerecorded query enum with 1 rows (48 bytes) in 0.030ms
02-21 23:50:28.661 25497-25513/com.example.itai.couchbasetest I/LiteCore [SQL]: Compiling JSON query: {"WHAT":[["."]],"WHERE":[">",[".TIME"],1519257028660]}
02-21 23:50:28.662 25497-25513/com.example.itai.couchbasetest I/LiteCore [SQL]: Compiled Query: SELECT fl_result(fl_root(body)) FROM kv_default WHERE (fl_value(body, 'TIME') > 1519257028660) AND (flags & 1) = 0
02-21 23:50:28.662 25497-25513/com.example.itai.couchbasetest I/LiteCore [SQL]: Created prerecorded query enum with 0 rows (2 bytes) in 0.036ms
02-21 23:50:29.360 25497-25513/com.example.itai.couchbasetest I/LiteCore [SQL]: Created prerecorded query enum with 1 rows (48 bytes) in 0.041ms
02-21 23:50:29.362 25497-25513/com.example.itai.couchbasetest I/LiteCore [SQL]: Compiling JSON query: {"WHAT":[["."]],"WHERE":[">",[".TIME"],1519257029360]}
02-21 23:50:29.362 25497-25513/com.example.itai.couchbasetest I/LiteCore [SQL]: Compiled Query: SELECT fl_result(fl_root(body)) FROM kv_default WHERE (fl_value(body, 'TIME') > 1519257029360) AND (flags & 1) = 0
02-21 23:50:29.362 25497-25513/com.example.itai.couchbasetest I/LiteCore [SQL]: Created prerecorded query enum with 0 rows (2 bytes) in 0.023ms
02-21 23:50:30.110 25497-25513/com.example.itai.couchbasetest I/LiteCore [SQL]: Created prerecorded query enum with 1 rows (48 bytes) in 0.104ms
02-21 23:50:30.112 25497-25513/com.example.itai.couchbasetest I/LiteCore [SQL]: Compiling JSON query: {"WHAT":[["."]],"WHERE":[">",[".TIME"],1519257030110]}
02-21 23:50:30.112 25497-25513/com.example.itai.couchbasetest I/LiteCore [SQL]: Compiled Query: SELECT fl_result(fl_root(body)) FROM kv_default WHERE (fl_value(body, 'TIME') > 1519257030110) AND (flags & 1) = 0
02-21 23:50:30.112 25497-25513/com.example.itai.couchbasetest I/LiteCore [SQL]: Created prerecorded query enum with 0 rows (2 bytes) in 0.023ms
02-21 23:50:30.831 25497-25513/com.example.itai.couchbasetest I/LiteCore [SQL]: Created prerecorded query enum with 1 rows (48 bytes) in 0.044ms
02-21 23:50:30.849 25497-25513/com.example.itai.couchbasetest I/LiteCore [SQL]: Compiling JSON query: {"WHAT":[["."]],"WHERE":[">",[".TIME"],1519257030848]}
02-21 23:50:30.849 25497-25513/com.example.itai.couchbasetest I/LiteCore [SQL]: Compiled Query: SELECT fl_result(fl_root(body)) FROM kv_default WHERE (fl_value(body, 'TIME') > 1519257030848) AND (flags & 1) = 0
02-21 23:50:30.850 25497-25513/com.example.itai.couchbasetest I/LiteCore [SQL]: Created prerecorded query enum with 0 rows (2 bytes) in 0.062ms
02-21 23:50:31.834 25497-25513/com.example.itai.couchbasetest I/LiteCore [SQL]: Created prerecorded query enum with 1 rows (48 bytes) in 0.028ms
02-21 23:50:31.835 25497-25513/com.example.itai.couchbasetest I/LiteCore [SQL]: Compiling JSON query: {"WHAT":[["."]],"WHERE":[">",[".TIME"],1519257031834]}
02-21 23:50:31.835 25497-25513/com.example.itai.couchbasetest I/LiteCore [SQL]: Compiled Query: SELECT fl_result(fl_root(body)) FROM kv_default WHERE (fl_value(body, 'TIME') > 1519257031834) AND (flags & 1) = 0
02-21 23:50:31.835 25497-25513/com.example.itai.couchbasetest I/LiteCore [SQL]: Created prerecorded query enum with 0 rows (2 bytes) in 0.018ms
```

**Comment by hideki** [comment]
@itaishalom,
Thanks again for your bug report. As written in prev comment, the issue is no longer reproducible with CBL build `2.0.0-333` which is a developer build from the master branch. If your application does not support the replication with Sync Gateway. Please try `2.0.0-333` (`compile 'com.couchbase.lite:couchbase-lite-android:2.0.0-333'`). This build requires latest Sync Gateway build, but it is not publicly available.
Thanks!

**Comment by itaishalom** [comment]
Will it be available in DB023?

**Comment by hideki** [comment]
I am not sure if we release DB023. Next could be 2.0.0 final release.
