### ISSUE TITLE
2.0: NullPointerException: Attempt to invoke virtual method 'boolean com.couchbase.litecore.C4QueryEnumerator.next()' on a null object reference

### ISSUE THREAD

**Issue by hideki** [couchbase/couchbase-lite-android#1615]
Original comment https://github.com/couchbase/couchbase-lite-android/issues/1610#issuecomment-368838603
Reported by @itaishalom

------------------------

Ok, It worked but another problem arouse:

```
02-27 11:07:10.412 11384-11384/com.itai.test W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.couchbase.litecore.C4QueryEnumerator.next()' on a null object reference
02-27 11:07:10.412 11384-11384/com.itai.test W/System.err:     at com.couchbase.lite.ResultSet.next(ResultSet.java:77)
02-27 11:07:10.412 11384-11384/com.itai.test W/System.err:     at com.itai.test.MyTestClass$MyListener.changed(MyTestClass.java:234)
02-27 11:07:10.412 11384-11384/com.itai.test W/System.err:     at com.couchbase.lite.QueryChangeListenerToken$1.run(QueryChangeListenerToken.java:37)
02-27 11:07:10.412 11384-11384/com.itai.test W/System.err:     at android.os.Handler.handleCallback(Handler.java:751)
02-27 11:07:10.412 11384-11384/com.itai.test W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
02-27 11:07:10.412 11384-11384/com.itai.test W/System.err:     at android.os.Looper.loop(Looper.java:154)
02-27 11:07:10.412 11384-11384/com.itai.test W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6119)
02-27 11:07:10.412 11384-11384/com.itai.test W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
02-27 11:07:10.413 11384-11384/com.itai.test W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
02-27 11:07:10.413 11384-11384/com.itai.test W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

The line at my code:
```
   ResultSet rows = queryChange.getResults();
 while ((rows != null) && ((row = rows.next()) != null)) { // here
```

I am not sure that the build solved it or not, I just got this crush on the live query. Are those related? If not, we can close this issue and I will open a new issue.

**Comment by hideki** [comment]
Note to self:

https://github.com/couchbase/couchbase-lite-android/blob/dbd0a80ce303d89935429fe4aef8e2fe6a5230de/shared/src/main/java/com/couchbase/lite/ResultSet.java#L71-L86

https://github.com/couchbase/couchbase-lite-android/blob/dbd0a80ce303d89935429fe4aef8e2fe6a5230de/shared/src/main/java/com/couchbase/lite/ResultSet.java#L134-L142

https://github.com/couchbase/couchbase-lite-android/blob/dbd0a80ce303d89935429fe4aef8e2fe6a5230de/shared/src/main/java/com/couchbase/lite/LiveQuery.java#L246-L251

https://github.com/couchbase/couchbase-lite-android/blob/dbd0a80ce303d89935429fe4aef8e2fe6a5230de/shared/src/main/java/com/couchbase/lite/LiveQuery.java#L134-L144

https://github.com/couchbase/couchbase-lite-android/blob/dbd0a80ce303d89935429fe4aef8e2fe6a5230de/shared/src/main/java/com/couchbase/lite/LiveQuery.java#L166-L172

https://github.com/couchbase/couchbase-lite-android/blob/dbd0a80ce303d89935429fe4aef8e2fe6a5230de/shared/src/main/java/com/couchbase/lite/AbstractQuery.java#L194-L198

**Comment by hideki** [comment]
@itaishalom
Could you please share your QueryChangeListener implementation? and add/remove QueryChangeListener codes?
Thanks!

**Comment by hideki** [comment]
https://github.com/itaishalom/CouchBase/blob/master/app/src/main/java/com/example/itai/couchbasetest/MyQueryListner.java#L35-L46
```java
        public void changed(QueryChange change) {
            ResultSet rows = change.getResults();
            Result row;
            if ((row = rows.next()) != null) {
                lastTime = System.currentTimeMillis();
                mQuery.removeChangeListener(mToken);
                mQuery = QueryBuilder.select(SelectResult.all()).from(DataSource.database(DBHandler.getInstance().mDb)).where(Expression.property(TIME).greaterThan(Expression.longValue(lastTime)));
                myQueryListner = new myQueryListnerImpl();
                mToken = mQuery.addChangeListener(myQueryListner);
            }
```

NOTE: calling `mQuery.removeChangeListener(mToken); ` frees `ResultSet` instance.

**Comment by hideki** [comment]
As expected, by changing from `if` condition to `while` loop, the issue is reproducible.
```java
        @Override
        public void changed(QueryChange change) {
            ResultSet rows = change.getResults();
            Result row;
            //if ((row = rows.next()) != null) {
            while ((rows != null) && ((row = rows.next()) != null)) { // here
                lastTime = System.currentTimeMillis();
                mQuery.removeChangeListener(mToken);
                mQuery = QueryBuilder.select(SelectResult.all()).from(DataSource.database(DBHandler.getInstance().mDb)).where(Expression.property(TIME).greaterThan(Expression.longValue(lastTime)));
                myQueryListner = new myQueryListnerImpl();
                mToken = mQuery.addChangeListener(myQueryListner);
            }
        }
```

```
02-27 12:44:22.534 18894-18922/com.example.itai.couchbasetest I/LiteCore [SQL]: Compiled {Query#3}: SELECT fl_result(fl_root(body)) FROM kv_default WHERE (fl_value(body, 'TIME') > 1519764262531) AND (flags & 1) = 0
02-27 12:44:22.534 18894-18894/com.example.itai.couchbasetest E/AndroidRuntime: FATAL EXCEPTION: main
        Process: com.example.itai.couchbasetest, PID: 18894
        java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.couchbase.litecore.C4QueryEnumerator.next()' on a null object reference
            at com.couchbase.lite.ResultSet.next(ResultSet.java:77)
            at com.example.itai.couchbasetest.MyQueryListner$myQueryListnerImpl.changed(MyQueryListner.java:40)
            at com.couchbase.lite.QueryChangeListenerToken$1.run(QueryChangeListenerToken.java:37)
            at android.os.Handler.handleCallback(Handler.java:751)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:154)
            at android.app.ActivityThread.main(ActivityThread.java:6119)
            at java.lang.reflect.Method.invoke(Native Method)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

**Comment by hideki** [comment]
Hi @itaishalom,
ResultSet is not detached from LiveQuery. With current implementation, ResultSet is freed when calling Query.removeChangeListener(Token). 
With the fix, `ResultSet.next()` returns `null` in case ResultSet is already freed.
In case query returns multiple `Result`s and your app need to access all of them, please call `Query.removeChangeListener(token)` after accessing all Results.
I will let you know when new build is ready.

**Comment by itaishalom** [comment]
Hi, let me point out something: I changed the implementation long time ago. Inside the while loop I update the query's parameters, I don't use the remove/add change listener as seen above. 
I don't know if the exception occurs when removing and adding the change listener But I can

**Comment by itaishalom** [comment]
Hi, let me point out something: I changed the implementation long time ago. Inside the while loop I update the query's parameters, I don't use the remove/add change listener as seen above. 
I don't know if the exception occurs when removing and adding the change listener But I can

**Comment by hideki** [comment]
Please try 2.0.0-360 which should not cause NPE within ResultSet.next().
http://mobile.maven.couchbase.com/feeds/dev//com/couchbase/lite/couchbase-lite-android/2.0.0-360

**Comment by itaishalom** [comment]
Ok, tomorrow morning. Did you see my latest reply?

**Comment by hideki** [comment]
yes.

**Comment by itaishalom** [comment]
Great. Many thanks to you

**Comment by itaishalom** [comment]
Hi, it seems to work but something caught my eye, there are many warning on the log:

```
02-28 08:37:22.744 3367-11824/com.itai.test W/art: Long monitor contention with owner pool-1-thread-1 (7857) at void com.couchbase.lite.Database.postDatabaseChanged()(Database.java:1065) waiters=0 in com.couchbase.lite.Document com.couchbase.lite.Database.getDocument(java.lang.String) for 1.044s
02-28 08:37:22.745 3367-3749/com.itai.test W/art: Long monitor contention with owner pool-1-thread-1 (7857) at void com.couchbase.lite.Database.postDatabaseChanged()(Database.java:1065) waiters=1 in com.couchbase.lite.ResultSet com.couchbase.lite.ResultSet.refresh() for 880ms
02-28 08:37:22.750 3367-3749/com.itai.test I/LiteCore [Query]: {QueryEnum#4181}==> N8litecore21SQLiteQueryEnumeratorE 0xab52e3c4
02-28 08:37:22.750 3367-3749/com.itai.test I/LiteCore [Query]: {QueryEnum#4181} Created on {Query#29} with 2 rows (2088 bytes) in 4.582ms
02-28 08:37:22.754 3367-3367/com.itai.test W/art: Long monitor contention with owner pool-2-thread-1 (3749) at void com.couchbase.lite.LiveQuery.update()(LiveQuery.java:208) waiters=0 in void com.couchbase.lite.LiveQuery.changed(com.couchbase.lite.DatabaseChange) for 813ms
02-28 08:37:23.701 3367-3749/com.itai.test W/art: Long monitor contention with owner pool-1-thread-1 (7857) at void com.couchbase.lite.Database.postDatabaseChanged()(Database.java:1065) waiters=0 in com.couchbase.lite.ResultSet com.couchbase.lite.ResultSet.refresh() for 947ms
02-28 08:37:23.704 3367-3749/com.itai.test I/LiteCore [Query]: {QueryEnum#4182}==> N8litecore21SQLiteQueryEnumeratorE 0xab52e414
02-28 08:37:23.704 3367-3749/com.itai.test I/LiteCore [Query]: {QueryEnum#4182} Created on {Query#47} with 0 rows (2 bytes) in 2.020ms
02-28 08:37:23.704 3367-3749/com.itai.test I/LiteCore [Query]: {QueryEnum#4182} Deleted
02-28 08:37:23.705 3367-11824/com.itai.test W/art: Long monitor contention with owner pool-1-thread-1 (7857) at void com.couchbase.lite.Database.postDatabaseChanged()(Database.java:1065) waiters=1 in com.couchbase.lite.Document com.couchbase.lite.Database.getDocument(java.lang.String) for 950ms
02-28 08:37:23.708 3367-3749/com.itai.test I/LiteCore [Query]: {QueryEnum#4183}==> N8litecore21SQLiteQueryEnumeratorE 0xab52e414
02-28 08:37:23.708 3367-3749/com.itai.test I/LiteCore [Query]: {QueryEnum#4183} Created on {Query#39} with 0 rows (2 bytes) in 3.472ms
02-28 08:37:23.708 3367-3749/com.itai.test I/LiteCore [Query]: {QueryEnum#4183} Deleted
02-28 08:37:23.710 3367-3367/com.itai.test W/art: Long monitor contention with owner pool-1-thread-1 (7857) at void com.couchbase.lite.Database.postDatabaseChanged()(Database.java:1065) waiters=2 in com.couchbase.lite.Result com.couchbase.lite.ResultSet.next() for 926ms
02-28 08:37:23.711 3367-3749/com.itai.test I/LiteCore [Query]: {QueryEnum#4184}==> N8litecore21SQLiteQueryEnumeratorE 0xab52e414
02-28 08:37:23.711 3367-3749/com.itai.test I/LiteCore [Query]: {QueryEnum#4184} Created on {Query#90} with 1 rows (1084 bytes) in 1.872ms
02-28 08:37:23.726 3367-3749/com.itai.test I/LiteCore [Query]: {QueryEnum#4185}==> N8litecore21SQLiteQueryEnumeratorE 0xab52e824
02-28 08:37:23.726 3367-3749/com.itai.test I/LiteCore [Query]: {QueryEnum#4185} Created on {Query#21} with 0 rows (2 bytes) in 12.071ms
02-28 08:37:23.726 3367-3749/com.itai.test I/LiteCore [Query]: {QueryEnum#4185} Deleted
02-28 08:37:23.732 3367-3749/com.itai.test I/LiteCore [Query]: {QueryEnum#4186}==> N8litecore21SQLiteQueryEnumeratorE 0xab52e824
02-28 08:37:23.732 3367-3749/com.itai.test I/LiteCore [Query]: {QueryEnum#4186} Created on {Query#29} with 2 rows (2088 bytes) in 5.651ms
```

**Comment by hideki** [comment]
`Long monitor contention with owner ...` warning message is caused by waiting for `synchronized(Object)` for a while.

Lock with Database.lock

https://github.com/couchbase/couchbase-lite-android/blob/f8dbb21946c0a1f59acc53be30933bd6d959ae31/shared/src/main/java/com/couchbase/lite/Database.java#L1065

https://github.com/couchbase/couchbase-lite-android/blob/f8dbb21946c0a1f59acc53be30933bd6d959ae31/shared/src/main/java/com/couchbase/lite/Database.java#L233

https://github.com/couchbase/couchbase-lite-android/blob/f8dbb21946c0a1f59acc53be30933bd6d959ae31/shared/src/main/java/com/couchbase/lite/ResultSet.java#L150

https://github.com/couchbase/couchbase-lite-android/blob/f8dbb21946c0a1f59acc53be30933bd6d959ae31/shared/src/main/java/com/couchbase/lite/ResultSet.java#L77

Lock with LiveQuery.lock

https://github.com/couchbase/couchbase-lite-android/blob/f8dbb21946c0a1f59acc53be30933bd6d959ae31/shared/src/main/java/com/couchbase/lite/LiveQuery.java#L208

https://github.com/couchbase/couchbase-lite-android/blob/f8dbb21946c0a1f59acc53be30933bd6d959ae31/shared/src/main/java/com/couchbase/lite/LiveQuery.java#L83

Following is my assumption. Frequent calling Database.save() and LiveQuery make accessing database busy. Or large data set makes query slow, then query might hold lock longer?

**Comment by itaishalom** [comment]
Do you ask me?

**Comment by hideki** [comment]
Hi @itaishalom,
I am not sure why some of the methods which internally hold the lock of Database takes a time around 1 second. If you can reproduce with this Warning with the simple application. Could you please share with us?

**Comment by itaishalom** [comment]
I will try but the setup is simple: 
One app with Content provider. On each update called, the app pulls from the db a document by id and save it with a new hash map (may be a big hash map with nested hash maps etc').
There are three to four liveQuery alive, at least two of them are relevant to the updates.
There are 5 updates each second from another app ( so another thread).
From tests, each update takes at most 25 milliseconds (from contentprovider and after db.save(doc) )
Hope it helps in the meantime

**Comment by itaishalom** [comment]
Oh and after change() is called, we update the query's parameters.

**Comment by hideki** [comment]
@itaishalom,

> Oh and after change() is called, we update the query's parameters.

do you create the index? I guess query is slow and it holds lock after storing a lot of documents in the database.

**Comment by itaishalom** [comment]
No, I do not. I will try and update you.

**Comment by hideki** [comment]
Hi @itaishalom,
Thank you for keep testing CBL.
Do you have time to update your CouchBase sample application?
Thanks!

**Comment by itaishalom** [comment]
I'm not sure, I tried before but I couldn't. The tests running on emulator on a large scale application, whereas I can upload simple application I write at home and tested on a real phone.
But I'll try to check it again

**Comment by hideki** [comment]
Hi @itaishalom,

I could reproduce the `Long monitor contention with owner ...` warning with customizing CouchBase sample app with CBL Android DB022. However, current latest build `2.0.0-378`, the WARNING is not reproducible. Could you please test `2.0.0-378`?

NOTE: `2.0.0-378` has `Database.save(MutableDocument)` API change. You might need to update your test codes.

```
03-01 18:57:55.441 6414-6452/com.example.itai.couchbasetest W/zygote: Long monitor contention with owner main (6414) at com.couchbase.lite.ResultSet com.couchbase.lite.ResultSet.refresh()(ResultSet.java:144) waiters=1 in com.couchbase.lite.Document com.couchbase.lite.Database.save(com.couchbase.lite.Document, boolean) for 323ms
03-01 18:57:55.442 6414-6414/com.example.itai.couchbasetest W/zygote: Long monitor contention with owner pool-1-thread-1 (6453) at void com.couchbase.lite.Database.postDatabaseChanged()(Database.java:1070) waiters=1 in com.couchbase.lite.ResultSet com.couchbase.lite.ResultSet.refresh() for 317ms
03-01 18:57:55.447 6414-6414/com.example.itai.couchbasetest I/LiteCore [SQL]: Created prerecorded query enum with 3 rows (120 bytes) in 4.217ms
03-01 18:57:55.972 6414-6452/com.example.itai.couchbasetest W/zygote: Long monitor contention with owner main (6414) at com.couchbase.lite.ResultSet com.couchbase.lite.ResultSet.refresh()(ResultSet.java:144) waiters=1 in com.couchbase.lite.Document com.couchbase.lite.Database.save(com.couchbase.lite.Document, boolean) for 527ms
03-01 18:57:55.973 6414-6414/com.example.itai.couchbasetest W/zygote: Long monitor contention with owner pool-1-thread-1 (6453) at void com.couchbase.lite.Database.postDatabaseChanged()(Database.java:1070) waiters=1 in com.couchbase.lite.ResultSet com.couchbase.lite.ResultSet.refresh() for 504ms
03-01 18:57:56.510 6414-6423/com.example.itai.couchbasetest W/zygote: Long monitor contention with owner pool-1-thread-1 (6453) at void com.couchbase.lite.Database.postDatabaseChanged()(Database.java:1070) waiters=2 in void com.couchbase.lite.ResultSet.free() for 884ms
03-01 18:57:56.510 6414-6414/com.example.itai.couchbasetest W/zygote: Long monitor contention with owner pool-1-thread-1 (6453) at void com.couchbase.lite.Database.postDatabaseChanged()(Database.java:1070) waiters=1 in com.couchbase.lite.ResultSet com.couchbase.lite.ResultSet.refresh()
```

**Comment by hideki** [comment]
Hi @itaishalom,

Do you me a favor? I removed `synchronized(Object)` block that should not be necessary. Updated codes can pass all unit tests. But I am not sure if it can work well with your application. Could you please test 2.0.0-382?

NOTE: `2.0.0-382` has Database.save(MutableDocument) API change from DB022. You might need to update your test codes.

http://mobile.maven.couchbase.com/feeds/dev//com/couchbase/lite/couchbase-lite-android/2.0.0-382

**Comment by itaishalom** [comment]
Thank you for your latest build. It's weekend over here so I will test both 378 and 382 on Sunday morning.
Thanks again!

**Comment by itaishalom** [comment]
Teststed 2.0.0-382, one update per second and the issue remains. Multiple warnings and no response from change() function.

**Comment by itaishalom** [comment]
Can we reopen this issue?

**Comment by hideki** [comment]
@itaishalom Can you file the new ticket?
