### ISSUE TITLE
Mix of logical operator not working correctly for FTS

### ISSUE THREAD

**Issue by hrajput89** [couchbase/couchbase-lite-android#1621]
I'm running a complex FTS query with MIX of both AND and OR operator. I'm not getting the expected result. I'm using travel-sample db for running queries.

This is my argument to match (stemming enabled) - **(beauty AND art) OR cafe**. My understanding is this, give all documents in which indexed property have either "beauty" and "art" (with stemming) in it OR  "cafe"  in it OR all three in it. 

As I understood query is actually searching for documents which has all there tokens. I made this conclusion based on different argument to match - **(beauty AND art) OR photograph**. 

> document with (beauty AND art) - 8
> document with (photograph) - 26
> document with (beauty AND art AND Photograph) - 1
> document with (beauty AND art) OR photograph - 1 (same document as above)

Similarly,

> document with (cafe) - 258
> document with (beauty AND art AND cafe) - 0
> document with (beauty AND art) OR cafe - 0 (same document as above)

{'content': u"Created out of a historic mattress factory showroom in the Westside of Ventura. There are free children's programs that enhance young lives through the arts and provide a cultural revitalization of the Westside. There are also many talented resident artists in studios creating beautiful paintings, jewelry, sculptures, weavings, photographs and ceramics.", 'name': u'Bell Arts Factory', 'id': u'landmark_32180'}

- CBL method for FTS query - https://github.com/couchbaselabs/mobile-testkit/blob/feature/cbl20-ver1/CBLClient/Apps/CBLTestServer-Android/app/src/main/java/com/couchbase/CouchbaseLiteServ/server/RequestHandler/QueryRequestHandler.java#L570
```
public List<Object> multiplePropertyFTS(Args args) throws CouchbaseLiteException {
        Database db = args.get("database");
        String prop1 = args.get("prop1");
        String prop2 = args.get("prop2");
        String val = args.get("val");
        Expression docType = Expression.value(args.get("doc_type"));
        Expression limit = Expression.value(args.get("limit"));
        String index = "multiplePropertyIndex";

        FullTextIndex ftsIndex = IndexBuilder.fullTextIndex(FullTextIndexItem.property(prop1), FullTextIndexItem.property(prop2));
        db.createIndex(index,ftsIndex);
        FullTextExpression ftsExpression = FullTextExpression.index(index);
        List<Object> resultArray = new ArrayList<>();

        Query query = QueryBuilder
                .select(SelectResult.expression(Meta.id),
                        SelectResult.expression(Expression.property(prop1)),
                        SelectResult.expression(Expression.property(prop2)))
                .from(DataSource.database(db))
                .where(Expression.property("type").equalTo(docType).and(ftsExpression.match(val)))
                .limit(limit);
        for (Result row : query.execute()) {
            resultArray.add(row.toMap());
        }
        return resultArray;
    }
```

- CBL log 

```
I/DB: Opening Database@a3b3944{name='suite_db'} at path /data/user/0/com.couchbase.TestServerApp/files/suite_db.cblite2
I/LiteCore [DB]: Opening DataFile /data/user/0/com.couchbase.TestServerApp/files/suite_db.cblite2/db.sqlite3
V/Query: Query encoded as {"WHAT":[["._id"],[".content"],[".name"]],"WHERE":["AND",["=",[".type"],"landmark"],["MATCH","multiplePropertyIndex","(beauty AND art) OR cafe"]],"LIMIT":100000}
I/LiteCore [Query]: {Query#93}==> N8litecore11SQLiteQueryE 0xf16af02c
I/LiteCore [Query]: {Query#93} Compiling JSON query: {"WHAT":[["._id"],[".content"],[".name"]],"WHERE":["AND",["=",[".type"],"landmark"],["MATCH","multiplePropertyIndex","(beauty AND art) OR cafe"]],"LIMIT":100000}
I/LiteCore [SQL]: Compiled {Query#93}: SELECT kv_default.rowid, offsets("kv_default::multiplePropertyIndex"), fl_result(key), fl_result(fl_value(body, 'content')), fl_result(fl_value(body, 'name')) FROM kv_default JOIN "kv_default::multiplePropertyIndex" AS FTS1 ON FTS1.docid = kv_default.rowid WHERE (fl_value(body, 'type') = 'landmark' AND FTS1."kv_default::multiplePropertyIndex" MATCH '(beauty AND art) OR cafe') AND (flags & 1) = 0 LIMIT MAX(0, 100000)
I/LiteCore [Query]: {QueryEnum#94}==> N8litecore21SQLiteQueryEnumeratorE 0xf16af454
I/LiteCore [Query]: {QueryEnum#94} Created on {Query#93} with 0 rows (2 bytes) in 0.262ms
```

**Comment by hideki** [comment]
Root cause of this issue is same with #1620

Unit test: https://github.com/couchbase/couchbase-lite-android/commit/f050f8e554cb4a521b97ec4d32fbd161a73e3853
