### ISSUE TITLE
ForestDB Documentation Or Sample Code

### ISSUE THREAD

**Issue by andredoubleu** [couchbase/couchbase-lite-android#1645]
Hi, I read all about the benefits of using ForestDB instead of SQLite from this link: [What is ForestDB?](https://developer.couchbase.com/documentation/mobile/1.3/guides/couchbase-lite/native-api/database/index.html#what-is-forestdb)

But from the 2.0 beta's documentation page I could only find a single mention of ForestDB: [Migrating from 1.x Databases](https://developer.couchbase.com/documentation/mobile/2.0/couchbase-lite/java.html#migrating-from-1.x-databases).

Is there anywhere where I can find basic documentation or sample code on how to use ForestDB in Couchbase Lite Android 2.0?

**Comment by rajagp** [comment]
We will not support ForestDB in Couchbase Lite 2.0 . Also, in future, please post questions for clarifications on our Dev Forums (https://forums.couchbase.com). We track issues in our GitHub repo.
