### ISSUE TITLE
Exception thrown openDatabase (Proguard strips methods that CBL uses)

### ISSUE THREAD

**Issue by sytolk** [couchbase/couchbase-lite-android#1665]
Couchbase Lite 2.0, Android 4.4 (with Android 7 and 8 I don't have this exception)
```
java.lang.NoSuchMethodError: no static method with name='callback' signature='(J)V' in class Lcom/couchbase/litecore/C4DatabaseObserver;
	at java.lang.Runtime.nativeLoad(Native Method)
	at java.lang.Runtime.doLoad(Runtime.java:421)
	at java.lang.Runtime.loadLibrary(Runtime.java:362)
	at java.lang.System.loadLibrary(System.java:526)
	at com.couchbase.lite.NativeLibraryLoader.loadSystemLibrary(NativeLibraryLoader.java:45)
	at com.couchbase.lite.NativeLibraryLoader.load(NativeLibraryLoader.java:40)
	at com.couchbase.lite.NativeLibraryLoader.load(NativeLibraryLoader.java:30)
	at com.couchbase.lite.Database.<clinit>(Database.java:65)
	at de.drivelog.triplog.persistence.BasePersistenceManager.openDatabase(BasePersistenceManager.java:30)
	at de.drivelog.triplog.persistence.PersistenceManager.init(PersistenceManager.java:21)
	at de.drivelog.triplog.MainApplication.onCreate(MainApplication.java:124)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4440)
	at android.app.ActivityThread.access$1500(ActivityThread.java:141)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1272)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5113)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:796)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:612)
	at dalvik.system.NativeStart.main(Native Method)
```
```
public class BasePersistenceManager {
public void openDatabase(Context context, String dbname) {
        DatabaseConfiguration config = new DatabaseConfiguration(context.getApplicationContext());
        try {
            database = new Database(dbname, config); // **row 30**
            createDatabaseIndex();
            Database.setLogLevel(Database.LogDomain.QUERY, Database.LogLevel.VERBOSE);
        } catch (CouchbaseLiteException e) {
            Log.e(TAG, "Failed to create Database instance: %s - %s", e, dbname, config);
        }
    }
}
```

**Comment by hideki** [comment]
Hi @sytolk,

Could you please provide the Device architecture? CBL 2.x supports `armeabi-v7a`, `arm64-v8a` and `x86`. To build for other architectures, please build CBL  with modifying the `build.gradle`.

If your test device architecture is one of `armeabi-v7a`, `arm64-v8a` and `x86`, we need detail information about the device.

**Comment by hideki** [comment]
FYI: We test CBL 2.x Android against API 19 `armeabi-v7a` and `x86` emulators.

**Comment by hideki** [comment]
Note to self:

From error message `java.lang.NoSuchMethodError: no static method with name='callback' signature='(J)V' in class Lcom/couchbase/litecore/C4DatabaseObserver;`, the native codes can not find the `static void C4DatabaseObserver.callback(long)` java static method.

During application build time or application installation time, the method could be stripped by code minification tool or something?

**Comment by hideki** [comment]
Hi @sytolk,

Currently, I am wondering ProGuard minify stripped `C4DatabaseObserver.callback(long)` method from APK because the method is only called from the native C/C++ codes. I believe ProGuard could not detect this dependency.  Could you please test with `minifyEnabled false`  in `build.gradle`? Or can you check if ProGuard removes  `C4DatabaseObserver.callback(long)` method?
Following article is really useful.
https://medium.com/google-developers/troubleshooting-proguard-issues-on-android-bce9de4f8a74

Thanks!

**Comment by hideki** [comment]
Hi @sytolk,
We have planned to release CBL 2.0.0 near future. If we could not reproduce the problem soon, we need to postpone the bug fix in next release. If you face the problem even after disable minify, please let us know.
Thanks!

**Comment by sytolk** [comment]
Hi @hideki yes I use Proguard in release build. Will check if this issue is from Proguard..

**Comment by hideki** [comment]
TODOs:
- investigate if  adding `com.couchbase.*` classes as ignore list in `proguard-rules.pro` in the library can solve the problem.
- If not, need to add this to the documentation (cc: @jamiltz )

**Comment by hideki** [comment]
adding `@Keep` annotation in front of class or method could be a solution.
https://developer.android.com/reference/android/support/annotation/Keep.html

**Comment by hideki** [comment]
Notes:

Way to test `minifyEnabled true` with debug build
```
    buildTypes {
        debug {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
```

**Comment by hideki** [comment]
proguard-rules.pro in application
```
#OkHttp
-dontwarn okhttp3.**
-dontwarn okio.**
-dontwarn javax.annotation.**
-dontwarn org.conscrypt.**
# A resource is loaded with a relative path so the package of this class must be preserved.
-keepnames class okhttp3.internal.publicsuffix.PublicSuffixDatabase

#CBL2.0
-keep class com.couchbase.**{ *; }
#-keep class com.couchbase.litecore.**{ *; }
#-keep class com.couchbase.lite.**{ *; }
```

**Comment by hideki** [comment]
@djpongh This is a documentation item. kind of how to use CBL. This is not a bug!

**Comment by sytolk** [comment]
@hideki I think it's better to ship proguard.cfg in the couchbase-lite-android-2.0.0-DB022.aar (Gradle build will find it and automatically add this rules)
Bundled rules can be done with:
 ```
 buildTypes {
    release {
      minifyEnabled true
      proguardFiles 'proguard.cfg'
      consumerProguardFiles 'proguard.cfg'
    }
  } 
```

**Comment by jamiltz** [comment]
@hideki will all users of the library need to disable code minification to use it (i.e `minifyEnabled: false`)? I'm surprised we haven't heard about this issue before. Is this required for debug and/or release builds?

**Comment by hideki** [comment]
@jamiltz Without setting `minifyEnabled: false` or adding `-keep class com.couchbase.**{ *; }` in `proguard-rules.pro`, Proguard strips some java classes/methods which are used by reflection or called from only C/C++ native codes.

**Comment by hideki** [comment]
@sytolk 
Thank you for sharing the Proguard tips
`consumerProguardFiles 'proguard.cfg'` works.

Note to self:
section `Library modules may include their own ProGuard configuration file`
https://developer.android.com/studio/projects/android-library.html#Considerations

**Comment by hideki** [comment]
@sytolk 
For 2.0.0 release, we might not able to add this change. Please add followings in your proguard config?
```
# OkHttp3
-dontwarn okhttp3.**
-dontwarn okio.**
-dontwarn javax.annotation.**
-dontwarn org.conscrypt.**
# A resource is loaded with a relative path so the package of this class must be preserved.
-keepnames class okhttp3.internal.publicsuffix.PublicSuffixDatabase

# CBL2.x
-keep class com.couchbase.litecore.**{ *; }
-keep class com.couchbase.lite.**{ *; }
```

**Comment by hideki** [comment]
@jamiltz,

Could you please document to add the following setting into `proguard-rules.pro` file if `minifyEnabled true` is set in the `build.gradle` file. 

NOTE: In the `build.gradle` file Android Studio generates, `minifyEnabled false` is defined as default.

```
# OkHttp3
-dontwarn okhttp3.**
-dontwarn okio.**
-dontwarn javax.annotation.**
-dontwarn org.conscrypt.**
# A resource is loaded with a relative path so the package of this class must be preserved.
-keepnames class okhttp3.internal.publicsuffix.PublicSuffixDatabase

# CBL2.x
-keep class com.couchbase.litecore.**{ *; }
-keep class com.couchbase.lite.**{ *; }
```

**Comment by hideki** [comment]
FYI: From 2.1.0, the developer does not need to write the proguard rule file.
