### ISSUE TITLE
ReplicatorConfiguration.setDocumentIDs has no effect

### ISSUE THREAD

**Issue by kuscsik** [couchbase/couchbase-lite-android#1674]
Setting document ID in replicator configuration has no effect, pull replication not working.

lite client v2
commit tested: 881cea188578bb86406e69b4c52ca7c2b48bc88a

Steps to reproduce:

1. Created document X using couchbase sync REST API.
2. Android client sets up a push-pull replication of document X. setDocumentIDs() used to specify the document ID.
3. Android client subscribes to document changes using addDocumentChangeListener(..)
4. Modify document X using couchbase sync REST API.

Expected outcome: Android device should receive the updated document.
Actual outcome: document update is not received.

In case setDocumentIDs() is not used at all, the client is successfully notified about document changes.

Replicator config:
```java
        ReplicatorConfiguration replicatorConfiguration = new ReplicatorConfiguration(database, endpoint);
        replicatorConfiguration.setReplicatorType(ReplicatorType.PUSH_AND_PULL);
        replicatorConfiguration.setContinuous(true);
        replicatorConfiguration.setAuthenticator(auth);
        replicatorConfiguration.setDocumentIDs(docIds);
```

Note:
Also tested on the latest master branch, the document change listener is called on update of the document, but the document is not being pulled/synchronized as expected.

**Comment by hideki** [comment]
Hi @kuscsik,

Sync Gateway does not support document ID filtering with **continuous** mode. Only single shot (non-continuous) mode supports it.

From documentation.

> In one-shot pull replications with Sync Gateway, it's possible to specify a list of document IDs (this feature is not available for replications in continuous mode, see #1703). The code below pulls the documents with ID "123" and "xyz" if they exist and the user has access to them.

https://developer.couchbase.com/documentation/mobile/2.0/guides/couchbase-lite/native-api/replication/index.html#filtering-by-document-ids

SG ticket:
Fix target is `2.2.0` of SG release.
https://github.com/couchbase/sync_gateway/issues/1703

**Comment by djpongh** [comment]
@hideki , we can close this, correct? (assuming the answer is yes and doing just that)

**Comment by hideki** [comment]
CBL Android 2.0.0 does not set the error message for replication errors in addition to error codes. This makes little harder to identify the problem.
https://github.com/couchbase/couchbase-lite-android/issues/1676

**Comment by kuscsik** [comment]
Hi @hideki ,

thanks for the quick response. It perfectly explains the behavior.

Zoltan
