### ISSUE TITLE
Add P2P Support

### ISSUE THREAD

**Issue by djpongh** [couchbase/couchbase-lite-android#1678]

**Comment by RocketRider** [comment]
Why is this a EE Feature in 2.1? It was free in 1.4.
Is it possible to implement a own peer to peer sync in the community edition?

**Comment by rajagp** [comment]
@RocketRider While not a hard and fast rule, very broadly, our motivation behind EE features is to support business critical applications. These applications impose high demands on scalability, availability, security and performance.  Our p2p solution ensures availability  in disconnected environments.  The 2.x version of our p2p solution is completely different from 1.x in that we are now transport agnostic and we provide the flexibility for apps to integrate any third party p2p communications framework with with our p2p replicator . For that reason, on-device encryption and on-device replicas are EE only . 

Besides, our EE features enables us to continue to keep a majority of our features open source and free for the community.

**Comment by geraldapeoples** [comment]
That is a worrying economic argument, if you make on device encryption available on mobile then you will lose revenue and hence not be able to afford to keep the open source project going? Paying the license requires a significant customer base, a significant customer base requires a investment in a product that will appeal to enterprises and that requires enterprise features ... after a significant investment to move from couchdb to couchbase I am left wondering if it was worth it ... it looks that you are deliberately not providing a path for small companies to use your product to grow to the point where they then not only become successful but then add to your own revenue stream ...
