### ISSUE TITLE
Compress (gzip) data uploaded by the replicator

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-android#168]
Compressing the documents being uploaded by the replicator would be a significant win since JSON compresses really well, and devices are often on low-bandwidth networks. The Sync Gateway now (as of today) supports receiving such gzip-encoded request bodies.

Same as couchbase/couchbase-lite-ios#240 -- see the 3 commits there for reference.

**Comment by zgramana** [comment]
Duplicate of couchbase/couchbase-lite-java-core#172
