### ISSUE TITLE
Replicator in Android get stuck at busy state when it goes back to online from offline (Genymotion)

### ISSUE THREAD

**Issue by sridevi-15** [couchbase/couchbase-lite-android#1685]
### Environment
1. Android version : 454
2. Sg version : 823
3. Emulator : Geny motion : Google Nexus 9,  7.0.0 API 24

### steps to reproduce : 
1. Launch todo app on both ios and android.
2. Create task list on both app and create docs on both iOS and Android as one user each.
3. Share the task list each other.
4. Have iOS and Android offline.
5. update on iOS couple of times and update on Android for more than 10 times.
     Have that todo item of iOS to be checked.
     Have that todo item of android to be unchecked
6. Get the iOS and Android online.

### Result : 
As Android has big rev id , Android update should get pushed to sg and iOS, 
but replicator got stucked busy and did not update on sg and iOS

###
Android cbl logs : 
https://gist.github.com/sridevi-15/6a98dffe7b5f56607b77b54f33fc6e46

Android Thread dump : 
[threads_report.txt](https://github.com/couchbase/couchbase-lite-android/files/1849717/threads_report.txt)

### Rev Trees
sg Rev Tree : 
<img width="676" alt="screen shot 2018-03-26 at 2 59 23 pm" src="https://user-images.githubusercontent.com/17035128/37936037-da90c920-3108-11e8-9aae-52ed72fe7131.png">

iOS rev tree : 
'''
./cblite revs --remotes com.couchbase.Todo\ 2018-03-26\ 15\:01.28.927.xcappdata/AppData/Library/Application\ Support/CouchbaseLite/sridevi.cblite2/ 24054607-909b-4db6-b459-2d9aeb709e11
Document "24054607-909b-4db6-b459-2d9aeb709e11"
 * 1-6ccf12bd4686d38205d96b86962059390f1d27c6     ------ #8
   * 2-9cbf3a736a60a6107c17f7925f74ee61901bcfb4   ------ #9
     * 3-a741236cf3c2abfa63e7e62a83bcefbe0bdd80ba ------ #11
       * 4-17b8d209035079e370340e45a3503ae13160ae01------ #12
         * 5-848d15437e3d612fada7c3a2ad2af6f35a9a764b------ #13
           * 6-a8504c7a01c5ae80720bc534899d8e4a3b222bad----KL #14, 124 bytes  [CURRENT]  [REMOTE#1]

'''
Android Rev tree:
'''
 ./cblite revs --remotes raghu.cblite2/ 24054607-909b-4db6-b459-2d9aeb709e11
Document "24054607-909b-4db6-b459-2d9aeb709e11"
 * 2-9cbf3a736a60a6107c17f7925f74ee61901bcfb4     ----K- #5, 124 bytes  [REMOTE#1]
   * 3-459cfc19b83786922753e809cea5ce25802b6901   ------ #10
     * 4-7338bfcad66a4d5ed9de487b12c06a0eb26f5d99 ------ #11
       * 5-b437b51db66e49334b5c39e556632704313d5138------ #12
         * 6-f1cf8ee2589ceb8059d08670fae604600c663a15------ #13
           * 7-3eec6a32e044c394bfe9d0ca7ac1cd58123982bc------ #14
             * 8-58a1b7fc063f4cfef54c16d47850a9fe805f1d16------ #15
               * 9-1f98c11ce89b1328202ef587f21afc376464efa5------ #16
                 * 10-304be3d7b42f30c74c530c146a079f0f8f53b386------ #17
                   * 11-447ee6f3522a756bd21f74bbe3bb110dd1e2c843------ #18
                     * 12-1e0ad559426991cb1737cfedb1533bcc6839ade0------ #19
                       * 13-92ef752372b31006ac00d041645bd158d16c39e2------ #20
                         * 14-818a8ca613ed6364656f651f8001b13807841d92------ #21
                           * 15-f49e0055428ceac718a6f809dfdfbda8b60738ea------ #22
                             * 16-db030f99d5396898c7bafb8ce2149b86a4317649------ #23
                               * 17-f0a7ee26bcd2255546d7fdaf643a42cdbe7d2de0------ #24
                                 * 18-73defb91e65eee64c53c3c9ba65be74d73b73199------ #25
                                   * 19-ccd55a35a4189bf4de41d5734f1e89cbef3bb038------ #26
                                     * 20-e14119678525cdf9508bdcaa681455dceacf7230------ #27
                                       * 21-4c66d81fba6666e99f9e8a26cc8d6c57a46b69f0-----L #28, 124 bytes  [CURRENT]
'''

**Comment by hideki** [comment]
Notes to self:
- With genymotion, issue is easily reproducible.
- It seems online/offline network notification does not work.

**Comment by hideki** [comment]
This could be caused by Gennymotion issue or OkHttp issue.
https://github.com/square/okhttp/issues/3278

**Comment by hideki** [comment]
Notes:

In case a device becomes OFFLINE mode, CBL expects that [`WebSocketListener.onFailure()`](https://square.github.io/okhttp/3.x/okhttp/okhttp3/WebSocketListener.html#onFailure-okhttp3.WebSocket-java.lang.Throwable-okhttp3.Response-) callback is called. However, with Genneymotion, it is not called. With the real devices and Android stack emulators, `onFailure()` callback is called.

To detect online/offline, CBL1.x always relies on Android provided `ConnectivityManager` for both become ONLINE and OFFLINE. CBL2.x relies on `onFailure()` callback to detect OFFLINE, and Android `ConnectivityManager` to detect ONLINE.

As this is GennyMotion emulator specific problem, it is not sure if it is worth to change to use Android ConnectivityManager for detect ONLINE.

**Comment by hideki** [comment]
- Genymotion - Android 8.0: disable network or enable airplane mode does not effect. CBL always can communicate with SG.
- Genymotion - Android 7.0: Once disabled network, CBL can not recover.

Notes: command line to enable data and wifi with `adb`
```
svc wifi disable        
svc data disable
svc wifi enable
svc data enable
```

**Comment by djpongh** [comment]
This is a genymotion issue. Nothing we can do.
