### ISSUE TITLE
Custom Conflict Resolution

### ISSUE THREAD

**Issue by ascendancy05** [couchbase/couchbase-lite-android#1690]
We noticed that in https://github.com/couchbase/couchbase-lite-android/issues/1607 the custom ConflictResolver API was removed. What is the reason behind this, and what is the default conflict resolution rule in place now? Couldn't an assumption here potentially create issues with "Client wins" vs "Server wins" for certain data types, especially ones edited offline?

**Comment by hideki** [comment]
The primary reason for removing custom ConflictResolver feature is to simplify the API. 

Conflict resolver of Database.save() and .delete() operations: 
- Majority of Couchbase Mobile users satisfied with `LAST_WRITE_WINS`. So default resolver for save() and delete() method is `LAST_WRITE_WINS`. Another option is `FAIL_ON_CONFLICT`.

```java
public enum ConcurrencyControl {
    /**
     * The last write operation will win if there is a conflict.
     */
    LAST_WRITE_WINS(0),
    /**
     * The operation will fail if there is a conflict.
     */
    FAIL_ON_CONFLICT(1);
    ...
}
```
https://github.com/couchbase/couchbase-lite-android/blob/master/shared/src/main/java/com/couchbase/lite/ConcurrencyControl.java#L23-L31

Conflict resolver of replication time confliction:
Following algo is kicked in in case of confliction during replication.
1. Always delete win
2. longer history revision win
3. compare revision ID which is random value
```java
    private Document resolveConflict(Document localDoc, Document remoteDoc) {
        if (remoteDoc.isDeleted())
            return remoteDoc;
        else if (localDoc.isDeleted())
            return localDoc;
        else if (localDoc.generation() > remoteDoc.generation())
            return localDoc;
        else if (localDoc.generation() < remoteDoc.generation())
            return remoteDoc;
        else if (localDoc.getRevID() != null && localDoc.getRevID().compareTo(remoteDoc.getRevID()) > 0)
            return localDoc;
        else
            return remoteDoc;
    }
```

**Comment by ascendancy05** [comment]
I am well aware of the couchbase forums. Historically we have had entirely unhelpful or just non-responses to issues or questions I've posted there, and considering we are trying to productionalize code that is using couch, we needed an answer from the developer.
