### ISSUE TITLE
database.save is not throwing couchbaseliteException in 2.1.0

### ISSUE THREAD

**Issue by sridevi-15** [couchbase/couchbase-lite-android#1706]
### Environment : 
Android version : 2.1.0-102
Android studio version : 3.0.1

### Steps to reproduce : 
1. Change the cbl version on gradle app to 2.1.0-102
2. Build app

### Result : 
database.save complains that it cannot throw couchbaseLiteException

### Exception : 
It should not complain , it should compile successfully.

**Comment by sridevi-15** [comment]
This is the code used in TestServer app
'''
public void updateDocuments(Args args) throws CouchbaseLiteException {
        final Database database = args.get("database");
        final Map<String, Map<String, Object>> documents = args.get("documents");
        database.inBatch(new Runnable() {
            @Override
            public void run() {
                for (Map.Entry<String, Map<String, Object>> entry : documents.entrySet()) {
                    String id = entry.getKey();
                    Map<String, Object> data = entry.getValue();
                    MutableDocument updatedDoc = database.getDocument(id).toMutable();
                    updatedDoc.setData(data);
                    try {
                        database.save(updatedDoc);
                    } catch (CouchbaseLiteException e) {
                        e.printStackTrace();
                    }
                }
            }
        });
    }
'''

**Comment by sridevi-15** [comment]
seeing same issue on todo app too

**Comment by sytolk** [comment]
@sridevi-15 it works but I'm not sure that this is better fix for this issue 
https://github.com/couchbase/couchbase-lite-android/commit/c6f5befc4202d9fc74e387b03738395e031ae215
