### ISSUE TITLE
2.1: Auto PGP signing for Maven Central

### ISSUE THREAD

**Issue by hideki** [couchbase/couchbase-lite-android#1713]
<name>com.couchbase.lite:couchbase-lite-android</name>
  <description>Couchbase-Lite-Android is a lightweight embedded NoSQL database engine for Android with the built-in ability to sync to Couchbase Server on the backend.</description>
  <url>http://developer.couchbase.com/mobile/</url>

**Comment by pasin** [comment]
I believe this is already done my @kimtrang. @kimtrang could you please confirm?

**Comment by kimtrang** [comment]
Correct, this has been done

**Comment by pasin** [comment]
Thanks!
