### ISSUE TITLE
removing encryption key is throwing null pointer exception

### ISSUE THREAD

**Issue by sridevi-15** [couchbase/couchbase-lite-android#1720]
### Environment 
android Version : 2.1.0-115

### Steps to reproduce : 
1. Create database with encryption
2. Verify database can be accessed with encryption key.
3. Now remove the encryption key by passing null to 
    database.changeEncryptionKey(null)

### Result : 
It throws an error 
**Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'byte[] com.couchbase.lite.EncryptionKey.getKey()' on a null object reference
E               	at com.couchbase.lite.Database.changeEncryptionKey(Database.java:53)**

### Expected . : 
It should successfully remove encryption key and it should be accessible without encryption key

**Comment by hideki** [comment]
PR: https://github.com/couchbaselabs/couchbase-lite-android-ee/pull/13
