### ISSUE TITLE
Symbols cause crash in Select statement

### ISSUE THREAD

**Issue by percula** [couchbase/couchbase-lite-android#1744]
I am using CBL 2.0. My objects have a key "$writable". When trying to query these objects and return (amongst other values) the "$writable" value, a CouchBaseLiteException is thrown. Are symbols like $ meant to be supported? For now, I am simply removing the symbol before storing it in CBL, which avoids this issue.

**Comment by pasin** [comment]
Can you provide the Exception message?

**Comment by snej** [comment]
Pretty much anything is allowed in a key except for leading underscores (and empty strings.) So this is unexpected. We'd like to see the source code that creates the query, as well as the exception.

**Comment by djpongh** [comment]
Moved issue to LiteCore repo:
 https://github.com/couchbase/couchbase-lite-core/issues/545
