### ISSUE TITLE
p2p : filter doc ids does not work 

### ISSUE THREAD

**Issue by sridevi-15** [couchbase/couchbase-lite-android#1749]
### Environment 
SG = 2.1.0-121
lite android version - 2.1.0-168

### Steps to reproduce : 
1. Create docs on client.
        2. Start the server.
        3. Start replication from client with 5  doc ids list with one shot and push_pull/push
        4. Verify replication is completed.
        5. Verify docs which are filtered got replicated on server

### Result : 
All docs got replicated

### Expected : 
Only 5 docs should get replicated

**Comment by pasin** [comment]
@sridevi-15 I have added units to test documentIDs filter with push, pull, and push-and-pull P2P replication but I couldn't reproduce the issue above. Could you please check if the tests?
