### ISSUE TITLE
Concat query not working

### ISSUE THREAD

**Issue by nuxzero** [couchbase/couchbase-lite-android#1754]
Not sure why when concat the query after the query created not working?

```
val query = QueryBuilder
                .select(SelectResult.all())
                .from(DataSource.database(database))
                
if (limit > 0) {
    query.limit(Expression.intValue(limit), Expression.intValue(offset))
}
```

But if group I add `limit()` in creating the query it work fine.

```
val query = QueryBuilder
                .select(SelectResult.all())
                .from(DataSource.database(database))
                .limit(Expression.intValue(limit), Expression.intValue(offset))
```

Do you have another way to deal with the concating query after the query created?

**Comment by pasin** [comment]
When calling .from(), .where(), .limit(), and etc, a new query object returns. Try this:

```Java
query = query.limit(Expression.intValue(limit), Expression.intValue(offset))
```

Or you could execute the query right away after calling limit:

```Java
query.limit(Expression.intValue(limit), Expression.intValue(offset)).execute()
```

As this is not an issue. I will close the issue.
