### ISSUE TITLE
Release 1.x (1.4.4)?

### ISSUE THREAD

**Issue by mmueller-abacus** [couchbase/couchbase-lite-android#1758]
Hello,

When will the next 1.x version be released?
Thank you.

**Comment by rajagp** [comment]
We are actively working on 1.4.4 maintenance release that should hopefully be out within the  next month or so. Is there a specific bug fix that you were looking for in this release ? 

Also, for future, please use our [developer forums](https://forums.couchbase.com) for similar questions for clarifications . The GitHub repo is mainly for tracking issues.

**Comment by mmueller-abacus** [comment]
Waiting for #994 
Thank you.

**Comment by rajagp** [comment]
Thanks for the info on the bug of interest (CC @pasin ).
