### ISSUE TITLE
ResultSet.toMap() and ResultSet.indexForColumnName() not working for FTS

### ISSUE THREAD

**Issue by percula** [couchbase/couchbase-lite-android#1767]
In CBL 2.0 and 2.1, I cannot get FTS to return all the properties that I ask for in the SelectResult. When I run the exact same query without the FTS Where expression, it works as expected. Specifically, the `indexForColumnName()` method returns `-1` when the value is in-fact present in the values. As shown in the screenshot, the correct index for `"overview"` is `9`. In `indexForColumnName`, the first line correctly returns `9`, but the bitwise operators in the third line return `false` so `-1` is returned. I assume the issue lies in how `missingColumns` is calculated.

```java
private int indexForColumnName(String name) {
        Integer index = rs.getColumnNames().get(name);  // Expected result: 9, Actual result: 9
        if (index == null) return -1;
        boolean hasValue = (missingColumns & (1 << index.intValue())) == 0; // Expected: true, Actual: false
        return hasValue ? index.intValue() : -1;
    }
```

![cbl issue](https://user-images.githubusercontent.com/16809252/47158361-7f389f00-d2b9-11e8-879e-6004c9f0f5b8.jpg)

**Comment by pasin** [comment]
@percula Can you provide the FTS query that you constructed? I want to use that to reproduce that the issue.

**Comment by percula** [comment]
Hi @pasin , thanks for looking into this! I am using a temporary workaround: I added CBL as a local library and bypassed the last two lines of `indexForColumnName()` and now it's working, so that is definitely the issue. This works fine, but now my build times are horribly slow. I looked for the .aar that Android Studio is supposed to build, but cannot find it. Does CBL for Android output that to a custom location?

Here is my FTS query as requested:
```
Limit[json={OFFSET=0, LIMIT=500, WHAT=[[.security], [.mn_cbl_dkp], [.mn_server_dkp], [._id], [.mn_view], [.sort_date], [.searchable_text], [.writable], [.visibility_writable], [.overview], [.location], [.type]], WHERE=[AND, [=, [.mn_view], Assets], [MATCH, searchable_text, north]]}]
```

A sample document would have a string value with key `searchable_text` with some value containing the word "North". We have a dozen or so such documents in our sample database that should match.

**Comment by percula** [comment]
I was curious if the `._id` was causing issues, so I tried removing that but the issue persists.

**Comment by Sandychuang8** [comment]
Hi @percula, In order to repro this issue, I will need to know how you constructed the document or provide us a sample of the data set (JSON will do).

**Comment by djpongh** [comment]
Closing. If you get the needed info feel free to reopen.
