### ISSUE TITLE
Meta.id.like is not working

### ISSUE THREAD

**Issue by brije111** [couchbase/couchbase-lite-android#1772]
Here is my code to fetch all records with having email passed as parameter(emId) & ID starts with "login_".

`public static ResultSet queryLoginModelEmail(String emId, Database database) {
        Query query = QueryBuilder.select(SelectResult.all())
                .from(DataSource.database(database))
                .where(Expression.property("email").equalTo(Expression.string(emId))
                        .and(Meta.id.like(Expression.string("login_%e%"))));
        ResultSet result = null;
        try {
            result = query.execute();
        } catch (CouchbaseLiteException e) {
            e.printStackTrace();
        }
        return result;
    }`

![image](https://user-images.githubusercontent.com/11292348/47641349-d711b880-db8b-11e8-9c78-9c80db3c70c6.png)

But it is fetching all details with that email-id, "login_" condition is not working
Please help

**Comment by pasin** [comment]
The expression above, LIKE `login_%e%` doesn't mean that the ID starts with "login_" but it means that the ID has 'login_' as the prefix AND has anything that contains an 'e' character after that. I think you would need LIKE `login_%` to achieve the 'login_` prefix checking. Please check your query.

I have also tested both LIKE "login_%" and LIKE "login_%e%" against meta.id and both worked as expected.
