### ISSUE TITLE
http://mobile.maven.couchbase.com/maven2/dev/ not working

### ISSUE THREAD

**Issue by bitfrost** [couchbase/couchbase-lite-android#1781]
This has started happening today with no change in our projects.  Seems like an infrastructure problem.

could not resolve all files for configuration ':app:debugRuntimeClasspath'.
> Could not find com.couchbase.lite:couchbase-lite-android-ee:2.1.0.
  Searched in the following locations:
      file:/Users/kobrien/Library/Android/sdk/extras/m2repository/com/couchbase/lite/couchbase-lite-android-ee/2.1.0/couchbase-lite-android-ee-2.1.0.pom
      file:/Users/kobrien/Library/Android/sdk/extras/m2repository/com/couchbase/lite/couchbase-lite-android-ee/2.1.0/couchbase-lite-android-ee-2.1.0.jar
      file:/Users/kobrien/Library/Android/sdk/extras/google/m2repository/com/couchbase/lite/couchbase-lite-android-ee/2.1.0/couchbase-lite-android-ee-2.1.0.pom
      file:/Users/kobrien/Library/Android/sdk/extras/google/m2repository/com/couchbase/lite/couchbase-lite-android-ee/2.1.0/couchbase-lite-android-ee-2.1.0.jar
      file:/Users/kobrien/Library/Android/sdk/extras/android/m2repository/com/couchbase/lite/couchbase-lite-android-ee/2.1.0/couchbase-lite-android-ee-2.1.0.pom
      file:/Users/kobrien/Library/Android/sdk/extras/android/m2repository/com/couchbase/lite/couchbase-lite-android-ee/2.1.0/couchbase-lite-android-ee-2.1.0.jar
      https://dl.google.com/dl/android/maven2/com/couchbase/lite/couchbase-lite-android-ee/2.1.0/couchbase-lite-android-ee-2.1.0.pom
      https://dl.google.com/dl/android/maven2/com/couchbase/lite/couchbase-lite-android-ee/2.1.0/couchbase-lite-android-ee-2.1.0.jar
      file:/Users/kobrien/.m2/repository/com/couchbase/lite/couchbase-lite-android-ee/2.1.0/couchbase-lite-android-ee-2.1.0.pom
      file:/Users/kobrien/.m2/repository/com/couchbase/lite/couchbase-lite-android-ee/2.1.0/couchbase-lite-android-ee-2.1.0.jar
      https://jcenter.bintray.com/com/couchbase/lite/couchbase-lite-android-ee/2.1.0/couchbase-lite-android-ee-2.1.0.pom
      https://jcenter.bintray.com/com/couchbase/lite/couchbase-lite-android-ee/2.1.0/couchbase-lite-android-ee-2.1.0.jar
      file:/Users/kobrien/dev/falcon-app/node_modules/react-native/android/com/couchbase/lite/couchbase-lite-android-ee/2.1.0/couchbase-lite-android-ee-2.1.0.pom
      file:/Users/kobrien/dev/falcon-app/node_modules/react-native/android/com/couchbase/lite/couchbase-lite-android-ee/2.1.0/couchbase-lite-android-ee-2.1.0.jar
      http://mobile.maven.couchbase.com/maven2/dev/com/couchbase/lite/couchbase-lite-android-ee/2.1.0/couchbase-lite-android-ee-2.1.0.pom
      http://mobile.maven.couchbase.com/maven2/dev/com/couchbase/lite/couchbase-lite-android-ee/2.1.0/couchbase-lite-android-ee-2.1.0.jar

**Comment by pasin** [comment]
We are looking into the issue. Meanwhile you can use couchbase-lite-android deployed on jcenter() by removing couchbase maven from the repository list in `build.gradle` and add `jcenter()` instead.

**Comment by bitfrost** [comment]
Download appears to be working again.   The one on jcenter appears to be 1.4.X  we are customers using 2.1.0 with encryption so that would not be an alternative.
