### ISSUE TITLE
2.1.0 : LAST_WRITE_WINS flag not working. getting conflict Android SDK

### ISSUE THREAD

**Issue by verma171** [couchbase/couchbase-lite-android#1782]
As per the documentation https://blog.couchbase.com/document-conflicts-couchbase-mobile/ 
In Couchlite 2.0 a feature introduced automatic conflict resolution but it seems not working in my case. 
I am getting following error message ReplicatorChangeListener in Android SDK. 
"Document update conflict".

**Comment by pasin** [comment]
The LAST_WRITE_WINS conflict resolution is only for local save operation. Then using replication, the conflict resolution will be done on the client side during pull replication using MOST-ACTIVE_WINS algorithm.

From the error, I guess that the push-only replicator is using. To use replication's auto conflict resolution, pull replicator is needed. Can you check the type of the replicator?

**Comment by pasin** [comment]
On another note, if using push and pull replicator separately (not push-pull replicator), the above error could be still shown up but harmlessly as the conflict will be resolved in pull replicator.
