### ISSUE TITLE
java.lang.NoClassDefFoundError caused by apache legacy library API 28

### ISSUE THREAD

**Issue by jlurena** [couchbase/couchbase-lite-android#1784]
More info https://issuetracker.google.com/issues/79478779

Can be fixed by adding
`<uses-library android:name="org.apache.http.legacy" android:required="false"/>` to manifest.xml

**Comment by pasin** [comment]
CC: @rajagp

**Comment by pasin** [comment]
CBL doesn't use org.apache.http and I don't think this is directly relevant to CBL. It's something that the Android application might need to do.
