### ISSUE TITLE
Result.toMap() does not return boolean values

### ISSUE THREAD

**Issue by percula** [couchbase/couchbase-lite-android#1785]
`Result.toMap()` returns boolean values as numbers instead of booleans. Is there a way to fix this? It looks like `toMap()` calls `toList()` which eventually calls `FLValue.toObject()`, which is supposed to check for booleans. So it looks like it *should* work, but isn't.

I also confirmed that when creating the document, the value is a boolean, so the issue occurs during read, not write.

**Comment by pasin** [comment]
Thanks for reporting. We need to investigate this issue.

**Comment by Sandychuang8** [comment]
Cannot reproduce the issue with the latest build.
