### ISSUE TITLE
Ensure file logger max size is 64-bit type

### ISSUE THREAD

**Issue by borrrden** [couchbase/couchbase-lite-android#1802]
Spec recently changed from int32 to int64

**Comment by jayahariv** [comment]
Can see the `maxSize` type as long. And it is 64 bit. 

https://github.com/couchbase/couchbase-lite-android/blob/e6c47578060629e1d82ecfc321dadc587a61bc3c/shared/src/main/java/com/couchbase/lite/FileLogger.java#L96

https://developer.android.com/reference/java/lang/Long.html#SIZE

**Comment by jayahariv** [comment]
Confirmed and hence closing this
