### ISSUE TITLE
Iridium Logging Test Cases

### ISSUE THREAD

**Issue by borrrden** [couchbase/couchbase-lite-android#1808]
See the CBL Logging test plan for details on each item

- [ ] Log availability at default location
- [x] Logging format with default behavior
- [x] Enabling Text logging
- [x] Logs for each log level
- [x] Max size log rotation
- [x] Disable logging
- [x] Re-enable logging
- [x] log file name
- [x] System configuration Snippet at the start of log
- [x] Custom logging
- [x] Custom logging log level
- [x] Disable custom logging
- [x] re-enable custom logging

**Comment by jayahariv** [comment]
File logging, will add unit tests after the new change is included

**Comment by jayahariv** [comment]
Log availability at default location: no checking done, since we are getting the directory from the users.

**Comment by jayahariv** [comment]
Disable custom logging can be checked inside the Re-enable custom logging. As the re-enable custom logging include a disabling and validation for not printing the logs. So will go ahead and mark disable as done.
