### ISSUE TITLE
Document packaging changes to Android

### ISSUE THREAD

**Issue by djpongh** [couchbase/couchbase-lite-android#1852]
Originally: https://issues.couchbase.com/browse/CM-151

Put together a diagram that shows current package structure and what's planned with the "internal" renaming so it is clear to all stakeholders on which ones are impacted .
I think that would also be good to add to the repo README so users who build from source know what has changed

**Comment by bmeike** [comment]
One does not normally use the README to document changes in a version.  ... well, maybe a changelog in the readme.  I can't confirm the commitment to support a changelog (not a bad idea!), so I am just going to introduce a RELEASE.md that documents the changes.  We can replace or add to the contents, in the next release, or delete it entirely, when we get tired of looking at it.

**Comment by bmeike** [comment]
I have added `release-notes.md` files to each of the three affected repos.  It seems reasonable to me to have this info right next to the code, but open to suggestion.  I can also add the related tickets to the release, when this goes out.

Here are the two diagrams, as requested:

![jni-repackage-before](https://user-images.githubusercontent.com/277848/52306464-e5226280-294c-11e9-949b-68040081bdc7.png)
![jni-repackage-after](https://user-images.githubusercontent.com/277848/52306465-e5226280-294c-11e9-8b01-380fa7056988.png)

**Comment by bmeike** [comment]
Documentation complete.
