### ISSUE TITLE
No implementation found for java.lang.string com.couchbase.litecore.c4.getversion()

### ISSUE THREAD

**Issue by Mahan3340** [couchbase/couchbase-lite-android#1878]
when I try to run app normally on emulator with any API version 28 I get this error while creating new database. However it works fine when I create a release version APK and manually install it on emulators, in this case it just works fine, but it really slows debugging process.

Errors:
Can not load Native Library
No implementation found for java.lang.string com.couchbase.litecore.c4.getversion()

this issues has been around for more than 6 months and been reported before but its not fixed yet !

**Comment by bmeike** [comment]
What do you mean by "manually" install, as opposed to "normally" install?

This is most likely an installation problem.  Are you, perhaps, using "Instant Run"?

**Comment by Mahan3340** [comment]
Manually installing release version = Creating APK drag & drop to emulator, this works fine 
Running using IDE (instant run is Disabled) , crash with this exception

**Comment by pasin** [comment]
Can you provide your Android Emulator info as well?

**Comment by pasin** [comment]
I have just tested it with a sample app by using CBL v2.1.2 and Android Emulator X86 API 28 and I couldn't reproduce the issue. So could you please provide more info about your build tool, the Android Emulator and etc that we can use to reproduce the issue. Thanks.

**Comment by Mahan3340** [comment]
Emulator Info: 
Release Name: Pie, API Level: 28, ABI = x86_64, Target: Android 9.0 (Google APIs)
compileSdkVersion: 28 minSdkVersion: 19  targetSdkVersion:28  multiDexEnabled: true using androidX and CBL 2.12, gradle build tools 3.1.3. Wiped data, recreated the emulator and still the same.

**Comment by MatFl** [comment]
This is probably a duplicate of #1769 
The release build contains all ABIs, while the debug build probably only contains the ABI required for the emulator (in this case x86_64) which CBL2.x does not provide.

**Comment by Mahan3340** [comment]
@pasin @bmeike : @MatFI is right , when I added 
```
ndk {
     abiFilters "x86", "armeabi-v7a"
   }
```
to debug version as well as release version in gradle, it installs and runs succesfully without any problem and I see CBL has
` ndk { abiFilters 'x86', 'armeabi-v7a', 'arm64-v8a' }`
in its gradle that might cause this problem, on possible reason might be that it cover most of the android devices or due to APK size reduction ( which might be unnecessary now with the use of google play bundles)

**Comment by Mahan3340** [comment]
I will close this issue for now because it's not that related to CBL lib it self but to your policy to support different architectures.

**Comment by SagarPatil04** [comment]
I am facing the same issue with emulator with x84_64. @bmeike mentioned the issue is in progress and will be released in Cobalt milestone. Any retentive release date for that milestone?

**Comment by rajagp** [comment]
@SagarPatil04   We do not have a release date for that milestone at this time.
