### ISSUE TITLE
Iridium release or nightly builds

### ISSUE THREAD

**Issue by MatFl** [couchbase/couchbase-lite-android#1895]
Hi,
we are still waiting for the replication filters which should come with iridium. The milestone was dated until January 2019. Is there a schedule for the release?
Or is there a way to get current nightly builds?

Thanks!

**Comment by djpongh** [comment]
The January 2019 release date was added during very early phases of our planning and never updated. Sorry about that. We are looking to get Iridium out the door by May.

**Comment by MatFl** [comment]
Is there a way to get nightly builds or RCs? We then could start migrating (we are still on 1.4.4) and maybe check for issues before the release.
