### ISSUE TITLE
2.1.2: Replicators do not share a ConnectionPool

### ISSUE THREAD

**Issue by johnvm** [couchbase/couchbase-lite-android#1896]
Replicators do not release resources when they are finished. As such for long-running applications, the replicators end up filling memory and causing an application crash.

We declare the replicator

> private Replicator remote;

Initialize the replicator

> Endpoint targetEndpoint = new URLEndpoint(new URI(getRemoteURL()));
> ReplicatorConfiguration replConfig = new ReplicatorConfiguration(database, targetEndpoint);
> replConfig.setReplicatorType(ReplicatorConfiguration.ReplicatorType.PUSH_AND_PULL);
> replConfig.setAuthenticator(new BasicAuthenticator(getUsername(), getPassword()));
> replConfig.setContinuous(false);
> remote = new Replicator(replConfig);
> remote.start();

For the test case we run the following code every 5 seconds:

> remote.stop();
> remote.start();

After waiting for a while the following is the thread pool state for the application:

> 2019-03-30 11:27:51.474 6252-6360/pos D/DeviceManagement: Thread (59):Thread[OkHttp ConnectionPool,4,main]:state:TIMED_WAITING
> 2019-03-30 11:27:51.475 6252-6360/pos D/DeviceManagement: Thread (60):Thread[OkHttp ConnectionPool,4,main]:state:TIMED_WAITING
> 2019-03-30 11:27:51.475 6252-6360/pos D/DeviceManagement: Thread (61):Thread[OkHttp ConnectionPool,4,main]:state:TIMED_WAITING
> 2019-03-30 11:27:51.475 6252-6360/pos D/DeviceManagement: Thread (62):Thread[OkHttp ConnectionPool,4,main]:state:TIMED_WAITING
> 2019-03-30 11:27:51.476 6252-6360/pos D/DeviceManagement: Thread (63):Thread[OkHttp ConnectionPool,4,main]:state:TIMED_WAITING
> 2019-03-30 11:27:51.476 6252-6360/pos D/DeviceManagement: Thread (64):Thread[OkHttp ConnectionPool,4,main]:state:TIMED_WAITING
> 2019-03-30 11:27:51.476 6252-6360/pos D/DeviceManagement: Thread (65):Thread[OkHttp ConnectionPool,4,main]:state:TIMED_WAITING
> 2019-03-30 11:27:51.477 6252-6360/pos D/DeviceManagement: Thread (66):Thread[OkHttp ConnectionPool,4,main]:state:TIMED_WAITING
> 2019-03-30 11:27:51.477 6252-6360/pos D/DeviceManagement: Thread (67):Thread[OkHttp ConnectionPool,4,main]:state:TIMED_WAITING
> 2019-03-30 11:27:51.477 6252-6360/pos D/DeviceManagement: Thread (68):Thread[OkHttp ConnectionPool,4,main]:state:TIMED_WAITING
> 2019-03-30 11:27:51.477 6252-6360/pos D/DeviceManagement: Thread (69):Thread[OkHttp ConnectionPool,4,main]:state:TIMED_WAITING
> 2019-03-30 11:27:51.478 6252-6360/pos D/DeviceManagement: Thread (70):Thread[OkHttp ConnectionPool,4,main]:state:TIMED_WAITING
> 2019-03-30 11:27:51.478 6252-6360/pos D/DeviceManagement: Thread (71):Thread[OkHttp ConnectionPool,4,main]:state:TIMED_WAITING
> 2019-03-30 11:27:51.478 6252-6360/pos D/DeviceManagement: Thread (72):Thread[OkHttp ConnectionPool,4,main]:state:TIMED_WAITING
> 2019-03-30 11:27:51.478 6252-6360/pos D/DeviceManagement: Thread (73):Thread[OkHttp ConnectionPool,4,main]:state:TIMED_WAITING
> 2019-03-30 11:27:51.479 6252-6360/pos D/DeviceManagement: Thread (74):Thread[OkHttp ConnectionPool,4,main]:state:TIMED_WAITING
> 2019-03-30 11:27:51.479 6252-6360/pos D/DeviceManagement: Thread (75):Thread[OkHttp ConnectionPool,4,main]:state:TIMED_WAITING
> 2019-03-30 11:27:51.479 6252-6360/pos D/DeviceManagement: Thread (76):Thread[OkHttp ConnectionPool,4,main]:state:TIMED_WAITING
> 2019-03-30 11:27:51.479 6252-6360/pos D/DeviceManagement: Thread (77):Thread[OkHttp ConnectionPool,4,main]:state:TIMED_WAITING
> 2019-03-30 11:27:51.480 6252-6360/pos D/DeviceManagement: Thread (78):Thread[OkHttp ConnectionPool,4,main]:state:TIMED_WAITING
> 2019-03-30 11:27:51.480 6252-6360/pos D/DeviceManagement: Thread (79):Thread[OkHttp ConnectionPool,4,main]:state:TIMED_WAITING
> 2019-03-30 11:27:51.480 6252-6360/pos D/DeviceManagement: Thread (80):Thread[OkHttp ConnectionPool,4,main]:state:TIMED_WAITING
> 2019-03-30 11:27:51.480 6252-6360/pos D/DeviceManagement: Thread (81):Thread[OkHttp ConnectionPool,4,main]:state:TIMED_WAITING
> 2019-03-30 11:27:51.481 6252-6360/pos D/DeviceManagement: Thread (82):Thread[OkHttp ConnectionPool,4,main]:state:TIMED_WAITING
> 2019-03-30 11:27:51.481 6252-6360/pos D/DeviceManagement: Thread (83):Thread[OkHttp ConnectionPool,4,main]:state:TIMED_WAITING
> 2019-03-30 11:27:51.481 6252-6360/pos D/DeviceManagement: Thread (84):Thread[OkHttp ConnectionPool,4,main]:state:TIMED_WAITING
> 2019-03-30 11:27:51.482 6252-6360/pos D/DeviceManagement: Thread (85):Thread[OkHttp Dispatcher,4,main]:state:TIMED_WAITING
> 2019-03-30 11:27:51.482 6252-6360/pos D/DeviceManagement: Thread (86):Thread[OkHttp ConnectionPool,4,main]:state:TIMED_WAITING
> 2019-03-30 11:27:51.482 6252-6360/pos D/DeviceManagement: Thread (87):Thread[OkHttp Dispatcher,4,main]:state:TIMED_WAITING
> 2019-03-30 11:27:51.482 6252-6360/pos D/DeviceManagement: Thread (88):Thread[OkHttp Dispatcher,4,main]:state:TIMED_WAITING
> 2019-03-30 11:27:51.483 6252-6360/pos D/DeviceManagement: Thread (89):Thread[OkHttp Dispatcher,4,main]:state:TIMED_WAITING
> 2019-03-30 11:27:51.483 6252-6360/pos D/DeviceManagement: Thread (90):Thread[OkHttp Dispatcher,4,main]:state:TIMED_WAITING
> 2019-03-30 11:27:51.483 6252-6360/pos D/DeviceManagement: Thread (91):Thread[AsyncTask #13,5,main]:state:TIMED_WAITING
> 2019-03-30 11:27:51.483 6252-6360/pos D/DeviceManagement: Thread (92):Thread[OkHttp Dispatcher,4,main]:state:TIMED_WAITING
> 2019-03-30 11:27:51.484 6252-6360/pos D/DeviceManagement: Thread pool size:92

Every replicator start() seems to create a new OkHttp Client/Connection Pool.

Please see for usage guidelines: https://square.github.io/okhttp/3.x/okhttp/okhttp3/OkHttpClient.html

**Comment by bmeike** [comment]
I've reproduced this problem.  Looking into it now.

**Comment by bmeike** [comment]
This is, indeed, a something that needs to be fixed.  I have a patch that I will put into the master branch, shortly.
On the other hand it looks to me as if it is pretty easy to avoid the problem.  Although Replicators are, indeed, creating a new `ConnectionPool` for each new Replicator (not `start`, exactly), that `ConnectionPool` thread only sticks around for 5 minutes.
As a work-around, turn on continuous replication, if that is what you mean to do.  If you don't want continuous replication, one-shots every couple of minutes will generate only a couple extra threads.

**Comment by bmeike** [comment]
Feh.  You are correct.  Each call to `Replicator.start()`.

**Comment by bmeike** [comment]
PR is here: https://github.com/couchbase/couchbase-lite-java/pull/105

**Comment by bmeike** [comment]
fixed in https://github.com/couchbase/couchbase-lite-java/pull/105
