### ISSUE TITLE
Close all query listeners

### ISSUE THREAD

**Issue by RocketRider** [couchbase/couchbase-lite-android#1901]
Is there any way to close all query listeners without knowing them.
I want to delete the database and for that I need to close all listeners.

> Cannot delete the database.  Please remove all of the query listeners before closing the database.

**Comment by pasin** [comment]
A short answer is no. As of now, the app needs to keep tracking the returned tokens when adding the listener.

**Comment by pasin** [comment]
CC: @rajagp
