### ISSUE TITLE
Change to the WebSocket Timeout in in LiteCore

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-android#1913]
Per this https://github.com/couchbase/couchbase-lite-ios/pull/2447, the WebScoket implementation in LiteCore has implemented the timeout. To avoid conflict or duplication, we should disable WebSocket (read/write) timeout from the platform code. If it cannot be disabled, we probably need to set it to be longer that what LiteCore is using.

**Comment by bmeike** [comment]
FIled against the wrong repo.  Replaced by https://github.com/couchbase/couchbase-lite-java/issues/110
