### ISSUE TITLE
Android specific replication using WorkManager

### ISSUE THREAD

**Issue by bmeike** [couchbase/couchbase-lite-android#1916]
In order to avoid Android's draconian battery saving tactics, replication should be scheduled using Android's WorkManager.

Android devs should be discouraged from using continuous replication, ever, because it won't work.

**Comment by RocketRider** [comment]
What is the reason, why you think continuous replication won't work?
With a foreground service there should be no issue, or am I missing something?

**Comment by bmeike** [comment]
I don't think you are missing anything except, sort of, the intention of continuous integration.  You are definitely right that a foreground service would "work".  I don't think, though that it is what most developers will want: a notification in the user's face, that she can stop at random times.  The intention of continuous replication is that the local DB is kept up-to-date, "in the background": without user intervention.  That kind of describes a WorkManager task.
I can see very specific uses of continuous integration, while an app is in the foreground.  I think, for instance, of apps supporting ticket-takers or something like that.  In those cases you won't need a foreground service.  When the app is backgrounded, I think the WorkManager will provide the behavior that most devs expect.
