### ISSUE TITLE
support for OAuth in replicator

### ISSUE THREAD

**Issue by jchris** [couchbase/couchbase-lite-android#193]
Currently [iOS supports the replicator syncing to backends which are using OAuth](https://github.com/couchbase/couchbase-lite-ios/blob/master/Source/API/CBLManager.m?source=c#L562)

Sync Gateway doesn't do OAuth, but [CouchDB does.](https://wiki.apache.org/couchdb/Replication#OAuth)

**Comment by hideki** [comment]
CBL Android/Java support OpenID connect authenticator. So we don't have no plan to implement OAuth authenticator.
