### ISSUE TITLE
Gzipped attachment support with Replicator does not seem to be working

### ISSUE THREAD

**Issue by tleyden** [couchbase/couchbase-lite-android#197]
I noticed this while debugging another issue.

**Comment by hideki** [comment]
#327 and this is same issue?

**Comment by hideki** [comment]
Note to self:

There are at least two issues with gzipped attachment.

1. In case gzipped attachment is stored with Base64 encoding using Map,  gzipped attachment is automatically unzipped. And it is stored as unzipped data.
2. `attachments` tables `encoding` and `encoded_length` are not used (not updated).
3. Replicator does not set `Content-Encoding` for gzipped attachment.
