### ISSUE TITLE
Multiple updates of a document in single transaction cause conflict

### ISSUE THREAD

**Issue by march44** [couchbase/couchbase-lite-android#220]
I’m seeing an issue when doing more that one update to a document, this is part of a revisions performance test.

The following commands are run in a single thread:

for (int j = 0; j < _numberOfDocuments; j++) {

                   Document doc = docs[j];

                   for(int k=0; k<_numberOfUpdates; k++)
                   {
                       Map<String, Object> contents = new HashMap(doc.getProperties());

                       Boolean wasChecked = (Boolean) contents.get("toogle");

                       //toggle value of check property
                       contents.put("toogle",!wasChecked);

                       try {
                           doc.putProperties(contents);
                       } catch (CouchbaseLiteException cblex) {
                           return false;
                       }
                   }
               }

If the value _numberOfUpdates is set to one, the test completes without error.

If however the value of _numberOfUpdates is set greater than one then I get a conflict error:

"Conflicts not allowed and there is already an existing doc with id: e63a76fc-c5fd-4b9e-b2c9-73a7189a77b3"

**Comment by hideki** [comment]
It seems this is duplicated with https://github.com/couchbase/couchbase-lite-java-core/issues/419

Need to review and test
