### ISSUE TITLE
createAllDocumentsQuery().toLiveQuery() Throws Exception

### ISSUE THREAD

**Issue by shaundonnell** [couchbase/couchbase-lite-android#237]
When calling:

database.createAllDocumentsQuery().toLiveQuery()

At runtime, it throws The following:

/AndroidRuntime(12698): Caused by: java.lang.IllegalStateException: Cannot convert a Query to LiveQuery if the view is null

**Comment by Takhion** [comment]
By the way, this is the workaround we're using at the moment (essentially instead of not passing a `View`, we build one without a name):

```java
package com.couchbase.lite;

public final class AllDocumentsLiveQuery
{
    private AllDocumentsLiveQuery() {}

    public static LiveQuery createAllDocumentsLiveQuery(
            Database database, Query.AllDocsMode allDocsMode)
    {
        final Query q = new Query(database, new View(database, null));
        if (allDocsMode != null) { q.setAllDocsMode(allDocsMode); }
        return new LiveQuery(q);
    }
}
```
