### ISSUE TITLE
Case mismatch between Android and iOS attachment names

### ISSUE THREAD

**Issue by natevw** [couchbase/couchbase-lite-android#310]
The iOS lib stores attachments as `ABCDEF.blob`, whereas the Android library needs them to be loaded in to the replaceDatabase call as `abcdef.blob`.

**Comment by hideki** [comment]
Discussion with @zgramana  and @pasin about how to migrate from lower case file name to upper case file name.

- Fixed version of CBL Android/Java should handle both uppercase and lowercase attachment file name.
- If CBL found the lowercase attachment filename, show error or warning message.
- Manager should have option for auto migrate for attachment filename.
- If auto migration for attachment filename is TRUE, change all filenames from lowercase filename to uppercase filename.
- If migration is down, store the flag into local doc.
