### ISSUE TITLE
Missing test coverage for _bulk_get and _all_docs pull replications

### ISSUE THREAD

**Issue by tleyden** [couchbase/couchbase-lite-android#360]
I noticed this while digging in to https://github.com/couchbase/couchbase-lite-android/issues/331

When the pull replicator has to pull a certain number of docs, it will use `_bulk_get` in the Sync Gateway case, and `_all_docs` in the CouchDB case.  Neither of these have good test coverage at the moment.

See failingTestMockBulkPullSyngGw and failingTestMockBulkPullCouchDb

**Comment by hideki** [comment]
Hi @sethrosetter,
Can you verify if _bulk_get and _all_docs are covered by functional test? If yes, please close this ticket?

**Comment by sethrosetter** [comment]
@hideki I am using these api calls in the new listener tests. They API's are being used but not in every combination of input params.

**Comment by hideki** [comment]
@sethrosetter, thank you for confirming this. Covering all combination takes long time. If basic configurations are covered, I think it is good enough for now.

**Comment by hideki** [comment]
@sethrosetter, thank you for confirming this. Covering all combination takes long time. If basic configurations are covered, I think it is good enough for now.

**Comment by hideki** [comment]
@sethrosetter, thank you for confirming this. Covering all combination takes long time. If basic configurations are covered, I think it is good enough for now.

**Comment by sethrosetter** [comment]
@hideki. I looked through this again. _all_docs is being tested, however, _bulk_get is not exposed via the Listener as far as I can tell according to http://developer.couchbase.com/documentation/mobile/1.2/develop/references/couchbase-lite/rest-api/database/index.html. With our current setup, it would be hard to test _bulk_get without exposing it as the listener level. Is that possible?

**Comment by hideki** [comment]
Hi @sethrosetter,
Recent SG supports `_bulk_get`, default replication against SG uses  `_bulk_get`.
`_all_docs` is old style, replication against CouchDB uses `_all_docs`.
However, with Listener, CBL can not specify the replication API.
If you could add CouchDB in addition to SG, I believe we could cover both of them.

**Comment by sethrosetter** [comment]
@hideki Oh so under the the hood, if a Listener is replicating with a sg_gateway, it would be using `_bulk_get`? If that is the case, we are good.

**Comment by hideki** [comment]
@sethrosetter thanks!
