### ISSUE TITLE
Can't authenticate using non-ASCII passwords

### ISSUE THREAD

**Issue by mjq** [couchbase/couchbase-lite-android#382]
Tested against CouchDB 1.3.1.

Repro steps:
- Create a user with the password `“` (that's a curly double quotation mark, available on the Android keyboard by tap-and-holding on the double quote key).
- Try to authenticate through CBL with that password (tested by embedding directly in URL and by `BasicAuthenticator`)
- **Expected**: Successful authentication
- **Actual**: CBL fails to authenticate

[CouchDB expects passwords to be UTF8-encoded before they're Base64-encoded](https://mail-archives.apache.org/mod_mbox/couchdb-user/201407.mbox/%3CCAHdjipL00FmWF__2yn24c837kqXTL8PDu7%3DTyOhFz67Lm2sSLg%40mail.gmail.com%3E) as part of the basic authentication header.

This same password *does* work in the iOS version of CBL, since it [does the required UTF8 encoding](https://github.com/couchbase/couchbase-lite-ios/blob/master/Source/CBLAuthorizer.m#L43-L54).

I don't know how this works with Sync Gateway, but I'm guessing that it works the same way as Couch given that iOS code.

Possible fix
---------------
BasicScheme has a static [authenticate](http://developer.android.com/reference/org/apache/http/impl/auth/BasicScheme.html#authenticate%28org.apache.http.auth.Credentials,%20java.lang.String,%20boolean%29) method that takes an encoding. So, when making requests, replacing:
```java
HttpRequestInterceptor preemptiveAuth = new HttpRequestInterceptor() {
  @Override
  public void process(HttpRequest request, HttpContext context) throws HttpException, IOException {
    AuthState authState = (AuthState) context.getAttribute(ClientContext.TARGET_AUTH_STATE);
    if (authState.getAuthScheme() == null) {
      authState.setAuthScheme(new BasicScheme());
      authState.setCredentials(credentials);
    }
  }
};
```
with:
```java
HttpRequestInterceptor preemptiveAuth = new HttpRequestInterceptor() {
  @Override
  public void process(HttpRequest request, HttpContext context) throws HttpException, IOException {
    request.addHeader(BasicScheme.authenticate(credentials, "UTF-8", false));
  }
};
```
does the trick. This code appears at least twice in CBL (`ChangeTracker` and `RemoteRequest`).

I can't think of what kind of test to write for this.

Any ideas? (Non-ASCII passwords are an edge case, but a couple of our users have indeed hit this). Thanks!

**Comment by sergio91pt** [comment]
Encoding the userinfo in BasicAuthenticator seems to fix this issue, as then the username and password only contain ASCII as deemed valid in RFC 3986.

PR in couchbase/couchbase-lite-java-core#568

**Comment by sergio91pt** [comment]
Speaked too soon, as that doesn't make sense if it gets decoded after (was testing with the performance unit tests, with the password encoded in the url).

Using `basicHttpParams.setParameter(AuthPNames.CREDENTIAL_CHARSET, HTTP.UTF_8);`
in CouchbaseLiteHttpClientFactory should fix this. I'll test and create a PR.
