### ISSUE TITLE
Insertion time increasing too much with lots of documents

### ISSUE THREAD

**Issue by fernandocamargoti** [couchbase/couchbase-lite-android#399]
I have a case where I have to download lots of documents from my server. It's not using Couchbase, so I use a REST API to get the objects and insert them in my database. Then, I keep it in sync with the server.

The problem is that I can have tons of documents. Right now, I'm downloading and inserting 100 documents, asking the views to update, inserting another 100 documents and so on. Clearly, the time to update the views is not incresing and it's very short. But, the time to insert 100 documents is heavily increasing through this process. The first group of 100 documents is inserted in about 2 seconds. When there are more than 8000 documents, it's taking 16 seconds to insert. With 12000 documents, it's taking 22 seconds.

This way, when I tried to sync 27000 documents, I've lost 2 hours waiting and ended up quiting the process.

Is it a limitation of Couchbase Lite or the SQLite? Can it be fixed?

**Comment by hideki** [comment]
Since v1.1.0, pull replication is much faster than previous one. I will close this ticket.
