### ISSUE TITLE
Querying without updating the view

### ISSUE THREAD

**Issue by fernandocamargoti** [couchbase/couchbase-lite-android#400]
This problem happened to me in the same case that I registered in #399. As I said there, there was a moment when it was taking more than 20 seconds to insert a group of documents. And this synchronization will be running while the user is using the app to query some registers. The problem is that it's an app to control the entrance of an event. The user will be validating tickets using a barcode scanner. So, it's really important that the search for a ticket by its code in the database is very fast. But while the sync is running, it's taking 20 seconds to confirm if a ticket exists in the database.

My guess is that the insertion of the group of documents (that is taking too long) makes Couchbase Lite aware that the index must be updated. Then, when I try to query the view for the document, it starts to update the view and finishes only after the insertion is done.

I'd like to be able to query a view without updating the index, making use of the current index. So, in cases that speed is more important than if the index is up-to-date, I'd be able to use the current index.

Maybe there's another solution for this problem.

**Comment by hideki** [comment]
We are actively looking for the solution to improve the indexing performance.
By Fix of https://github.com/couchbase/couchbase-lite-java-core/issues/502 , indexing performance significantly improved if JSON document only uses ASCII range characters.

Following is performance result for indexing that compared with iOS and previous version. Master branch version of CBL Android on real device is 2x-3x slower than CBL iOS v1.0.4.
https://github.com/couchbase/couchbase-lite-java-core/issues/491#issuecomment-79863629

We have kept looking for solution to improve the any performance.

**Comment by hideki** [comment]
If master branch version of CBL Android is still slow for your use-case, please reopen this ticket. Thanks!
