### ISSUE TITLE
Encryption of database

### ISSUE THREAD

**Issue by fakeh** [couchbase/couchbase-lite-android#403]
Hi CBL-Android folks,

I'm investigating encryption of the local copy of the SQLite database. I'm not familiar with options in this area, but I wonder if this is something upcoming for CBL or whether you could point me in an appropriate existing direction? I found some reference to encryption in CBL files, e.g. https://github.com/couchbase/couchbase-lite-android/blob/f4d96e40a24ffafa16c04df21b0f73aa81d335bf/src/main/jni/JsonCollator/sqlite3.h but I imagine these aren't so relevant except as a potential hint?
http://www.zetetic.net/sqlcipher/sqlcipher-for-android/ Looked interesting - is it compatible? Would I be able to register the collator with it?
Best, Dan.

**Comment by fakeh** [comment]
Hi, is there any progress towards this? I notice that couchbase.com is claiming "local encryption support", is that still iOS only?

**Comment by hideki** [comment]
Hi @fakeh,

Encryption is still iOS only.

This feature is in our plan.
https://github.com/couchbase/couchbase-lite-java-core/issues/702

Thanks,
Hideki

**Comment by hideki** [comment]
This feature was already implemented with v1.2.0
