### ISSUE TITLE
Improve performance of javascript views

### ISSUE THREAD

**Issue by beilharz** [couchbase/couchbase-lite-android#407]
I have a small database (600 documents, only one revision each, 10 simple string-properties each).
The first time I query a very simple view, the response takes about 7 minutes. 

This trace looks like the most time is spend creating the json for the map function. 
![screen shot 2014-09-02 at 17 18 33](https://cloud.githubusercontent.com/assets/106003/4120721/99de7856-32b4-11e4-99d7-66753b941903.png)

Is this Jackson method really the main problem, or am i overlooking something? Any Ideas?

**Comment by hideki** [comment]
With v1.2.0, indexing by JavaScript mapper should be faster.
