### ISSUE TITLE
CBLQuery groupLevel Bug

### ISSUE THREAD

**Issue by tleyden** [couchbase/couchbase-lite-android#409]
From https://github.com/couchbase/couchbase-lite-ios/issues/435

Step 1 is to port unit test to see if this is currently failing on couchbase-lite-android.

**Comment by hideki** [comment]
Dec 22, 2014, @andreibaranouski added unit  test `testViewGroupedNoReduce()` into ViewsTest.java

**Comment by hideki** [comment]
master branch codes can pass this unit test, and codes are almost identical with iOS implementation. No code change for this ticket.
