### ISSUE TITLE
Please enable perf tests to run against couchbase lite!

### ISSUE THREAD

**Issue by yaronyg** [couchbase/couchbase-lite-android#414]
With the PR I had previously provided we could automatically run the perf tests against CouchBase Lite. 

This is a huge deal for me since my entire project is just CouchBase lite instances replicating with themselves. 

That PR got ripped out because most of the tests went to mocks. That seemed completely reasonable to me. But the perf tests are still in couchbase-lite-android! 

So PLEASE, for the sake of us trying to push CouchBase Lite into peer to peer, please do one of two things:

* Put back in the code to let us set up and run a local listener in couchbase-lite-android so we can run the perf tests easily and automatically against couchbase lite

or

* Put the perf tests in a separate project (so couchbase-lite-android can stay 'pure mock') that is just for perf testing so we can put the code to deploy a local listener there

Right now I'm actually doing my own perf testing on CouchBase lite because the replication performance is pretty seriously awful when replicating between two CouchBase lite instances. Having these perf tests available would be a big help. But right now they aren't in the right state to be used.

Thanks!

**Comment by hideki** [comment]
Performance test's target sync URL is configurable. I believe we don't need to do additional change.
