### ISSUE TITLE
Pull replication stop event called twice

### ISSUE THREAD

**Issue by ikartikss** [couchbase/couchbase-lite-android#442]
Hi the stop event on pull replication  is getting called twice ,can you confirm the issue.

**Comment by hideki** [comment]
notes to self

Three possibilities

1. user was confused by STOPPING and STOPPED events. Both STOPPING event and STOPPED event are notified.

2. If user runs both push and pull replicators,  STOPPED notification should be fired for each replicators.

3. Theoretically, following phenomenon should not occur.  When a replicator is stopped, a replicator fires STOPPED notification. Then, when a database is closed, it calls databaseClosing() of a replicator which also tries to stop replicator. With latest master codes, STOPPED state should not be entered more than one time. So this should not be occurred.
