### ISSUE TITLE
Push Replication, never receive REPLICATION_ACTIVE status

### ISSUE THREAD

**Issue by jcnorman48** [couchbase/couchbase-lite-android#451]
In the ChangeListener on my PushReplicator I never receive the "REPLICATION_ACTIVE" status after sending data.  I have verified that the data is being sent to the server.  In CB 1.0.2 the ChangeListener would receive the "REPLICATION_ACTIVE" status then go back to REPLICATION_IDLE after the data was sent.  This was tested with the master branch from this morning.  Here's a short log from the PushReplicator, I will follow up with detailed sync logs later.

10-31 11:56:07.385  17060-17390/com.assayrt I/System.out﹕ PUSH REP: PUSH replication event. Source: com.couchbase.lite.replicator.Replication@415dc050 Transition: INITIAL -> RUNNING Total changes: 0 Completed changes: 0
10-31 11:56:07.385  17060-17390/com.assayrt I/System.out﹕ PUSH REP: REPLICATION_ACTIVE
10-31 11:56:08.340  17060-17390/com.assayrt I/System.out﹕ PUSH REP: PUSH replication event. Source: com.couchbase.lite.replicator.Replication@415dc050 Transition: RUNNING -> IDLE Total changes: 0 Completed changes: 0
10-31 11:56:08.340  17060-17390/com.assayrt I/System.out﹕ PUSH REP: REPLICATION_IDLE
10-31 11:56:17.560  17060-17390/com.assayrt I/System.out﹕ PUSH REP: PUSH replication event. Source: com.couchbase.lite.replicator.Replication@415dc050 Total changes: 1 Completed changes: 0
10-31 11:56:17.560  17060-17390/com.assayrt I/System.out﹕ PUSH REP: REPLICATION_IDLE
10-31 11:56:17.680  17060-17390/com.assayrt I/System.out﹕ PUSH REP: PUSH replication event. Source: com.couchbase.lite.replicator.Replication@415dc050 Total changes: 1 Completed changes: 1
10-31 11:56:17.680  17060-17390/com.assayrt I/System.out﹕ PUSH REP: REPLICATION_IDLE

**Comment by tleyden** [comment]
I think this should be working on master already, we just need to verify this.

**Comment by zgramana** [comment]
Needs a unit test to determine if anything needs to be done.
