### ISSUE TITLE
Duplicate .so Gradle v0.14.0

### ISSUE THREAD

**Issue by RicardoBelchior** [couchbase/couchbase-lite-android#453]
Since updating Android Studio to v0.9.0 and therefore gradle to v0.14.0, I'm having the issue of: 
"Duplicate files copied in APK lib/armeabi/libcom_couchbase_touchdb_RevCollator.so"
when running proguard.

Has anyone experienced this?

**Comment by hideki** [comment]
Now Android Studio is v1.2. It seems this issue is out of date for now.
