### ISSUE TITLE
Doc_ids needs extra string quotes in _replicate POST request

### ISSUE THREAD

**Issue by laurent-g** [couchbase/couchbase-lite-android#476]
Hello,

I'm using phonegap plugin/android env.
I try to replicate a remote db to my local db with a specific document id but all the remote db is replicated.

POST _replicate
{"source":"http://192.168.1.15:5984/crm_demo_companies","target":"crm_companies","doc_ids":["12295ce12a5fd2a3e2867efdac00bdce"]}

My param doc_ids is ignored. 
The same test with 2 couchdb db is working.

A workaround could be used by using a filter and query_params but i prefer avoid it.

TY
Laurent

**Comment by tleyden** [comment]
@laurent-g are you still seeing a bug?  I will close out the ticket, but if you need me to re-open it let me know.

@snej 

> Look at the handling of _docIDs in -[CBLChangeTracker changesFeedPath] — that's the code that adds the extra parameters to the _changes call.

AFAIK that's implemented and working.  Here's a [test case](https://github.com/couchbase/couchbase-lite-android/blob/416c6039dc36ffa671cc09bbeae32998d41ee3fe/src/androidTest/java/com/couchbase/lite/replicator/ChangeTrackerTest.java#L137-L160) that has assertions related to the extra parameters to the `_changes` call.

**Comment by laurent-g** [comment]
Hey,

I just go deeper into this problem.I succeed making this working with couchbase lite.

My working post request to _replicate is :
{
  "source":"http://192.168.50.12/protocrm/db/crm_reporting",
  "target":"crm_reporting",
  "filter" : "_doc_ids",
  "query_params" : {
	"doc_ids": "[\"lge\"]"
  }
}
adb logcat
V/ChangeTracker(14273): com.couchbase.lite.replicator.ChangeTracker@425f28c0: Making request to http://192.168.50.12/protocrm/db/crm_reporting/_changes?feed=normal&heartbeat=300000&style=all_docs&filter=_doc_ids&doc_ids=%5B%22lge%22%5D

With CouchDB, I can make this working in a different way : 
{
  "source":"http://192.168.50.12/protocrm/db/crm_reporting",
  "target":"crm_reporting",
   "doc_ids": ["lge"]
}

So there is a different behavior with _replicate POST call.
It's not a big deal because i have now a workaround, but this is not the same parameters for couchbase lite and couchdb. 
doc_ids should not be included in query_params and should not be a stringified array.

I think this issue can be fixed starting from Router.java/do_POST_replicate.

**Comment by laurent-g** [comment]
@tleyden So can you reopen this issue ?

**Comment by tleyden** [comment]
@laurent-g yup -- reopened and changed the title.  

@andreibaranouski can you check cblite-tests to see if this is covered?  See https://github.com/couchbase/couchbase-lite-android/issues/476#issuecomment-71058452

**Comment by laurent-g** [comment]
It should be better if couchbase lite can make a POST instead of a GET request to _changes because of the limited size of URL. With a GET request it should not be possible to set a large list of ID.

See http://docs.couchdb.org/en/latest/api/database/changes.html

**Comment by tleyden** [comment]
> It should be better if couchbase lite can make a POST instead of a GET request to _changes because of the limited size of URL.

Couchbase Lite should do that by default when replicating against Sync Gateway.  If it's not, please file a separate ticket for that.

**Comment by snej** [comment]
It already does on iOS.

According to the [API docs](http://docs.couchdb.org/en/latest/api/database/changes.html#post--db-_changes), CouchDB also supports POSTs to `_changes`. IIRC it didn't use to, but the docs don't say what version it was added in.

**Comment by hideki** [comment]
With latest master (v1.2.1 plus fixes), I can not reproduce the issue anymore. I just submit Unit Test. And I will close this ticket.
