### ISSUE TITLE
Data repeat???how to set a unique document ?

### ISSUE THREAD

**Issue by 79144876** [couchbase/couchbase-lite-android#482]
@steveyen 
Hi!
```
{id=2859a63c-b4c9-4056-8822-28c8bbbc3a04, value={unit=97_15, ease_factor=2.5, level=0, due_time=0, last_ease_factor=2.5, status=0, book_id=97, delete=0, owner=0f0665e1-a0fa-4c57-ab00-b4a2bd4cf7d9, uuid=126728, type=Card, last_due_time=0, _rev=1-ff10d56b0ba1876bf6a66345e1487b30, _id=2859a63c-b4c9-4056-8822-28c8bbbc3a04}, key=97_15}

{id=24e0805d-09be-40e0-9673-6d753294c3e8, value={unit=97_15, ease_factor=2.5, level=0, due_time=0, last_ease_factor=2.5, status=0, book_id=97, delete=0, owner=0f0665e1-a0fa-4c57-ab00-b4a2bd4cf7d9, uuid=126728, type=Card, last_due_time=0, _rev=1-ff10d56b0ba1876bf6a66345e1487b30, _id=24e0805d-09be-40e0-9673-6d753294c3e8}, key=97_15}

{id=4680cd2d-0f73-44b3-88f3-3ecc57f21154, value={unit=97_15, ease_factor=2.5, level=0, due_time=0, last_ease_factor=2.5, status=0, book_id=97, delete=0, owner=0f0665e1-a0fa-4c57-ab00-b4a2bd4cf7d9, uuid=126728, type=Card, last_due_time=0, _rev=1-ff10d56b0ba1876bf6a66345e1487b30, _id=4680cd2d-0f73-44b3-88f3-3ecc57f21154}, key=97_15}
```

In fact, i only have 13 rows.But when i tested,and synced some devices,then i found 256 rows when i searched. 
it mean all data repeat('uuid' is my card unique key).I have login same user  on different devices ('owner').
So, i want to know,how to set a unique document ?
You can find that the value is the same. but "_id" not same. what's wrong??
Thanks.

**Comment by 79144876** [comment]
ok .maybe this is my problem.
When you create a document by calling the createDocument: method, Couchbase Lite generates a random unique identifier (a long string of hex digits) for it. You can choose your own identifier by calling getDocument() instead. When creating your own identifiers, remember that each identifier must be unique so you don’t get conflict errors when you save documents.
(http://docs.couchbase.com/couchbase-lite/cbl-android/cbl-android-1.0b2/)
i will test it.
Thanks,

**Comment by tleyden** [comment]
Those are the old docs, please see http://developer.couchbase.com/mobile/develop/references/couchbase-lite/index.html
