### ISSUE TITLE
getResourceAsStream() excessively inflating memory on Android 

### ISSUE THREAD

**Issue by Takhion** [couchbase/couchbase-lite-android#488]
I've recently become aware that [`ClassLoader.getResourceAsStream()`](http://developer.android.com/reference/java/lang/ClassLoader.html#getResourceAsStream(java.lang.String)) does some extreme caching and keeps the entire contents of the class's .jar in memory when used (see [here](https://github.com/FasterXML/jackson-core/pull/49) and [here](http://blog.danlew.net/2013/08/20/joda_time_s_memory_issue_in_android/)).
[`LoggerFactory.createLogger()`](https://github.com/couchbase/couchbase-lite-java-core/blob/1.0.3.1/src/main/java/com/couchbase/lite/util/LoggerFactory.java#L31) is using it, may I suggest adopting the same pattern used in #436 to get rid of it? It's an easy fix which would also be cleaner, more efficient, and fix #460 as a side effect (I know it's been suggested before, but this time it's for another reason!).

**Comment by tleyden** [comment]
@Takhion thanks for this very clear bug report.  I agree that we should do this.

**Comment by tleyden** [comment]
This will reduce tech support effort and we'll be able to close #460
