### ISSUE TITLE
View not indexing older revisions

### ISSUE THREAD

**Issue by Takhion** [couchbase/couchbase-lite-android#494]
Please consider the following example:
```java
// [] : revision
// () : current revision
// {} : tombstone revision
// *  : conflicts

Document d = db.createDocument();
SavedRevision r0 = d.createRevision().save();
// r0 becomes the current revision

// d -> (r0)

view.updateIndex();
// r0 gets indexed

SavedRevision r1 = r0.createRevision().save();
// r1 becomes the current revision

// d -> [r0] -> (r1)

view.updateIndex();
// r0 gets removed from the index
// r1 gets indexed

SavedRevision r2 = r0.createRevision().save(true); // this conflicts with r1
// r2 becomes the current revision

// d -> [r0] -> [r1]*
//           -> (r2)*

view.updateIndex();
// r1 gets removed from the index
// r2 gets indexed

UnsavedRevision $r3 = r2.createRevision();
$r3.setIsDeletion(true);
SavedRevision r3 = $r3.save(true);
// r1 becomes the current revision (again)

// d -> [r0] -> (r1)
//           -> [r2] -> {r3}

view.updateIndex();
// r2 gets removed from the index
```

**I would expect `r1` to get indexed again, being that it becomes (again) the "current revision", but that doesn't happen!**
The view only checks `lastSequence` and doesn't look at older revisions: in fact executing `view.deleteIndex()` properly maps `r1` again.

I don't know if this is intended behavior or a design flaw, but it's the behavior on Android with CouchBase Lite version `1.0.4-1004`.

**Comment by tleyden** [comment]
@snej / @pasin do you guys know if there is a test case on iOS that demonstrates this scenario works as expected?

**Comment by snej** [comment]
Yeah, look at `-[ViewInternalTests test06_ConflictLoser:]`.

**Comment by tleyden** [comment]
Thanks!  Ok here is the test that needs to be ported over to android:

https://github.com/couchbase/couchbase-lite-ios/blob/9430f708c8b191be2e96a0dfce9c8b0d855715ba/Unit-Tests/ViewInternal_Tests.m#L263-L298

@andreibaranouski can you port the above test case and then re-assign the ticket back to me?

**Comment by tleyden** [comment]
[test_ConflictWinner](https://github.com/couchbase/couchbase-lite-ios/blob/9430f708c8b191be2e96a0dfce9c8b0d855715ba/Unit-Tests/ViewInternal_Tests.m#L225-L260) should also be ported at the same time, since it is very similar.

**Comment by snej** [comment]
FYI the code that solves this bug on iOS is in the `-updateIndexes:` method under the comment `// Find conflicts with documents from previous indexings.`. It's an ugly hack that slows down re-indexing but I couldn't think of a better way to do it, at least not without significant schema changes.

**Comment by tleyden** [comment]
Thanks, that'll be helpful when we go to implement the fix.

**Comment by hideki** [comment]
Note to self

- Ported test case test_ConflictWinner and test_ConflictLoser from iOS. https://github.com/couchbase/couchbase-lite-android/commit/22996d2df2bfb0d8f366ad688727dee0932fd70f
- Current master branch can pass both unit test cases.

Action Items: 
- Write unit test case that community developer described in this ticket.
- Compare iOS and Android codes. The solution could be already ported from iOS to Android

**Comment by hideki** [comment]
This issue is also reproducible with CBL iOS. Filed the ticket for iOS and send PR for unit test.

**Comment by snej** [comment]
I just fixed this on iOS with commit https://github.com/couchbase/couchbase-lite-ios/commit/2b465f77852239335b8a743d4254c546d92ae719.

**Comment by hideki** [comment]
@snej Thank you for all your helps!

**Comment by hideki** [comment]
@Takhion Fix is in the master branch. Could you please verify the fix with your codes? Thanks for crystal clear bug report!
