### ISSUE TITLE
getDocIDs is null?!

### ISSUE THREAD

**Issue by Euphrates-Media** [couchbase/couchbase-lite-android#501]
Why event.getSource().getDocIds() is null in following code? I can't find out which docs added and pulled from CB!

 pullReplication.addChangeListener(new Replication.ChangeListener() {
            @Override
            public void changed(Replication.ChangeEvent event) {
event.getSource().getDocIds() IS NULL HERE
                int c=event.getChangeCount();
                c=c+1;
            }
        });

**Comment by hideki** [comment]
@Euphrates-Media Thank you for your report.

Could you please add additional information?
- What is value of event.getSource().getStatus()?
- What is other Replication.ChangeEvent variables?

Thanks!

**Comment by hideki** [comment]
With current implementation, `Replication.ChangeListener` does not provide the updated document ids. Please use `Database.ChangeListener` to detect updated documents.
