### ISSUE TITLE
Why was this unit test removed?

### ISSUE THREAD

**Issue by borrrden** [couchbase/couchbase-lite-android#502]
https://github.com/couchbase/couchbase-lite-android/commit/2ed09856d1d14b9d7a82cf530bd5e834bb825197

The "latency" batcher tests were removed from the test suite.  I'm curious as to what they were testing and why they were removed.  Could someone answer that for me?

**Comment by hideki** [comment]
@tleyden can you answer for @borrden 's question?

**Comment by tleyden** [comment]
@borrrden well, you looked at the tests and said they didn't make any sense.  That's basically the reason I removed them -- they didn't make any sense.

I added those based on some requirements handed down to me, without fully understanding them, and then later when they started failing and I tried to understand them, they made no sense to me.  I didn't get what they were trying to assert.

I'd suggest removing them on the .net side as well, unless you can make a strong case for their value.
