### ISSUE TITLE
Don't get all my Docs because of Conflicts

### ISSUE THREAD

**Issue by TheSlowlySnail** [couchbase/couchbase-lite-android#507]
Hey Guys, 

I have 20 items in my Document but in my Android App it just shows 1 in my Sync Gateway it says  PUT /sync_gateway/_local/2acd68717503aca5526cf9af4415ae763cad27bb
18:14:12.610507 HTTP: #020:     --> 409 Document update conflict 

Made a Couchbase Server with Sync Gateway on ubuntu 32 Bit. 
there is my config file

{    "interface": ":4984",
    "adminInterface": ":4985",
    "log": ["CRUD", "CRUD+", "HTTP", "HTTP+", "Access", "Cache", "Shadow", "Shadow+", "Changes", "Changes+"],
    "databases": {
        "sync_gateway": {
            "server": "Server:8091",
            "bucket": "test_sync_gateway",
            "sync": `function(doc) {channel(doc.channels);}`,
            "users": {
                "GUEST": {
                    "disabled": false,
                    "admin_channels": ["*"]
               }
			},
			"shadow": {
                 "server": "Server:8091",
                 "bucket": "test_shadow"
            }
		} 
	}
}

I don't update something with android I just changed some inserts on my Server itself.
I hope someone can help me :) 
so how can I fix the conflict ?

**Comment by hideki** [comment]
@TheSlowlySnail Could you please post more detailed information with following our guideline. https://github.com/couchbase/couchbase-lite-android/blob/master/CONTRIBUTING.md

**Comment by hideki** [comment]
@adamcfraser @ajres and @tleyden Do you have any idea about this issue?

**Comment by TheSlowlySnail** [comment]
So I don't know what I should tell more about my bug, I'm using Android 5 I told everything about the Server. I also tried to connect my Couchbase Server with the GroceryStore example but I just get this. 
![2015-01-30 20 32 56](https://cloud.githubusercontent.com/assets/2567347/5982826/b52f19ba-a8c7-11e4-98e2-b61c3a881846.png) 

Sync Gateway shows this when I try to connect the Couchbase Server with GroceryStore 

21:34:25.007012 HTTP:  #053: POST /sync_gateway/_changes
21:34:25.007143 Changes: MultiChangesFeed({*}, {Since:428 Limit:50 Conflicts:true IncludeDocs:false Wait:true Continuous:false Terminator:0x1902e9f0}) ...
21:34:25.007431 Changes+: MultiChangesFeed: channels expand to channels.TimedSet{"*":0x1} ...
21:34:25.007669 Changes+: MultiChangesFeed waiting...
21:34:25.007924 Changes+: Waiting for "test_sync_gateway"'s count to pass 0


I want that I can see my Data in the Grocery Store example 
and of course in my own App.

**Comment by TheSlowlySnail** [comment]
also when I try to get some Data in my App it shows 

01-30 22:05:03.906: E/RemoteRequest(12390): Got error status: 409 for http://server:4984/sync_gateway/_local/2acd68717503aca5526cf9af4415ae763cad27bb.  Reason: Conflict

**Comment by TheSlowlySnail** [comment]
my class there I try to get my Data looks like this  

package com.jwetherell.quick_response_code;

import java.io.IOException;
import java.util.Iterator;
import java.util.Map;

import android.app.Activity;
import android.content.Intent;
import android.os.Bundle;
import android.view.Menu;
import android.view.View;
import android.widget.TextView;

import com.couchbase.lite.CouchbaseLiteException;
import com.couchbase.lite.Database;
import com.couchbase.lite.Emitter;
import com.couchbase.lite.Manager;
import com.couchbase.lite.Mapper;
import com.couchbase.lite.Query;
import com.couchbase.lite.QueryEnumerator;
import com.couchbase.lite.QueryRow;
import com.couchbase.lite.SavedRevision;
import com.couchbase.lite.android.AndroidContext;
import com.couchbase.lite.replicator.Replication.ChangeEvent;
import com.couchbase.lite.replicator.Replication.ChangeListener;
import com.jwetherell.quick_response_code.database.SyncGate;

public class main extends Activity implements ChangeListener {

	private Intent iScan;
	private Intent iProfil;
	
	private TextView showUnv; 
	
	
	
	private Database database = null;
	private Manager manager = null;
	private SyncGate sgWay = new SyncGate(); 
	
	@Override
	protected void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);
		setContentView(R.layout.activity_main);
		iScan = new Intent(this, CaptureActivity.class);
		iProfil = new Intent(this, Profil.class);
		
		try {
			database= sgWay.startCBLite(new AndroidContext(this)); 
			manager = sgWay.getManager(); 
			startQuery();
			
			//startCBLite();
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
//	
//		showUnv				= (TextView) findViewById(R.id.showUnv);	
//		String UnvList		= getUnvList();
//		showUnv.setText(UnvList);
//		
	}

	@Override
	public boolean onCreateOptionsMenu(Menu menu) {
		// Inflate the menu; this adds items to the action bar if it is present.
		getMenuInflater().inflate(R.menu.main, menu);
		return true;
	}
	
	@Override
	public void onResume(){
		 super.onResume();
		   this.onCreate(null);
	}
	
	
	public void toScan(View view){
		startActivity(iScan);
	}
	public void toProfil(View view){
		startActivity(iProfil);
	}

	
	
	private void startQuery() throws CouchbaseLiteException{

		com.couchbase.lite.View viewItem = database.getView("AusgabeProdukt");
		
				if (viewItem.getMap() == null) {
			viewItem.setMap(new Mapper() {
				@Override
				public void map(Map<String, Object> document, Emitter emitter) {
					Object createdType = document.get("type");
					Object createdid = document.get("id");
					if (createdType != null && createdType.toString().equals("Lebensmittel")) {
						emitter.emit(createdType.toString(),createdid.toString());
					}
				}
			}, "1.0");
		}


		Query query = viewItem.createQuery();
		
                  TextView textView = (TextView) findViewById(R.id.showUnv);
		 String c = "" ;
		QueryEnumerator rowEnum = query.run();
		
		for (Iterator<QueryRow> it = rowEnum; it.hasNext();) {
			QueryRow row = it.next();
			SavedRevision currentRevision = row.getDocument().getCurrentRevision();
			
			  c += "___"+currentRevision.getProperty("type")+ currentRevision.getProperties()+ "\n" ;
			 
			//getDocument().getProperty("id")
			}
		
		textView.setText(c);

	}

	
	
	@Override
	public void changed(ChangeEvent arg0) {
		// TODO Auto-generated method stub
		
	}
	
}


I also made an Class called Sync Gate which looks like this 

package com.jwetherell.quick_response_code.database;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.Iterator;
import java.util.Map;

import android.app.Activity;
import android.os.Bundle;
import android.view.Menu;
import android.view.MenuItem;
import android.widget.TextView;
import android.widget.Toast;

import com.couchbase.lite.CouchbaseLiteException;
import com.couchbase.lite.Database;
import com.couchbase.lite.Document;
import com.couchbase.lite.Emitter;
import com.couchbase.lite.Manager;
import com.couchbase.lite.Mapper;
import com.couchbase.lite.Query;
import com.couchbase.lite.QueryEnumerator;
import com.couchbase.lite.QueryRow;
import com.couchbase.lite.Database.ChangeEvent;
import com.couchbase.lite.View;
import com.couchbase.lite.android.AndroidContext;
import com.couchbase.lite.replicator.Replication;
import com.couchbase.lite.replicator.Replication.ChangeListener;
import com.couchbase.lite.util.Log;
import com.jwetherell.quick_response_code.R;


public class SyncGate extends Activity implements ChangeListener {
	public static String TAG = "GrocerySync";

	// constants
	public static final String DATABASE_NAME = "test_sync_gateway";
	public static final String designDocName = "meinTellerchenLocal";
	private Database database = null;
	private Manager manager = null;
	

	public static final String SYNC_URL = "http://server:4984/sync_gateway";

	

	public Database startCBLite( AndroidContext aContext) throws Exception {
		// TODO Auto-generated method stub
		manager = new Manager(aContext, Manager.DEFAULT_OPTIONS);

		database = manager.getDatabase(DATABASE_NAME);
				
		startSync();
		return database;
	}
	
	
	public Manager getManager(){
		return manager;
	}
	

	
	private void startSync() {

		URL syncUrl;
		try {
			syncUrl = new URL(SYNC_URL);
		} catch (MalformedURLException e) {
			throw new RuntimeException(e);
		}

		Replication pullReplication = database.createPullReplication(syncUrl);
		pullReplication.setContinuous(true);

		Replication pushReplication = database.createPushReplication(syncUrl);
		pushReplication.setContinuous(true);

		pullReplication.start();
		pushReplication.start();

		pullReplication.addChangeListener(this);
		pushReplication.addChangeListener(this);

	}

	@Override
	public boolean onCreateOptionsMenu(Menu menu) {
		// Inflate the menu; this adds items to the action bar if it is present.
		getMenuInflater().inflate(R.menu.main, menu);
		return true;
	}

	public boolean onOptionsItemSelected(MenuItem item) {
		// Handle action bar item clicks here. The action bar will
		// automatically handle clicks on the Home/Up button, so long
		// as you specify a parent activity in AndroidManifest.xml.
		int id = item.getItemId();
		if (id == R.id.action_settings) {
			return true;
		}
		return super.onOptionsItemSelected(item);
	}

	@Override
	protected void onDestroy() {
		// TODO Auto-generated method stub
		if (manager != null) {
			manager.close();
		}

		super.onDestroy();
	}

	
	@Override
	public void changed(
			com.couchbase.lite.replicator.Replication.ChangeEvent arg0) {
		// TODO Auto-generated method stub
		
	}

}

**Comment by tleyden** [comment]
@TheSlowlySnail can we go back to a known good starting point and go from there?  

What happens if you:

* Uninstall your app from device / emulator
* Clone an *unmodified* version of GrocerySync Android, which is pointed to our demo cluster sync gateway
* Run the app
* Wait a few minutes

Do you see this?

![screen shot 2015-01-30 at 1 47 19 pm](https://cloud.githubusercontent.com/assets/296876/5983943/91c5d216-a886-11e4-87af-1a666d5dc8ec.png)

**Comment by TheSlowlySnail** [comment]
I just tried what you said and it shows the result above 

but when I changed this line in the code I got everthing in the grocerySync List
String groceryItemText = (String) currentRevision.getProperty("type");

**Comment by tleyden** [comment]
> I just tried what you said and it shows the result above

Ok, great.

> but when I changed this line in the code I got everthing in the grocerySync List
String groceryItemText = (String) currentRevision.getProperty("type");

I'm confused.  What problem are you trying to solve at this point?

**Comment by TheSlowlySnail** [comment]
Like you see above I had the problem that I just seen empty fields when it was : 
String groceryItemText = (String) currentRevision.getProperty("texts"); 

because I haven't the attribute texts in my json files nothing showed so I changed it in
String groceryItemText = (String) currentRevision.getProperty("type"); 
which is in my json files.

**Comment by hideki** [comment]
Hi @TheSlowlySnail 

Do you have any update about this ticket?

I think non of documents does not pass if-else condition in `map()` method below. Can you add Log.e(...); before emit() method? Also can you share your sample document? 
```
viewItem.setMap(new Mapper() {
            @Override
            public void map(Map<String, Object> document, Emitter emitter) {
                Object createdType = document.get("type");
                Object createdid = document.get("id");
                if (createdType != null && createdType.toString().equals("Lebensmittel")) {
                    emitter.emit(createdType.toString(),createdid.toString());
                }
            }
        }, "1.0");
```

Thanks!

**Comment by hideki** [comment]
Hi @TheSlowlySnail,
As we could not get any additional information, so I will close this ticket.
If this is still reproducible, please reopen the ticket with additional information.
Thanks!
Hideki
