### ISSUE TITLE
Stop replication problem

### ISSUE THREAD

**Issue by QRPro** [couchbase/couchbase-lite-android#518]
I create one-shot replication:

Replication = database.createPullReplication(Url);
Replication.setAuthenticator(auth);
Replication.setContinuous(false);
Replication.addChangeListener( .... );
Replication.start();

But I can not stop it by method stop...
Replication.stop();

Couchbase version 1.0.3.1

**Comment by hideki** [comment]
Hi @QRPro

Replication.stop() does not stop replicator immediately. It  sends the  trigger to stop.

**Comment by QRPro** [comment]
Replication continues to work for a long time ((Is there a way to stop it?

**Comment by hideki** [comment]
As far as I know, Replication does not provide the method that you are looking for. You can submit the feature request.
