### ISSUE TITLE
Gradle/Maven setup seems to be wrong in README (Need to update `Adding Couchbase Lite to your Gradle project` section of README)

### ISSUE THREAD

**Issue by FeanorsCurse** [couchbase/couchbase-lite-android#526]
In the readme it tells me to set up gradle the following way:

```xml
<dependency>
  <groupId>com.couchbase.lite</groupId>
  <artifactId>android</artifactId>
  <version>${latest_version}</version>
</dependency>
```

Then it gives a link to the maven repo to find out the correct version: http://files.couchbase.com/maven2/com/couchbase/lite/couchbase-lite-java-core/

Maybe I'm getting maven wrong, but the path in the link you provide here is different than in the dependency: couchbase-lite-java-core != android

In any case, I cannot get it working (tried a couple of things, this is just one exemplary error message):
```
Error:(31, 13) Failed to resolve: com.couchbase.lite:android:1.0.4
```

**Comment by hideki** [comment]
Hi @FeanorsCurse 

Please refer following instruction.
http://developer.couchbase.com/mobile/develop/training/build-first-android-app/get-started-studio/index.html

I recommend to use version 1.0.4.
