### ISSUE TITLE
Preexisting documents in a channel are not replicating to the client.

### ISSUE THREAD

**Issue by J-R-W** [couchbase/couchbase-lite-android#535]
I am on my second prototype iteration. This round I have separated documents into additional channels. I am now allowing the client (android CBL 1.0.4) to request to join a given channel by creating a join document.  

After a join document is received I can see from the user's sync gateway's changes feed that the user is added to the requested channel and the preexisting documents do show up in the feed. However these documents are not replicated down to the client. 

Steps
1) The client creates the join document in this case doc_id "fcj-46584223b5640e61e058b24353dd73cfadcc5cfad231f31ccc47dfd772136d5c-0238db848c67469b8ee90993524567834a9c3a9802963726dc32a76feb7cae09-0"

2) In the below sync gateway changes feed link.  You should see the six identified preexisting documents  that the client does not receive.  I do think it looks odd that the join document and the six preexisting documents share the same sequence number but I am assuming it's normal.

https://gist.github.com/J-R-W/6ac205a63846d3cbe192

3) Below are the CBL logs I cannot see any of the missing documents being replicated in the log. For sequence 46 (seq=46) I am only seeing the join doc.

https://gist.github.com/J-R-W/4519b43e66a1fc454edc

4) I don't see the missing documents in the CBL's "docs" view below. 

![screenshot_2015-03-02-09-54-12](https://cloud.githubusercontent.com/assets/8051304/6441280/03d40df0-c119-11e4-9be3-d80c327af7ef.png)

5) Below is the sync gateway's log. 

https://gist.github.com/J-R-W/6788a1014ee34a9c8af7

I think this could be an issue with either the SGW or CBL lite I am now running the most recent github build of SGW on Ubuntu 14 LTS and can reliably reproduce this issue. 

I'm looking forward to getting this iteration out to my alpha user's so do not hesitate to ask me anything. 

-Justin

P.S. Overall the framework has been great to work with.  Kudos. :)

**Comment by tleyden** [comment]
@J-R-W thanks for the bug report.  Which version of sync gateway are you testing against?

**Comment by J-R-W** [comment]
@tleyden 

Saturday's github build.

**Comment by J-R-W** [comment]
@tleyden 

I found that if I briefly filter the newly added channels via a pull replication filter, I can consistently pull down the docs in the channels.  I hope this helps. 

I'm still looking at the issue as well.  I do need to keep my project moving forward though so far now I"m using this band aid.

**Comment by tleyden** [comment]
@snej do you know if this is supposed to work?

> After a join document is received I can see from the user's sync gateway's changes feed that the user is added to the requested channel and the preexisting documents do show up in the feed. However these documents are not replicated down to the client.

**Comment by snej** [comment]
Yes, when a user gets access to a channel the pre-existing docs in that channel should be synced to the user on their next pull. SG detects that the sequence # at which you gained access is later than the `since` sequence, so it sends you a bunch of old sequences for all the docs in the channel. (They actually get renumbered with the weird compound sequence IDs, to avoid confusion if the sync gets interrupted in the middle of the backfill.)

**Comment by hideki** [comment]
Hi @snej, 

Thank you very much for your inputs.

If my understanding is correct, sequence number should be integer value. So <seq number>:<another seq number> should not be allowed. Does it cause the problem?

Do you know any documentation which explains about join document?

Thanks!

**Comment by snej** [comment]
No, in the replication protocol a _remote_ sequence ID can be any JSON object. It's important to handle any type of object, and to preserve its type when you save it in a checkpoint and later pass it to `_changes`. Sync Gateway sometimes uses strings, and Cloudant and BigCouch always do.

I think "join document" just refers to something specific to somebody's app. It's not a general term of ours.

**Comment by tleyden** [comment]
Sync gw config:

```
	"databases": {
		"db": {
			"server": "walrus:data",
			"sync": `
		    function(doc){
			    console.log("sync function called")
			channel(doc.channels);
			console.log("checking doc type")
			if (doc.type == "accessGrant") {
			    
			    console.log("giving accessGrant access.")
			    console.log("doc.user. " + doc.user + " doc.accessChannel: " + doc.accessChannel)
			    access(doc.user, doc.accessChannel);
			} else {
			    console.log("not an accessGrant")
			}
}`,
			"users": {
			    "GUEST": {"disabled": true, "admin_channels": ["*"]},
			    "Hideki": {"name": "Hideki", "password": "passw0rd", "disabled": false,  "admin_channels": ["ABC"]}
			}

		},
```

Curl requests:

```
curl -X "POST" "http://localhost:4984/db/" \
	-H "Authorization: Basic SGlkZWtpOnBhc3N3MHJk" \
	-d "{\"foo\":\"bar2\",\"channels\":[\"NBC\"]}"

curl -X "POST" "http://localhost:4984/db/" \
	-H "Authorization: Basic SGlkZWtpOnBhc3N3MHJk" \
	-d "{\"type\":\"accessGrant\",\"accessChannel\":\"NBC\",\"user\":\"Hideki\"}"

curl -X "GET" "http://localhost:4984/db/_changes?since=5" \
	-H "Authorization: Basic SGlkZWtpOnBhc3N3MHJk"

```

**Comment by hideki** [comment]
Hi @J-R-W,

I tried to reproduce this issue, and I wrote the unit test https://github.com/couchbase/couchbase-lite-android/pull/610/files. However, I could not reproduce this issue.

If you have chance, can you review test case if it covers your scenario? https://github.com/couchbase/couchbase-lite-android/pull/610/files

Thanks,
Hideki

**Comment by hideki** [comment]
This issue is reproducible with CBL v1.0.4. However, the issue is no longer reproducible with master and release/1.1.0 branches.

Test results:
- Unit Test with release/1.0.4 branch: joined documents are not replicated.
- Unit Test with master branch (same with release/1.1.0 branch): joined documents are replicated.

**Comment by J-R-W** [comment]
@hideki  et al, 

Awesome thank you for looking into this issue and resolving it.  I'm looking forward to the 1.1.0 release.  :)

**Comment by hideki** [comment]
Hi @J-R-W,
Please let us know your test results with 1.1.0.
Have a nice weekend!
