### ISSUE TITLE
Bulk Insert, Update and Delete operations.

### ISSUE THREAD

**Issue by PankaJJakhar** [couchbase/couchbase-lite-android#536]
In some cases I need to insert, update and delete multiple documents. So doing so one by one in a loop is very cumbersome operation. Is there any way to perform these operations in bulk instead of doing it in a loop.

**Comment by tleyden** [comment]
No, but you can wrap in a transaction which should have better performance.  For questions, please ask on the google group or in [gitter](https://gitter.im/couchbase/mobile) rather than opening a ticket.
