### ISSUE TITLE
No Callback on Replication Change Listeners for Errors (401)

### ISSUE THREAD

**Issue by tikimcfee** [couchbase/couchbase-lite-android#540]
Hey there guys,

Working on a project at the moment where the flow of UI and sync execution is dependent on whether or not a user has a valid set of credentials and is authenticated against our back end.

As of now, it seems that the Replication change listener does not fire off its ````changed(ChangeEvent event);```` callback on registered listeners for errors.

Our base is off a direct pull from master branch as of March 1, 2015.

An example execution:
````java
//Listener registration
for (Replication r : replicators) {
	...
    r.addChangeListener(this);
    r.start();
}
````
````
// Password for authentication target is changed
[...]
[...]
[...] W/Sync﹕ com.couchbase.lite.replicator.PullerInternal@425f39a0: starting ChangeTracker with since=107857 mode=OneShot
[...] W/Sync﹕ com.couchbase.lite.replicator.PullerInternal@425f39a0: started ChangeTracker com.couchbase.lite.replicator.ChangeTracker@42a89d98
[...] E/ChangeTracker﹕ com.couchbase.lite.replicator.ChangeTracker@42a89d98: Change tracker got error 401
[...] W/ChangeTracker﹕ com.couchbase.lite.replicator.ChangeTracker@42a89d98: Change tracker calling changeTrackerStopped, client: com.couchbase.lite.replicator.PullerInternal@425f39a0
[...] E/Sync﹕ Change tracker stopped during continuous replication
[...] W/Sync﹕ [fireTrigger()] => WAITING_FOR_CHANGES
[...] W/Sync﹕ com.couchbase.lite.replicator.PullerInternal@425f39a0: starting ChangeTracker with since=107857 mode=OneShot
[...] W/Sync﹕ com.couchbase.lite.replicator.PullerInternal@425f39a0: started ChangeTracker com.couchbase.lite.replicator.ChangeTracker@426ed698
[...] E/ChangeTracker﹕ com.couchbase.lite.replicator.ChangeTracker@426ed698: Change tracker got error 401
[...] W/ChangeTracker﹕ com.couchbase.lite.replicator.ChangeTracker@426ed698: Change tracker calling changeTrackerStopped, client: com.couchbase.lite.replicator.PullerInternal@425f39a0
[...] E/Sync﹕ Change tracker stopped during continuous replication
[...] W/Sync﹕ [fireTrigger()] => WAITING_FOR_CHANGES
[...] W/Sync﹕ com.couchbase.lite.replicator.PullerInternal@425f39a0: starting ChangeTracker with since=107857 mode=OneShot
[...] W/Sync﹕ com.couchbase.lite.replicator.PullerInternal@425f39a0: started ChangeTracker com.couchbase.lite.replicator.ChangeTracker@42597e90
[...] E/ChangeTracker﹕ com.couchbase.lite.replicator.ChangeTracker@42597e90: Change tracker got error 401
[...] W/ChangeTracker﹕ com.couchbase.lite.replicator.ChangeTracker@42597e90: Change tracker calling changeTrackerStopped, client: com.couchbase.lite.replicator.PullerInternal@425f39a0
[...] E/Sync﹕ Change tracker stopped during continuous replication
[...]  W/Sync﹕ [fireTrigger()] => WAITING_FOR_CHANGES
[...]
[...]
// No callbacks are fired for the above events
````

**Comment by tleyden** [comment]
Which version are you running?  (please see https://github.com/couchbase/couchbase-lite-android/blob/master/CONTRIBUTING.md)

**Comment by tikimcfee** [comment]
Whoops - my mistakes. Thanks for the link to that. Edited original:

Our base is off a direct pull from master branch as of March 1, 2015.

**Comment by tikimcfee** [comment]
Hey there folks! Just checking in to see if there is an update on this. Any word on being able to reproduce this, or is it proving tricky? Any way we can help?

Thanks!

**Comment by hideki** [comment]
Hi @tikimcfee,

Sorry, we could not look into this issue yet. We will try to fix this as soon as possible.

Thanks!

**Comment by tikimcfee** [comment]
No worries there - thanks for the update! Just let us know if we can help in any way.

**Comment by hideki** [comment]
Hi @tikimcfee,

Thank you very much for your patience.

Replicator of CBL Android/Java calls callback for HTTP 401 Error. But problem is it is not developer friendly way (not obvious).

In case HTTP related errors occurs in the replicator, the replicator creates an instance of org.apache.http.client.HttpResponseException with setting HTTP status code and message, and set it in `ChangeEvent.error`, and calls `Replication.ChangeListener.changed(Replication.ChangeEvent)`. You can retrieve error codes like below sample.

Sample code
```
    @Override
    public void changed(final Replication.ChangeEvent event) {
        if(event != null) {
            Log.e(TAG_REPL , event.toString());
            if(event.getError() instanceof HttpResponseException){
                HttpResponseException ex = (HttpResponseException)event.getError();
                Log.e(TAG_REPL, "HTTP Error: " + ex.getStatusCode() + ": " + ex.getMessage());
            }
        }
    }
```

Entire sample code
https://github.com/hideki/couchbase-lite/tree/master/test/Issue540

I hope this helps you.

Thanks,
Hideki

**Comment by anisart** [comment]
Hi all,

I use version 1.1.0 via gradle. @hideki's sample code works only if app pushes change to server.

For example, I create user "foo" with password "bar" and login with this in ToDoLite sample app. I create new task in list. After sync I change user password via REST API and change task in Sync Gateway /_admin. I see many "ChangeTracker: com.couchbase.lite.replicator.ChangeTracker@42b16590: Change tracker got error 401" in logcat but unautorized callback is not called. It's called only if I make some changes in app.

**Comment by hideki** [comment]
Hi @anisart,
Could you please create new ticket for authentication issue with changing password?
Thanks a lot!
