### ISSUE TITLE
Updating a document in a transaction block twice using Document.DocumentUpdater results in an infinite loop

### ISSUE THREAD

**Issue by nantoka69** [couchbase/couchbase-lite-android#563]
The following code was used with Couchbase Light for Android, Community Edition 1.0.3.1:

	Document myDocument;
	
	public void updateDocumentInTransactionTest() throws CouchbaseLiteException{
		
		myDocument = database.createDocument();
		HashMap <String, Object> properties = new HashMap <String, Object>();
		properties.put("key", "value1");		
		myDocument.putProperties(properties);
		
		database.runInTransaction(
			new TransactionalTask(){

				@Override
				public boolean run() {
					
					try {
						myDocument.update(new Document.DocumentUpdater() {
						    @Override
						    public boolean update(UnsavedRevision newRevision) {
						    	Log.d("updateDocumentInTransactionTest", "Trying to update key to value 2");
						        Map<String, Object> properties = newRevision.getUserProperties();
						        properties.put("key", "value2");
						        newRevision.setUserProperties(properties);
						        return true;
						    }
						});
						myDocument.update(new Document.DocumentUpdater() {
						    @Override
						    public boolean update(UnsavedRevision newRevision) {
						    	Log.d("updateDocumentInTransactionTest", "Trying to update key to value 3");
						        Map<String, Object> properties = newRevision.getUserProperties();
						        properties.put("key", "value3");
						        newRevision.setUserProperties(properties);
						        return true;
						    }
						});
					} catch (CouchbaseLiteException e) {
						
						e.printStackTrace();
						return false;
					}
					
					return true;
				}
		});
	}

The result is an endless loop of this output:
	...
	04-04 02:17:21.945: D/updateDocumentInTransactionTest(25571): Trying to update key to value 3
	...

As using putProperties() multiple times on the same document in a ```TransactionalTask``` creates a ```CouchbaseLiteException```, it is currently impossible to update a document more than once in a task.

**Comment by hideki** [comment]
@pasin Did you work for same issue on iOS? If so, can you provide link to iOS ticket?

**Comment by pasin** [comment]
Jens fixed this issue. See here:
https://github.com/couchbase/couchbase-lite-ios/commit/56ef7a202480885ad33a27e299b667fbcdb86f9a

**Comment by hideki** [comment]
@pasin Thanks!

**Comment by hideki** [comment]
Note to self:
This issue is reproducible with 1.0.4. But not with master. I could fix this when I fixed others. Need to compare with couchbase/couchbase-lite-ios@56ef7a2 .

**Comment by hideki** [comment]
It seems this is duplicated with https://github.com/couchbase/couchbase-lite-java-core/issues/419

**Comment by hideki** [comment]
This ticket is duplicate with #563 and couchbase/couchbase-lite-java-core#419.  I will close this.
