### ISSUE TITLE
Exclude build-zip scripts from couchbase/build, and merge it into couchbase/couchbase-lite-android.

### ISSUE THREAD

**Issue by hideki** [couchbase/couchbase-lite-android#568]
1. Exclude build-zip scripts from couchbase/build
https://github.com/couchbase/build/tree/master/scripts/jenkins/mobile/zip_jars

2. Merge script into couchbase/couchbase-lite-android
https://github.com/couchbase/couchbase-lite-android/tree/master/release

3. Fix Jenkins's side script file to apply above changes

**Comment by andreibaranouski** [comment]
@hideki I fixed master branch and changed jenkins jobs accordingly. do we have to leave libraries in release/1.0.4 branch as they are now? or is there any libs/version we want to change?

**Comment by hideki** [comment]
Hi @andreibaranouski 
Thank you very much for your work.

For release/1.0.4 
- Jackson v1.9.2
- stateless4j - v2.4.0

**Comment by andreibaranouski** [comment]
all done
