### ISSUE TITLE
Can't find in maven repo

### ISSUE THREAD

**Issue by JoshElias** [couchbase/couchbase-lite-android#577]
I've followed the instructions to add this to my Android Studio project but cannot download the dependencies.

**Comment by hideki** [comment]
Hi @JoshElias,

1) Follow the instruction here:
http://developer.couchbase.com/mobile/develop/training/build-first-android-app/get-started-studio/index.html

2) `{latest-version}` should be replaced with `1.0.4`
`compile 'com.couchbase.lite:couchbase-lite-android:{latest-version}'`
=> `compile 'com.couchbase.lite:couchbase-lite-android:1.0.4'`

Please let us know if you have additional question
