### ISSUE TITLE
Document.addChangeListener(new Document.ChangeListener() {} not getting any changed callback after putProperties.

### ISSUE THREAD

**Issue by NitzDKoder** [couchbase/couchbase-lite-android#584]
Folks,
Wont i get any callback after i do putProperties to document.Local DB callback is suppressed? Do i get a callback after synced to server?

I am puzzled.Is it linked to Database.addChangeListener or something.

In general can i listen to single doc update and avoid Database.addChangeListener for a instance.?

Thanks
Nithin

**Comment by hideki** [comment]
Hi @NitzDKoder ,

You can obtain Document Change Event through Database.ChangeListener. http://developer.couchbase.com/mobile/develop/references/couchbase-lite/couchbase-lite/database/database/index.html#void-addchangelistenerchangedelegate-delegate
Database.ChangeEvent contains list of updated Document's ChangeEvent.

Hope this helps you.

**Comment by NitzDKoder** [comment]
Hi @hideki ,
Well i am able to get Database.changeListener event.But question is why am i not able to get Document.changeListner ?
http://developer.couchbase.com/mobile/develop/references/couchbase-lite/couchbase-lite/document/document/index.html#void-addchangelistenerchangedelegate-delegate

**Comment by hideki** [comment]
Hi @NitzDKoder ,
I wrote simple unit test from http://developer.couchbase.com/mobile/develop/guides/couchbase-lite/native-api/document/index.html#notifications . Document.addChangeListener() works as expected. Please confirm. Following is the unit test code that tests `Document.addChangeListener()` method.
https://github.com/couchbase/couchbase-lite-android/commit/4169c7f5c69c503a362a4711474b49583fc03c20
