### ISSUE TITLE
Attachment as URL/Absolute path and filtered only attachment pull.

### ISSUE THREAD

**Issue by NitzDKoder** [couchbase/couchbase-lite-android#594]
Hi Folks,

As per CB android LITE document http://developer.couchbase.com/mobile/develop/references/couchbase-lite/couchbase-lite/attachment/attachment/index.html
i  see the attchements contents get is only of byte[], cant we get the absolute path of the content store?
Does get metadata has info of it, i am yet to try the code.

In CBLIte sdk i see something done to iOS to get the absloute path.

How excatly attachments are stored, a example in reference docs will be more useful. Ex jpeg image is stored as /data/files/cb..../images/image1.jpeg?

Once text and attachment pushed as part of document, is there option to pull only text first and pull attachment separately later point of time at receiving end?

Thanks
Nithin

**Comment by hideki** [comment]
Hi @NitzDKoder,

It seems official documentation is out of date or not precise. For Android/Java, getContent() returns InputStream.

https://github.com/couchbase/couchbase-lite-java-core/blob/master/src/main/java/com/couchbase/lite/Attachment.java#L124

If you want to get path, you can use `public URL getContentURL()`. But this is not official API. And this API is only available with master branch. I believe 1.0.3 and 1.0.4 don't support this API.
https://github.com/couchbase/couchbase-lite-java-core/blob/master/src/main/java/com/couchbase/lite/Attachment.java#L142

To know actual data structure, you can use `Android Device Monitor` to check.
- Navigate to `/data/data/<classpath + appname>/files/`
- You can see the directory which name is same with your database name.

> Once text and attachment pushed as part of document, is there option to pull only text first and pull attachment separately later point of time at receiving end?

From sync_gateway? We don't support this

Thanks,
Hideki
