### ISSUE TITLE
Attachment loading

### ISSUE THREAD

**Issue by singlese** [couchbase/couchbase-lite-android#596]
Is it possible to exclude all attachments from the replication process and start an attachment download manually? We have problems with syncing large attachments and they should be synced only on demand. 
Thanks

**Comment by hideki** [comment]
Hi @singlese,

Couchbase Lite does not support the replication with excluding attachment.

For workaround, you might store the attachment somewhere else, then document just contains link to the attachment.

Thanks,

**Comment by sergio91pt** [comment]
Hi @singlese,
I researched this a few days ago, only for pulling. Didn't actually tried with couchbase lite, just curl and coucdb.

Assuming you first create the document and newer revs only add/remove attachments, then you could use a server side filter like this:

```json
{
   "_id": "_design/repl",
   "language": "javascript",
   "filters": {
       "no_attach": "function(doc, req) { return !doc._attachments }"
   }
}
```

Then you can reference the filter in CBL with `replication.setFilter("repl/no_attach");`.
This will only work if the database server has all revisions of the document (I'm not sure if CBL is replicating non-current revisions).

If you follow this path and start editing the doc without the attachments,  the document will have conflicts and you may need extra logic to handle them.
