### ISSUE TITLE
Merge Document Conflicts and notification/db change callback details(Offline Mode).

### ISSUE THREAD

**Issue by NitzDKoder** [couchbase/couchbase-lite-android#602]
Hi Folks,

http://developer.couchbase.com/mobile/develop/guides/couchbase-lite/native-api/document/index.html#Understanding Conflicts

When client is offline and their were changes made at client and server on a document, now both has same _rev.

After i come online i start  push and pull replication , later get database change callback.

Followed this documentation and tried to merge the conflicts and save as below after i get database change callback .

	private void mergeRevisonUpdated(DocumentChange change){
	
		
		boolean isConflict = change.isConflict();
		boolean isCurrentRev = change.isCurrentRevision(); // for checking addded revision and winning revision are identical
		if(isConflict){
			try{
				Document document = database.getDocument(change.getDocumentId());
				List <SavedRevision> revList = document.getConflictingRevisions();
			 //server revision is winning revision
					
					SavedRevision serverRevision = revList.get(0);
					SavedRevision clientRevision = revList.get(1);
					
					SavedRevision updatedRev = document.createRevision().save();
					
					
					final Map<String, Object> serverDocMap = serverRevision.getProperties();
					final Map<String, Object> clientDocMap = clientRevision.getProperties();
					.
					Map<String, Object> properties = updatedRev.getUserProperties();
					if(serverDocMap.get("doc_type").equals("item")){
						properties.put("channels", userChannel);
						properties.put("itemName", clientDocMap.get("itemName"));
						properties.put("id", serverDocMap.get("id"));
						properties.put("doc_type",  serverDocMap.get("doc_type"));
						properties.put("itemvalue", serverDocMap.get("value"));
						properties.put("_rev", serverDocMap.get("_rev"));
					}
					updatedRev.createRevision(properties);//Client - Server Merge.
					SavedRevision finalRev = updatedRev.createRevision().save(true);
					clientRevision.deleteDocument();//Once merge delete the loser.
				
			}catch(CouchbaseLiteException e){
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
	}

itemName i want client changed value , and itemvalue as server changed value.

Somehow i end up with wrong data also get too many database change callback on this document with conflict true.

When and where to make conflict management is not clearly mentions in the docs,a example will help me to proceed.

Thanks
Nithin

**Comment by jamiltz** [comment]
The conflict is likely to happen when a current or non current revision is pulled from the server. So you can check the `event.isExternal()` like so https://github.com/couchbaselabs/ToDoLite-Android/blob/master/ToDoLite/src/main/java/com/couchbase/todolite/TasksFragment.java#L336-L351

In ToDoLite, the conflicts are resolved by the user in the UI. Once a revision is picked, the user properties of the winning revision are saved on the current revisions and all others get deleted  https://github.com/couchbaselabs/ToDoLite-Android/blob/master/ToDoLite/src/main/java/com/couchbase/todolite/ListConflicts.java#L49-L91

**Comment by NitzDKoder** [comment]
@jamiltz Thanks for the links..

How about merge both client and sever and then delete pragmatically?

Basically in above example i want itemName client changed value , and itemvalue as server changed value.

IS this possible without user interaction?

**Comment by jamiltz** [comment]
Yes, create a new revision with the merged properties (from the server doc and client doc) and save it then delete all other non current revisions.
The code snippet above looks good.
You can get the current revision with `document.getCurrentRevision()`. If you are seeing unexpected behaviour in the resolution, could you provide a bit more detail about the issue (the rev numbers, user properties you would expect to see and the actual result).

**Comment by hideki** [comment]
Hi @NitzDKoder,
Does @jamiltz comment solve your problem? Please let us know!
Thanks!

**Comment by hideki** [comment]
I believe @jamiltz comment could solve this issue. So I will close this ticket. If this is still issue, please let us know.
