### ISSUE TITLE
Is it possible to cancel an async query?

### ISSUE THREAD

**Issue by condesales** [couchbase/couchbase-lite-android#608]
Is there any way of cancel an async run?
```java
mMyQuery.runAsync(new QueryCompleteListener() {
          @Override
          public void completed(QueryEnumerator rowsEnum, Throwable error) {
               //some-stuff
          }
});
```
and if i'm not anymore interest in the result, ask this query to cancel itself, calling something like:
```java
mMyQuery.cancel();
```
this pattern follows the AsyncTask class from Android

**Comment by hideki** [comment]
Hi @condesales,

`Query.runAsync()` returns [Future](http://docs.oracle.com/javase/7/docs/api/java/util/concurrent/Future.html). You can try to call `Future.cancel()`. I have never tried to cancel Query. Please share the test result if this works!

https://github.com/couchbase/couchbase-lite-java-core/blob/81d3662b10149725481555b570e3697124e0a202/src/main/java/com/couchbase/lite/Query.java#L414-L417
```
@InterfaceAudience.Public
public Future runAsync(final QueryCompleteListener onComplete) {
   return runAsyncInternal(onComplete);
}
```

I will close this ticket. If above solution does not work, please reopen the ticket.

Have a nice weekend!

**Comment by condesales** [comment]
That's exactly what I was looking for. Thanks @hideki
