### ISSUE TITLE
Incomplete document fetched?

### ISSUE THREAD

**Issue by ashwinbhaskar** [couchbase/couchbase-lite-android#619]
I am fetching a couchbase document using ```database.getDocument(document_id)``` And I am printing the document using ```document.getProperties().toString()```. But it prints incomplete document. The size of the document is 25 KB in the couchbase server. But in my mobile when I print, it prints content only upto 7 KB. 
Is this a couchbase lite issue or couchbase sync server issue? I couldn't find any documentation for this on the internet.

**Comment by hideki** [comment]
Hi @ashwinbhaskar, I believe `toString()` is truncated or `print method` truncate string because 25KB is too large. `Document.getProoperties()` return `Map<String,Object>`, so try to print each item one by one.

**Comment by ashwinbhaskar** [comment]
@hideki You are right. The android Logger has a limit of 4 KB. It truncates whatever it considers too long. I don't know how it even allowed 7KB. My bad here. This is NOT a Couchbase lite or couchbase server or Sync server issue. Can you close the issue or do you want me to close it?
