### ISSUE TITLE
Unauthorized replication not marked as stopped

### ISSUE THREAD

**Issue by feralex** [couchbase/couchbase-lite-android#623]
HI, i'm using cbl 1.1.0-527 to perform replications using basic authentication ( AuthenticatorFactory().createBasicAuthenticator(...) ), i have a changelistener attached to it but when the replication fails, due to being unauthorized, i only get an event with status=REPLICATION_ACTIVE and error!=null, shouldn't the replication send the event with the status REPLICATION_STOPPED in this case?

**Comment by hideki** [comment]
Hi @feralex,

As you wrote, the replicator should stop as soon as it encounters non-transient error.  However current implementation keeps trying to replicate all documents. This wrong behavior should be addressed.

Thanks!

**Comment by hideki** [comment]
I just transfer this ticket to couchbase-lite-java-core. 
https://github.com/couchbase/couchbase-lite-java-core/issues/646
