### ISSUE TITLE
Modify an existing document if it has not been synced.

### ISSUE THREAD

**Issue by anishcodes** [couchbase/couchbase-lite-android#626]
From what I have understood, to update a document you have to always create a new document (revision).

What if the user is doing a lot of changes in a short period of time (like tapping on single item on a single entry in say...GrocerySync app). This creates a lot of unnecessary entries on the server in a short period of time.

Is it possible to edit an existing document if it has not been synced to handle the case mentioned above?

Also, how can I control sync ops?

**Comment by jamiltz** [comment]
Hi @anishcodes, would it be possible to move this thread to the [forum](https://forums.couchbase.com/) or [mailing list](https://groups.google.com/forum/#!forum/mobile-couchbase). We'd love to answer it there, we try to keep github issues for tracking bugs and features. Thanks! :)

**Comment by anishcodes** [comment]
Thanks @jamiltz ... I have posted this question in the mailing list.
Closing this issue.
