### ISSUE TITLE
SetDescending not working with List<Object> query android

### ISSUE THREAD

**Issue by mikekaraa** [couchbase/couchbase-lite-android#627]
greetings, My listview is not descending by key order when I use List<Object> to query a couchdb. It works perfectly without the List<Object>. Here is my gist https://gist.github.com/mikekaraa/b8c29721de3077bd8630

Please help me out if you have a solution

**Comment by hideki** [comment]
currently we are discussing this issue at Forum. https://forums.couchbase.com/t/edit-new-issue-setdescending-not-working-with-list-object-query-android/4116

**Comment by hideki** [comment]
Hi @mikekaraa,
Does Forums help you to solve this question or issue? Please let us know. 
Thanks!
