### ISSUE TITLE
Documents missing after full sync thru SyncGateway

### ISSUE THREAD

**Issue by popy** [couchbase/couchbase-lite-android#628]
We've had a strange behaviour when testing sync process. I must warn that this problem seems to be related to another one on the SyncGateway side (see: https://github.com/couchbase/sync_gateway/issues/870). 

The context is a SyncGateway that doesn't deliver all documents that should be delivered on the _changes url, 2 documents are missing at the end of the result (9950 and 9951 on a total of 10000 docs that are all the same with different id for testing purpose) but following documents from 9952 to 10000 are returned (so, just a gap of 2 documents that should be here). The strange thing is that the sync process on android successfully pulls all docs before the two missing, and then seems to stop pulling documents after the missing ones and consider itself up to date. I was expecting to get all documents except the 2 missing in the _changes url result, but all documents after the missing ones are never synced.

I realize that fixing the problem on the SyncGateway side should fix the problem on android too, but I think there may be a bug because there is no reason for this behaviour. If the SyncGateway returns x documents, the client should get x documents, whether there a some missing or not in the result ... And morevover, the android client should not even be aware that 2 documents are missing if they are not returned by the SyncGateway.

Let me know if you want more details on the context of this bug.
Thanks

**Comment by hideki** [comment]
Hi @popy,
Thank  you for your report. From current information, it seems SG has problem with /_changes. Currently SG team is working for couchbase/sync_gateway#870. We should retest this after 870 will be fixed.

**Comment by popy** [comment]
Hi @hideki 

I commented on the related issue on the Sync Gateway project. After restarting the couchbase server (sync gateway was restarted multiple times but not couchbase server), the problem disappeared and we haven't been able to reproduce it since.
