### ISSUE TITLE
Provide a default Adapter

### ISSUE THREAD

**Issue by djensen47** [couchbase/couchbase-lite-android#630]
I was comparing Couchbase Lite with Realm and I almost chose Realm (but then realized it's not really a document store). However, it has a ton of niceties that are missing from CBL. For instance, a default adapter that I can use with ListViews.

https://realm.io/docs/java/latest/#adapter

**Comment by djensen47** [comment]
I see there is an implementation of an adapter in the ToDo app. Might be able to just port it over. Should I submit a pull request?

**Comment by hideki** [comment]
@djensen47 
Thank you for your offer. Please send us PR.
And, if you are not signed contributor license agreement, could you please sign it.

**Comment by djensen47** [comment]
I'd actually like to retract my request for this feature. I'm starting to be of the opinion that Android libraries need to do one thing and one thing very well. 

I still think there should be a library that implements this feature but it should be in it's own library. CBL-Views or something like that.

Reason to have a separate library handle this:
- If I don't want to use the adapter, it won't be there counting against my limited 65k methods on Android.
- I may want an alternative implementation, for instance by using RxJava

**Comment by hideki** [comment]
@djensen47, Thank you for your reply.

I will close this ticket.
