### ISSUE TITLE
Allow read/write using actual JSON instead of Map<String, Object>

### ISSUE THREAD

**Issue by djensen47** [couchbase/couchbase-lite-android#631]
If I'm pulling a JSON object from a third party API and all I want to do is store it in CBL, I shouldn't need to translate the JSON to a `Map<String, Object>`. Concordantly, if I'm pulling an object out of CBL that I just want to send over the wire as JSON, allow me to read the document as JSON.

**Comment by zgramana** [comment]
@djensen47 This will get addressed in our upcoming convenience API.

**Comment by djensen47** [comment]
Thanks, is there another issue tracking this?
