### ISSUE TITLE
Updating CBL with Model objects fails

### ISSUE THREAD

**Issue by koustuvsinha** [couchbase/couchbase-lite-android#632]
Hi, I am trying to perform CRUD operations in CBL with a custom pojo model. The insertion and retrieval works well as follows : 
```java
String KEY_HEADER = "couchHeader";
        Iterator it = modelList.iterator();
        int count = 0;
        Map<String,Object> record = new HashMap<>();
        while(it.hasNext()) {
            String KEY = KEY_HEADER + count;
            count++;
            DbTestRecordModel recordModel = (DbTestRecordModel)it.next();
            record.put(KEY,recordModel);
        }
        Document document = database.createDocument();
        try {
            document.putProperties(record);
            docId = document.getId();
        } catch (CouchbaseLiteException e) {
            Log.e(Constants.APP_NAME,e.getMessage());
        }
```
Now, whenever I am trying to update the data as this snippet : 
```java
Document retrieveDoc = database.getDocument(docId);
        Map<String ,Object> record = new HashMap<>();
        record.putAll(retrieveDoc.getProperties());
        Iterator<Map.Entry<String,Object>> it = record.entrySet().iterator();
        while(it.hasNext()) {
            Map.Entry<String,Object> rec = it.next();
            String key = rec.getKey();
            DbTestRecordModel recordModel = new DbTestRecordModel();
            recordModel.setAddress("na");
            recordModel.setName("na");
            recordModel.setAge(0);
            record.put(key,recordModel);
        }
        try {
            retrieveDoc.putProperties(record);
        }catch(CouchbaseLiteException e) {
            Log.e(Constants.APP_NAME,"Error in updating CouchBase");
        }
```
I am getting an error in the `retrieveDoc.putProperties(record)` line, stating 
```java
java.lang.ClassCastException: DbTestRecordModel cannot be cast to java.lang.String
```
which is absurd as I am specifically using put(String key,Object object) notation. Please help!

**Comment by hideki** [comment]
Hi @koustuvsinha,

Thank you for your report. Could you please provide us stack trace at ClassCastException was thrown.

Thanks!

**Comment by koustuvsinha** [comment]
```java
java.lang.ClassCastException: com.koustuvsinha.benchmarker.models.DbTestRecordModel cannot be cast to java.lang.String
            at com.couchbase.lite.Document.putProperties(Document.java:250)
            at com.koustuvsinha.benchmarker.databases.DbCouchHelper.updateData(DbCouchHelper.java:114)
            at com.koustuvsinha.benchmarker.services.DbTestRunnerService.testUpdate(DbTestRunnerService.java:106)
            at com.koustuvsinha.benchmarker.services.DbTestRunnerService.executeTest(DbTestRunnerService.java:213)
            at com.koustuvsinha.benchmarker.services.DbTestRunnerService.testRunner(DbTestRunnerService.java:170)
            at com.koustuvsinha.benchmarker.services.DbTestRunnerService.onHandleIntent(DbTestRunnerService.java:282)
            at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by hideki** [comment]
Hi @koustuvsinha,

https://github.com/couchbase/couchbase-lite-java-core/blob/release/1.1.0/src/main/java/com/couchbase/lite/Document.java#L250

`_rev ` is one of Couchbase Lite's reserved field. And its value should be String. 

See Special Properties
http://developer.couchbase.com/mobile/develop/guides/couchbase-lite/native-api/document/index.html#special-properies

In your code, these special properties should not be changed.

You can refer James's blog post about adding model layer for CBL Android.
http://jamiltz.github.io/simple-model-class-for-couchbase-lite-android/

Hope this helps you.

**Comment by koustuvsinha** [comment]
Thanks for the blog post. I think adding `@JsonIgnoreProperties(ignoreUnknown = true)` should resolve the issue as `_rev` was unwittingly modified. Will update in this thread once I implement it how it went. Thanks again :)

**Comment by koustuvsinha** [comment]
Issue resolved. Actually the problem was that, firstly I was iterating through **all** the keys, and setting each key with an updated value. Thus, the reserved keys `_rev` and `_id` were getting accidentally updated by the model value, hence the error. Thanks for the help!
