### ISSUE TITLE
perform livequery on a specific document couchbase android

### ISSUE THREAD

**Issue by mikekaraa** [couchbase/couchbase-lite-android#633]
Greetings everyone, I wanted to find out how to perform a livequery on a specific document in the couchbase cloud? Most examples perform queries on several documents, however I want to perform the livequery on one document here is my gist https://gist.github.com/mikekaraa/89416ea8b074c71d7153

thanks in an advance

**Comment by jamiltz** [comment]
Hi @mikekaraa.
There is [change listener api](http://developer.couchbase.com/mobile/develop/guides/couchbase-lite/native-api/document/index.html#notifications) on the Document object to get notified of changes to a document.

Please ask any "how-to" questions on the forum (forums.couchbase.com) and we'll be happy to answer there too :) We keep GitHub for tracking bugs and features.
Thanks
