### ISSUE TITLE
android Live query on documents not working 

### ISSUE THREAD

**Issue by mikekaraa** [couchbase/couchbase-lite-android#634]
greetings!
I am trying to get real time changes on a document using the changelistener, however i have to refresh tha mobile app to see the change. Here is my gist https://gist.github.com/mikekaraa/89416ea8b074c71d7153

Please help me out if you have a solution
NB: I have tried to post to https://forums.couchbase.com/ but it keeps telling me that i cannot post to that host

**Comment by hideki** [comment]
Hi @mikekaraa,

ChangeListner is called when document is updated (Revision is updated). You don't need to refresh the app.  See https://github.com/couchbase/couchbase-lite-java-core/blob/ffa885e0df8ce3827b1161af7896ce90c23d34e1/src/main/java/com/couchbase/lite/Database.java#L1961

About Replicator.Listener,  you might need to set before replicator.start().

If you have further questions, I recommend to post on https://forums.couchbase.com/c/mobile . You might get answer quickly.

Thanks,
