### ISSUE TITLE
Build problems w/ Cordova v4

### ISSUE THREAD

**Issue by floydf** [couchbase/couchbase-lite-android#636]
The following changes are required in order to successfully build Couchbase Lite with Cordova v4 for Android:

plugin.xml:

(see below in comment)

add new file src/android/build-extras.gradle
```
android {
     packagingOptions {
	  exclude 'META-INF/LICENSE';
	  exclude 'META-INF/NOTICE';	  
     }
}
```

**Comment by floydf** [comment]
hmmm, looks like xml doesn't work so well  in the web interface.

**Comment by hideki** [comment]
Hi @floydf Thank you very much for sharing information. We will review our PhoneGap/Cordova plugin package.

**Comment by hideki** [comment]
TodoLite-PhoneGap sample has updated README.
https://github.com/couchbaselabs/TodoLite-PhoneGap
