### ISSUE TITLE
Attachment filepath should not have %20 in it - for use with FileProviders

### ISSUE THREAD

**Issue by ryankennedyio** [couchbase/couchbase-lite-android#641]
Hi all,

First - unsure if this is locked-in behaviour of Couchbase or if it's configurable. 

*Problem:* Files are stored in `/data/data/com.example/files/database%20attachments/381914883BB47CDBF4E13A0F0085EE31D492F4B1.blob`.
*Fix:* I believe that `database%20attachments` should be `database-attachments` or otherwise.

*Why it's a problem:*
Ran into issues when trying to present my couchbase attachments to other applications (e.g. native gallery app cannot see them by default). This requires setting up a FileProvider, which isn't too hard.

Problem is that the FileProvider will return a content URI like:

`content://com.example.fileprovider/attachments/database%2520attachments/381914883BB47CDBF4E13A0F0085EE31D492F4B1.blob`

When in reality, it **should** return 

`content://com.example.fileprovider/attachments/database%20attachments/381914883BB47CDBF4E13A0F0085EE31D492F4B1.blob`

Note the %2520 and %20.

FileProvider will urlencode the filepath, so the only way around this is to rewrite the entire FileProvider and add an exception to leave out `&` for `Uri.encode()` in `FileProvider.getUriForFile()`.

Happy to do the dirty work and submit a PR if this is something for couchbase rather than a config issue.

**Comment by hideki** [comment]
Hi @ryankennedyio,
From v1.2.0, the path to the attachments will change to \<application file directory>/\<databasename + ".cblite2">/attachments/. As white-space is not valid character for database name, next version will not have the issue you reported.
Thanks!

**Comment by ryankennedyio** [comment]
Thanks @hideki, appreciate it.
