### ISSUE TITLE
Document do not have any information which says it is successfully synced with the Couchbase server DB

### ISSUE THREAD

**Issue by k10kumbhare** [couchbase/couchbase-lite-android#646]
Currently I am using a Couchbase Android Library to implement only the Push Replication. After the Push Replication is completed I want to see which Documents are synced successfully to the Couchbase Server DB. So that I can purge that Document IDs from the device. 
But Currently I do not get the exact document ID but instead I get only the Sync Count which is not sufficient to identify the synced Document. 

In the forum, I read that for IOS Platform there is an implementation for PendingDocuments(which is not synced) but not in Android. 

Is there any specific date for releasing this for Android Platform?

Thanks
Ketan Kumbhare

**Comment by hideki** [comment]
https://github.com/couchbase/couchbase-lite-java-core/issues/696

**Comment by zgramana** [comment]
Duplicate
