### ISSUE TITLE
problem with documents and populating listview

### ISSUE THREAD

**Issue by mikekaraa** [couchbase/couchbase-lite-android#650]
Greetings, I am a populating a listview with documents from couchdb in a descending order, but whenever a document is updated it immediately moves to the top of the listview and when a new document is included it is added below the old document instead of on top of it. What could be the problem.   Here is a code snippet of querying the view:

private void startLiveQuery() throws Exception {

            query = applicationz.getDatabase5().getView(String.format("%s/%s", designDocName, byDateViewName)).createQuery();
            query.setDescending(true);
            query.setLimit(30);

            liveQuery = query.toLiveQuery();
            liveQuery.setDescending(true);
            liveQuery.setLimit(30);
            liveQuery.addChangeListener(new LiveQuery.ChangeListener() {
                public void changed(final LiveQuery.ChangeEvent event) {

                    getActivity().runOnUiThread(new Runnable() {
                        public void run() {
                            grocerySyncArrayAdapter.clear();
                            for (Iterator<QueryRow> it = event.getRows(); it.hasNext(); ) {
                                grocerySyncArrayAdapter.add(it.next());
                            }
                            grocerySyncArrayAdapter.notifyDataSetChanged();
                        }
                    });
                }
            });
            liveQuery.start();
        
    }

**Comment by hideki** [comment]
Hi @mikekaraa,

About sort order: What is your map function? Sort order is based on key which is emitted from map function.
Why moved to top: When ever changeEven is fired,  code re-create data in Adapter. I believe it re-populate list view.

FYI: For question, I recommend to post on https://forums.couchbase.com/c/mobile. You might get answer quickly.

Thanks!
Hideki

**Comment by mikekaraa** [comment]
ok thanks for the reply @hideki, let me post the full question there.
