### ISSUE TITLE
Document Channel Removed Flag, Revision isGone()  isDeletion() Works?

### ISSUE THREAD

**Issue by NitzDKoder** [couchbase/couchbase-lite-android#652]
Hi Folks,

a) Have a document at the sever with two channels(A and B) assigned.
b) Document is shared between A and B now.
c)Channel A is removed by updating the the document.
d)Client  gets the A document updated revision 
e)Document A does not have property to check that the channel is removed.?

Is there a property to check if the channel is removed?

http://developer.couchbase.com/mobile/develop/guides/sync-gateway/channels/developing/index.html

    public boolean isGone() {
}
public boolean isDeletion() { 
}
https://github.com/couchbase/couchbase-lite-java-core/blob/a832e407d4f31f0a0601a1bc8a0e6a48c4fa688e/src/main/java/com/couchbase/lite/Revision.java

Does the above API's works? if so Pls highlight the usage?

Thanks
Nithin

**Comment by pasin** [comment]
Regarding the usage, iOS CBLDocument has -isGone() method that internally calls isGone method on the current revision. I don't know if Java already has that implemented on the CBLDocument or not.

**Comment by hideki** [comment]
Hi @NitzDKoder,

CBL Android has same implementation with iOS version. From code point of view, `isGone()` method should work as you expected. 

Note: For question, I recommend to post a question on https://forums.couchbase.com/c/mobile because Forum is observed by more people. You might receive response/answer quickly.

Thanks

**Comment by hideki** [comment]
Hi @NitzDKoder,
Do you have enough information about your question?

**Comment by hideki** [comment]
I hope our answer satisfied user's question. I will close this ticket.
