### ISSUE TITLE
Create a JSON doc with empty key value can cause replication hang up

### ISSUE THREAD

**Issue by atom992** [couchbase/couchbase-lite-android#657]
CBL version:1.1.0
Create a JSON by REST API like this:

curl -X PUT -H "Content-Type: application/json"  -d '{"key":"value","":"value2"}' 'http://127.0.0.1:59840/db/doc2'

return OK.

 It will cause replication hang up with sync gateway, see also sync gateway isssue 976:
https://github.com/couchbase/sync_gateway/issues/976

**Comment by hideki** [comment]
iOS ticket: https://github.com/couchbase/couchbase-lite-ios/issues/906

**Comment by hideki** [comment]
Based on conversation at iOS ticket, couchbase/couchbase-lite-ios#906, this issue looks like sync gateway issue. So I will close this. If this is client issue, please reopen.
