### ISSUE TITLE
Delete attachment return 404 by REST API

### ISSUE THREAD

**Issue by atom992** [couchbase/couchbase-lite-android#660]
I am using Couchbase-Lite-PhoneGap-Plugin on anroid (couchbase lite 1.1.0), when I delete a attachment by REST API, I got the following errors:
```
V/Listener( 1093): Credentials: 
V/Listener( 1093): Authorized via basic auth
E/Router  ( 1093): Router unable to route request to do_DELETE_Attachment
E/Router  ( 1093): java.lang.reflect.InvocationTargetException
E/Router  ( 1093): 	at java.lang.reflect.Method.invoke(Native Method)
E/Router  ( 1093): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/Router  ( 1093): 	at com.couchbase.lite.router.Router.start(Router.java:471)
E/Router  ( 1093): 	at com.couchbase.lite.listener.LiteServlet.service(LiteServlet.java:128)
E/Router  ( 1093): 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:802)
E/Router  ( 1093): 	at Acme.Serve.Serve$ServeConnection.runServlet(Serve.java:2251)
E/Router  ( 1093): 	at Acme.Serve.Serve$ServeConnection.parseRequest(Serve.java:2176)
E/Router  ( 1093): 	at Acme.Serve.Serve$ServeConnection.run(Serve.java:1988)
E/Router  ( 1093): 	at Acme.Utils$ThreadPool$PooledThread.run(Utils.java:1223)
E/Router  ( 1093): 	at java.lang.Thread.run(Thread.java:818)
E/Router  ( 1093): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.io.InputStream.read(byte[])' on a null object reference
E/Router  ( 1093): 	at com.couchbase.lite.util.StreamUtils.copyStream(StreamUtils.java:27)
E/Router  ( 1093): 	at com.couchbase.lite.router.Router.updateAttachment(Router.java:1831)
E/Router  ( 1093): 	at com.couchbase.lite.router.Router.do_DELETE_Attachment(Router.java:1857)
E/Router  ( 1093): 	… 10 more
```
@tleyden I am not sure it is the same issue:
https://github.com/couchbase/couchbase-lite-android/issues/152

**Comment by hideki** [comment]
Hi @atom992,

It seems dynamic binding between REST API and actual method is broken.

How did you call REST API to delete attachment? can you verify it?

http://developer.couchbase.com/documentation/mobile/1.1.0/develop/references/couchbase-lite/rest-api/document/delete---db---doc---attachment-/index.html

**Comment by atom992** [comment]
yes, I do call REST API to delete attachment. the log is teh android log  when I call REAT API.

**Comment by atom992** [comment]
any update?

**Comment by hideki** [comment]
sorry, this ticket is still in incoming.

**Comment by atom992** [comment]
any update?

**Comment by hideki** [comment]
Hi @atom992, Sorry, we don't have enough resource to fix all issues immediately.

**Comment by subbu-nama** [comment]
Hi,
   is this issue fixed and working fine?
I guess, me too also running with same problem, when I try to delete the attachment with below query
http://xxxxxx:xxxx/attachments/53982/sample.pdf?rev=22-6dfd29e7f2d0d9479958b4f441d6df8f
returns 405 method not allowed, can you please suggest me , your help would be highly appreciated and thanks for your time.

**Comment by hideki** [comment]
This ticket is still in backlog queue.

**Comment by hideki** [comment]
duplicated with https://github.com/couchbase/couchbase-lite-java-core/issues/191
