### ISSUE TITLE
purge the documents by filter

### ISSUE THREAD

**Issue by atom992** [couchbase/couchbase-lite-android#663]
From doc :
http://developer.couchbase.com/documentation/mobile/1.1.0/develop/references/couchbase-lite/rest-api/database/post-purge/index.html
the purge operation effect database, but some times user only want to purge the Specific document, such as message document.

**Comment by hideki** [comment]
If  you are using native library, you can use Document.purge() method.
http://developer.couchbase.com/documentation/mobile/1.1.0/develop/references/couchbase-lite/couchbase-lite/document/document/index.html#void-purge

For rest API, you can refer CouchDB doc, 10.3.11. /db/_purge
http://docs.couchdb.org/en/latest/api/database/misc.html
