### ISSUE TITLE
Money (BigDecimal) fields, whats is the best solution?

### ISSUE THREAD

**Issue by ricardolonga** [couchbase/couchbase-lite-android#680]
Hi,

I'm trying to work with monetary value persisting them as BigDecimal.
I'm realizing that the value is being saved as Double. I think it's the default serializer Jackson.
What do you think of allowing us to configure customized JsonSerializer and JsonDeserializer?
Or should I store the BigDecimal as a String?
Perhaps we could move on to the database direct one json as []byte or string...

Thanks a lot!

**Comment by hideki** [comment]
Sorry for we did not response for long time.

As you know, CBL relies on Jackson for JSON serialization.

I think you could set `WRITE_BIGDECIMAL_AS_PLAIN`.
http://fasterxml.github.io/jackson-databind/javadoc/2.2.0/com/fasterxml/jackson/databind/SerializationFeature.html#WRITE_BIGDECIMAL_AS_PLAIN

By setting to ObjectMapper.
https://fasterxml.github.io/jackson-databind/javadoc/2.0.0/com/fasterxml/jackson/databind/ObjectMapper.html#configure(com.fasterxml.jackson.databind.SerializationFeature, boolean)

Accessing ObjectMapper of Manager is not public API. But actually we defined the method with `public`. you could set `WRITE_BIGDECIMAL_AS_PLAIN` to ObjectMaper instance CBL uses.
https://github.com/couchbase/couchbase-lite-java-core/blob/master/src/main/java/com/couchbase/lite/Manager.java#L487-L490
