### ISSUE TITLE
include_docs in _change-feed when replicating from server

### ISSUE THREAD

**Issue by tinderangler** [couchbase/couchbase-lite-android#683]
I'm running Couchbase Lite via Phone Gap plugin on an Android device and Sync Gateway on my server. In CBL I set up an empty database and start listening to the _changes-feed (longpoll) with include_docs set. Then I set up replication to pull data from the server.

As soon as the replication pulls down the data the _changes-feed gives me a result including all the docs. That's fine but when I later add or modify a document on the server which gets repicated to CBL the feed doesn't include the doc anymore. Everything else is right, just the doc is always null.

Any ideas what could be the problem? Or is this a bug?

**Comment by hideki** [comment]
It could be bug in CBL Java. We needs to reproduce this.

**Comment by hideki** [comment]
Hi @tinderangler,
Could you please provide us detail steps to reproduce this issue?
Thanks a lot.
Hideki

**Comment by tinderangler** [comment]
Here are the steps. I'm on Android phonegap build using the REST API doing $http (from AngularJS) calls.

Create am empty local DB on phone:
<code>PUT http://23b87a67-90eb-4398-af51-0fa4ac3c0d63:71de0838-976b-4073-ac87-c083407582bf@localhost:5984/user_3</code>

Set up continuous bidirectional replication, user_3 has only access to his own channel user_3: 
<code>POST http://23b87a67-90eb-4398-af51-0fa4ac3c0d63:71de0838-976b-4073-ac87-c083407582bf@localhost:5984/_replicate {"source":"user_3","target":{"headers":{"Cookie":"SyncGatewaySession=abc"},"url":"http://192.168.178.52:4984/user_data"},"continuous":true}
POST http://23b87a67-90eb-4398-af51-0fa4ac3c0d63:71de0838-976b-4073-ac87-c083407582bf@localhost:5984/_replicate {"source":{"headers":{"Cookie":"SyncGatewaySession=abc"},"url":"http://192.168.178.52:4984/user_data"},"target":"user_3","continuous":true}</code>

Listen to the changes. This gives me all results from the pull replication. Here all docs are included as expected:
<code>GET http://23b87a67-90eb-4398-af51-0fa4ac3c0d63:71de0838-976b-4073-ac87-c083407582bf@localhost:5984/user_3/_changes?feed=longpoll&include_docs=true&since=3</code> 

Create a new longpoll waiting for changes:
<code>GET http://23b87a67-90eb-4398-af51-0fa4ac3c0d63:71de0838-976b-4073-ac87-c083407582bf@localhost:5984/user_3/_changes?feed=longpoll&include_docs=true&since=127</code>

Then on the server I add a test document to the DB via SyncGateway, which goes into channel 'user_3':
<code>PUT http://localhost:4985/user_data/5641deedaea73 {"creatorID":3,"docType":"testdoc","title":"test"}</code>

Replication now also pulls this doc and change listener resolves but this time "doc" is null.

Just let me know if you need anything else.

**Comment by hideki** [comment]
@tinderangler Thank you very much for detailed explanation.

**Comment by hideki** [comment]
Note to self

/_changes response for pulled document from Sync Gateway
```
curl -X GET "http://192.168.57.101:5984/db/_changes?feed=longpoll&include_docs=true&since=0"
{
  "results": [
    {
      "doc": null,
      "id": "766a54024bea9698013c44e847f4eb8c",
      "seq": 1,
      "changes": [
        {
          "rev": "1-bc2aefb99b9a90c6a7bcd276cd661215"
        }
      ]
    }
  ],
  "last_seq": 1
}
```

/_changes response for new document at local
```
curl -X GET "http://192.168.57.101:5984/db/_changes?feed=longpoll&include_docs=true&since=1"
{
  "results": [
    {
      "doc": {
        "Name": "tom",
        "_rev": "1-01c9a81d9d59fbe5e8a51c9d13d357c9",
        "type": "user",
        "_id": "2fe8750c-c757-4d4d-bbbf-845ca546100b"
      },
      "id": "2fe8750c-c757-4d4d-bbbf-845ca546100b",
      "seq": 2,
      "changes": [
        {
          "rev": "1-01c9a81d9d59fbe5e8a51c9d13d357c9"
        }
      ]
    }
  ],
  "last_seq": 2
}
```

**Comment by hideki** [comment]
In master branch, this issue was already addressed.
https://github.com/couchbase/couchbase-lite-java-core/blob/master/src/main/java/com/couchbase/lite/replicator/PullerInternal.java#L534-L535
We don't merge https://github.com/couchbase/couchbase-lite-java-core/tree/hotfix/1.1.0.2184 into master branch.

TODO: Verify if this issue is not reproducible with current master

**Comment by hideki** [comment]
Verified this issue is not reproducible with current master branch.
