### ISSUE TITLE
Compaction Time for Large Document Counts is Excessive

### ISSUE THREAD

**Issue by tikimcfee** [couchbase/couchbase-lite-android#687]
We have a new customer use case that not only increases the number of documents synchronized to and held on an offline mobile device, but which also generates a large number of image captures on device. Images are initially captured in a high-resolution format, synchronized as soon as possible, and then back-end processed to archive these images. Once processed, the attachments are removed in favor of a remote URL on the JSON document.

We need to perform a regular compaction to recover mobile storage associated with the deleted attachments. Unfortunately, Android compaction takes in excess of 3 minutes, compared to less than 20 seconds on iOS for the same operations. These long compaction times are a show-stopper for us, because the app is effectively locked without meaningful feedback. We would like to know how to minimize the impact of this process on our mobile clients. Ideally this would be a non-blocking operation that could be run in the background with some kind of progress feedback (even allowing operations to progress).

For more insight, two test devices (Nexus 4, CBLite v1.1.0, iPad 3, CBLite v1.0.1) replicated 16,000 documents with attachments ranging in size from 50kb to 2mb. A server side change was made to a single document’s attachments so the _attachments hash no longer contained a reference to a single attachment. Across 5 executions, the Nexus 4 took an average of 3 minutes and 20 seconds to finish compacting; the overall runtime time did not change between each execution. At completion, the attachment was successfully removed from disk, though an issue has been opened (GitHub #685) that details how client-side attachment compaction on Android seems to be nonfunctional. The iPad 3 finished this compaction process in an average of 15 seconds. It showed the same behavior of compact times remaining equal between executions.

As stated before, these compactions  need to be run frequently, and doing so is a best practice from [https://groups.google.com/d/msg/mobile-couchbase/OAAW8IABtaw/0DyobmddkmsJ]. Our application must remain responsive and on-demand for our customers, and we cannot ask that our customers sit through a three-minute wait, even a scheduled one, before they can continue use. How can we best move forward on improving this with the Android library?

**Comment by zgramana** [comment]
This should be resolved in 1.2, but we'll test for it.

**Comment by hideki** [comment]
Related: https://github.com/couchbase/couchbase-lite-java-core/issues/301

**Comment by hideki** [comment]
I will close this ticket as couchbase/couchbase-lite-java-core#301 is addressed.
