### ISSUE TITLE
ClassCastException: Properties converts Floats to Double

### ISSUE THREAD

**Issue by Ph1b** [couchbase/couchbase-lite-android#692]
I have the problem that when I add a float to a property map and retrieve it later from the database it's no longer a float but a double and thus I get a 

````
java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.Float
````

The Library should keep the types inserted and don't convert them.

**Comment by hideki** [comment]
Hi @Ph1b,
Couchbase Lite Android uses Jackson JSON parser internally. To put data, Map<String, Object> => JSON in Databae, And to get data, JSON => Map<String, Object>. When you retrieve data,  I recommend to cast to `Number`. Then call `Number.floatValue()`.

**Comment by Ph1b** [comment]
Yeah that solves it. Thanks!
