### ISSUE TITLE
Next build of master branch

### ISSUE THREAD

**Issue by kebouh** [couchbase/couchbase-lite-android#696]
Hey guys !

I was wondering when will be the next build ? I can see that you have modifications on the master branch but no build of it. The last one was in august. I need to use the getPendingDocumentIDs functionnality that i found here: https://github.com/couchbase/couchbase-lite-java-core/blob/master/src/main/java/com/couchbase/lite/replicator/Replication.java but could not find any build corresponding to this update.

Thanks,

**Comment by hideki** [comment]
@michaelkwok
Can you post build from master branch on  couchbase maven repo?

**Comment by zgramana** [comment]
@kebouh we're getting close to a release, so keep an eye out.
