### ISSUE TITLE
Metadata purge interval not work

### ISSUE THREAD

**Issue by sebastian989** [couchbase/couchbase-lite-android#700]
HI, I am trying to delete the tombstones or deleted documents, I am setting the Metadata purge interval with a value of 0.04 = 1H but notting ever happen and the tombs are always present and there are a lot of these now,

**Comment by hideki** [comment]
Hi @sebastian989, I wonder if Couchbase Lite supports Metadata purge interval??

**Comment by sebastian989** [comment]
I put this parameter in the sync gateway bucket because android client is syncing a lot of deleted documents and each time this take more time.

**Comment by hideki** [comment]
Hi @sebastian989,
 
It seems this is Sync Gateway issue. Could you please post this on Sync Gateway?
https://github.com/couchbase/sync_gateway/issues

Thanks!
