### ISSUE TITLE
manager.getDatabase(DB_NAME) returns null

### ISSUE THREAD

**Issue by niravbsoftweb** [couchbase/couchbase-lite-android#702]
![db_manager](https://cloud.githubusercontent.com/assets/14075594/11237573/cad7cae4-8e06-11e5-9573-81c0cb2dbcb5.png)

Hello,

I am using couchbase lite android v1.1.0

I stuck on blocker issue with retrieving database.

I used manager.getDatabase(DB_NAME) to retrieve instance of database, but it returns null.

Don't have specific steps to reproduce it, but getting issue multiple times.

Attached screen shot for manager from debug mode. It shows that it has database with DB_NAME, but while retrieving using getDatabase(DB_NAME) method, it retrieves null.

Help will be appreciated.

**Comment by niravbsoftweb** [comment]
With more investigation, i have tried using manager.getExistingDatabase(DB_NAME).

It provides database instance but "open=false".

Attached screenshot for ref.
![managerissue2](https://cloud.githubusercontent.com/assets/14075594/11238742/b637c452-8e0d-11e5-99f7-171a7d2019d5.png)

**Comment by hideki** [comment]
Duplicated with https://github.com/couchbase/couchbase-lite-java-core/issues/822

I will close this ticket.
