### ISSUE TITLE
Replication Change Listeners callback for errors 401 is called only for push replication

### ISSUE THREAD

**Issue by anisart** [couchbase/couchbase-lite-android#703]
Hi all,

I use couchbase-lite-android 1.1.0 via gradle and Sync Gateway/1.1.0(28;86f028c). Solution flom #540 works only for push replucation.

For example, I create user "foo" with password "bar" and login with this in ToDoLite sample app. I create new task in list. After sync I change user password via REST API and change task in Sync Gateway /_admin. I see many ```ChangeTracker: com.couchbase.lite.replicator.ChangeTracker@42b1659: Change tracker got error 401``` in logcat but unautorized callback is not called. It's called only if I make some changes in app.

**Comment by hideki** [comment]
related? https://github.com/couchbase/couchbase-lite-java-core/issues/723

**Comment by anisart** [comment]
@hideki yes

**Comment by hideki** [comment]
I will close this. Issue will be tracked with couchbase/couchbase-lite-java-core#723 .
