### ISSUE TITLE
_replicate REST Endpoint does not receive remote docs

### ISSUE THREAD

**Issue by jfspencer** [couchbase/couchbase-lite-android#708]
When attempting to perform a single replication from the sync gateway to cbl the following occurs. The same code functions normally in iOS.

using:
couch base-lite 1.1.0
cordova-android 4.1.1

- the _replicate request is made to and from the remote db
- both _replicate requests will stall for 30 seconds before returning a 200 response containing the sessionId **but not the "ok" key** as mentioned in the [ _replicate API doc](http://developer.couchbase.com/documentation/mobile/1.1.0/develop/references/couchbase-lite/rest-api/server/post-replicate/index.html)
- the local doc count never increases.

The highlighted code linked is how I am constructing the _replicate request
https://github.com/happieio/cordova-plugin-couchbase-lite/blob/master/APIs/typescript/cbl.ts#L274-L298

this is the general XHR function that the replicate functions call
https://github.com/happieio/cordova-plugin-couchbase-lite/blob/master/APIs/typescript/cbl.ts#L383-L404

any direction on troubleshooting or debugging suggestions would be very helpful.

**Comment by jamiltz** [comment]
FYI discussion taking place in the forum so far https://forums.couchbase.com/t/android--replicate-rest-endpoint-never-receives-docs-from-sgw/6010.

**Comment by hideki** [comment]
I will close this ticket. If CBL Android has issue, please reopen the ticket? Thanks!
