### ISSUE TITLE
query include deleted does not work

### ISSUE THREAD

**Issue by hex6ng** [couchbase/couchbase-lite-android#709]
calling query.setAllDocsMode(Query.AllDocsMode.INCLUDE_DELETED) and/or query.setIncludeDeleted(true) has no effect.

Returned documents do not include any deleted documents.

**Comment by hideki** [comment]
Hi @hex6ng,

Are you using v1.1.0?

**Comment by hex6ng** [comment]
@hideki 
Yes.  I have also tried 'com.couchbase.lite:couchbase-lite-android:1.1.0-2184'.  Same issue.

**Comment by hideki** [comment]
Hi @hex6ng, We will fix this as soon as possible.

**Comment by hideki** [comment]
From documentation, includeDeleted is only effective for all documents query. this is not effect for other type of queries
```
Gets or sets whether Queries created via the Database createAllDocumentsQuery method will include deleted Documents. This property has no effect in other types of Queries.
```
http://developer.couchbase.com/documentation/mobile/1.2/develop/references/couchbase-lite/couchbase-lite/query/query/index.html#boolean-includedeleted--get-set-
