### ISSUE TITLE
Continuous replication stops retrying when server not reachable

### ISSUE THREAD

**Issue by tinderangler** [couchbase/couchbase-lite-android#730]
In my App I've set up (PhonegGap plugin) one continuous push and one continuous pull replication. From the docs I understand that this is something like fire and forget so if there are any communication errors during the sync process the replication will retry later until everything is in sync again.

Monitoring the replications I found out the following:
* When the phone goes offline both replications go offline too until the connection comes back. Documents stored locally in the meanwhile are replicated as expected.
* When the phone isn't able to reach the server (bad mobile connection, server went offline, ...) the replications will retry to reach the server for a number of times but then stop retrying. If I store a document locally they will retry again for a number of times but then they stop again. When connection is back nothing happens until I save another doc locally. This gets replicated as expected but the one saved previously (when there was no connection) will never be replicated. This doc only gets synced if I restart the replication processes.
* If the server is not reachable when creating the replications they will retry for a number of times and then stop completely without retrying later again.

I'm not sure if this is on purpose or some kind of bug. At least for the last scenario I could check the state of the replications but personally I would prefer something more automatic for continuous replications.

Any suggestions?

**Comment by hideki** [comment]
Hi @tinderangler,

> When the phone isn't able to reach the server (bad mobile connection, server went offline, ...) the replications will retry to reach the server for a number of times but then stop retrying. If I store a document locally they will retry again for a number of times but then they stop again. When connection is back nothing happens until I save another doc locally. This gets replicated as expected but the one saved previously (when there was no connection) will never be replicated. This doc only gets synced if I restart the replication processes.

It seems there is bug in our replication. 

> If the server is not reachable when creating the replications they will retry for a number of times and then stop completely without retrying later again.

CBL considers this error as a permanent error. CBL stops replicator even though it is continuous mode. Please restart replicator.

**Comment by hideki** [comment]
I believe https://github.com/couchbase/couchbase-lite-java-core/commit/6699f0314047795b06c99a3448c75520ea050458 fixed this issue also.

This commits includes the fix of `Utils.isTransientError()` which prevented to retry the replication under network error.

I will close this ticket. If this issue is still reproducible, please let us know.
