### ISSUE TITLE
Multiple Keys on View

### ISSUE THREAD

**Issue by sivailango** [couchbase/couchbase-lite-android#740]
This is duplicate one from http://stackoverflow.com/questions/31288941/query-multiple-keys-in-couchbase-lite-view, I would like to filter the documents based on two key values. There is way to acheive this in Couchbase server through the Java SDK by using Complex Key. But i could not see anything like Complex key in Couhbase Lite Android.

`{
	"type": "card",
	"userId": "u100",
	"cardType": "debit"
}`

I want to filter the documents by userId and cardType

This is my view,
```
cardsByTypeView.setMap(new Mapper() {
    @Override
    public void map(Map<String, Object> document, Emitter emitter) {
        if (document.get("type").toString().equals("card")) {
        	List<Object> keys = new ArrayList<Object>();
        	keys.add(document.get("userId"));
        	keys.add(document.get("cardType"));
            emitter.emit(keys, document);
        }
    }
}, "1");

Query orderedQuery = cardsByTypeView.createQuery();
List<Object> keys = new ArrayList<Object>();
keys.add("u100");
keys.add("debit");
orderedQuery.setKeys(keys);
```

But it did not get result. Is there any examples to get it works? Should i use emit two time like 

```
cardsByTypeView.setMap(new Mapper() {
    @Override
    public void map(Map<String, Object> document, Emitter emitter) {
        if (document.get("type").toString().equals("card")) {
            emitter.emit(document.get("userId"), document);
            emitter.emit(document.get("cardType"), document);
        }
    }
}, "1");
```
Just i found this here https://gist.github.com/mikekaraa/b8c29721de3077bd8630

**Comment by hideki** [comment]
Hi @sivailango,

`setKeys(keys)` each key should match for each emit. 

Could you please try following codes? 
```
Query orderedQuery = cardsByTypeView.createQuery();
List<Object> keys = new ArrayList<Object>();
List<Object> key = new ArrayList<Object>();
key.add("u100");
key.add("debit");
keys.add(key);
orderedQuery.setKeys(keys);
```

Thanks!

**Comment by sivailango** [comment]
@hideki Great it works, it should be documented. Another question, Can i add startKey in it?

**Comment by hideki** [comment]
> Another question, Can i add startKey in it?

Yes, you can.

**Comment by sivailango** [comment]
Can you add a simple snippet? It would be great.

**Comment by hideki** [comment]
Hi @sivailango,
Can you find the `startKey` query example from following unit tests?
https://github.com/couchbase/couchbase-lite-android/blob/master/src/androidTest/java/com/couchbase/lite/ApiTest.java
https://github.com/couchbase/couchbase-lite-android/blob/master/src/androidTest/java/com/couchbase/lite/ViewsTest.java
Thanks!

**Comment by jcbanez** [comment]
Hi, I have as scenario below, words 1~3 are emitted

"word1": "apple", "word2": "orange", "word2": "grapes"

search term: orange;

I want my app to search each "word" for the term orange and return documents where one or more of the keys contain the search word, how do i go about implementing this on couchbase android?

thanks in advance
