### ISSUE TITLE
Document update not updated immediately ..while the changelistner say it is .

### ISSUE THREAD

**Issue by orenyodfat** [couchbase/couchbase-lite-android#742]
A delay of 100 ms between the change listener indication for the update and the query solve the issue.
Why?

**Comment by hideki** [comment]
Hi @orenyodfat,
Could you please provide detailed information?

**Comment by orenyodfat** [comment]
The scenario is as follow:
1.Add a change listener for a change in the DB.
2.Create a new doc : DOCID_A with field {"X","Y"}.
3.Update DOCID_A  with filed {"X","Z"}.
4.Get a change on the change listener 
5. immediately issue a query to get DOCID_A.
6 .Read the DOCID_A
In this case you will get DOCID_A with field {"X","Y"} as if it was not changed.
A delay of 100 ms between step 4 and 5 will solve the issue,
The issue found on Android using couchbase lite 1.1.0
Hope it is clear.

**Comment by hideki** [comment]
Hi @orenyodfat, 
Thank you for detailed info. We will look into the problem.

**Comment by hideki** [comment]
This issue is not reproducible with master branch (v1.2.1 + some fixes). I wrote uni test https://github.com/couchbase/couchbase-lite-android/commit/cc59fe1edb8d1618092f97e6137d7a2b61902e45, If this test is not valid test or this issue is still reproducible with latest release, please let us know.
