### ISSUE TITLE
./gradlew build upload pom files with incorrect groupId

### ISSUE THREAD

**Issue by andreibaranouski** [couchbase/couchbase-lite-android#744]
very similar to https://github.com/couchbase/couchbase-lite-java/issues/85 when we build couchbase-lite-android

for couchbase-lite-android I need to apply the following workaround 

https://github.com/couchbase/couchbase-lite-android/blob/master/release/upload_android_artifacts.sh#L11-L13

**Comment by hideki** [comment]
duplicated: https://github.com/couchbase/couchbase-lite-java/issues/85
