### ISSUE TITLE
Library for 1.2 is not updated on Maven. 

### ISSUE THREAD

**Issue by sethrosetter** [couchbase/couchbase-lite-android#767]
After specifying dependencies
```
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:22.+'
    compile 'de.hdodenhof:circleimageview:1.2.1'
    compile 'com.android.support:recyclerview-v7:22.0.+'
    compile 'com.google.android.gms:play-services:3.1.+'
    compile 'com.jakewharton:butterknife:6.0.0'
    compile 'com.facebook.android:facebook-android-sdk:4.1.0'

    compile 'com.couchbase.lite:couchbase-lite-android:1.2.0'
    compile 'com.couchbase.lite:couchbase-lite-android-forestdb:1.2.0'
}
```

Expected: Using d3b2164c53fb304802f80ec661a8ded4baa54efd
Actual: Inspecting User-Agent - CouchbaseLite/1.2 (Android 6.0/x86 1.2.0/a3e1945956bb96dc6bc24300f93cef4bac420fff)

It appears that the library on Maven is not latest RC but is pointing to one commit behind

**Comment by hideki** [comment]
Android Studio caches libraries under <USER HOME>/.gradle. 
Because we overwrote library with same version number on maven, we need to clean this cache. Otherwise, gradle does not download new one.
