### ISSUE TITLE
existsDocumentWithIDAndRev API at 1.2.0 removed?

### ISSUE THREAD

**Issue by orenyodfat** [couchbase/couchbase-lite-android#770]
It was exist on 1.1.0

**Comment by hideki** [comment]
Hi @orenyodfat,

`existsDocumentWithIDAndRev` was not public API, but for internal implmentation purpose, the method had public access modifier. http://developer.couchbase.com/documentation/mobile/1.1.0/develop/references/couchbase-lite/couchbase-lite/database/database/index.html

```java
/**
 * @exclude
 */
@InterfaceAudience.Private
public boolean existsDocumentWithIDAndRev(String docId, String revId) {
    return getDocumentWithIDAndRev(docId, revId, EnumSet.of(TDContentOptions.TDNoBody)) != null;
}
```

I recommend to use [Document Database.getExistingDocument(String docID)](http://developer.couchbase.com/documentation/mobile/1.1.0/develop/references/couchbase-lite/couchbase-lite/database/database/index.html) and  [SavedRevision  Document.getRevision(String revID)](
http://developer.couchbase.com/documentation/mobile/1.1.0/develop/references/couchbase-lite/couchbase-lite/document/document/index.html) to identify if specified revision exists.

Thanks,
Hideki

**Comment by orenyodfat** [comment]
Thanks!

**Comment by hideki** [comment]
I will close this ticket. If you have further question, please let us know.
