### ISSUE TITLE
Documents not syncing to local database

### ISSUE THREAD

**Issue by sivailango** [couchbase/couchbase-lite-android#771]
Take this scenario, I logged in as User "A" in my app and gets User "A" documents into my mobile database and it works well, then i logged out User "A" and logged in with User "B", now the document size is same as User "A", so i cleared the local data and try to login as User "B", now it works for User "B", then again tried to login as User "A", now my local database has only User "B" documents. I have pasted the SyncGateway code here,

```

public class SyncGateway implements Database.ChangeListener, Replication.ChangeListener {

    private static final String TAG = "SyncGateway";

    private static final String SYNC_URL = "http://127.0.0.1:4984/todo_sync";

    private Replication pullReplication;
    private Replication pushReplication;

    public void start(String username, String password) throws CouchbaseLiteException {

        Database db = Db.getDatabaseInstance();
        URL syncUrl;
        try {
            syncUrl = new URL(SYNC_URL);
        } catch (MalformedURLException e) {
            throw new RuntimeException(e);
        }

        pullReplication = db.createPullReplication(syncUrl);
        pullReplication.setContinuous(true);

        pushReplication = db.createPushReplication(syncUrl);
        pushReplication.setContinuous(true);

        Authenticator authenticator = AuthenticatorFactory.createBasicAuthenticator(username, password);

        pullReplication.setAuthenticator(authenticator);
        pushReplication.setAuthenticator(authenticator);

        pullReplication.start();
        pushReplication.start();

        pullReplication.addChangeListener(this);
        pushReplication.addChangeListener(this);

    }

    @Override
    public void changed(Replication.ChangeEvent event) {
        Replication replication = event.getSource();
        Log.d(TAG, "Replication : " + replication + " changed.");
        if (!replication.isRunning()) {
            String msg = String.format("Replicator %s not running", replication);
            Log.d(TAG, msg);
        } else {
            int processed = replication.getCompletedChangesCount();
            int total = replication.getChangesCount();
            String msg = String.format("Replicator processed %d / %d", processed, total);
        }

        if (event.getError() != null) {
            String msg = String.format("%s: %s", "Sync error", event.getError());
        }
    }

    @Override
    public void changed(Database.ChangeEvent event) {

    }

    public void stop() {
        pullReplication.stop();
        pushReplication.stop();
    }
}
```

Anyone can help me out to take this issue?

**Comment by hideki** [comment]
Hi @sivailango,

Do you create a database per user? Database name should be unique per user.

Thanks,
Hideki

**Comment by sivailango** [comment]
Should we create local database for every user?

**Comment by hideki** [comment]
Yes. Otherwise, all user using same database.
Or, you can store user information (ID) in each record to filer record by user. 

ToDoLite-Android is our sample app which supports Facebook authentication. This sample app crates database per user.
https://github.com/couchbaselabs/ToDoLite-Android/blob/master/ToDoLite/src/main/java/com/couchbase/todolite/Application.java#L356

**Comment by sivailango** [comment]
I am using Custom authentication, I added user ID in every document, the channels are working perfectly, I could see that the documents are routed through the channels. I could filter the documents by View. Is it the best practice to keep separate database for ever user?

**Comment by hideki** [comment]
I personally have more confidence for separated database approach as we tested well. Multi users in single database approach  is fine in general. I worry about following scenario:
1. Login User A at client, Logged out User A
2. Login User B at client
3. New document (DocA) is available for User A on server
4. New document (DocB) is available for User B on server
5. Client receives document (DodB) for User B because of currently logged in User B.
6. Logged out User B
7. Logged in User A.
8. Pull replicator might miss document (DocA) for User A on Server because DocA is created before DocB.

> Take this scenario, I logged in as User "A" in my app and gets User "A" documents into my mobile database and it works well, then i logged out User "A" and logged in with User "B", now the document size is same as User "A", so i cleared the local data and try to login as User "B", now it works for User "B", then again tried to login as User "A", now my local database has only User "B" documents. I have pasted the SyncGateway code here,

` i cleared the local data` I don't know how you cleared local data. If you deleted documents, they are tread ad deleted document. So User A can not see any more  after logged in second time.

**Comment by sivailango** [comment]
I cleared the My app data from Settings. I will try your way, but I tested with existing documents without creating new documents in Server, what my concern is,  why User B could not get their document?

**Comment by hideki** [comment]
>  why User B could not get their document?

I thought User A can not get  User A documents?

Could you please provide exact steps that you did? we might able to identify the problem.

**Comment by sivailango** [comment]
Let's say,  User A has 20 documents, User B has 10 documents and User C has 5 documents. I installed the app and tried to login as User A and check the total documents count by get all documents,  now I could see the count is 20 of User A. Then I logged out User A,  and login with User B,  still the document count is 20 of User A documents, it should be, 30 (User A 20 + User B 10) right?

**Comment by sivailango** [comment]
If I reinstall the app again and login with User B at first moment, now the local database has 10 documents of User B, Again I logged out User B and logged in with User A,  still the document size is 10, local database has only first logged in user documents.

**Comment by hideki** [comment]
> Let's say, User A has 20 documents, User B has 10 documents and User C has 5 documents. I installed the app and tried to login as User A and check the total documents count by get all documents, now I could see the count is 20 of User A. Then I logged out User A, and login with User B, still the document count is 20 of User A documents, it should be, 30 (User A 20 + User B 10) right?

Total document should be 30. But If you filtered query by logged in user id, it should be 10. This result depends on your implementation.

**Comment by hideki** [comment]
From current information, I am not sure if replication has issue.

Could you please check how many documents are replicated after logging in with second user by add ChangeEventListener for replicator? Also you can retrieve raw SQLite database from Android. Can you look into how many docs are in raw database?

**Comment by sivailango** [comment]
Yes, But the problem total document count is still 20 even I logged in as User B after User A, so it does pull only first log in I think.

**Comment by hideki** [comment]
> so it does pull only first log in I think.

After logging in with second user, is pull replicator running?

**Comment by sivailango** [comment]
Hi @hideki 

```
// private static final String SYNC_URL = "http://127.0.0.1:4984/todo_sync";

    private Replication pullReplication;
    private Replication pushReplication;

    public void start(String username, String password) throws CouchbaseLiteException {

        Database db = Db.getDatabaseInstance();
        URL syncUrl;
        try {
           syncUrl = new URL("http://" + username + ":" + password + "@127.0.0.1:4984/todo_sync");
        } catch (MalformedURLException e) {
            throw new RuntimeException(e);
        }

        pullReplication = db.createPullReplication(syncUrl);
        pullReplication.setContinuous(true);

        pushReplication = db.createPushReplication(syncUrl);
        pushReplication.setContinuous(true);

       // Authenticator authenticator = AuthenticatorFactory.createBasicAuthenticator(username, password);

      //  pullReplication.setAuthenticator(authenticator);
     //   pushReplication.setAuthenticator(authenticator);

        pullReplication.start();
        pushReplication.start();

        pullReplication.addChangeListener(this);
        pushReplication.addChangeListener(this);

    }

```

Just i embed the username and password in URL instead of setting it on Authenticator, now it works

**Comment by sivailango** [comment]
But still i could not understand that why Authenticator not working, should i reset the Authenticator for every logout, is it Singleton?

**Comment by hideki** [comment]
@sivailango, I guess there is bug in `setAuthenticator()` method.

**Comment by sivailango** [comment]
@hideki Bug in my code?

**Comment by hideki** [comment]
Bug in CBL codes.

**Comment by sivailango** [comment]
Hope you guys will fix this one
