### ISSUE TITLE
FATAL EXCEPTION  on 1.2.0 -Android.

### ISSUE THREAD

**Issue by orenyodfat** [couchbase/couchbase-lite-android#773]
Crash seen on 1.2.0 
Not seen on 1.1.0

It might related to some timing issue.

02-03 16:23:23.344 28567-28790/com.sparkup.device E/AndroidRuntime: FATAL EXCEPTION: ChangeTracker-http://52.11.107.126:4984/db/
02-03 16:23:23.344 28567-28790/com.sparkup.device E/AndroidRuntime: Process: com.sparkup.device, PID: 28567
02-03 16:23:23.344 28567-28790/com.sparkup.device E/AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'com.couchbase.lite.Manager com.couchbase.lite.Database.getManager()' on a null object reference
02-03 16:23:23.344 28567-28790/com.sparkup.device E/AndroidRuntime:     at com.couchbase.lite.replicator.PullerInternal.getUserAgent(PullerInternal.java:1122)
02-03 16:23:23.344 28567-28790/com.sparkup.device E/AndroidRuntime:     at com.couchbase.lite.replicator.ChangeTracker.runLoop(ChangeTracker.java:265)
02-03 16:23:23.344 28567-28790/com.sparkup.device E/AndroidRuntime:     at com.couchbase.lite.replicator.ChangeTracker.run(ChangeTracker.java:228)
02-03 16:23:23.344 28567-28790/com.sparkup.device E/AndroidRuntime:     at java.lang.Thread.run(Thread.java:818)

**Comment by hideki** [comment]
Hi @orenyodfat,
Thank you very much for your bug report. Exception occurs from pull replication. 
Can you explain what scenario causes NullPointerException?
Thank you,
Hideki

**Comment by orenyodfat** [comment]
Not sure .
Might be register to change listener and write a doc to db .

Might be timing related ... cannot reproduce while step by step debugging .

It is strange that it come from pull replication because wifi is off .

**Comment by hideki** [comment]
@orenyodfat , thank you for additional information.

**Comment by hideki** [comment]
Note to self:

What causes NPE:
- This NPE is caused if  ReplicationInternal.db variable is null but ChangeTracker is still running. 

Why enter above state:
- When the Replicator enters STOPPING state,  the replicator also tries to stop ChangeTracker. This does not guarantee ChangeTracker stops immediately.
- When the Replicator enters STOPPED state,  replicator set `db=null` in `clearDbRef()` method.
- As ChangeTracker is still running, hits NPE. 

https://github.com/couchbase/couchbase-lite-java-core/blob/01512ad4c1f6500db09e53857f5fea232bf860ee/src/main/java/com/couchbase/lite/replicator/ReplicationInternal.java#L1291

Solution:
- make sure if ChangeTracker is stopped before calling `clearDbRef()` method
- Add check if db is null to avoid NPE in Replicator.

**Comment by hideki** [comment]
Hi @orenyodfat,
Did your device become offline/online during you were testing?
Thanks,
Hideki

**Comment by orenyodfat** [comment]
How come the same code runs in  good in 1.1.0?

**Comment by hideki** [comment]
For 1.2.0, we updated way to generate UserAgent value. That causes NPE under special condition. The special condition means pull replicator state is STOPPED, but ChangeTracker is still running.

v1.1.0 or earlier version entered this special condition. But it did not cause side-affect problems like NPE.

I will keep investigating what causes this special condition.

Thank you very much for reporting this!

**Comment by orenyodfat** [comment]
Is there a solution released yet?

**Comment by hideki** [comment]
Hi @orenyodfat,

You can try the build from master branch. http://files.couchbase.com/maven2/com/couchbase/lite/couchbase-lite-android/0.0.0-600/.
It is not official release.

Thanks!

**Comment by orenyodfat** [comment]
Thanks.
When it will be officially released ?

**Comment by hideki** [comment]
Hi @orenyodfat,

If this is issue is categorized as hotfix, this fix could be in 1.2.1 that should be release in few weeks.

Thanks,
Hideki
