### ISSUE TITLE
[1.2.0] the value of version is "1.2.0-null"

### ISSUE THREAD

**Issue by atom992** [couchbase/couchbase-lite-android#775]
When I update couchabse-lite-android, and I access the REST API:
```
curl http://127.0.0.1:5984/
```
 I got the following response:
```
{"couchdb":"Welcome","CBLite":"Welcome","version":"1.2.0-**null**"}
```

why there is a null in the value of version?
Shouldn't it is a build ID instead of null, like the same REST API for MAC OX Version:
```
{"vendor":{"name":"Couchbase Lite (Objective-C)","version":"1.2.0 (build 112)"},"couchdb":"Welcome","CouchbaseLite":"Welcome","version":"1.2.0 (build 112)"}
```

So we can refer to the correct source?

**Comment by hideki** [comment]
This is reproducible with release version of 1.2.0
```
$ curl -f http://192.168.57.101:5984
{"couchdb":"Welcome","CBLite":"Welcome","version":"1.2.0-null"}
```
