### ISSUE TITLE
[docs] show diff info between old version and last version

### ISSUE THREAD

**Issue by atom992** [couchbase/couchbase-lite-android#778]
From [develop portal](http://developer.couchbase.com/documentation/mobile/1.2/develop/references/couchbase-lite/index.html) the docs has been updated to the last version.
 but I want to know that which part changed between old version and new version.
so I can check my app to ensure that which part of my app should be changed.

**Comment by hideki** [comment]
CBL does not provide `diff` feature. You could compare contents between current revision and previous revision.

**Comment by atom992** [comment]
I mean show the different part of docs (such as between 1.1.0 and 1.2.0).

**Comment by hideki** [comment]
We have Release note: https://github.com/couchbase/couchbase-lite-java-core/releases . I hope this helps you.

**Comment by hideki** [comment]
I will close this.
