### ISSUE TITLE
[enhancement] CUD attachments for a local document

### ISSUE THREAD

**Issue by atom992** [couchbase/couchbase-lite-android#779]
May be we can add a feature(native method and rest api) about attachments for a local document, so we can store some tmp file/no replicated attachments on couchbase-lite.

**Comment by zgramana** [comment]
You can just use regular documents with a push filter to achieve this today.

**Comment by atom992** [comment]
I don't understand. can you give me a example?

**Comment by hideki** [comment]
@atom992,
You can use Replication filter to meet your requirement
http://developer.couchbase.com/documentation/mobile/1.2/develop/guides/couchbase-lite/native-api/replication/index.html#filters
Thanks!
