### ISSUE TITLE
Pull Replication crashes Android client

### ISSUE THREAD

**Issue by househippo** [couchbase/couchbase-lite-android#782]
I'm having a new problem with my Android CBLite test app.
Somehow I got the client into a state where pull replication crashes the app.
On my Google drive I uploaded:

1. PullReplCrash.txt - this is a log of the crash. You'll see something like "JNI Error .... local reference table overflow"
2. prof2.cblite2 - this is the folder where the ForestDB lives, in case that helps you to debug this.

I'm using 
1.2 CB lite Android
1.2 Gateway on CentOS
4.1 CB Server on CentOS

[PullReplCrash.txt](https://github.com/couchbase/couchbase-lite-android/files/122637/PullReplCrash.txt)

**Comment by hideki** [comment]
https://gist.github.com/hideki/e6d62f0033c87d0e3b48

**Comment by hideki** [comment]
Code causes crash
```C++
jstring toJString(JNIEnv *env, C4Slice s) {
    if (s.buf == NULL)
        return NULL;
    std::string utf8Buf((char*)s.buf, s.size);
    // NOTE: This return value will be taken care by JVM. So not necessary to free by our self
    return env->NewStringUTF(utf8Buf.c_str());
}
```
https://github.com/couchbaselabs/cbforest/blob/0d6f8b8d7ac15bd169426e8851dd9dd64b92a254/Java/jni/native_glue.cc#L113

Potential cause:
It seems cbforest creates too many reference objects. It might requires manual delete reference by DeleteLocalRef
http://stackoverflow.com/questions/20917777/jni-error-local-reference-table-overflow-512-entries
http://stackoverflow.com/questions/11109497/android-jni-error-app-bug-local-reference-table-overflow-max-512
http://stackoverflow.com/questions/9372373/referencetable-overflow-max-512-jni

**Comment by hideki** [comment]
Hi @househippo ,
Is this crash always reproducible? or intermittently occurs?
Thanks,

**Comment by rainerg2000** [comment]
I'm the original submitter. I have an AVM that reliably reproduces the error every time my app starts a pull replication. I am not sure if my sync-gateway setup is required to reproduce it, but I can share the AVM and the backend database if that would help you figure out the issue.

**Comment by hideki** [comment]
Hi @rainerg2000,

I am sorry for late reply. To verify this bug, it could be huge help for us if you can share backend database (URL to sync gateway or CouchDB) and sample client code.

P.S.
Is AVM a abbreviation of  Android Virtual Machine?

Regards,
Hideki

**Comment by hideki** [comment]
Note to self:


##### Local and Global References
> Programmers are required to "not excessively allocate" local references. In practical terms this means that if you're creating large numbers of local references, perhaps while running through an array of objects, you should free them manually with DeleteLocalRef instead of letting JNI do it for you. The implementation is only required to reserve slots for 16 local references, so if you need more than that you should either delete as you go or use EnsureLocalCapacity/PushLocalFrame to reserve more.

http://developer.android.com/training/articles/perf-jni.html#local_and_global_references

**Comment by hideki** [comment]
Hi @rainerg2000,

From log message, crash occurs when calling [`Java_com_couchbase_cbforest_Document_insertRevisionWithHistory `](https://gist.github.com/hideki/e6d62f0033c87d0e3b48#file-gistfile1-txt-L85).

Do some documents have more than 512 revision history?

512 comes from JNI reference table size from log message. It is not necessary to be 512.

Regards,
Hideki

**Comment by hideki** [comment]
This issue is reproducible with calling `insertRevisionWithHistory()` with more than 512 revision history.
```
    public void testInsertRevisionWith512History() throws ForestException {
        String kBody2 = "{\"ok\":\"go\"}";
        createRev(kDocID, kRevID, kBody.getBytes());
        createRev(kDocID, kRev2ID, kBody2.getBytes());

        // Reload the doc:
        Document doc = db.getDocument(kDocID, true);

        // Add 18 revisions; the last two entries in the history repeat the two existing revs:
        Random r = new Random();
        int kHistoryCount = 512;
        List<String> revIDs = new ArrayList<String>();
        for(int i = kHistoryCount - 1; i >= 2; i--){
            String revID = String.format("%d-%08x", i + 1, r.nextInt());
            revIDs.add(revID);
        }
        revIDs.add(kRev2ID);
        revIDs.add(kRevID);

        int n;
        {
            boolean commit = false;
            db.beginTransaction();
            try {
                n = doc.insertRevisionWithHistory("{\"foo\":true}".getBytes(),
                        false, false,
                        revIDs.toArray(new String[revIDs.size()]));
                commit = true;
            } finally {
                db.endTransaction(commit);
            }
        }
        assertEquals(kHistoryCount - 2, n);
    }
```

**Comment by hideki** [comment]
log message from above test codes
https://gist.github.com/hideki/076b3068af3043647e08

**Comment by rainerg2000** [comment]
Hi @hideki, sorry for the late reply. 
It is very possible that my application has created a revision history of > 512 entries. 
I cannot make my sync_gateway publicly available, but I can send the data folder from the CB Server. I can also send you the virtual Android device (AVM) that reproduces the crash. It seems that in the meantime you have developed a solution, and I assume that you don't need the files from me anymore. I could try to verify your fix using my test app when you have an release candidate. Let me know if you still want me to share the data files.
Rainer.

**Comment by hideki** [comment]
Hi @rainerg2000,
We could solve this issue soon. Once we finished to fix this, we will create the build from master branch, and deploy it on our custom maven repo. As I will notify you here, please test it?
Thank you very much for all your helps.
Hideki

**Comment by hideki** [comment]
This issue is fixed by PR https://github.com/couchbaselabs/cbforest/pull/64

**Comment by hideki** [comment]
Hi @rainerg2000,

Build from master branch that includes fix for this issue is ready on couchbase custom maven repo.
http://files.couchbase.com/maven2/com/couchbase/lite/couchbase-lite-android/0.0.0-583/
Please refer https://github.com/couchbase/couchbase-lite-android#using-latest-official-release for how to use couchbase maven repo.

If you are using zip file one, you can download from following link.
http://latestbuilds.hq.couchbase.com/couchbase-lite-android/0.0.0/0.0.0-583/

Could you please try this?

Thanks!
Hideki

**Comment by rainerg2000** [comment]
@hideki 
I confirmed that build 0.0.0-583 fixes this issue.
Thank you for the quick turnaround.
Rainer.

**Comment by hideki** [comment]
Hi @rainerg2000,
Thank you for confirming the fix.

**Comment by sam0829** [comment]
@hideki I am facing similar Issue in couchbase-lite-android:1.2.1
[crash.txt](https://github.com/couchbase/couchbase-lite-android/files/414676/crash.txt)

also I am using couchbase-lite-android-forestdb:1.2.0 if this helps
