### ISSUE TITLE
Upgrading from 1.1.0 to 1.2.0 - ClassCastException

### ISSUE THREAD

**Issue by condesales** [couchbase/couchbase-lite-android#783]
After upgrading from 1.1.0 to 1.2.0, saving nested objects throws a ClassCastException

```java
java.lang.ClassCastException: java.util.ArrayList cannot be cast to java.lang.String
   at com.couchbase.lite.store.SQLiteStore.add(SQLiteStore.java:1448)
   at com.couchbase.lite.Database.put(Database.java:1748)
   at com.couchbase.lite.Database.putRevision(Database.java:1701)
   at com.couchbase.lite.Database.putRevision(Database.java:1692)
   at com.couchbase.lite.Document.putProperties(Document.java:428)
   at com.couchbase.lite.Document.putProperties(Document.java:260)
```

By nested objects read `HashMap<String, Object>` where Objects can be another `HashMap<String, Object>`

**Comment by hideki** [comment]
Hi @condesales,

https://github.com/couchbase/couchbase-lite-java-core/blob/release/1.2.0/src/main/java/com/couchbase/lite/store/SQLiteStore.java#L1448

Could you please provide sample `Map<String, Object>`object you store by `Document.putProperties(Map<String, Object>)`? `type` key name for document could cause the problem.

Thanks!
Hideki

**Comment by condesales** [comment]
You are absolutely right.
```
{
    dob=1/1/1990, 
    last_name=Sales, 
    phone=+44XXXXXXXXXXX, 
    email=xxxxxxxxxxx@gmail.com, 
    objectType=User, 
    allow_marketing=true, 
    event_ids=[], 
    claimed_event_ids=[], 
    type=[social:facebook, auth:phone], 
    first_name=Felipe
}
```

Shouldn't Couchbase use prefixed fields to avoid clashing with apps' models?

**Comment by snej** [comment]
We use `type` precisely because there's a convention of apps using it.
The bug here is that our code should be preflighting the value and ignoring it if it's not a string. It's only using the `type` value as an optional optimization for view indexing.

**Comment by condesales** [comment]
@snej :+1: 
That's exactly what I've done in my app to fix the issue.

Thanks for you time guys.
