### ISSUE TITLE
viewer for cblite2 file that is generated by couch base lite 1.2?

### ISSUE THREAD

**Issue by cuipengfei** [couchbase/couchbase-lite-android#789]
i used the demo grocery app, it generates a cblite2 file
i tried to use the CouchbaseLiteViewer to open it, but it reports: 

> The document “grocery-sync.cblite2” could not be opened. This database is too new to be opened by this app. Use a Viewer that supports Couchbase Lite 1.2.

is there a newer viewer that could view the content of the cblite2 file?

thanks

**Comment by hideki** [comment]
Please compile viewer from https://github.com/couchbaselabs/CouchbaseLiteViewer wit using CBL iOS/OSX v1.2
