### ISSUE TITLE
Query not filtering view properly, CB 1.2.0

### ISSUE THREAD

**Issue by vbenso** [couchbase/couchbase-lite-android#795]
After upgrading to 1.2.0, I've noticed that some queries where showing an extra row that wasn't there before. 
For instance, 
```
liveQueryAmostragens = viewAmostragens.createQuery().toLiveQuery();
liveQueryAmostragens.setDescending(true);
liveQueryAmostragens.setStartKey(Arrays.asList(mTalhaoId, new HashMap<String, Object>()));
liveQueryAmostragens.setEndKey(Arrays.asList(mTalhaoId, null));
```
when mTalhaoId is c41f3748b88ba118cf57daa253bc1f48,
the query gives me the following rows:

![image](https://cloud.githubusercontent.com/assets/8295627/13372971/551ae908-dd39-11e5-8a19-31d76ca17165.png)

Notice how row[0]'s key doesn't belong there.

Just another observation that can be helpful, 
after setting inclusiveStart to false, the "intruder" row[0] is not in the results, however, the element that should be in row[1] is also missing. 
Row's size should be 24. Not 25 from the previous case neither 23 as the following:
![image](https://cloud.githubusercontent.com/assets/8295627/13373080/138fa8fe-dd3c-11e5-8504-74faadeb0e81.png)

I've managed to get the correct results inverting the sorting order and start/end keys, 
![image](https://cloud.githubusercontent.com/assets/8295627/13373141/b991c4c0-dd3d-11e5-9ac1-a4b04b300029.png)

unfortunately that doesn't work for my application.
Is there another workaround, is a predicate a good idea?

**Comment by vbenso** [comment]
Just another observation that can be helpful, 
after setting inclusiveStart to false, the intruder row[0] is not in the results, however, the element that should be in row[1] is also missing. 
Row's size should be 24. Not 25 from the previous case neither 23 as the following:
![image](https://cloud.githubusercontent.com/assets/8295627/13373080/138fa8fe-dd3c-11e5-8504-74faadeb0e81.png)

This bug happens while using forestDB, I'll run further tests using sqLite engine and see if anything changes.

**Comment by hideki** [comment]
Hi @vbenso,

I wrote unit test, but I could  not reproduce the problem? Can you review unit test if it covers your scenario?
UnitTest: https://github.com/couchbase/couchbase-lite-android/blob/feature/issue_and795_compoundKeys_Descending/src/androidTest/java/com/couchbase/lite/ViewsTest.java#L3297-L3367. 

Also, can you share your map function, data structure, and some sample data if possible?

Thanks!

**Comment by vbenso** [comment]
Hi @hideki, 
this is my map function:
```
boolean b = viewAmostragens.setMap(new Mapper() {
                    @Override
                    public void map(Map<String, Object> document, Emitter emitter) {
                        if (document.get("type") != null) {
                            String type = document.get("type").toString();
                            if ("amostragem".equals(type)) {
                                Object odate_time = document.get("date_time");
                                Date date = dateUtils.getDateFromObject(odate_time);
                                int fase_order = dbUtils.getNumericFase(String.valueOf(document.get("cultura")), String.valueOf(document.get("fase")));
                                emitter.emit(Arrays.asList(document.get("contorno_id"), date.getYear() + 1900, date.getMonth(), date.getDate(), document.get("cultura"), fase_order, document.get("fase"), odate_time.toString()), document.get("amostragens"));
                            }
                        }
                    }
                }, "7.1");
```
The data goes attached as test_data.json.zip
[test_data.json.zip](https://github.com/couchbase/couchbase-lite-android/files/167062/test_data.json.zip)
In case you need my complete database, just ask for it and I'll provide a download link(is 130MB) didn't sound like a good idea to attach it here.

Just as a side question, I'm trying without luck to import the CBLite from source into my App's project in order to run tests and perhaps some further debugging in the issue. 
Does exist a guide for this procedure? (besides https://github.com/couchbase/couchbase-lite-android/READ.me)

BTW: 
I've managed to circumvent the issue by means of a predicate.

**Comment by hideki** [comment]
Hi @vbenso,

Sorry for I could not look into this issue for a while. And Thank you very much for test data and code snippet of map function.

I wrote new Unit test using test data and map function you provided. But I still can not reproduce the issue. Could you please look into the test I wrote? Is this issue still reproducible with your environment with using latest master branch build?
https://github.com/couchbase/couchbase-lite-android/blob/f5c3312eaef8a2f3607f28b61ed43cfd8d255c71/src/androidTest/java/com/couchbase/lite/ViewsTest.java#L3357-L3440

Thanks!
Hideki

**Comment by hideki** [comment]
Hi @vbenso,

I recently fixed the issue: https://github.com/couchbase/couchbase-lite-java-core/issues/1098.  In case multiple views exist sometimes old index data with old revision is not deleted. And as result, the query returns out-dated record. Do you think if the issues are same?

Thanks,
Hideki

**Comment by vbenso** [comment]
Hi @hideki,
Removed the Predicate from that view and did some testing against 0.0.0-673, worked like a charm.
Thanks,
Victor

**Comment by hideki** [comment]
@vbenso Thank you for your update!

**Comment by hideki** [comment]
Hi @vbenso,

Do not you mind if I merge https://github.com/couchbase/couchbase-lite-android/commit/f5c3312eaef8a2f3607f28b61ed43cfd8d255c71 into master branch as Unit test? This includes sample data and  map function you provided.

Please let me know.

**Comment by vbenso** [comment]
Hi @hideki,

That data isn't sensitive at all. 
Use as you please, glad to help.

Victor

**Comment by kunal228** [comment]
Hi Hideki,

I was having same issue. Scenario is that, first do the livequery and you get set of data e.g { A, B, C, D}. All { A, B, C, D} are different documents that I got from query. Now change some value on any of the document, say for document A I have changed one field-value. Now the Live Query is returning {A, A, B, C, D}, which is wrong. 
Can you please provide me the fixed build.

Thanks
Kunal

**Comment by hideki** [comment]
Hi @kunal228,

None of stable build includes fix for this issue. 
Please try the build from latest master. 
http://files.couchbase.com/maven2/com/couchbase/lite/couchbase-lite-android/0.0.0-709/

Thanks!

**Comment by npomfret** [comment]
I'm getting multiple revisions of a single document appearing in my indexes in CBL 1.2.1. Is there a fix available?

**Comment by gweisz** [comment]
We found this issue in the CBL 1.2.0 Android version.

We use CBL 1.2.0 by doing direct REST calls to it (We also use the CBL-phonegap plugin to initialize the local DB).
it seems to be a kind of race condition because sometimes it happens under the following scenario:

* Clean-up the application information
* Have a remote Sync-Gateway server already up & running with some existent documents
* Initialize a new local DB with bi-directional replication & quickly create a new document (that already exists in Sync-Gateway)
* Later the Sync-Gateway information is replicated into the local DB.
* Finally the _changes or _all_docs calls returns two different revisions of the same document. (The one that was retrieved from the remote Sync-Gateway & the one created at the local DB).

Notice that this happens sporadically, so we are not sure if this kind of race conditions happens during DB initialization or during replication.

Thanks, hope this helps to identify the issue!

**Comment by hideki** [comment]
Hi @npomfret, 

None of stable build includes fix for this issue. 
Please try the build from latest master. 
http://files.couchbase.com/maven2/com/couchbase/lite/couchbase-lite-android/0.0.0-710/

Thanks!

**Comment by npomfret** [comment]
I've tried 710 - same problem, still getting duplicate documents in my indexes when they are edited.  I upgraded and then re-built the indexes by creating a new design doc with a new name.

**Comment by hideki** [comment]
Hi @npomfret,
Do you have two different view issues? If not, can we keep track your view issue with the ticket:
https://github.com/couchbase/couchbase-lite-android/issues/855 ?

**Comment by npomfret** [comment]
No, I think its the same one.
