### ISSUE TITLE
Does couchbase stop pull replication when there is no space left on the device?

### ISSUE THREAD

**Issue by orenyodfat** [couchbase/couchbase-lite-android#799]
What is the proper way to handle that??

**Comment by hideki** [comment]
Hi @orenyodfat,
Honestly, I have never tested this scenario. I believe Database throws Exception if it is not able to insert new document anymore. This is critical error, pull replicator should stop by itself.

**Comment by orenyodfat** [comment]
So what the system should do in this case ?
Does the server knows that the device is out of space ?
Is there a mechanism that the server knows the device free space and limit
the syncs docs accordingly ?

**Comment by hideki** [comment]
Hi @orenyodfat,

1.So what the system should do in this case ?
 => It depends application's recovery strategy.
2. Does the server knows that the device is out of space ?
 => No, it does not. Sync gateway does not manage device.
3. Is there a mechanism that the server knows the device free space and limit the syncs docs accordingly ?
 => same with above

**Comment by zgramana** [comment]
@hideki: please work with @sethrosetter  let's add a functional test for out of disk space errors.

**Comment by borrrden** [comment]
We will track this ticket [here](https://github.com/couchbaselabs/mobile-testkit/issues/679)
