### ISSUE TITLE
Is there a proper way to tell that a pull replication is done?

### ISSUE THREAD

**Issue by vbenso** [couchbase/couchbase-lite-android#800]
Even in version 1.2, the pull replication's change listener receives some REPLICATION_IDLE stati before the replication is over.
I wan't my app to tell to its user when the replication is done, but couldn't find any reliable way of doing it.
Am I missing something obvious?

**Comment by hideki** [comment]
Hi @vbenso,
Checking replicator state is only way to detect all documents are replicated. 
Pull replicator detects all docs are replicated by checking 3 queues are empty, push replicator checks 2 queues. One of problem is these queue are not synchronized. it causes problem.
We will work for this.
Thanks!

**Comment by hideki** [comment]
This issue is duplicated with couchbase/couchbase-lite-java-core#1077. Issue will be tracked by other ticket. So I will close this.
