### ISSUE TITLE
Add support for auto-compaction

### ISSUE THREAD

**Issue by orenyodfat** [couchbase/couchbase-lite-android#803]
android CBL 1.2

**Comment by pradipvaghasiya** [comment]
same for iOS as well. I need to reduce the disk size by removing attachment from local database.

**Comment by hideki** [comment]
Please call `Database.compact()` which remove unused attachments.

**Comment by orenyodfat** [comment]
Thanks.
I thought that the compact is done automatically...is that not the case?

**Comment by orenyodfat** [comment]
How to remove the viewindex file. It also use some space?

**Comment by hideki** [comment]
auto compact is not yet supported by CBL Android/Java
https://github.com/couchbase/couchbase-lite-java-core/blob/4586f6a8f8b3ea8cbdb1362196eb5cb00d9b2969/src/main/java/com/couchbase/lite/store/Store.java#L69

iOS: https://github.com/couchbase/couchbase-lite-ios/blob/2ebec67a0296dd4215b51b48d9ca59aa26edf8a7/Source/CBLDatabase%2BInternal.h#L91

**Comment by hideki** [comment]
`viewindex` is an index file. if indexed data is small, it will be smaller.

**Comment by hideki** [comment]
This is duplicated with https://github.com/couchbase/couchbase-lite-java-core/issues/840.
We will track this issue with other ticket.
