### ISSUE TITLE
[cbl 1.2.0] document(there is no _removed field) don't  sync if the user is removed from the channel that the document belong to

### ISSUE THREAD

**Issue by atom992** [couchbase/couchbase-lite-android#805]
I am using com.couchbase.lite:couchbase-lite-android:1.2.0 on Android 5.0.1 with Couchbase Sync Gateway 1.2.0-79 on Ubuntu 12.04.5 LTS 64bit.
and my scene as follows:
1 user A has channel c1;
2 doc d1(with rev1) belongs to c1;
so user A can sync d1;
than I remove the c1 from A,and d1 has changed to rev2;
A still has doc d1with rev1, there is no _removed=true field.

**Comment by adamcfraser** [comment]
Once user A is removed from channel c1, they won't get any subsequent updates for documents in that channel (d1 in this case).  So it's expected that they won't see rev2 of d1.

If d1 was removed from channel c1 while user A still had access, they would see the _removed notification.

Currently Sync Gateway doesn't send removals for documents when a user is removed from a channel - see https://github.com/couchbase/sync_gateway/issues/264 for more details.

**Comment by atom992** [comment]
ok,Thank you. Is there a roadmap to fix it?

**Comment by adamcfraser** [comment]
There have been recent discussions on adding support for channel removal notification to clients - it's definitely something we want to address - but I don't have a more specific delivery timeline than that at this point.

**Comment by atom992** [comment]
ok,I got it.Thank you.
