### ISSUE TITLE
android grade option minifyEnabled (procured) not working

### ISSUE THREAD

**Issue by orenyodfat** [couchbase/couchbase-lite-android#806]
I saw it is documented..
BUT when it will be fixed?
It is important for our production build.

**Comment by zgramana** [comment]
Can you provide any details or error messages?

**Comment by orenyodfat** [comment]
From http://developer.couchbase.com/documentation/mobile/1.2/develop/training/build-first-android-app/get-started-studio/index.html

"Couchbase Lite for Android might not build correctly with ProGuard. If you get build errors that mention ProGuard, you can disable it by changing the build.gradle file `minifyEnabled` property (formerly `runProGuard`) in the android section to false."

**Comment by zgramana** [comment]
It's not saying that it _will_ break, but only that it _could_. The point of `minifyEnabled` is to remove unused code, but only app developers know which features of Couchbase Mobile they are using. We're simply not in a position to know that information. For example, if ProGuard dead-strips CBL code (or any code CBL depends on), especially types/members referenced via reflection, and your app later attempts to use a feature that depends on that code, then it will break. While [the tools are there for developers to manage this](http://tools.android.com/tech-docs/new-build-system/resource-shrinking), some people are not familiar with them, or cannot take the time to configure ProGuard rules to `-keep` all the necessary code.

**Comment by NitzDKoder** [comment]
-keep class com.couchbase.touchdb.TDCollateJSON { *; }
-dontwarn com.couchbase.touchdb.TDCollateJSON.**

-keep class com.couchbase.lite.**{ *; }
-dontwarn com.couchbase.lite.**


-keep class com.couchbase.lite.util.**{ *; }
-dontwarn com.couchbase.lite.util.**


-keep class com.couchbase.lite.store.**{ *; }
-dontwarn com.couchbase.lite.store.**



-keep class com.couchbase.lite.Manager.**{ *; }
-dontwarn com.couchbase.lite.Manager.**


-keep class com.couchbase.lite.Database.**{ *; }
-dontwarn com.couchbase.lite.Database.**

-keep class com.couchbase.cbforest.**{ *; }
-dontwarn com.couchbase.cbforest.**

-keep class couchbase.lite.listener.**{ *; }
-dontwarn couchbase.lite.listener.**

-keep class Acme.Serve.Serve.**{ *; }
-dontwarn Acme.Serve.Serve.**

-keep class Acme.Serve.SimpleAcceptor.**{ *; }
-dontwarn Acme.Serve.SimpleAcceptor.**

-keep class com.couchbase.lite.listener.LiteServer.serve.**{ *; }
-dontwarn com.couchbase.lite.listener.LiteServer.serve.**

-keep class Acme.Serve.**{ *; }
-dontwarn Acme.Serve.**

This will help..

**Comment by hshahdoost** [comment]
Also remember that at the time couchbase lite uses Jackson, okhttp and okio, so you are gonna need the following lines on your proguard file as well

```
# jackson
-keepattributes *Annotation*,EnclosingMethod,Signature
-keepnames class com.fasterxml.jackson.** { *; }
 -dontwarn com.fasterxml.jackson.databind.**
 -keep class org.codehaus.** { *; }
 -keepclassmembers public final enum org.codehaus.jackson.annotate.JsonAutoDetect$Visibility {
 public static final org.codehaus.jackson.annotate.JsonAutoDetect$Visibility *; }
-keep public class your.class.** {
  public void set*(***);
  public *** get*();
}

## okhttp
-dontwarn okhttp3.**
-dontwarn okio.**

```
