### ISSUE TITLE
Is there a way to remove viewindex files?

### ISSUE THREAD

**Issue by orenyodfat** [couchbase/couchbase-lite-android#809]
These viewindex files are not in used any more (after deleting the docs) but occupied some storage space.

**Comment by zgramana** [comment]
Are you calling [deleteIndex](http://developer.couchbase.com/documentation/mobile/1.2/develop/references/couchbase-lite/couchbase-lite/view/view/index.html)? If that doesn't remove the files on disk, then this is a bug.

**Comment by zgramana** [comment]
Please re-open if this continues.
