### ISSUE TITLE
Arquitecture and performance NoSQL vs SQLite

### ISSUE THREAD

**Issue by denebchorny** [couchbase/couchbase-lite-android#814]
Hi Couchbase team,
Sorry for boder you, but, I am trying to make an investigation for my organization about NoSQL and SQLite (as deep as I can for a decision making). I hope you help me. Meaby the answer could help someone else.

The first question I did was "Why NoSQL in the phone?". This is easy to answer. 
As we are using a document-oriented database, using the same engine in the phone could:

1) This reduces decomposition time document to convert a non-relational structure to a relational structure to the case of using SQLite.

2) This reduces efforts to make migration database whenever the application requires changes its attributes. And even more when the application is constantly changing.

Now if android natively has an engine SQLite, I wonder Why has not one of natively documents?

This is why I want to know the following to have a better criteria between the two types of database:

1) If I emit a document in a view, does the view duplicate the document?
2) Does the revisions duplicate the documents?

Thanks in advance.

Deneb Chorny

**Comment by hideki** [comment]
Hi @denebchorny 

> 1) If I emit a document in a view, does the view duplicate the document?

If you emit a document as the value, the document is stored in the index. You can set `null` in value field, at query time the document will be obtained from the storage. Please  

> 2) Does the revisions duplicate the documents?

I am not clear about question. Whenever updating the document, CBL creates new revisions. In json field of each revision, json is stored. Without calling Document.purge() or Database.compact(), all revisions are kept.

Thanks!

**Comment by denebchorny** [comment]
Thank you. I am grateful
