### ISSUE TITLE
Received invalid doc ID from _changes possibly blocking pull replication

### ISSUE THREAD

**Issue by tinderangler** [couchbase/couchbase-lite-android#816]
I'm not fully sure about this problem. Tried to investigate it for a couple of hours as the same code is working on CBL 1.1.0 but not with 1.2.0 (neither with the last nightly build).

Replication is push/pull to Sync Gateway. On the server I've created a user named "user_3" who has access to it's private channel "user_3". Authentication is done by creating a session in Sync Gateway and using a cookie.

When starting the pull replication it is not pulling any docs. As far as I can see the problem might be connected with those two lines from adb:

```
03-21 13:30:35.472: D/Sync(10850): changeTrackerReceivedChange: {seq=2, id=_user/user_3, changes=[]}
03-21 13:30:35.472: W/Sync(10850): com.couchbase.lite.replicator.PullerInternal@a406fca: Received invalid doc ID from _changes: {seq=2, id=_user/user_3, changes=[]}
```

Sometimes I also get flooded with messages repeating endlessly the following lines:
```
03-21 13:30:36.322: V/ChangeTracker(10850): com.couchbase.lite.replicator.ChangeTracker@3be8899c: Starting new longpoll
03-21 13:30:36.322: V/ChangeTracker(10850): com.couchbase.lite.replicator.ChangeTracker@3be8899c: Making request to http://192.168.178.52:4984/peakbook_app/_changes
03-21 13:30:36.324: D/Sync(10850): [PullerInternal.waitForPendingFutures()] STARTED - thread id: 52002
03-21 13:30:36.324: D/Sync(10850): [fireTrigger()] => WAITING_FOR_CHANGES
03-21 13:30:36.324: D/Sync(10850): [waitForPendingFutures()] END - thread id: 52002
03-21 13:30:36.324: D/Sync(10850): firing trigger: WAITING_FOR_CHANGES
03-21 13:30:36.324: V/Sync(10850): [onExit()] IDLE => IDLE
03-21 13:30:36.324: V/Sync(10850): [onEntry()] IDLE => IDLE
03-21 13:30:36.380: D/cr_Ime(10850): [ImeAdapter.java:140] onCreateInputConnection returns null.
03-21 13:30:36.430: V/ChangeTracker(10850): com.couchbase.lite.replicator.ChangeTracker@3be8899c: got response. status: HTTP/1.1 200 OK mode: LongPoll
03-21 13:30:36.431: V/ChangeTracker(10850): com.couchbase.lite.replicator.ChangeTracker@3be8899c: /entity.getContent().  mode: LongPoll
03-21 13:30:36.431: V/ChangeTracker(10850): com.couchbase.lite.replicator.ChangeTracker@3be8899c: readValue
03-21 13:30:36.431: V/ChangeTracker(10850): com.couchbase.lite.replicator.ChangeTracker@3be8899c: /readValue.  fullBody: {results=[], last_seq=2}
03-21 13:30:36.431: V/ChangeTracker(10850): com.couchbase.lite.replicator.ChangeTracker@3be8899c: responseOK: true
03-21 13:30:36.431: D/Sync(10850): changeTrackerCaughtUp
```

Full logs here: [logs.txt](https://github.com/couchbase/couchbase-lite-android/files/182202/logs.txt)

I'm thankful for any help as I don't see if this is something I'm doing wrong (maybe I have to change something in my code when switching to 1.2.0?) or if this might be a bug.

**Comment by tinderangler** [comment]
I found what went wrong, I was not adding the proper channel to the replication so it didn't have access to any docs. Now the blocking is gone, my mistake.

Anyways I think I would be good to have a look on this as this shouldn't lead to endlessly repeated log messages. Any idea why the replicator receives a document `_user/user_3` which looks like Sync Gateways doc for this user (I was authenticating as user_3)?

**Comment by hideki** [comment]
Hi @tinderangler,

I am glad to hear you could solve the problem by yourself.

About log message, I believe your app enable logging for `SYNC` with `VERBOSE` level. Default log level of CBL is WARNING. Can you find following line ,`Manager.enableLogging(Log.TAG_SYNC, Log.VERBOSE);`, in your codes? If so please comment out them.

Thanks!

**Comment by hideki** [comment]
Hi @tinderangler,

The warning message, `Received invalid doc ID from _changes:`, was unnecessary log message. I removed it from codes.
https://github.com/couchbase/couchbase-lite-java-core/pull/1190

Thanks,
Hideki
