### ISSUE TITLE
Clone and build couchbase lite as sub module Failure

### ISSUE THREAD

**Issue by DanGDroid** [couchbase/couchbase-lite-android#820]
i choos to build the project with forestDB and followed as described in:  
https://github.com/couchbase/couchbase-lite-android/wiki/Add-Couchbase-Lite-to-your-project-as-a-submodule  
but get an error : Error:Configuration with name 'default' not found.
same error on eny combination with forest or without  
im using-- distributionUrl=https\://services.gradle.org/distributions/gradle-2.5-all.zip

**Comment by hideki** [comment]
I guess you forgot to do `git submodule update --init --recursive`.

**Comment by DanGDroid** [comment]
i tryed again this time first i only try to clone and build the couchbase-lite-android librariey  
as described -- Building Couchbase Lite via Android Studio -- https://github.com/couchbase/couchbase-lite-android  
after importing the setting.gradle to android studio and build i get an error:  

Error:Execution failed for task ':libraries:couchbase-lite-java-forestdb:cleanNative'.
> A problem occurred starting process 'command 'C:\Users\Admin\AppData\Local\Android\sdk\ndk-bundle/ndk-build''  

so i guess i have to replace "ndk-build" to "ndk-build.cmd"??

**Comment by DanGDroid** [comment]
after rebuilding i get the following:  
9:43:14 AM Gradle build finished with 2 error(s) and 1 warning(s) in 1m 15s 11ms --  

:libraries:couchbase-lite-java-core:compileJava
Warning:[options] bootstrap class path not set in conjunction with -source 1.6
Note: Recompile with -Xlint:unchecked for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
1 warning  

Error:error opening 'C:/Users/Admin/couchbase-lite-android/libraries/couchbase-lite-java-forestdb/obj/local/armeabi-v7a/objs/CouchbaseLiteJavaForestDB/C_/Users/Admin/couchbase-lite-android/libraries/couchbase-lite-java-forestdb/jni/__/vendor/cbforest/vendor/sqlite3-unicodesn/fts3_unicode2.o.d': No such file or directory  

Error:Execution failed for task ':libraries:couchbase-lite-java-forestdb:buildNative'.
> Process 'command 'C:\Users\Admin\AppData\Local\Android\sdk\ndk-bundle/ndk-build.cmd'' finished with non-zero exit value 2

**Comment by hideki** [comment]
Sorry, I have never built `couchbase-lite-android` on Windows.

Following line repeat some of path (`C:/Users/Admin/couchbase-lite-android/libraries/couchbase-lite-java-forestdb/obj/local/armeabi-v7a/objs/CouchbaseLiteJavaForestDB`) twice. Do you know why?
```
`C:/Users/Admin/couchbase-lite-android/libraries/couchbase-lite-java-forestdb/obj/local/armeabi-v7a/objs/CouchbaseLiteJavaForestDB/C_/Users/Admin/couchbase-lite-android/libraries/couchbase-lite-java-forestdb/jni//vendor/cbforest/vendor/sqlite3-unicodesn/fts3_unicode2.o.d`
```

**Comment by hideki** [comment]
Note to self:
- Tried to build CBL Android on Windows Server 2012 on VM. NDK does not work. Android SDK does not support Windows Server 2012, this could be reason. Also None of Android emulator works on Windows on VM.
- I requested physical Windows machine to IT. Currently I am waiting it.

**Comment by DanGDroid** [comment]
the project cannot be built with Android Studio running on pc before trying to run on emulator or real android device

**Comment by hideki** [comment]
Note To Self:

Issue 1:
-  `..` does not work in Android.mk on Windows platform. No issue with OSX and Linux

**Comment by hideki** [comment]
refer: https://github.com/couchbase/couchbase-lite-android/issues/835

**Comment by hideki** [comment]
Fixed with PRs:
- https://github.com/couchbase/couchbase-lite-java-native/pull/42
- https://github.com/couchbaselabs/couchbase-lite-java-forestdb/pull/52

**Comment by hideki** [comment]
Hi @DanGDroid,
When you have time, please try to build from master branch? 
Thanks!

**Comment by DanGDroid** [comment]
Hi @hideki .
it works i cloned and built as a sub nodule in my project
Information:BUILD SUCCESSFUL
Thanx!
