### ISSUE TITLE
Emit with include_docs=true

### ISSUE THREAD

**Issue by denebchorny** [couchbase/couchbase-lite-android#822]
Hello team,

I'm new using couchbase in Android .

I have understood that if I emit a document this greatly increases the database because the document is duplicated completely when is indexing. So, the solution is to make a null emit (EMIT (key, null)). But just as in the desktop environment that can return a document by emitting null doing include_docs = true, How could I do this in Android?.

I hope you understand me.

Thanks in advance.

**Comment by hideki** [comment]
Please use `Document QueryRow.getDocument()`

http://developer.couchbase.com/documentation/mobile/1.2/develop/references/couchbase-lite/couchbase-lite/query/query-row/index.html

**Comment by denebchorny** [comment]
Sorry, but I don't understand all the process how to get the document. I mean, I am trying to find a way to work with CBL similar to the desktop environment. I am new with CBL on Android even with views in desktop environments. I am looking for a complete example and there are a few but I dont understand them at all.
I have a MongoDB in the cloud. I bring the documents to android with retrofit. At first I need to save the document in the phone checking if the ID exists to recognize if the document need to be updated. Second, I need to list them on a RecyclerView, for that I am thinking the have an array of documents like ArrayList<Document> It will be easy to modify just the UserProperties and update them on the phone.
For this I need to do a view I think. Maybe something similar to this (this is not my example, this is part of the ToDoLite project, I dont understand at all):

Example:


public static Query getQuery(Database database) {
        com.couchbase.lite.View view = database.getView(VIEW_NAME);
        if (view.getMap() == null) {
            Mapper mapper = new Mapper() {
                public void map(Map<String, Object> document, Emitter emitter) {
                    String type = (String)document.get("type");
                    if (DOC_TYPE.equals(type)) {

                        // Here I emit the document as null to avoid duplicate it in the database by this index.
                        emitter.emit(document.get("title"), null);
                    }
                }
            };
            view.setMap(mapper, "1");
        }

        Query query = view.createQuery();
        return query;
    }

In this case, how can I return on a View all the documents correctly?, using as you said Document QueryRow.getDocument().

**Comment by hideki** [comment]
To retrieve all documents from database, I recommend to use `Map<String, Object> allDocs = Database.getAllDocs(options);`
Example:
https://github.com/couchbase/couchbase-lite-android/blob/01281759e024cd7304c16fb7a082c1e45a6b9909/src/androidTest/java/com/couchbase/lite/ViewsTest.java#L785

Another example with Android:
https://github.com/couchbaselabs/mini-hacks/tree/master/kitchen-sync/android
Another example with Android:
https://github.com/couchbaselabs/GrocerySync-Android

**Comment by hideki** [comment]
@denebchorny ,
Could previous my response answer for your question?

**Comment by denebchorny** [comment]
@hideki  Sorry for my late reply,

I don't understand at all. I need to read more I think. 
My Idea is simple:

1) I bring data from a server (From MongoDB) to the phone.
2) I need to save it on the phone in CLB
3) I need to show the information in a list, then I need to retrieve data from CLB
4) I could edit data from de list showed before, then I need to update it on CLB.
5) I require to use views.

For all of these I need to reduce the size of the database because we are working on a phone and we know the is a limitation. For this part I am clear (I have an Idea) because I know I have to use something like include_docs=true as you told me and do something as Document.purge() or Database.compact() as someone told me here: https://github.com/couchbase/couchbase-lite-android/issues/814

But for the five steps I said before I don't know exactly the process to do it. IDK if you understand me. 

Obviously, I need to read more. But I am working on a project that I need to finish as sson as possible then I was looking for the best practice to do all of these.

Thank you for your time and all the help you offer me

**Comment by hideki** [comment]
Hi @denebchorny,

First I strongly recommend you to read [Couchbase Lite documentations]( http://developer.couchbase.com/documentation/mobile/1.2/get-started/couchbase-mobile-overview/index.html).

For any questions, I recommend to post to [Couchbase Forum](https://forums.couchbase.com/c/mobile). More people are observing this forum. You might get answer quickly.

CBL supports sync functionality with Couchbase Server through Sync Gateway and CouchDB. If you can use Couchbase Server or CouchDB, CBL provide sync functionality.

I will close this ticket now. If you have any issues, please post here. I will reopen this ticket.

Thanks,
Hideki
