### ISSUE TITLE
Unnecessary Log.e()

### ISSUE THREAD

**Issue by biokys** [couchbase/couchbase-lite-android#824]
I am just wondering if ReplicationInternal:1124 in latest release 1.2.1 log statement should be declared with severity ERROR?

``` Log.e(TAG, "run() count=%d changeEvent=%s", changeListeners.size(), changeEvent);```

and also row 1106:

``` Log.e(TAG, "notifyChangeListeners() %s", changeEvent); ```

**Comment by hideki** [comment]
https://github.com/couchbase/couchbase-lite-java-core/pull/1170
