### ISSUE TITLE
Pull Replicator failing if Push Replicator has no changes

### ISSUE THREAD

**Issue by BenStorey** [couchbase/couchbase-lite-android#830]
Hello everyone,

I'm building an android app which in dev has had no problems, but now I'm deploying it to production and started seeing strange behaviour from the pull replicator. Very little has changed between the two environments (obviously I'm aiming for them to be identical) so I'm a little stumped by this. 

In short, the problem is that my pull replicator doesn't seem to make the request to get _changes, and just thinks there is nothing to do. If I have a local change, the push replicator sends it, and then the pull replicator will wake up and pull down all the other changes. So a hacky workaround would be to create a new document before every sync request, but obviously I'd rather not do that ... :)

Couchbase lite version:
    `compile 'com.couchbase.lite:couchbase-lite-android:1.2.0'`
    `compile 'com.couchbase.lite:couchbase-lite-android-forestdb:1.2.0'`

Locally I'm using ForestDB and the new symmetric encryption option. 

Server details:
   CouchDB 1.6.0 from apt, running on Ubuntu 15.10. Connection to CouchDB is through an nginx reverse proxy.

The only real difference between dev and prod is that SSL is enabled in production, so protocol is https:// rather than http://. The rest of the nginx config is otherwise identical (but doesnt appear to be the problem here anyway)

If its helpful, the code looks like this:

`URL syncUrl = new URL(this.connectionDetails.GetCouchUrl() + database.getName());`

`HashMap<String, Object> headers = new HashMap<>(1);`
`headers.put("cookie", authCookie);`

`final Replication pull = database.createPullReplication(syncUrl);`
`pull.setContinuous(true);`
`pull.setHeaders(headers);`

`final Replication push = database.createPushReplication(syncUrl);`
`push.setContinuous(true);`
`push.setHeaders(headers);`

`push.start();`
`pull.start();`

If I remove my app, re-install it, when I attempt to replicate against my dev VM CouchDB it works perfectly, and I see logs like this:

Android:

`changed event: PUSH replication event. Source: com.couchbase.lite.replicator.Replication@3c94c245 Transition: INITIAL -> RUNNING Total changes: 0 Completed changes: 0`
`changed event: PULL replication event. Source: com.couchbase.lite.replicator.Replication@251e3f9 Transition: INITIAL -> RUNNING Total changes: 0 Completed changes: 0`
`changed event: PUSH replication event. Source: com.couchbase.lite.replicator.Replication@3c94c245 Transition: RUNNING -> IDLE Total changes: 0 Completed changes: 0`
`changed event: PULL replication event. Source: com.couchbase.lite.replicator.Replication@251e3f9 Total changes: 1 Completed changes: 0`
`changed event: PULL replication event. Source: com.couchbase.lite.replicator.Replication@251e3f9 Total changes: 1 Completed changes: 1`
`changed event: PULL replication event. Source: com.couchbase.lite.replicator.Replication@251e3f9 Transition: RUNNING -> IDLE Total changes: 1 Completed changes: 1`

CouchDB:

`192.168.1.43 - - GET /ben/_local/6bd421ed04a8246cdb232b360ec2106ec62f8d4e 404`
`192.168.1.43 - - GET /ben/_local/2495777f40b8eba65b62a362eb59f74c4814459c 404`
`192.168.1.43 - - GET /ben/_changes?feed=normal&heartbeat=300000&style=all_docs&active_only=true 200`
`192.168.1.43 - - GET /ben/_changes?feed=longpoll&limit=50&heartbeat=300000&style=all_docs&since=2 200`
`192.168.1.43 - - GET /ben/ab7bec04-6cc0-4445-a0bd-aac230221353?rev=1-2c1dd4d9f7ec59d6f6d644f305113e88&revs=true&attachments=true 200`
`192.168.1.43 - - PUT /ben/_local/2495777f40b8eba65b62a362eb59f74c4814459c 201`

All seems very reasonable. But then if I re-install the app, but point to production version rather than my VM:

Android:

`changed event: PUSH replication event. Source: com.couchbase.lite.replicator.Replication@27da8d54 Transition: INITIAL -> RUNNING Total changes: 0 Completed changes: 0`
`changed event: PULL replication event. Source: com.couchbase.lite.replicator.Replication@cbd91d8 Transition: INITIAL -> RUNNING Total changes: 0 Completed changes: 0`
`changed event: PUSH replication event. Source: com.couchbase.lite.replicator.Replication@27da8d54 Transition: RUNNING -> IDLE Total changes: 0 Completed changes: 0`
`changed event: PULL replication event. Source: com.couchbase.lite.replicator.Replication@cbd91d8 Transition: RUNNING -> IDLE Total changes: 0 Completed changes: 0`

CouchDB:

`123.202.72.28 - - GET /ben/_local/d7c9cdb29722a700b5d318a4a0db68a653356aee 404`
`123.202.72.28 - - GET /ben/_local/9b22fedaa921878c6738db2af69ed2b39e600208 404`

It seems like it just doesn't send messages to _changes, so the replicator happily goes idle thinking there is nothing to do. 

At first I figured I was somehow blocking the _changes requests at my proxy, but I found that if I add a random document to couchbase-lite, the push replicator will work correctly, and that is also somehow triggering the pull replicator into seeing the other changes. At which point the sync will work correctly. 

Android:

`changed event: PUSH replication event. Source: com.couchbase.lite.replicator.Replication@21923ddf Transition: INITIAL -> RUNNING Total changes: 0 Completed changes: 0`
`changed event: PULL replication event. Source: com.couchbase.lite.replicator.Replication@3f6009d7 Transition: INITIAL -> RUNNING Total changes: 0 Completed changes: 0`
`changed event: PULL replication event. Source: com.couchbase.lite.replicator.Replication@3f6009d7 Transition: RUNNING -> IDLE Total changes: 0 Completed changes: 0`
`changed event: PULL replication event. Source: com.couchbase.lite.replicator.Replication@3f6009d7 Total changes: 1 Completed changes: 0`
`changed event: PULL replication event. Source: com.couchbase.lite.replicator.Replication@3f6009d7 Total changes: 2 Completed changes: 0`
`changed event: PULL replication event. Source: com.couchbase.lite.replicator.Replication@3f6009d7 Total changes: 3 Completed changes: 0`
`changed event: PULL replication event. Source: com.couchbase.lite.replicator.Replication@3f6009d7 Total changes: 4 Completed changes: 0`
`changed event: PULL replication event. Source: com.couchbase.lite.replicator.Replication@3f6009d7 Total changes: 5 Completed changes: 0`
`changed event: PULL replication event. Source: com.couchbase.lite.replicator.Replication@3f6009d7 Total changes: 6 Completed changes: 0`
`changed event: PUSH replication event. Source: com.couchbase.lite.replicator.Replication@21923ddf Total changes: 1 Completed changes: 0`
`changed event: PUSH replication event. Source: com.couchbase.lite.replicator.Replication@21923ddf Total changes: 1 Completed changes: 1`
`changed event: PUSH replication event. Source: com.couchbase.lite.replicator.Replication@21923ddf Transition: RUNNING -> IDLE Total changes: 1 Completed changes: 1`
`changed event: PULL replication event. Source: com.couchbase.lite.replicator.Replication@3f6009d7 Total changes: 7 Completed changes: 0`
`Finished replicating, will now stop replicators`
`changed event: PULL replication event. Source: com.couchbase.lite.replicator.Replication@3f6009d7 Transition: IDLE -> STOPPING Total changes: 7 Completed changes: 0`
`changed event: PULL replication event. Source: com.couchbase.lite.replicator.Replication@3f6009d7 Transition: IDLE -> STOPPING Total changes: 7 Completed changes: 0`
`changed event: PUSH replication event. Source: com.couchbase.lite.replicator.Replication@21923ddf Transition: IDLE -> STOPPING Total changes: 1 Completed changes: 1`
`changed event: PUSH replication event. Source: com.couchbase.lite.replicator.Replication@21923ddf Transition: IDLE -> STOPPING Total changes: 1 Completed changes: 1`
`changed event: PULL replication event. Source: com.couchbase.lite.replicator.Replication@3f6009d7 Total changes: 7 Completed changes: 6`
`changed event: PUSH replication event. Source: com.couchbase.lite.replicator.Replication@21923ddf Transition: STOPPING -> STOPPED Total changes: 1 Completed changes: 1`
`changed event: PULL replication event. Source: com.couchbase.lite.replicator.Replication@3f6009d7 Total changes: 6 Completed changes: 6`
`changed event: PULL replication event. Source: com.couchbase.lite.replicator.Replication@3f6009d7 Transition: STOPPING -> STOPPED Total changes: 6 Completed changes: 6`

(You can ignore why it stops, I'm trying to do the async replication synchronously by stopping the replicators once both go into idle states. This breaks in prod version because the PULL replicator immediately goes into IDLE, it doesn't identify there are any changes to be made until the PUSH replicator gets going)

CouchDB:

`123.202.72.28 - - GET /ben/_local/9b22fedaa921878c6738db2af69ed2b39e600208 404`
`123.202.72.28 - - GET /ben/_local/d7c9cdb29722a700b5d318a4a0db68a653356aee 404`
`123.202.72.28 - - GET /ben/_changes?feed=normal&heartbeat=300000&style=all_docs&active_only=true 200`
`123.202.72.28 - - GET /ben/_changes?feed=longpoll&limit=50&heartbeat=300000&style=all_docs&since=7 200`
`123.202.72.28 - - POST /ben/_revs_diff 200`
`123.202.72.28 - - POST /ben/_all_docs?include_docs=true 200`
`123.202.72.28 - - POST /ben/_bulk_docs 201`
`123.202.72.28 - - PUT /ben/_local/9b22fedaa921878c6738db2af69ed2b39e600208 201`
`123.202.72.28 - - PUT /ben/_local/d7c9cdb29722a700b5d318a4a0db68a653356aee 201`

So it seems to do the same thing, Pull replicator is happy there are no changes to be made (although there are!), then the push replicator triggers the _changes message and suddenly we can pull the changes back down. 

Is there anything I'm obviously missing or doing wrong that could make it behave this way? 

Thank you!

Ben

**Comment by hideki** [comment]
Hi @BenStorey,

I guess the pull replicator stopped by the network error which is categorized as a permanent error.

I have some suggestions to debug this issue.
- Can you obtain thread-dump? Please check If you can see `ChangeTracker-xxxx` as thread name in thread-dump to make sure ChangeTracker is running.
- Can you enable logging by calling following methods?
```
Manager.enableLogging(Log.TAG_SYNC_ASYNC_TASK, Log.VERBOSE);
Manager.enableLogging(Log.TAG_SYNC, Log.VERBOSE);
Manager.enableLogging(Log.TAG_REMOTE_REQUEST, Log.VERBOSE);
Manager.enableLogging(Log.TAG_CHANGE_TRACKER, Log.VERBOSE);
```

I believe this could be first step.

Thanks!

**Comment by BenStorey** [comment]
Thanks for getting back so quickly!

I haven't obtained a thread dump yet (need to have a quick google around, I haven't done that before) but I've enabled the logging and put the output here:

https://gist.github.com/BenStorey/35e7698fcdbb45c3a4cb082a0afb56e3

Nothing too obvious jumps out at me, so any help would be super appreciated. Thanks again

**Comment by hideki** [comment]
From your log, Is the following URL accessible from your android device?
`https://multistorey.com:9001/ben/_changes?feed=normal&heartbeat=300000&style=all_docs&active_only=true`

**Comment by BenStorey** [comment]
Yes it is accessible. Clicking that link from my phone directly gives me the username/password auth box, so canceling it gives me the error : unauthorized couchdb json. 

I see it in the couchdb.log too.

**Comment by hideki** [comment]
I think CouchDB is enabled with basic authentication. Do you enable Basic Authentication with username and password to both push and pull replications?

**Comment by BenStorey** [comment]
Actually doing some more experimenting now, I *think* I'm getting closer to the root cause. I have code that is trying to make the asynchronous code synchronous (by waiting on a CountDownLatch which gets sent once the replicators are in Idle and seemingly done), and if I remove that completely then the replicators seem to do the right thing. 

I was working off an assumption that the state change would always be INITIAL -> RUNNING -> IDLE (all done), and then all would be done at the end. Instead it's doing INITIAL -> RUNNING -> IDLE (zero changes) -> RUNNING -> IDLE (all done). My code was calling stop() on it too early when it went into IDLE for the first time. I suspect on my local VM this happens so quickly that the replication can still work without moving into the first IDLE state, but with the extra latency going to my website it gets stopped too early. 

`changed event: PULL replication event. Source: com.couchbase.lite.replicator.Replication@27da8d54 Transition: INITIAL -> RUNNING Total changes: 0 Completed changes: 0`
`changed event: PULL replication event. Source: com.couchbase.lite.replicator.Replication@27da8d54 Transition: RUNNING -> IDLE Total changes: 0 Completed changes: 0`

My code here thinks we are all done, as we are in IDLE with 0 changes, so it calls stop() on the replicators. If I don't do that, it correctly updates after:

`changed event: PULL replication event. Source: com.couchbase.lite.replicator.Replication@27da8d54 Total changes: 1 Completed changes: 0`
`changed event: PULL replication event. Source: com.couchbase.lite.replicator.Replication@27da8d54 Total changes: 2 Completed changes: 0`
`changed event: PULL replication event. Source: com.couchbase.lite.replicator.Replication@27da8d54 Total changes: 3 Completed changes: 0`
`changed event: PULL replication event. Source: com.couchbase.lite.replicator.Replication@27da8d54 Total changes: 4 Completed changes: 0`
`changed event: PULL replication event. Source: com.couchbase.lite.replicator.Replication@27da8d54 Total changes: 5 Completed changes: 0`
`changed event: PULL replication event. Source: com.couchbase.lite.replicator.Replication@27da8d54 Total changes: 6 Completed changes: 0`
`changed event: PULL replication event. Source: com.couchbase.lite.replicator.Replication@27da8d54 Total changes: 7 Completed changes: 0`
`changed event: PULL replication event. Source: com.couchbase.lite.replicator.Replication@27da8d54 Total changes: 7 Completed changes: 7`
`changed event: PULL replication event. Source: com.couchbase.lite.replicator.Replication@27da8d54 Transition: IDLE -> RUNNING Total changes: 7 Completed changes: 7`
`changed event: PULL replication event. Source: com.couchbase.lite.replicator.Replication@27da8d54 Transition: RUNNING -> IDLE Total changes: 7 Completed changes: 7`

I think this is likely the issue, so I should be able to fix it from here. Thanks very much for all your help and sorry for taking up so much of your time. 

(FYI on the authentication, it accepts both basic authentication and cookie authentication. From couchbase-lite android though I only store cookies so always use cookie auth)

**Comment by BenStorey** [comment]
Actually though if you don't mind me asking since I've got your attention ... :)

Is there a reasonable way to do the async replication synchronously? My sync process is essentially:

1) sync database
2) use result of sync to know how to sync other data/media files
3) sync again if necessary

Since I can't do (2) without (1) being complete, I'm trying to make sure I only start the second step once the first has completed. If I can't rely on it being complete because its in the IDLE state, is there any other way for me to know that its finished replicating?

Thanks again,

Ben

**Comment by BenStorey** [comment]
Actually never mind, seems its as simple as turning off continuous replication and just letting it go into the STOPPED state by itself. I can't remember why I didn't do it this way earlier...

So I'm all good, thanks!
