### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by welniak** [couchbase/couchbase-lite-android#832]
*some reason body text was gone. Following is copy-pated from email notification*

-----------------------

Doing some tests with cbl android 1.2.0 release I noticed a potential memory leak (an actual one in our case).

Replications are being registered as networkReachabilityListeners in NetworkReachabilityManager class by ReplicationInternal instances, whenever those are started (inside of the initNetworkReachabilityManager() method, called by start() method), but they are never unregistered. So even if the Replication objects are stopped and set to null in the client code, they will continue to linger around.

Perhaps the Replication could be removed from the list of listeners in ReplicationInternal.stop() method?
Something like

db.getManager().getContext().getNetworkReachabilityManager().removeNetworkReachabilityListener(parentReplication);

Haven't tested behaviour of 1.2.1 release, but just looking at the code it seems the issue might still be there. Could you please have a look?

Thanks

**Comment by zgramana** [comment]
@welniak can you provide more details?

**Comment by zgramana** [comment]
Make sure you are not creating reference cycles when you add change listeners. This may appear as a leak if your main activity re-launches (e.g. user rotates the app--assuming you're not fragments based, etc.).

**Comment by welniak** [comment]
@zgramana The scenario when this would happen:

1) Manager instance is created, passing the AndroidContext instance to the constructor- the default, AndroidNetworkReachabilityManager is thus used,
2) New replications are created and started- in the start() method they're eventually added to the list of networkReachabilityListeners in the NetworkReachabilityManager class.
3) Now imagine replication is stopped and the local reference is set to null in the client code- that's all good, but the replication instance is still there in the list of networkReachabilityListeners, since it's never unregistered. 
4) After some time we want to start the replication again- we request new replication from the database, by calling Database.createPushReplication()/createPullReplication(), but this will create a brand new instance! So now there are two replication instances when there should be only one.
5) Perhaps this could be avoided in the client code by reusing the existing instance of the Replication class, but simply adding that one line I suggested in the first comment, in the stop() method of the ReplicationInternal class, could assure this does not happen in the library?

Thanks

**Comment by welniak** [comment]
Just looking at the code of 1.0.0 release- the replications were being removed from the list of listeners there, inside of Replication.stopped() method.

**Comment by hideki** [comment]
When continuous replicator stopped, replicator is removed from NetworkReachabilityManager.

1. https://github.com/couchbase/couchbase-lite-java-core/blob/262a8fab84a1ca239cb3b9735c3fed7209c28909/src/main/java/com/couchbase/lite/replicator/ReplicationInternal.java#L1313
1. https://github.com/couchbase/couchbase-lite-java-core/blob/262a8fab84a1ca239cb3b9735c3fed7209c28909/src/main/java/com/couchbase/lite/replicator/ReplicationInternal.java#L331
1. https://github.com/couchbase/couchbase-lite-java-core/blob/4cc2f7d66a9be58ca774d102497b7a725885e168/src/main/java/com/couchbase/lite/NetworkReachabilityManager.java#L37
