### ISSUE TITLE
Cant build chouchbase-lite-android on windows using Android Studio version-2.0 Gradle version -2.10

### ISSUE THREAD

**Issue by dhams** [couchbase/couchbase-lite-android#835]
I am trying to build couchbase-lite-android using command '/gradlew assemble' in windows 7 and its giving me below error 

```
Execution failed for task ':libraries:couchbase-lite-java-forestdb:buildNative'.
> A problem occurred starting process 'command  C:\Users\..\android-ndk-r11c-windows-x86_64\android-ndk-r11c/ndk-build
```

Android Studio version-2.0
Gradle version -2.10

I believe there in windows system 'ndk-build' would be 'ndk-build.cmd' and I tried using this command in every grade file where this used but again I am having below error 

`make: *** No rule to make target `C:/Users/../CouchBAseDemo/libraries/couchbase-lite-java-forestdb/jni/../vendor/cbforest/vendor/sqlite3-unicodesn/fts3_unicode2.c', needed by `C:/Users/../CouchBAseDemo/libraries/couchbase-lite-java-forestdb/obj/local/armeabi-v7a/objs/CouchbaseLiteJavaForestDB/C_/Users/../CouchBAseDemo/libraries/couchbase-lite-java-forestdb/jni/__/vendor/cbforest/vendor/sqlite3-unicodesn/fts3_unicode2.o'.  Stop.`

**Comment by hideki** [comment]
duplicated with https://github.com/couchbase/couchbase-lite-android/issues/820

**Comment by hideki** [comment]
Hi @dhams ,
When you have time, please try to build from master branch? 
Thanks!

**Comment by dhams** [comment]
Hi @hideki . I have tested with master branch and it seem issue is still there.Getting error like 

make: *** No rule to make targetC:/Users/../CouchBAseDemo/libraries/couchbase-lite-java-forestdb/jni/../vendor/cbforest/vendor/sqlite3-unicodesn/fts3_unicode2.c', needed by C:/Users/../CouchBAseDemo/libraries/couchbase-lite-java-forestdb/obj/local/armeabi-v7a/objs/CouchbaseLiteJavaForestDB/C_/Users/../CouchBAseDemo/libraries/couchbase-lite-java-forestdb/jni/__/vendor/cbforest/vendor/sqlite3-unicodesn/fts3_unicode2.o'. Stop.

my project structure is like below. 

Project
    |
  -app
  -libraries
       |
     -couchbase-lite-android
     -couchbase-lite-java-core
     -couchbase-lite-java-forestdb
     -couchbase-lite-java-native

**Comment by hideki** [comment]
Hi @dhams,

Can you check followings?
- Did you call 'git submodule update --init --recursive'?
- Is current Android.mk same with https://github.com/couchbaselabs/couchbase-lite-java-forestdb/blob/master/jni/Android.mk? Please check.
- Does calling `ndk-build -C jni` at directory of couchbase-lite-java-forestdb work?

Note to Self:
I tested the build with couchbase-lite-android. Not build with  application. I should test submodule solution.

**Comment by hideki** [comment]
@dhams,

I believe the deepest file path by nested submodules is longer than 255 (windows file path limitation). Then `git submodule update --init --recursive` does not work. There are not entire source codes are not cloned from github.

```
<directly>\<application project dir>\libraries\couchbase-lite-android\libraries\couchbase-lite-java-forestdb\vender\....
```

Please try to create you application folder under `C:\`? or use `libs` instead of `libraries`?

Thanks!
Hideki

**Comment by dhams** [comment]
@hideki Thanks for your reply. 
I have also tried to checkout the code in C folder. The code is almost downloaded from gihub using 
`git submodule update --init --recursive` command but two times that has generated failed logs 

`Clone of 'git://github.com/snej/sqlite3-unicodesn.git' into submodule path 'vendor/sqlite3-unicodesn' failed
Failed to recurse into submodule path 'libraries/couchbase-lite-java-forestdb/vendor/cbforest'`

`Submodule path 'libraries/couchbase-lite-java-native/vendor/sqlcipher/vendor/sqlcipher': checked out 'c01b94fb6a6b54e00b9839e7314893f72c9dab22'
Failed to recurse into submodule path 'libraries/couchbase-lite-java-forestdb'`

Attached full logs of that event . Please check if you can find anything wrong.
[module_log.txt](https://github.com/couchbase/couchbase-lite-android/files/217166/module_log.txt)

**Comment by hideki** [comment]
@dhams, I believe longest file path makes `git submodule update --init --recursive` fail. Can you try to change project name shorter. Also you can try to change `libraries` to `libs` that is described in https://github.com/couchbase/couchbase-lite-android/wiki/Add-Couchbase-Lite-to-your-project-as-a-submodule. Also you can also change `couchbase-lite-android`, `couchbase-lite-java-core`, `couchbase-lite-java-forestdb` and `couchbase-lite-java-native` shorter name when you do `git submodule add`.
