### ISSUE TITLE
viewNameToFilename generates invalid filename

### ISSUE THREAD

**Issue by vbenso** [couchbase/couchbase-lite-android#837]
When using FORESTDB_STORAGE my views aren't being created properly.
Replacing the "/" by ":" doesn't seem to work well when the application's storage is pointing to an SDCard. 
Is ":" a valid character for filenames in fat32 cards?

Just for clarity I'm reproducing the function that generates the filename for a given view.
```
private static String viewNameToFileName(String viewName) throws CouchbaseLiteException {
        if(!viewName.startsWith(".") && viewName.indexOf(":") <= 0) {
            viewName = isWindows()?escapeViewNameWindows(viewName):viewName.replaceAll("/", ":");
            return viewName + "." + "viewindex";
        } else {
            throw new CouchbaseLiteException(495);
        }
    }
```
I'm using:
```
compile 'com.couchbase.lite:couchbase-lite-android:0.0.0-660'
compile 'com.couchbase.lite:couchbase-lite-android-forestdb:0.0.0-660'
```

**Comment by zgramana** [comment]
Just need to rename `isWindows` to `isExternalDrive` and check to see if we are on the SD card, at which point we can assume FAT32. Eventually, we probably want to do more robust FS checking as other formats may come along later.

**Comment by vbenso** [comment]
Nice work, 
thanks for the migration code.

**Comment by hideki** [comment]
Fixed in couchbase-lite-java-forestdb. PR: https://github.com/couchbaselabs/couchbase-lite-java-forestdb/pull/53
