### ISSUE TITLE
Check document fields

### ISSUE THREAD

**Issue by denebchorny** [couchbase/couchbase-lite-android#838]
Hi, I know this is an (meaby) stupid question, but here we go.

I want to know if there is a way to check if a property exists in a document. Let me make you an example:

```json
I have this type of document (Json):{
    "type":String,
    "fullName":String,
    "age":Number
}

Easily I could have something documents like this

// Doc 1
{
    "type":"user",
    "fullName":"Peter Capaldi",
    "age":"1200"
}

// Doc 2
{
    "type":"user",
    "age":"100"
}
```

I want to check if the document have de "fullName" property because I am trying to display it in a recyclerview and it could be null or the property doesn't exists.

This is the way I am doing it on the recyclerview:

```java
@Override
    public void onBindViewHolder(TicketViewholder holder, int position) {
        // Getting the document
        Document ticketDoc = enumerator.getRow(position).getDocument();

        // Checking if the property exists
        int priority = ticketDoc.getProperty(Ticket.PRIORITY) != null
                ? (int) ticketDoc.getProperty(Ticket.PRIORITY)
                : 0;

       holder.priority
                .setBackgroundColor(Color.parseColor(
                        Ticket.getPriorityColor(priority)));

....
}
```

Is there a better way to do this?.

Thanks in advance

**Comment by hideki** [comment]
Hi @denebchorny,

Using `Document.getProperty(key)` is good solution. Or you can call `public Map<String, Object> getProperties()`.

https://github.com/couchbase/couchbase-lite-java-core/blob/d4cde83f2e92b3379305cd78339836f40cc81b7e/src/main/java/com/couchbase/lite/Document.java#L242-L248

https://github.com/couchbase/couchbase-lite-java-core/blob/d4cde83f2e92b3379305cd78339836f40cc81b7e/src/main/java/com/couchbase/lite/Document.java#L166

For questions, please use https://forums.couchbase.com/ from next time. More people are observing forums. 

thanks!
