### ISSUE TITLE
Error re-adding a document after it's been purged

### ISSUE THREAD

**Issue by orenyodfat** [couchbase/couchbase-lite-android#839]
This issue is fixed in the iOS version .https://github.com/couchbase/couchbase-lite-ios/issues/714

Is that been fixed on android also?

**Comment by hideki** [comment]
It is not ported yet to CBL Android.

Note to Self:
- https://github.com/couchbase/couchbase-lite-ios/blob/0705423d3d030b208e87f48ee63725c7b553f7ca/Source/CBL_SQLiteStorage.m#L765-L771

- https://github.com/couchbase/couchbase-lite-java-core/blob/4cc2f7d66a9be58ca774d102497b7a725885e168/src/main/java/com/couchbase/lite/store/SQLiteStore.java#L2338

**Comment by hideki** [comment]
Note to Self:
- https://github.com/couchbase/couchbase-lite-ios/blob/0705423d3d030b208e87f48ee63725c7b553f7ca/Source/CBL_SQLiteStorage.m#L765-L771
- https://github.com/couchbase/couchbase-lite-java-core/blob/4cc2f7d66a9be58ca774d102497b7a725885e168/src/main/java/com/couchbase/lite/store/SQLiteStore.java#L2338

**Comment by orenyodfat** [comment]
Thanks.
I suggest you will have a common test procedure for both iOS and Android ..so both version will behave the same against the server.

**Comment by hideki** [comment]
before calling `insertDocumentID()`, CBL android/java check value. So CONFLICT never occurs. https://github.com/couchbase/couchbase-lite-java-core/blob/4cc2f7d66a9be58ca774d102497b7a725885e168/src/main/java/com/couchbase/lite/store/SQLiteStore.java#L2338
