### ISSUE TITLE
Update deep keys on a document

### ISSUE THREAD

**Issue by denebchorny** [couchbase/couchbase-lite-android#842]
Hi againg sir, and sorry for bother you. but more I ask more I (meaby someone else) learn and understand better.

At first, let me show you how is composed a document 
```json
{
     "_id": "",
     "type": "ticket",
     "idNetmatrix": "",
     "idEvent": "",
     "actionPlan": {
          "idActionPlan": "",
          "activities": [
               {
                    "idActivity": "",
                    "status": "",
                    "idPersonal": ""
               }
          ]
     }
}
```

Imagine I have a Document as shown before. I can access it as this to the simple properties:

```java
Document docDB = <document retrieved from database>;
Map<String, Object> doc = docDD.getProperties();

// accessing to ID is simple
String id = (String) doc.get("_id");

// accessing to idNetmatrixis simple
String idNetmatrix= (String) doc.get("idNetmatrix");
```

If I want to access to the activities "actionPlan.activities", how can I do this? and how can I edit this to  update the document. is it like this?

```java
Document docDB = <document retrieved from database>;
Map<String, Object> doc = docDD.getProperties();

// As I know that actionPlan is like a JsonObject I can cast it to a Map  (I think, correct me if I am wrong)
Map<String, Object> actionPlan = (Map<String, Object>) doc.get("actionPlan");

// Now to get the activities Do I do it this way?
List<Object> activities = (List<Object>) actionPlan.get("activities");

// or could be something like this to be able to access to every property in the activity object?
List<Map<String, Object>> activities = (List<Map<String, Object>>) actionPlan.get("activities");

/*
* If the idea above is correct and assuming I changed the list of activities. 
* I just put them back to the actionPlan variable and put this last back to the document 
* as this. Is this correct?:
*/
actionPlan.put("activities", activities);
doc.put("actionPlan", actionPlan);
try {
     docDB.putProperties(doc);
} catch (CouchbaseLiteException e) {
      e.printStackTrace();
}
```

I could try this, but I don't know if I am doing this correctly. I'm a little maniac trying to do my job using the best practices as possible.

I am asking this because imagine I have to update many documents as this way, then there could have much processing, maybe.

Another way I think could be a good Idea is to parse properties of a document to JsonString and use this library https://github.com/jayway/JsonPath to access directly to the deep properties, change whatever I need and parse back to document properties and save them.

Imagine that there could be a very deep properties. I am trying to find the best way in performance and processing to do it.

Again, excuse me for my annoying or stupid questions.

Thanks in advance.

**Comment by hideki** [comment]
Hi @denebchorny,

Sorry for late reply.

Your code is correct. CBL Android/Java tries to provide simple interface to store/read data with Map/List/Object. CBL internally convert/parse Object to/from JSON.

CBL uses [Jackson](https://github.com/FasterXML/jackson), you can get some ideas from it.

Thanks,
Hideki

**Comment by denebchorny** [comment]
Thanks Sir... I appreciate your help... Have a nice day and thanks again :D
