### ISSUE TITLE
"SQLiteDatabaseCorruptException: database disk image is malformed" occurs frequently while querying a View.

### ISSUE THREAD

**Issue by maheswaranapk** [couchbase/couchbase-lite-android#846]
App getting "SQLiteDatabaseCorruptException" at a particular Scenario.

**Scenario :** 
1  When the App is Launched for First time, A set of 1000 Document get added to the CouchBase.
2  Then Data from the CouchBase is retrieved by querying a view and displayed in a ListView.
Log :
```
> V/View: #1122: map '1122' for view NameView...
> V/View: #1123: map '1123' for view NameView...
> V/View: #1124: map '1124' for view NameView...
> V/View: #1125: map '1125' for view NameView...
> V/Database: CBLManagerWorkExecutor Begin transaction (level 1)
> V/Database: CBLManagerWorkExecutor Committing transaction (level 1)
> V/View: ...Finished re-indexing (NameView) to #1125 (deleted 0, added 0)
> V/Database: CBLManagerWorkExecutor Committing transaction (level 0)
> V/View: Query NameView: SELECT key, value, docid, revs.sequence FROM 'maps_1', revs, docs WHERE 1 AND revs.sequence = 'maps_1'.sequence AND docs.doc_id = revs.doc_id ORDER BY key, docid LIMIT ? OFFSET ? | args: [2147483647, 0]
> D/Database: Query view NameView completed in 1251 milliseconds
```
3  In Background, Sync is enabled and the documents are pushed to the server via sync gateway.
4  Server process the document and append result to each document.
5  Then  changes are pulled to the Device.
6  Once both push and Pull is completed. Same view is queried again to  get all data with changes. 
7  After re-indexing, App crashes with  SQLiteDatabaseCorruptException.

Log :
```
> V/View: #1994: map '1123' for view NameView...
> V/View: #2136: map '1124' for view NameView...
> V/View: #2208: map '1125' for view NameView...
> V/Database: main Begin transaction (level 1)
> V/Database: main Committing transaction (level 1)
> V/View: ...Finished re-indexing (NameView) to #2240 (deleted 1115, added 0)
> V/Database: main Committing transaction (level 0)
> V/View: Query NameView: SELECT key, value, docid, revs.sequence FROM 'maps_1', revs, docs WHERE 1 AND revs.sequence = 'maps_1'.sequence AND docs.doc_id = revs.doc_id ORDER BY key, docid LIMIT ? OFFSET ? | args: [2147483647, 0]
> E/SQLiteLog: (11) database corruption at line 64991 of [b3bb660af9]
> E/SQLiteLog: (11) statement aborts at 19: [SELECT key, value, docid, revs.sequence FROM 'maps_1', revs, docs WHERE 1 AND revs.sequence = 'maps_1'.sequence AND docs.doc_id = revs.doc_id ORDER BY key, docid LIMIT ? OFFSET ?] data
> D/AndroidRuntime: Shutting down VM

> E/AndroidRuntime: FATAL EXCEPTION: main
>                com.couchbase.lite.internal.database.sqlite.exception.SQLiteDatabaseCorruptException: database disk image is malformed (code 11)
>                    at com.couchbase.lite.internal.database.sqlite.SQLiteQueryCursor.nativeMoveToNext(Native Method)
>                    at com.couchbase.lite.internal.database.sqlite.SQLiteQueryCursor.moveToNext(SQLiteQueryCursor.java:58)
.....
>                    at com.couchbase.lite.Query.run(Query.java:433)
```
Once this Exception is raised, then continue until App Data is cleared.

Queries : 
1. What are the cases/Scenario in which SQLiteDatabaseCorruptException is possible ?
2. Is there any best practices need to be followed to avoid this Exception ?
3. Is there any limit for View Index size ?

**Comment by hideki** [comment]
Hi @maheswaranapk,

This is normal scenario. Currently I don't know what causes `SQLiteDatabaseCorruptException`. According to the Java Doc, database is corrupt.
http://developer.android.com/reference/android/database/sqlite/SQLiteDatabaseCorruptException.html
```
An exception that indicates that the SQLite database file is corrupt.
```

> 1. What are the cases/Scenario in which SQLiteDatabaseCorruptException is possible ?

I have never encountered SQLiteDatabaseCorruptException before.

> 2. Is there any best practices need to be followed to avoid this Exception ?

Also, I don't know.

> 3. Is there any limit for View Index size ?

Unlimited (depends on Android disk size)

**Comment by hideki** [comment]
Hi @maheswaranapk 
This is really critical issue. It seems you have encountered this issue constantly. But we don't know what causes problem. Don't you mind to write simple app to reproduce this issue?
Thanks!
Hideki

**Comment by maheswaranapk** [comment]
Hi @hideki, 
Thanks for the answering my queries.

The actual problem is the Sample set of Data what I used as Key in View Emitter. It has some non Alpha numeric Characters. [Actually we are processing Contact Detail in Phones and we use Contact name as Key for View. Some Contact names are in different format or font.]

Currently I had put the validation and avoiding this issue. We had done a complete set of testing and we cant able to reproduce it.

Now, I am not focusing on which type of data caused the issue. I will do soon. once I found the reason, I will update here.  

Once again Thank you so much for the answers and after that I can look at the problem in different way.

**Comment by hideki** [comment]
@maheswaranapk Thank you for your update!

**Comment by zgramana** [comment]
@maheswaranapk please reopen if this comes up again.

**Comment by poulsp** [comment]
Hi,
It is a really critical issue. I use the Danish character set with 'øæåÆØÅ', and CB Lite is useless with this problem.

You can reproduce this issue with the GrocerySync-Android Demo app.

Changes the emitter in the view definition to:

	Object text = (String) document.get("text");
	Object check = (Boolean)document.get("check");
	if (text != null) {
	    List<Object> key = new ArrayList<Object>();
	    key.add(check);
	    key.add(text.toString());
	    emitter.emit(key, null);
	}

Insert 20 documents: æøå:20
click on the items a few times.

**Comment by kombadzomba** [comment]
I got the same error. The scenario is the following: 

The document is:

`{
   "_id": "4e48a10c-d93a-40c3-b110-f5680f598a20",
   "_rev": "2-a36c405ead111918b2df2b7c09ba4a59",
   "time_create": "2016-05-25T08:32:55.352Z",
   "shortcut": "BT",
   "duration_min": 30,
   "color": "#ffffc107",
   "name": "But the most important thing in the right ↪ the same as a reference to the receipt for the first to review my resume for the first to review my own ",
   "time_update": "2016-05-26T01:49:29.599Z",
   "type": "service"
}`

I add a new field:
`"time_delete":` "2016-05-26T01:49:29.598Z"`

and then save the document.

After that, when quering a view that emits this document with field 'name' as key I get: 

> com.couchbase.lite.internal.database.sqlite.exception.SQLiteDatabaseCorruptException: database disk image is malformed (code 11)

It seems that ↪ char in the name field causes this crash. 

I have to emphasize that this is the very critical bug for our business. It is a blocker for our app and we lose users!!! They can not see any data after this crash! The damage is irreversible. The database remains corrupted forever. The only solution right now is to completely uninstall the app and then sync the data with the server again and eventually get the same crash if they add special characters.

**Comment by kombadzomba** [comment]
Here is another example of name field content that causes the database corruption:
`"name": "Torte i 🍪 i 🐷"`

**Comment by kombadzomba** [comment]
Hi @hideki,

[Here](https://gist.github.com/401849e215fc5e2bb07c54f648fcda55) you can find test case testSerbianClientNameQuery() that doesn't pass.

Hope this helps.

**Comment by hideki** [comment]
@kombadzomba Thank you very much for providing test. I might be able to look into the issue next week.

**Comment by ashihaby** [comment]
I have fixed it in this pull request couchbase/couchbase-lite-java-core#1246 
@hideki Please check

**Comment by hideki** [comment]
Hi @kombadzomba,

I ported your test case into our unit tests. I could observe test failure, but I can not see `SQLiteDatabaseCorruptException`.  I guess there is a condition we don't know to cause `SQLiteDatabaseCorruptException` such as Android OS version or Language setting of Android. Could you please share your test condition?

Test codes: https://github.com/couchbase/couchbase-lite-android/commit/fbde5d774a05a338afe861de2f00da7838aded0b

**Comment by hideki** [comment]
Note to Self:

Instead of `UTF-8`, by using `UTF-16` query could be matched. It seems String encoding does not match between `UTF-8` and `UTF-16`.

**Comment by hideki** [comment]
### What might be happened internally
In case non-Ascii characters are emitted as a key, invalid memory access could be occurred in the custom collator because of not NULL terminated string. For ASCII characters, calling different method, it does not cause invalid memory access. Because of invalid memory access in native codes, app could crashed and SQLite database operation is terminated in middle of any operation. When app is restarted, SQLite codes throws `SQLiteDatabaseCorruptException` because of in-appropriate termination of SQLite.

For my environment, I could not reproduce the `SQLiteDatabaseCorruptException` issue coincidently. However I could observed Non-NULL terminated string, and string matching always fails because of non-NULL terminated string.

**Comment by hideki** [comment]
Hi All,

Following is built from latest master branch which includes the fix. If you have time, could you please try? If `SQLiteDatabaseCorruptException` issue is still reproducible, please let us know!
http://files.couchbase.com/maven2/com/couchbase/lite/couchbase-lite-android/0.0.0-724/

Thanks!

**Comment by poulsp** [comment]
It works!
Perfect, Great job.

Thanks.

**Comment by kombadzomba** [comment]
We couldn't reproduce SQLiteDatabaseCorruptException with this fix which is good. Good job!

However, we had some other issues regarding pull replication with this 0.0.0-724 library (not pulling all the docs) but I guess that will be fine with 1.3. We are looking forward for that version. Do you have the release date for it? We are using internal patch for UTF-8 keys until that. The patch is based on mapping all the keys and query ranges to ASCII charset and additional filtering on the query results.

Thanks.

**Comment by Takhion** [comment]
We're still getting this when upgrading from 1.1 to 1.3:
```
com.couchbase.lite.internal.database.sqlite.exception.SQLiteDatabaseCorruptException: database disk image is malformed (code 11)
  at com.couchbase.lite.internal.database.sqlite.SQLiteQueryCursor.nativeMoveToNext(Native Method)
  at com.couchbase.lite.internal.database.sqlite.SQLiteQueryCursor.moveToNext(SQLiteQueryCursor.java:58)
  at com.couchbase.lite.storage.SQLiteStorageEngineBase$SQLiteCursor.moveToNext(SQLiteStorageEngineBase.java:257)
  at com.couchbase.lite.DatabaseUpgrade.importDoc(DatabaseUpgrade.java:223)
  at com.couchbase.lite.DatabaseUpgrade.access$000(DatabaseUpgrade.java:38)
  at com.couchbase.lite.DatabaseUpgrade$1.run(DatabaseUpgrade.java:118)
  at com.couchbase.lite.store.SQLiteStore.runInTransaction(SQLiteStore.java:717)
  at com.couchbase.lite.Database.runInTransaction(Database.java:565)
  at com.couchbase.lite.DatabaseUpgrade.importData(DatabaseUpgrade.java:111)
  at com.couchbase.lite.Manager.upgradeDatabase(Manager.java:839)
  at com.couchbase.lite.Manager.upgradeOldDatabaseFiles(Manager.java:817)
  at com.couchbase.lite.Manager.<init>(Manager.java:130)
  ...
  at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
  at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4730)
  at android.app.ActivityThread.access$1600(ActivityThread.java:175)
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1368)
  at android.os.Handler.dispatchMessage(Handler.java:102)
  at android.os.Looper.loop(Looper.java:146)
  at android.app.ActivityThread.main(ActivityThread.java:5602)
  at java.lang.reflect.Method.invokeNative(Native Method)
  at java.lang.reflect.Method.invoke(Method.java:515)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
```

**Comment by hideki** [comment]
@Takhion,
I have some questions.
1) Is this root cause of #888? 
2) Is this 100% reproducible?

**Comment by hideki** [comment]
@Takhion,
Don't you mind to file new ticket with detail steps to reproduce?
As unit test covers simple database migration from 1.x to latest, so I think there is special condition to reproduce the issue.
Thanks!

**Comment by hideki** [comment]
Ref: #985 - SQLiteDatabaseCorruptException: database disk image is malformed (code 11)

**Comment by hideki** [comment]
Hi @maheswaranapk, @poulsp, @kombadzomba, and @ashihaby,

I am working for #985 which is another `SQLiteDatabaseCorruptException` issue. But we are no idea what causes database corruption. Currently I am wondering if [the fix for this issue](https://github.com/couchbase/couchbase-lite-java-native/commit/bbfdf5ba922a39b684833a3c82e67a6064cf26d9) is not sufficient. Have you ever observed `SQLiteDatabaseCorruptException` again after we had addressed this issue? If yes, can you share your experience?

Thanks,
Hideki

**Comment by kombadzomba** [comment]
Hi @hideki,

We don't get SQLiteDatabaseCorruptException neither with 1.3.0 nor 1.3.1-30.

**Comment by hideki** [comment]
@kombadzomba Thank you for your reply.
