### ISSUE TITLE
Attachment content lengths set to 0, causes iOS replication to fail

### ISSUE THREAD

**Issue by tikimcfee** [couchbase/couchbase-lite-android#849]
We have an issue with the Android CBLite lib related to corrupted attachment metadata. Following synchronization the server side will have the attachment length attribute on most or all attachments changed 0. To date all examples of this seem to have manifest on a conflict revision, with both the base document and the bodymap impacted. In other words, if Android wins a conflict, the base document has the length attributes zeroed. If Android loses, the bodymap length attributes are zeroed. In no case are the attachments lost or actually themselves zero length. In fact, you can GET the documents from the Sync Gateway and the Content-Length header is correct and the attachment is in tact.

This is occurring with CBLite 1.1.0 (com.couchbase.lite:couchbase-lite-android:1.1.0).

When the problem manifests iOS continuous replication cannot succeed, and this is impacting production customers making this a blocking issue for us.

We will file a separate ticket on the iOS replication failure, because on Android, an initial synchronization with OneShot replication seems to bypass these bad content lengths, and switching to continuous replication then seems to work.

We do not have clear reproduction steps on this, but we have have tens of examples of these documents, and they all impact iOS significantly. Simple conflict resolution does not always resolve the issue, because of the cases where Android has won and the tip revision has length attributes set to zero. We currently have to try to strip and re-attach attachments in order to try to correct lengths.

We are hoping there is a hotfix for this, because the 1.2.0/1.2.1 branches are not yet candidates for us on Android due to open issues (#797, #686).

**Comment by tikimcfee** [comment]
We just found this report of a similar (same?) problem in the CouchBase forums, wherein the stack trace shows 'incorrect field length of 0'.
https://forums.couchbase.com/t/bulk-download-causes-trouble/7917
https://forums.couchbase.com/t/couchbase-lite-attachments-syncing/7918/3

**Comment by hideki** [comment]
ref: https://github.com/couchbase/couchbase-lite-ios/issues/1218

**Comment by hideki** [comment]
I guess given attachment size is 0.

https://github.com/couchbase/couchbase-lite-java-core/blob/release/1.1.0/src/main/java/com/couchbase/lite/BlobStoreWriter.java#L77-L96

**Comment by tikimcfee** [comment]
Hey there guys. Has there been any traction gained on this issue, or the similar occurrences documented on the forums? Really hoping for some more information about this, as it's something that's actively corrupting customer data and is taking considerable amounts of time to manually attempt corrections.

**Comment by hideki** [comment]
@tikimcfee, you wrote this issue is intermittently happens with v1.1.0. From the code review point of view, I believe attachment size is set 0 in case attachment size is 0. We also don't have enough information. Could you please provide additional information?

**Comment by tikimcfee** [comment]
Everything that we can provide so far is already in this ticket. We have more than one million documents in production and only a handful of them show this issue. However, those singular documents in a user's channel are enough to entirely stop synchronization for iOS CBLite.

In terms of the codebase, you mention that the attachment size is set to 0 when the attachment size is 0. After looking through the current code base for 1.1.0, there are a number of error scenarios where the default value is 0, or on error, is set to zero. For example, BlobStoreWriter.java defaults to 0 and increments only on read(). If it fails, it does not retry or otherwise fail writing an attachment - the exception is just caught and the flow continues; following it is a metadata put of "length" : 0.

**Comment by lightandshadow68** [comment]
We know the offending documents have an attachment length that is not zero since, when the replicator stalls on iOS, the client reports the actual length of the attachment in the warning log output. Also, dumping attachments to disk and re-attaching them on server corrects the attachment length and iOS clients can sync. 

```
Apr 20 11:55:28 Pixel-iPhone App Name[xxxxx] <Warning>: WARNING: CBLMultipartDocumentReader[_id="8effbdee-bf15-49f6-b924-d8ba44c82ddf"]: Attachment 'objective' has incorrect length field 0 (should be 9767)
Apr 20 11:55:28 Pixel-iPhone App Name[xxxxx] <Warning>: SyncSession: active=0; mode=2; 0/0; 502 Invalid response from remote replication server
```
See...

https://github.com/couchbase/couchbase-lite-ios/issues/1218

**Comment by hideki** [comment]
Hi @tikimcfee and @lightandshadow68,

> In terms of the codebase, you mention that the attachment size is set to 0 when the attachment size is 0. After looking through the current code base for 1.1.0, there are a number of error scenarios where the default value is 0, or on error, is set to zero. For example, BlobStoreWriter.java defaults to 0 and increments only on read(). If it fails, it does not retry or otherwise fail writing an attachment - the exception is just caught and the flow continues; following it is a metadata put of "length" : 0.

As you wrote, default value is 0. But, in case error occurs, it throws IOException. 
https://github.com/couchbase/couchbase-lite-java-core/blob/release/1.1.0/src/main/java/com/couchbase/lite/BlobStoreWriter.java#L66-L96

And IOException is caught in `Attachment.installAttachmentBodies()`, and it throws `CouchbaseLiteException`.
https://github.com/couchbase/couchbase-lite-java-core/blob/release/1.1.0/src/main/java/com/couchbase/lite/Attachment.java#L237-L241

However, from iOS log message, attachment data is correct, but `"length"` value is `0`. I believe error is something else. 

Can you provide us small sample app to reproduce this issue?

Thanks!

**Comment by tikimcfee** [comment]
Thanks for the reply. As mentioned in the initial issue comment:

> We do not have clear reproduction steps on this, but we have have tens of examples of these documents, and they all impact iOS significantly.

Unfortunately, this is something that continues to happen some 28 days later. We still have customers that are failing to sync on iOS, and we still have to spend 30 minutes to multiple hours doing manual labor to fix this attachment issue every time the library fails to save an attachment correctly. Has there been any more time put into this issue, or perhaps a branch we can track changes on?

**Comment by hideki** [comment]
@tikimcfee, I understand your frustration. However, without additional information, it is really hard to identify the problem.

**Comment by tikimcfee** [comment]
We have not been able to reproduce this on our side in any way. Every instance we have of this are remote clients that we troll our sync gateway logs for. If we are able to provide these, which are set to maximum, with a given set of timestamps, would you be able to diagnose this issue?

Also posting this alongside https://github.com/couchbase/couchbase-lite-ios/issues/1218, https://forums.couchbase.com/t/couchbase-lite-attachments-syncing/7918/3

**Comment by hideki** [comment]
this issue might be caused by the parsing JSON issue. According to the https://github.com/couchbase/couchbase-lite-java-core/issues/1379, the `length` field could be parsed as `Double` instead of `Integer`.
