### ISSUE TITLE
changesFeedPOSTBodyMap NPE

### ISSUE THREAD

**Issue by mtrakal** [couchbase/couchbase-lite-android#853]
I get this NPE in latest:

```
 compile 'com.couchbase.lite:couchbase-lite-android:0.0.0-687'
 compile 'com.couchbase.lite:couchbase-lite-android-forestdb:0.0.0-687'
```

```
 java.lang.NullPointerException: Attempt to invoke interface method 'int java.util.Map.size()' on a null object reference
  at java.util.HashMap.putAll(HashMap.java:502)
  at com.couchbase.lite.replicator.ChangeTracker.changesFeedPOSTBodyMap(ChangeTracker.java:672)
  at com.couchbase.lite.replicator.ChangeTracker.changesFeedPOSTBody(ChangeTracker.java:630)
  at com.couchbase.lite.replicator.ChangeTracker.runLoop(ChangeTracker.java:314)
  at com.couchbase.lite.replicator.ChangeTracker.run(ChangeTracker.java:241)
  at java.lang.Thread.run(Thread.java:818)
```

I have bad connection (testing on proxy, when no response from server, proxy drop all packets), application wait for some response and stuck for 30s on timeout on couchDB request on replication.

After I close app, try to start again and get this exception and app crash.

**Comment by hideki** [comment]
Note to Self:

It seems `filterParams` is `null`.
- changesFeedPOSTBodyMap()
```java
        if (filterName != null) {
            post.put("filter", filterName);
            post.putAll(filterParams);
        }
```

- HashMap
```java
    @Override public void putAll(Map<? extends K, ? extends V> map) {
        ensureCapacity(map.size());
        super.putAll(map);
    }
```
https://android.googlesource.com/platform/libcore.git/+/android-3.2.4_r1/luni/src/main/java/java/util/HashMap.java#510

**Comment by hideki** [comment]
Fixed in couchbase-lite-java-core: PR https://github.com/couchbase/couchbase-lite-java-core/pull/1220

**Comment by hideki** [comment]
Hi @mtrakal,
If you have a chance, please try http://files.couchbase.com/maven2/com/couchbase/lite/couchbase-lite-android/0.0.0-688/ to verify the fix? Thanks you!

**Comment by mtrakal** [comment]
Same scenario as on 0.0.0-687 (with 687 crash my app), with 688 looks good and app start normally. 

Thanks
