### ISSUE TITLE
Stop/start/restart replication

### ISSUE THREAD

**Issue by npomfret** [couchbase/couchbase-lite-android#856]
I would like to be able to stop / start or restart replication tasks programatically via the rest API.  Is this possible?  Can't find anything in the docs.

**Comment by hideki** [comment]
Hi @npomfret,
I don't know why our REST API doc does not explain `cancel` request parameter.
Please refer: http://docs.couchdb.org/en/stable/api/server/common.html#post--_replicate
CBL Android support `cancel` parameter.
Thanks!

**Comment by npomfret** [comment]
Thanks.
