### ISSUE TITLE
Proper livequery listener

### ISSUE THREAD

**Issue by denebchorny** [couchbase/couchbase-lite-android#872]
Hi sir,

I am doing an Application that serves data from a server. Then, I have 2 fragments. Master and detail. Everytime the user open de MasterFragment the app request a list of items and creates or updates them locally with clb.

As it is known using a normal query and check it for updates manually is not recommended because it could be a false positive o false negative. That's the reason I'm using LiveQuery. The problem is that when there is an update we wouldn't know whitch document changed and the livequery see this change wherever happens, it updates itself.

This is the code I'm using:

```java
LiveQuery mQuery;

// No matter how this procedure works
mQuery = Ticket.getLiveQueryByStatus(idTechnician
                        , DatabaseWrapper.getDatabase()
                        , Ticket.ASSIGNED
                        , Ticket.OPENED
                        , Ticket.IN_PROGRESS
                        , Ticket.ON_PAUSE
                        , Ticket.FINISHED);

// Change listener
mQuery.addChangeListener(new LiveQuery.ChangeListener() {
            @Override
            public void changed(final LiveQuery.ChangeEvent event) {
                 // This function just update the enumerator from the adapter.
                displayRows(event.getRows());
                ((AppCompatActivity) 

// TicketLiveQueryRecyclerAdapter this is the class
TicketLiveQueryRecyclerAdapter.this.mContext).runOnUiThread(new Runnable() {
                    @Override
                    public void run() {
                        notifyDataSetChanged();
                    }
                });
            }
        });
        mQuery.start();
```

As the livequery execute the "addlistener" the performance of the application could falls. Imagine this, the application requests data and receive 10 items, this mean that every time the user go back to MasterFragment the application requests again the items and there will be 10 documents updated. Then, the livequery is going to do notifyDataSetChanged(), ten times?. Even worst, imagine tha the app receive 100 documents then  is the livequery going to execute 100 times notifyDataSetChanged?

Is there a way to notify once after I updates all the documents? something like, IDK, this?:

```java
// before update
livequery.stop()
... 

update documents

...
after update
livequery.start()
```

could this work?

thanks in advance

**Comment by hideki** [comment]
LiveQuery listens `Database.ChangeEvent`. So notification is sent whenever Database.ChangeEvent is fired. If you insert 100 documents separately, you could receive notification 100 times.

Your sudo code might not work as you expected.

During LiveQuery is stopping, event would not be fired.

**Comment by denebchorny** [comment]
Is there a way to save abd update documents in batch?

**Comment by hideki** [comment]
Please store/update data in Transaction by using `Database.runInTransaction()`

**Comment by denebchorny** [comment]
Thanks sir. Let me read about it. Is there any example?... I will find one :D...
