### ISSUE TITLE
Push Replication Issue(tested with 0.0.0-688  build version)

### ISSUE THREAD

**Issue by prasannakumark** [couchbase/couchbase-lite-android#873]
Hi All,
I am facing very big issue relating to push replication, i made changes in some of the documents and also i created some documents but it is not pushing to server with any information. I think push replication issue. I've tested using this libraries http://latestbuilds.hq.couchbase.com/couchbase-lite-android/0.0.0/0.0.0-688/. Please let know the how i can solve that problem and if you need information/clarifications.

Thanks
Prasanna Kumar

**Comment by hideki** [comment]
Hi @prasannakumark,
Could you please provide more detailed information?

**Comment by hideki** [comment]
Hi @prasannakumark,
As we don't get additional information, I will close this ticket. If you are still facing this issue, please reopen the ticket.
