### ISSUE TITLE
App crash after losing network connection

### ISSUE THREAD

**Issue by npomfret** [couchbase/couchbase-lite-android#875]
Shortly after my app lost a network connection it died completely with a java.lang.NullPointerException:

```
E/AndroidRuntime: FATAL EXCEPTION: ChangeTracker-http://139.59.180.64:4984/sync_gateway
 Process: com.pomochat, PID: 5249
 java.lang.NullPointerException: Attempt to invoke virtual method 'com.couchbase.lite.Manager com.couchbase.lite.Database.getManager()' on a null object reference
     at com.couchbase.lite.replicator.PullerInternal.getUserAgent(PullerInternal.java:1122)
     at com.couchbase.lite.replicator.ChangeTracker.runLoop(ChangeTracker.java:263)
     at com.couchbase.lite.replicator.ChangeTracker.run(ChangeTracker.java:226)
     at java.lang.Thread.run(Thread.java:818)
```

As far as I can tell, internally my app was attempting to restart a 2-way synchronisation. But I didn't get any more log messages before the app stopped.

Using v1.2

**Comment by hideki** [comment]
Hi @npomfret,
Could you please provide more detailed information?

**Comment by hideki** [comment]
As master branch version of CBL does not use `Database.getManager()` from ChangeTracker. By upgrade to latest (1.2.1), this issue should be addressed.
