### ISSUE TITLE
E/SQLiteLog: (283) recovered 164 frames from WAL file

### ISSUE THREAD

**Issue by yokei15** [couchbase/couchbase-lite-android#886]
Hi,
Am facing this type of error,
E/SQLiteLog: (283) recovered 164 frames from WAL file /data/data/com.example.android/files/couchbaseevents.cblite2/db.sqlite3-wal

**Comment by hideki** [comment]
Hi @yokei15,
Could you please provide us more detailed information. How to reproduce, version number of CBL and Android API, etc.

**Comment by hideki** [comment]
Hi @yokei15, 
As we did not get additional information, so I will close this ticket. If you still encounter this issue, please reopen the ticket. Thanks!
