### ISSUE TITLE
Missing docs

### ISSUE THREAD

**Issue by npomfret** [couchbase/couchbase-lite-android#899]
I'm using android build 0.0.0-710, running on an emulator with android 4.3. This bug (if it is a bug) is intermittent, I'm not sure of the steps to reproduce it. (Apologies if this is a duplicate, I'm sure I've logged a bug about this before but have managed to lose it)

I have this user:

![screen shot 2016-06-11 at 10 46 54](https://cloud.githubusercontent.com/assets/5489469/15984418/dcc18ea4-2fc1-11e6-972a-07bb80ea4ef2.png)

Who has access to channel `ch_private_b20cd233-567a-4009-938c-08f0dde18f2e`.

This document `a20c0366d433ffed3f5ba0fc6e4a5ee6` is in that channel:

![screen shot 2016-06-11 at 10 48 13](https://cloud.githubusercontent.com/assets/5489469/15984424/098b1b8a-2fc2-11e6-955d-c1ecbdbc3bea.png)

But the document is not in that users CBL database:

![screen shot 2016-06-11 at 10 49 47](https://cloud.githubusercontent.com/assets/5489469/15984429/439c8f20-2fc2-11e6-91a6-deafd43c3312.png)

However, it is in that user's sync-gateway changes feed:

![screen shot 2016-06-11 at 10 51 00](https://cloud.githubusercontent.com/assets/5489469/15984434/6beb2a72-2fc2-11e6-8097-9003e7ea9655.png)

I have bi-directional sync set up, and both tasks are running - I log out the details when the app starts:

![screen shot 2016-06-11 at 10 54 12](https://cloud.githubusercontent.com/assets/5489469/15984444/e3be9138-2fc2-11e6-9e64-9acafd199beb.png)

Have I missed something? Is there something else I should check for?

**Comment by jamiltz** [comment]
Can you confirm if this is the same issue as https://github.com/couchbase/couchbase-lite-android/issues/890?

**Comment by npomfret** [comment]
Sorry, yes same issue - I'll close this one.
