### ISSUE TITLE
[Release 1.2.1] Database upgrades 1.1 -> 1.2.1 not copying "content_type" of attachments during upgrade

### ISSUE THREAD

**Issue by tikimcfee** [couchbase/couchbase-lite-android#900]
Hey there folks,

We're testing the latest released version of 1.2.1 and attempting to get some developmental versions running with it. While testing the upgrade cycle from 1.1.0 to 1.2.1, I noticed that document attachments are not properly copying over the "content_type" during DB upgrade. _All_ of the documents with attachments tested on this are missing that metadata.

We have places in our code where we check said content_type, but is now returning a _null_ string and crashing out our string comparisons from an NPE.

Is this a known issue with the current release?

To reproduce this:
1. Synchronize an initial database from any sync gateway with any number of image attachments > 2 on as many documents as you'd like. **It is not yet known if this happens only for image attachments.**
2. Completely close your application, change your dependencies to start using the 1.2.1 release branch build, and let the database upgrade complete.
3. Find a document with one of the attachments synchronized initially. Check its content type with Document.getAttachment("someAttachmentName").getContentType();
4. The content type is null.

**Comment by tikimcfee** [comment]
Side note, just confirmed that creating documents and adding attachments to them sets and persists the content_type correctly in 1.2.1.

**Comment by tikimcfee** [comment]
Looking through the codebase, we see:

String sql = "SELECT filename, key, type, length," +
        " revpos, encoding, encoded_length FROM attachments WHERE sequence=?";
String[] args = {String.valueOf(sequence)};
Cursor cursor = storageEngine.rawQuery(sql, args);
try {
    cursor.moveToNext();
    while (!cursor.isAfterLast()) {
        String name = cursor.getString(0);
        byte[] key = cursor.getBlob(1);
        String mimeType = cursor.getString(2);
        long length = cursor.getLong(3);
        int revpos = cursor.getInt(4);
        int encoding = cursor.getInt(5);
        long encodingLength = cursor.getLong(6);

        BlobKey blobKey = new BlobKey(key);
        String digest = blobKey.base64Digest();

        Map<String, Object> att = new HashMap<String, Object>();
        att.put("type", mimeType);
        att.put("digest", digest);
        att.put("length", length);
        att.put("revpos", revpos);
        att.put("follows", true);
        att.put("encoding", AttachmentInternal.AttachmentEncoding.values()[encoding] ==
                AttachmentInternal.AttachmentEncoding.AttachmentEncodingGZIP ?
                "gzip" : null);
        att.put("encoded_length", AttachmentInternal.AttachmentEncoding.values()[encoding] ==
                AttachmentInternal.AttachmentEncoding.AttachmentEncodingGZIP ?
                encodingLength : null);

        attachments.put(name, att);
        cursor.moveToNext();
    }
} finally {
    if (cursor != null)
        cursor.close();
}

calling out:
`
String sql = "SELECT filename, key, type, length," +
        " revpos, encoding, encoded_length FROM attachments WHERE sequence=?";
`
and
`
att.put("type", mimeType);
`

Should that instead be:
`
String sql = "SELECT filename, key, content_type, length," +
        " revpos, encoding, encoded_length FROM attachments WHERE sequence=?";
`
and
`
att.put("content_type", mimeType);
`

**Comment by tikimcfee** [comment]
Going through the code in debug mode, seeing these lines:

```
String sql = "SELECT filename, key, type, length," +
                " revpos, encoding, encoded_length FROM attachments WHERE sequence=?";
        String[] args = {String.valueOf(sequence)};
        Cursor cursor = storageEngine.rawQuery(sql, args);
        try {
            cursor.moveToNext();
            while (!cursor.isAfterLast()) {
                String name = cursor.getString(0);
                byte[] key = cursor.getBlob(1);
                String mimeType = cursor.getString(2);
                long length = cursor.getLong(3);
                int revpos = cursor.getInt(4);
                int encoding = cursor.getInt(5);
                long encodingLength = cursor.getLong(6);

                BlobKey blobKey = new BlobKey(key);
                String digest = blobKey.base64Digest();

                Map<String, Object> att = new HashMap<String, Object>();
                att.put("type", mimeType);
                att.put("digest", digest);
                att.put("length", length);
                att.put("revpos", revpos);
                att.put("follows", true);
                att.put("encoding", AttachmentInternal.AttachmentEncoding.values()[encoding] ==
                        AttachmentInternal.AttachmentEncoding.AttachmentEncodingGZIP ?
                        "gzip" : null);
                att.put("encoded_length", AttachmentInternal.AttachmentEncoding.values()[encoding] ==
                        AttachmentInternal.AttachmentEncoding.AttachmentEncodingGZIP ?
                        encodingLength : null);

                attachments.put(name, att);
                cursor.moveToNext();
            }
        } finally {
            if (cursor != null)
                cursor.close();
        }
```

at:
```
Map<String, Object> att = new HashMap<String, Object>();
att.put("type", mimeType);
```

should instead be:
```
Map<String, Object> att = new HashMap<String, Object>();
att.put("content_type", mimeType);
```

since later in:
```
db.forceInsert(rev, history, null);
```

the Attachment model class is used, which does not have a 'type' field.

**Comment by tikimcfee** [comment]
In AttachmentInternal, constructor:
```
public AttachmentInternal(String name, Map<String, Object> attachInfo)
```

**Comment by hideki** [comment]
@tikimcfee,
Thank you very much for catching this. As you wrote, there is name mismatching. AttachmentInternal class expects `content_type`, but DatabaseUpgrade class store into `type`.

**Comment by snej** [comment]
This mistake is in the Objective-C codebase too. Will need to fix it there.
