### ISSUE TITLE
WAL does not prevent SQLiteConnectionPool Lock on 1.2.1

### ISSUE THREAD

**Issue by tikimcfee** [couchbase/couchbase-lite-android#902]
Hey guys,

As mentioned in the last comment in #854, the current 1.2.1 code with the WAL SQLite open change still causes the SQLiteConnectionPool to lock.

The thread dump for our current locks is in this gist: https://gist.github.com/tikimcfee/bbaf1b01e2bf0a5113893ecdf3aff94e

The log lines are

```
 W/database: SQLiteConnectionPool: The connection pool for database '/data/data/our.app.package.name/files/ourDB.cblite2/db.sqlite3' has been unable to grant a connection to thread 1653 (CBLReplicationWorker) with flags 0x2 for 120.003006 seconds.
```

The underlying issues with the SQL implementation seem to be related with a general non-thread-safe set of methods within the replicator, database save manager, et al. 

I commented on this issue as well : https://github.com/couchbase/couchbase-lite-java-core/issues/903#issuecomment-224757117

We have been battling these issues ever since our original 1.2.X testing. Has there been _any_ additional work on fixing threading issues in 1.2.1+? Are there fixes incoming?

**Comment by hideki** [comment]
Hi @tikimcfee,

From this thread dump, I can not identify which thread holds SQLite connection. Something unexpected error happens. To debug this issue, could you please capture log message from logcat?

Recently We switched from single SQLite connection to multiple SQLite connections (4 connections total).
couchbase/couchbase-lite-java-core#1222
Could you please try recent build from master branch?

**Comment by tikimcfee** [comment]
In that ticket you mentioned, you might see that we actually forked the **java-core** lib and cherry picked the commit that included the additional WAL flag ( https://github.com/Sightplan/Sightplan-Android-Client/commit/6eea3539e24d6ded825cb35f2efcad68032718c4 ).

It definitely has helped a number of cases, but we still get the log line I posted above

> W/database: SQLiteConnectionPool: The connection pool for database '/data/data/our.app.package.name/files/ourDB.cblite2/db.sqlite3' has been unable to grant a connection to thread 1653 (CBLReplicationWorker) with flags 0x2 for 120.003006 seconds.

We are also now seeing new exceptions thrown from the database:

```
Fatal Exception: com.couchbase.lite.internal.database.sqlite.exception.SQLiteDatabaseLockedException
database is locked (code 5)

com.couchbase.lite.internal.database.sqlite.SQLiteQueryCursor.nativeMoveToNext (SQLiteQueryCursor.java)
com.couchbase.lite.internal.database.sqlite.SQLiteQueryCursor.moveToNext (SQLiteQueryCursor.java:58)
com.couchbase.lite.storage.SQLiteStorageEngineBase$SQLiteCursor.moveToNext (SQLiteStorageEngineBase.java:248)
com.couchbase.lite.util.SQLiteUtils.longForQuery (SQLiteUtils.java:41)
com.couchbase.lite.store.SQLiteStore.getDocNumericID (SQLiteStore.java:2296)
com.couchbase.lite.store.SQLiteStore.getDocument (SQLiteStore.java:699)
com.couchbase.lite.Database.getDocument (Database.java:1338)
com.couchbase.lite.Database.getExistingDocument (Database.java:395)
our.app.cblitedatabase.wrapper.singleton.Database.getDocument (Database.java:289)
```

It looks like there is just a fundamental threading issue with how the replicators and database manager all handle the underlying Android SQLite database. The only way we have mitigated (but not completely solved) this issue is to do the following:

Whenever we want to start doing many saves:
1. Stop every live query in the application (this can be up to 4)
2. Stop every single class that would update itself and query for additional documents when a ChangeEvent is posted from the database
3. Finish all of our saves
4. Re-enable live queries, re-enable other document gets()

**Comment by hideki** [comment]
Hi @tikimcfee,

Latest master branch version and v1.2.x of Couchbase Lite Android with SQLite uses SQLiteDatabase which was ported from Android SDK. SQLiteDatabase takes the connection pool approach. Without WAL enabled (through API), connection pool size is 1. With WAL, size is 4. I believe SQLiteDatabase is thread-safe as SQLiteDatabase is used for long time as part of Android SDK.

From the tread-dump you posted, I could not find which thread holds SQLite connection. I guess one thread could not return the connection to the connection pool by unknown reason. We need to figure out what the root cause is. But currently we don't have enough information to debug this.

About `SQLiteDatabaseLockedException` exception, what version of CBL Android are you using? Build from latest master?

The exception is thrown from native (JNI) library. SQLite error is [SQLITE_BUSY](https://www.sqlite.org/rescode.html#busy) which could be caused by concurrent access to the SQLite database. This could be caused by WAL with multiple SQLite connections that we recently switched to.
```c++
case SQLITE_BUSY:
   exceptionClass = "com/couchbase/lite/internal/database/sqlite/exception/SQLiteDatabaseLockedException";
   break;
```

**Comment by tikimcfee** [comment]
Thanks for taking this on  @hideki - it's been hectic, so we're trying our best to tackle these issues on our end as quickly as we report them.

> I believe SQLiteDatabase is thread-safe as SQLiteDatabase is used for long time as part of Android SDK.

It is indeed thread safe, but only when there is a _single instance of the underlying database_, meaning if you have a customer version of the SQLite engine Android uses but create multiple handles to it, you will lost thread safety. See the Android dev docs related to the [SQLiteOpenHelper](https://developer.android.com/reference/android/database/sqlite/SQLiteOpenHelper.html)

> ...what version of CBL Android are you using? Build from latest master?
We have tried 1.2.1 release, 0.0.0.733 and 0.0.0.738, as well as 1.2.1 with the cherry picked SQLite WAL fixes.

> The exception is thrown from native (JNI) library. 
Yep, that makes sense. See my comment above about the inherent thread UN-safety that having multiple database handles can cause. While we haven't completely combed through the entire **lite-java-core** or **lite-android** releases, we have seen that for the most part, everything seems to be using the same database handle, but it's very hard to confirm this.

The best method of reproduction we can give you is essentially to just overload the database with requests and commands. Here is the state we were / are in when we see these issues:

1. Create an Android HandlerThread and Handler object. Use `Handler.post()` to quickly save updates to many documents at once with single transactions. Something like:
```
while(doMore) {
  handler.post(new Runnable() {
  public void run() {
    someDocument.putProperties(someNewPropertiesMap);
  }
  });
}
```
2. Have a 2 - 4 live queries actively listening to 2 - 4 **different** couchbase views. Make sure they are running.
3. Have a **single** Database listener object that is listening to every Database.ChangeEvent - we do not use DocumentChangeListeners.
4. Have both a Push and Pull replicator pointed at a Sync Gateway instance and attached to the same database that has the above live queries listening for changes, and the same database you are saving revisions to. Make sure the Pull and Pull replicator are alive, and mock out behind the sync gateway a number of documents being created and/or modified.

This above reproduction path invariably lead us to the issue, and as mentioned, we've had to mitigate the issue by essentially turning off all live queries and change-event-spawned document pulls (e.g., Document A points to Document B, so we fetch Document B again once we get Document A's Document.ChangeEvent);

**Comment by hideki** [comment]
@tikimcfee,

Thank you very much for your comment.

In the sample code you posted, `endTransaction()` method is not guaranteed to be called. if exception is thrown by previous methods. Can you make sure `endTransaction()` is called in `try-finally{}` block? or please use [`Database.runInTransaction()`](http://developer.couchbase.com/documentation/mobile/1.2/develop/references/couchbase-lite/couchbase-lite/database/database/index.html#boolean-runintransactionrunintransactiondelegate-delegate).  
Also I am not familier with `HandlerThread` class, I am not sure how it works. If you can, please use [`Database.runAsync()`](http://developer.couchbase.com/documentation/mobile/1.2/develop/references/couchbase-lite/couchbase-lite/database/database/index.html#void-runasyncrunasyncdelegate-delegate). `runAsync()` use single-thread executor to execute the task block.

**Comment by tikimcfee** [comment]
No problem @hideki. A HandlerThread is just a simple, single, serially executed thread offered by the Android SDK that allows you to easily post runnables for commands. We use that in our app, and it is equivalent to the Database.runAsync() call which essentially submits work to a single threaded task block. 

That sample was not meant to be an exact reproduction step. It is just saying, "Hey, do a bunch of repeated transaction operations on a thread." If you want something a little more concrete that follows your advice, this is an example - please note, that this is NOT a case of transactions not being ended by our code.

```
com.couchbase.lite.Database db = Database.getInstance().getCBDatabase();
int toSave = 1000;
final String[] docIdsToSave = new String[toSave]; // Just a bunch of doc ids
// insertDocsIdsIntoArray(docIdsToSave);
for(int i = 0; i < toSave; i++) {
    final int toSavePos = i;
    db.runAsync(new AsyncTask() {
        @Override
        public void run(final com.couchbase.lite.Database database) {
            database.runInTransaction(new TransactionalTask() {
                @Override
                public boolean run() {
                    try {
                        Document d = database.getDocument(docIdsToSave[toSavePos]);
                        Map properties = d.getProperties();
                        properties.put("some_key", "some_value");
                        d.putProperties(properties);
                    }catch (CouchbaseLiteException e) {
                        Log.e("SOME_SAVE_CLASS", "Something Bad Happened.");
                        e.printStackTrace();
                        return false;
                    }
                    return true;
                }
            });
        }
    });
}
```

The above code will still cause the error.

**Comment by hideki** [comment]
@tikimcfee,

http://grepcode.com/file_/repository.grepcode.com/java/ext/com.google.android/android/5.1.1_r1/android/database/sqlite/SQLiteOpenHelper.java/?v=source

`SQLiteOpenHelper` prevents to create multiple `SQLiteDatabase` instances by using `synchronized` keyword. Do you think Couchbase Lite could create multiple instances of `SQLiteDatabase` class?

**Comment by tikimcfee** [comment]
@hideki ,

It seems very unlikely CBLite would create additional instances - we looked through ReplicationInternal, Manager, Database, SQLiteStore/EngineBase, etc. All those classes _seemed_ to share an instance of the database which would be exactly right. Unfortunately, we haven't had the time to go through every flow and make sure that's true.

A thought on the side, though : You mentioned that the **couchbase-lite-java-core** uses a _forked_ implementation of the Android SDK's SQLite implementation. Is it possible any changes you guys needed to make for the CBLite implementation introduced some thread instability? Or, another thought, how often has that underlying SQLite been updated to match current SDK if it has changed?

**Comment by hideki** [comment]
>  thought on the side, though : You mentioned that the couchbase-lite-java-core uses a forked implementation of the Android SDK's SQLite implementation. Is it possible any changes you guys needed to make for the CBLite implementation introduced some thread instability? Or, another thought, how often has that underlying SQLite been updated to match current SDK if it has changed?

History:
- v1.1.x or earlier: CBL uses Android's SQLiteDatabase. (Android's SQLiteDatabase has 2MB/doc limitation).
- v1.2.x: Ported SQLiteDatabase under CBL, and CBL supports Android provided system libsqlite.so, custom libsqlite.so (Couchbase compiled), and SQLCipher library for encrypted database.
- v1.3.x: CBL will drops system libsqlite.so for Android N. Android N does not allow the application to access non private native libraries. Custom SQLite is current default.

About SQLiteDatabase porting:
- We dropped WindowsCursor which is tightly integrated with Android platform. WindowsCursor also causes 2MB/doc limitation.
- no other major changes

We don't frequently update SQLiteDatabase classes which are not frequently updated.

**Comment by tikimcfee** [comment]
@hideki; Hey hey.

Appreciate the history, it gives us some context on the libs we're using. The removal of WindowCursor doesn't seem like a major change. I don't have enough knowledge of the base or custom implementations to give you a review of that, however.

On another note, has the test case pointed out above proven useful yet?

**Comment by tikimcfee** [comment]
@hideki, Hey again, I have some more information for you:

I have tracked down a path in accessing documents that seems to cause this locking to occur almost 100% of the time.

There are two document getters in the Database class - getDocument() and getExistingDocument(). The `getExistingDocument()` call will almost always lock when accessing data asynchronously, while calling `getDocument()` and following with a 'getProperties()' _seems to be_ OK.

The documentation for `getDocument()` says:
```
/**
 * Instantiates a Document object with the given ID.
 * Doesn't touch the on-disk sqliteDb; a document with that ID doesn't
 * even need to exist yet. CBLDocuments are cached, so there will
 * never be more than one instance (in this sqliteDb) at a time with
 * the same documentID.
 * NOTE: the caching described above is not implemented yet
 */
```

The documentation for `getExistingDocument()` says:
```
/**
 * Gets the Document with the given id, or null if it does not exist.
 */
```

Notice that the former documentation mentions that it `doesn't touch the on-disk sqliteDB`; the implementation of that is correct. The document object is simply instantiated with the target database and a given ID. However, the latter mentions nothing about the underlying document store, and accesses it directly with a call flow of:

```
RevisionInternal revisionInternal = getDocument(docID, null, true);
return store.getDocument(docID, revID, withBody);
```

When retrieving doc properties, the call flow is :

```
SavedRevision currentRevision = getCurrentRevision();
... currentRevision.getProperties();
... database.getDocument(getId(), revID, true);
return store.getDocument(docID, revID, withBody);

```

Notice that in the former, the revID is NULL; in the latter, the revID can be null OR not null. That is the biggest difference I can find between these two calls, and it is almost guaranteed that the `getExistingDocument()` call will fail. The *actual* line that is throwing the exception is `long docNumericID = getDocNumericID(docID);`, which uses the `SQLiteUtils` class to do another query against `docs`:

```
SQLiteUtils.longForQuery(storageEngine,
    "SELECT doc_id FROM docs WHERE docid=?",
    new String[]{docID});
```

The only difference between the two AFTER the above returns ends up being 

```
if (revID != null) {
    sql = "SELECT " + cols + " FROM revs WHERE revs.doc_id=? AND revid=? AND json notnull LIMIT 1";
    String[] args = {Long.toString(docNumericID), revID};
    cursor = storageEngine.rawQuery(sql, args);
}
```

vs. 

```
else {
    sql = "SELECT " + cols + " FROM revs WHERE revs.doc_id=? and current=1 and deleted=0 ORDER BY revid DESC LIMIT 1";
    String[] args = {Long.toString(docNumericID)};
    cursor = storageEngine.rawQuery(sql, args);
}

```

This leads to me believe that there is _something_ going on as a result of the different SQL query statements. Thoughts?

**Comment by hideki** [comment]
Hi @tikimcfee, thank you very much for sharing your investigation.

What is trigger to call `Database.getExistingDocument()`? Is listener callbacks from CBL?

**Comment by tikimcfee** [comment]
@hideki : There are some cases where that is the case. For example, that ends up being called after a replication change event, or after a database change event in a number of our classes. In other cases, it is a call we make ourselves to build a UI around the data. I think it's safe to assume that the **_majority_** of the exceptions come from the first case - when it is called from a listener callback - but it does not seem to be **_all_**.

**Comment by hideki** [comment]
For pull replication, CBL uses transaction to improve the performance. Between calling `beginTransaction()` and `endTransaction()`, SQLite Connection is held by the pull replicator. Without enabling WAL through API, connection-pool size is one. So other threads can not obtain SQLite Connection. Case 1 & 2 (Replicator & Database Listener callbacks) during pull replication with large data set, I believe `SQLiteDatabaseLockedException` is not avoidable without WAL through API.

For other cases, we needs to keep investigating.

**Comment by tikimcfee** [comment]
Thanks for the info. I'm a little confused, though - you're saying without WAL that's likely to happen, but we *are* using the WAL change. Are you saying that even *with* WAL, you do not have confidence in the thread safety of the SQLite store?

**Comment by hideki** [comment]
[WAL](https://www.sqlite.org/wal.html) is SQLite feature. WAL is independent from Connection Pool which is implemented in SQLiteDatabase. Till CBL v1.2, CBL enables WAL by SQL. From CBL v1.3, CBL enables WAL through [`SQLiteDatabase.enableWriteAheadLogging()`](https://developer.android.com/reference/android/database/sqlite/SQLiteDatabase.html#enableWriteAheadLogging()) which makes connection pool size 4.

Thread-safety and WAL is independent. SQLiteDatabase provides Thread-safety by connection pool. By calling `enableWriteAheadLogging()`, SQLiteDatabase changes connection pool size to 4. So multiple threads accessing SQLite concurrently. But writer is still one, so no multiple writer.

**Comment by tikimcfee** [comment]
@hideki Hey again!

Just giving a heads up for now. So for the last few days, we've been working on a test app for you guys to get this issue hard-reproduced. It's a minor reworking of the GrocerySync sample app, and should be fairly easy to get up and running with a little instruction on the super basic configuration.

The sample app represents pretty much every example of our thread usage around the CBLite database. We plan to include a few logs from our test runs as well, hopefully giving a little pre-flight info.

We're not quite yet ready to get it shipped over your way yet, as we're also trying our best to target https://github.com/couchbase/couchbase-lite-android/issues/849 as well, our biggest issue so far. We haven't yet replicated that in the sample app, but will ping you if/when we do.

To get this rolling, what would be the best way to get this over to you? A private repository? Simple email? Let us know and we'll start getting it worked out.

**Comment by hideki** [comment]
Hi @tikimcfee,

Thank you very much for helping Couchbase Lite to be great product.

If you can share it publicly, sharing sample app public repo is easiest.
If it includes private information, we are fine with both private repo or sending me by email. my email address is `hideki at couchbase dot com`.

Thanks again!!
Hideki

**Comment by hideki** [comment]
https://github.com/couchbase/couchbase-lite-android/issues/929#issuecomment-234795097
https://github.com/couchbase/couchbase-lite-android/issues/929#issuecomment-234795516

**Comment by hideki** [comment]
@tikimcfee, 
Do you have any updates about this tickets? Can you still observe this issue with v1.3.1?
Thanks!

**Comment by djpongh** [comment]
Haven't heard anything se we'll assume (and hope) the issue has been fixed. Feel free to reopen if that's not the case.
