### ISSUE TITLE
java.lang.ClassCastException: java.util.HashMap cannot be cast to com.couchbase.lite.Document

### ISSUE THREAD

**Issue by Ruturajraval** [couchbase/couchbase-lite-android#904]
I have done coding as given below,

```java
QueryOptions options = new QueryOptions();
Document retrievedDocument = null;

try {
    retrievedDocument = (Document) database.getAllDocs(options);
} catch (CouchbaseLiteException e) {
    e.printStackTrace();
}


List<String> expectedRows = new ArrayList<>();

for (int i = 0; i <= database.getDocumentCount(); i++) {
    if (retrievedDocument != null) {
        expectedRows.add(String.valueOf(retrievedDocument.getProperties()));
    }
}

ArrayAdapter<String> adapter = new ArrayAdapter<>(this, R.layout.listview_layout, expectedRows);

lvGroup.setAdapter(adapter);
```

And here I get the error of **java.lang.ClassCastException: java.util.HashMap cannot be cast to com.couchbase.lite.Document**

in **retrievedDocument = (Document) database.getAllDocs(options);** line.

Please give me the solution Thanks.

**Comment by hideki** [comment]
Hi @Ruturajraval,

I believe [Getting Start - Query]( http://developer.couchbase.com/documentation/mobile/1.2/get-started/query-sorting/index.html#story-h2-2) could help you.

**Comment by hideki** [comment]
For questions, I recommend you to use Couchbase Forum with Mobile tag. https://forums.couchbase.com/c/mobile

**Comment by Ruturajraval** [comment]
The solution is

I have to write 

> Map<String, Object> retrievedDocument = database.getAllDocs(options);

instead of writing,

> Document retrievedDocument = (Document) database.getAllDocs(options);

@hideki
