### ISSUE TITLE
Excessive logging

### ISSUE THREAD

**Issue by npomfret** [couchbase/couchbase-lite-android#932]
I'm sees 1000's of these messages in the logs using 1.3.0-8.

`W/Router: Cannot add Content-Type header because getResHeader() returned null`

**Comment by hideki** [comment]
I think debugging log message remains with incorrect Log level. I will fix by 1.3.0 release. Thank you.

**Comment by npomfret** [comment]
![screen shot 2016-07-05 at 18 01 34](https://cloud.githubusercontent.com/assets/5489469/16592872/9735d08a-42da-11e6-9bef-00e0bb7cc00f.png)

**Comment by pasin** [comment]
This is a regression from the incorrect if check.

https://github.com/couchbase/couchbase-lite-java-core/commit/b8d11b40083ce6ec3d717fbfd4669e1cf304ed82#diff-34d6c6091cbd2b4d22c6e2c5a274f76cR741

**Comment by pasin** [comment]
I will fix the issue today.
