### ISSUE TITLE
Failed to resolve

### ISSUE THREAD

**Issue by iCRG** [couchbase/couchbase-lite-android#934]
Hi All,

 Greate new for  v1.3.0 but i am getting error importing an file for 1.3.0, error is
```
D:\BD\NewCBLLibraryTest\app\build.gradle
Error:(25, 13) Failed to resolve: com.couchbase.lite:couchbase-lite-android:1.3.0-12
<a href="openFile:D:/BD/NewCBLLibraryTest/app/build.gradle">Show in File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>
```
Note:
My android studio version: 2.1.2
My gradle version  - classpath 'com.android.tools.build:gradle:2.1.2'
My projecct gradle is :
apply plugin: 'com.android.application'

```
android {
    compileSdkVersion 23
    buildToolsVersion "24.0.0"

    defaultConfig {
        applicationId "meteortest.test.com.newcbllibrarytest"
        minSdkVersion 15
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:23.4.0'
    compile 'com.couchbase.lite:couchbase-lite-android:1.3.0-12'
}
```

How i can solve this problem? Or any solutions?

Thanks
prasanna

**Comment by hideki** [comment]
Hi @iCRG,
We did not deploy developer preview on Jcenter. So please add Couchbase custom maven repo in dependency URL in build.gradle?
Instraction => https://github.com/couchbase/couchbase-lite-android#optional-maven-repo-url-httpfilescouchbasecommaven2
Thanks!

**Comment by jamiltz** [comment]
When using CI build (which is the case for the developer preview builds), the couchbase maven URL must also be specified in build.gradle. It was missing from the docs but is now updated http://developer.couchbase.com/documentation/mobile/1.2/developer-preview/download/index.html. Sorry about that.

**Comment by iCRG** [comment]
@jamiltz 
Thanks for your update, still i am getting error like

```
Information:Gradle tasks [:app:generateDebugSources, :app:mockableAndroidJar, :app:prepareDebugUnitTestDependencies, :app:generateDebugAndroidTestSources]
Error:A problem occurred configuring project ':app'.
> Could not download couchbase-lite-java-core.jar (com.couchbase.lite:couchbase-lite-java-core:1.3.0-12)
   > Could not get resource 'http://files.couchbase.com/maven2/com/couchbase/lite/couchbase-lite-java-core/1.3.0-12/couchbase-lite-java-core-1.3.0-12.jar'.
      > Could not GET 'http://files.couchbase.com/maven2/com/couchbase/lite/couchbase-lite-java-core/1.3.0-12/couchbase-lite-java-core-1.3.0-12.jar'.
         > The target server failed to respond
Information:BUILD FAILED
Information:Total time: 2.045 secs
Information:1 error
Information:0 warnings
Information:See complete output in console
```

my project level gradle

```
// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.1.2'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}
allprojects {
    repositories {
        mavenCentral()
        maven {
            url "http://files.couchbase.com/maven2/"
        }
    }
}
```
in dependencies section

```
dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile 'com.android.support:appcompat-v7:23.0.1'
    compile 'com.android.support:design:23.0.1'
    compile 'com.couchbase.lite:couchbase-lite-android:1.1.0'
    compile 'com.android.support:recyclerview-v7:+'
    compile 'com.android.support:cardview-v7:+'
    compile "com.splitwise:tokenautocomplete:2.0.7@aar"
    compile 'com.wnafee:vector-compat:1.0.5'
    compile 'com.google.android.gms:play-services-maps:6.5.87'
    compile 'com.mcxiaoke.volley:library-aar:1.0.0'
    compile 'com.couchbase.lite:couchbase-lite-android:1.3.0-12'
    //compile 'library.test.com.makelibrary:make-library:1.1.2'
    compile('com.crashlytics.sdk.android:crashlytics:2.5.5@aar') {
        transitive = true;
    }
    compile 'com.squareup.retrofit:retrofit:1.9.0'
}
android {
    packagingOptions {
        exclude 'META-INF/ASL2.0'
        exclude 'META-INF/DEPENDENCIES.txt'
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/NOTICE.txt'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/DEPENDENCIES'
        exclude 'META-INF/notice.txt'
        exclude 'META-INF/license.txt'
        exclude 'META-INF/dependencies.txt'
        exclude 'META-INF/LGPL2.1'
    }
}
```

**Comment by jamiltz** [comment]
Those settings look correct, I remember having an issue with Android Studio once where it wouldn't fetch the resource although it was there. (check that the offline mode is disabled in Android Studio preferences).

Here's a project that works on my machine, let us know if it works on yours.

https://cl.ly/1K3Y3I1G1Q2U/UntitledApp.zip

**Comment by hideki** [comment]
Hi @iCRG,

 Please set maven repo into top-level `build.gradle`. 

Followig is sample build.gradle
```
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:1.5.0'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        jcenter()
        maven {
            url "http://files.couchbase.com/maven2/"
        }
    }
}
```

**Comment by iCRG** [comment]
Hi @hideki & @jamiltz,

Thanks for you update here, it is working fine now

Thanks
Prasanna

**Comment by vidyajejurkar** [comment]
@iCRG iCRG:I got same error 
Error:(32, 17) Failed to resolve: com.couchbase.lite:couchbase-lite-android:1.3.0
Show in File
Show in Project Structure
my build gradle is:

apply plugin: 'com.android.application'

android {
    compileSdkVersion 24
    buildToolsVersion "24.0.2"

    defaultConfig {
        applicationId "com.example.invjejurka.myapplication"
        minSdkVersion 15
        targetSdkVersion 24
        versionCode 1
        versionName "1.0"
    }
    packagingOptions {
        exclude 'META-INF/ASL2.0'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/NOTICE'
    }


        buildTypes {
            release {
                minifyEnabled false
                proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            }
        }
    }

    dependencies {
        compile fileTree(dir: 'libs', include: ['*.jar'])
        testCompile 'junit:junit:4.12'
        compile 'com.android.support:appcompat-v7:24.2.0'
        compile 'com.couchbase.lite:couchbase-lite-android:1.3.0'

    }﻿
plz give me solution.

Thanks,
Vidya

**Comment by hideki** [comment]
Hi @vidyajejurkar,
Are you using Android Studio? And also is the project configured with JCenter or Maven Central? If yes, I don't know what cause the problem with your environment. Please confirm your maven repository configuration.
Thanks,
Hideki

**Comment by vidyajejurkar** [comment]
@hideki hideki:
yes i am using Android Studio 2.1.3 
Now i got different error
build.gradle is:
apply plugin: 'com.android.application'

android {
    compileSdkVersion 24
    buildToolsVersion "24.0.2"

    defaultConfig {
        applicationId "com.example.invjejurka.myapplication"
        minSdkVersion 15
        targetSdkVersion 24
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
   // workaround for "duplicate files during packaging of APK" issue
// see https://groups.google.com/d/msg/adt-dev/bl5Rc4Szpzg/wC8cylTWuIEJ
    packagingOptions {
        exclude 'META-INF/ASL2.0'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/NOTICE'
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:24.2.0'
    compile 'com.couchbase.lite:couchbase-lite-android:1.0.4'

}

Project:MyApplication build.gradle
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        jcenter()

    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.1.3'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        jcenter()
        maven {
            url "http://files.couchbase.com/maven2/"
        }
    }
}




Error:
E:\AndroidStudioWorkspace\MyApplication\app\build.gradle
Error:Failed to resolve: com.github.oxo42:stateless4j:2.4.0
<a href="openFile:E:/AndroidStudioWorkspace/MyApplication/app/build.gradle">Open File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>
Error:Failed to resolve: org.codehaus.jackson:jackson-core-asl:1.9.2
<a href="openFile:E:/AndroidStudioWorkspace/MyApplication/app/build.gradle">Open File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>
Error:Failed to resolve: org.codehaus.jackson:jackson-mapper-asl:1.9.2
<a href="openFile:E:/AndroidStudioWorkspace/MyApplication/app/build.gradle">Open File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

can u give me any suggestion or solution for it.

**Comment by hideki** [comment]
@vidyajejurkar 

Do you intentionally use CBL v1.0.4?
```
compile 'com.couchbase.lite:couchbase-lite-android:1.0.4'
```

**Comment by vidyajejurkar** [comment]
hideki :actually i tried all verions means 1.1,1.3,1.0.4 .n got same error for all verions

**Comment by vidyajejurkar** [comment]
@hideki : i tried with 1.0.4 n also with 1.3

**Comment by hideki** [comment]
I don't know what cause the problem with your environment.

Could you please try CBL from scratch with following tutorial?
http://developer.couchbase.com/documentation/mobile/1.1.0/develop/training/build-first-android-app/index.html
