### ISSUE TITLE
Lots of 'replicator.RemoteRequest' warnings (v1.3.0-23)

### ISSUE THREAD

**Issue by npomfret** [couchbase/couchbase-lite-android#939]
I'm seeing lots of these messages from my android app:

`W/RemoteRequest: com.couchbase.lite.replicator.RemoteRequest {PUT, http://192.168.1.185:4986/sync_gateway/_local/6ae341151d5655a7f18337c7a605c380188483ae}: Got error status: 409 for http://192.168.1.185:4986/sync_gateway/_local/6ae341151d5655a7f18337c7a605c380188483ae. Reason: Conflict
`

There's nothing obviously wrong, what do they mean please?

**Comment by hideki** [comment]
`409` indicates `conflict`. So document is conflicting.

**Comment by npomfret** [comment]
I understand what a 409 is.  These warnings have started since upgrading from 1.2.1 to 1.3.x.   And if you take a look at the url it contains `_local` in the path.  I've what does `_local` mean, I don't have any local docs?  What can I do to investigate?

**Comment by npomfret** [comment]
When I look at one of these docs it doesn't look like anything to do with my app:

`...:4984/sync_gateway/_local/65a01129927a847dfe72245205bc820b36b2774e` ->

```
{
_id: "_local/65a01129927a847dfe72245205bc820b36b2774e",
_rev: "0-378",
lastSequence: "71772"
}
```

**Comment by npomfret** [comment]
Still getting lots of these with build 1.3.0-45 and a physical android device running 5.1

```
07-29 12:09:37.433 12043-473/com.pomochat V/RemoteRequest: com.couchbase.lite.replicator.RemoteRequest {PUT, http://192.168.1.185:4986/sync_gateway/_local/c8c30368ebd6611c728f48aa11c31fe92ed94f50}: RemoteRequest called httpClient.execute, url: http://192.168.1.185:4986/sync_gateway/_local/c8c30368ebd6611c728f48aa11c31fe92ed94f50
07-29 12:09:37.433 12043-473/com.pomochat W/RemoteRequest: com.couchbase.lite.replicator.RemoteRequest {PUT, http://192.168.1.185:4986/sync_gateway/_local/c8c30368ebd6611c728f48aa11c31fe92ed94f50}: Got error status: 409 for http://192.168.1.185:4986/sync_gateway/_local/c8c30368ebd6611c728f48aa11c31fe92ed94f50. Reason: Conflict
07-29 12:09:37.434 12043-473/com.pomochat D/RemoteRequest: com.couchbase.lite.replicator.RemoteRequestRetry$1@244e5a7e: RemoteRequestRetry inner request finished, url: http://192.168.1.185:4986/sync_gateway/_local/c8c30368ebd6611c728f48aa11c31fe92ed94f50
07-29 12:09:37.434 12043-473/com.pomochat D/RemoteRequest: com.couchbase.lite.replicator.RemoteRequestRetry@226fa400: isTransientError, httpResponse: Response{protocol=http/1.1, code=409, message=Conflict, url=http://192.168.1.185:4986/sync_gateway/_local/c8c30368ebd6611c728f48aa11c31fe92ed94f50} e: com.couchbase.lite.replicator.RemoteRequestResponseException: Conflict
07-29 12:09:37.434 12043-473/com.pomochat D/RemoteRequest: com.couchbase.lite.replicator.RemoteRequestRetry@226fa400: isTransientError, status code: 409
07-29 12:09:37.434 12043-473/com.pomochat D/RemoteRequest: com.couchbase.lite.replicator.RemoteRequestRetry@226fa400: isTransientError, return false
07-29 12:09:37.434 12043-473/com.pomochat D/RemoteRequest: com.couchbase.lite.replicator.RemoteRequestRetry$1@244e5a7e: RemoteRequestRetry failed, non-transient error.  NOT retrying. url: http://192.168.1.185:4986/sync_gateway/_local/c8c30368ebd6611c728f48aa11c31fe92ed94f50
07-29 12:09:37.434 12043-473/com.pomochat D/Sync: com.couchbase.lite.replicator.ReplicationInternal$8@10631bdf: put remote _local document request finished.  checkpointID: c8c30368ebd6611c728f48aa11c31fe92ed94f50 body: {_rev=0-836, lastSequence=103535, _id=_local/c8c30368ebd6611c728f48aa11c31fe92ed94f50}
07-29 12:09:37.434 12043-473/com.pomochat I/Sync: com.couchbase.lite.replicator.ReplicationInternal$8@10631bdf: could not save remote checkpoint: 409 CONFLICT
07-29 12:09:37.434 12043-473/com.pomochat I/Sync: PullerInternal{unknown, pull, c8c30}: Refreshing remote checkpoint to get its _rev...

```

**Comment by pasin** [comment]
The local doc here is the replication checkpoint document. It has lastSequence info used to determine the last progress of the replication.

> Still getting lots of these with build 1.3.0-45

Can you explain more about this? If general, you shouldn't see a lot unless maybe there are 2 replicator that has the exact same parameters running at the same time?

**Comment by npomfret** [comment]
It could be 2 replicators I suppose, my code is supposed to guard against that but it could be a bug.  If there are 2 with the same parameters would that cause the 409 that I'm seeing?

**Comment by sethrosetter** [comment]
@pasin Once this is resolved can you follow up with me on adding a regression / unit test?

**Comment by pasin** [comment]
@npomfret Can you post the full logcat (maybe in gist) to show all the 409 errors?

**Comment by pasin** [comment]
I was able to reproduce by submitting multiple POST _replicate to create pull replicators with the same properties. When multiple replicator objects with the same type and properties are created, they will try to save the remote checkpoint at the same time and end up with the conflict. 

In general, CBL shouldn't allow multiple replicators of the same type to be created. This should be fixed.
