### ISSUE TITLE
Pull replicator filter not working in 1.3.0-27 against CouchDB

### ISSUE THREAD

**Issue by moritz-scandit** [couchbase/couchbase-lite-android#942]
Setting a pull replicator filter does not seem to be working in any of the 1.3.0 pre-releases (tested 1.3.0-12, 23 and 27). So until now when for example setting a server-side filter function like:

pullReplication.setFilter("sync/pull");

Then the request query string would contain &filter=sync%2Fpull to allow for filtering. However, with 1.3.0 the filter seems to no longer be added to the query string.

**Comment by jamiltz** [comment]
Is the replication running with Sync Gateway or CouchDB? (the version might be helpful to have as well).

**Comment by moritz-scandit** [comment]
It is running with CouchDB 1.6.

**Comment by hideki** [comment]
Hi @moritz-scandit,

I have some questions:
- Are you using CBL Native API? or using CBL  from PhoneGap?
- How did you set filter method? could you please provide code snippet?

Thanks!

**Comment by moritz-scandit** [comment]
We are using the Native Android API in our app. The filter is set through just a call to .setFilter(string), removing a few detail this is how the whole thing more or less looks like:
```
manager = new Manager(new AndroidContext(context), managerOptions);
database = manager.getDatabase(DATABASE_NAME);

BasicAuthenticator authenticator = new BasicAuthenticator(user, password);
pullReplication = database.createPullReplication(remoteDatabaseUrl);
pushReplication = database.createPushReplication(remoteDatabaseUrl);
pullReplication.setAuthenticator(authenticator);
pushReplication.setAuthenticator(authenticator);
pullReplication.setContinuous(true);
pushReplication.setContinuous(true);

pullReplication.setFilter("sync/pull");

pullReplication.start();
pushReplication.start();
```

It works perfectly like this in 1.1.0 and 1.2.1 but does no longer add the filter to the request's query string in 3.0.0.

**Comment by hideki** [comment]
Hi @moritz-scandit,

Thank you for code snippet. Could you please also provide your filter function which is set to database?
http://developer.couchbase.com/documentation/mobile/current/develop/guides/couchbase-lite/native-api/replication/index.html#filters

**Comment by hideki** [comment]
Hi @moritz-scandit,

Sorry, I misunderstand your issue. You'd like to use CouchDB server side filter function? We will look into the issue.
http://developer.couchbase.com/documentation/mobile/current/develop/guides/couchbase-lite/native-api/replication/index.html

**Comment by moritz-scandit** [comment]
Yes, exactly. The filter is server-side which is why I expect it to be part of the query string of change requests as it was until 3.0.0.

**Comment by philmay** [comment]
I tested this with the new 1.4.0 release of the Android Couchbase Lite, and it's still not working. 

I have looked at the client code in couchbase-lite-java-core, and I see where it's dropping the filter params from the query string (the filter name gets placed in the query string in all cases, but the filter params get skipped for a POST). I think the right fix may be to set the request to a POST only if `docIDs` is set in `ChangeTracker`, but still do GET for all other filtered `_changes` queries. I'll look into this.

**Comment by hideki** [comment]
@philmay, CouchDB only handle docIDs as request body of POST `/_changes REST`.  CouchDB requires all other parameters in the HTTP query parameter. I guess Cloudant requires everything in HTTP query parameter.

If you can not modify server side codes, you can modify CBL code to use `GET` instead of `POST`, and build CBL by yourself.

**Comment by philmay** [comment]
@hideki, Yep, that's what I plan to do. I have what I think is a quick and simple fix to keep the POST around for docIDs, but use GET for all others. This should be compatible with CouchDB/Cloudant.

**Comment by hideki** [comment]
simplest solution could be set `usePOST` variable in ChangeTracker `false`.
https://github.com/couchbase/couchbase-lite-java-core/blob/master/src/main/java/com/couchbase/lite/replicator/ChangeTracker.java#L68

**Comment by philmay** [comment]
I was looking at that. If I make the default for `usePOST` `false` in the `ChangeTracker` constructor, and then have it set to `true` if `setDocIDs()` is called, then it should work for all cases. You really do need to use the POST if you have a list of docIDs, and that's still compatible with CouchDB/Cloudant as well.

Thanks!

**Comment by philmay** [comment]
@hideki, I made the following change to `ChangeTracker.java`
- Default to GET for `_changes` queries, except for the following two cases.
- Use POST if the filter is on Sync Gateway channels (`filter=sync_gateway/bychannel`).
- Use POST if the filter is on doc_ids (`filter=_doc_ids`).

I think this should cover the long URL string issue with using GET always.

Would you be open to accepting this as a pull request? It's about 25 lines of new code in ChangeTracker.java, and 6 lines in the unit tests. If so, I'll submit it.

**Comment by hideki** [comment]
Hi @philmay 

We can not accept this change at this point. There are two reasons:
- We have discussed incompatibility with CouchDB and Cloudant for a while. As Couchbase Lite development team, we decided to implement current way. We hope CouchDB and Cloudant fix their `POST /_changes` REST API.
- Couchbase Lite has other implementation CBL iOS and .NET. We can not accept this change only for CBL Android/Java.

Hope you can understand this.

Regards,

**Comment by philmay** [comment]
Hi @hideki,
Thanks for the quick reply. I do have followup questions:
1. If we make the same changes to the iOS and .NET versions, would you be open to accepting the change?
2. In the CBL docs, it is stated that filtered pull replication is supported against Cloudant/CouchDB (http://developer.couchbase.com/documentation/mobile/current/guides/couchbase-lite/native-api/replication/index.html#filtered-pull-from-couchdb-pouchdb-or-cloudant). Have you decided to no longer support compatibility?
3. Is Couchbase currently engaging with the CouchDB/Cloudant community in any way to come to a consensus on how to remain compatible with replication?

I'm just trying to get a better idea of what our options are going forward. 

Thanks for your help! I really appreciate it!

**Comment by hideki** [comment]
@philmay,

1) My comment 1 is a primary reason. So we might not be able to accept changes.

2) CBL started to call /_changes REST API with POST. If its request fails, try to use GET. As far as I know, CBL should work with CouchDB 1.6.1 that I confirmed.
https://github.com/couchbase/couchbase-lite-java-core/blob/3ed5056ee4edfe27e67f816f08d6e342fd7f8b73/src/main/java/com/couchbase/lite/replicator/ChangeTracker.java#L341

3) Couchbase founders started CouchDB. But currently, we do not actively involve with CouchDB. Honestly, we don't discuss the compatibility issues with them

**Comment by philmay** [comment]
@hideki, Thanks for the info!

In response to #2 above – CBL is putting the filter name (set via `setFilter()` call) into the query string for a POST, but not the filter parameters (set via `setFilterParams()` call). In response to this POST, CouchDB does not generate an error. Rather, the filter function is happily called with `null` for all the filter parameters and we get a 200 OK, but the results are not what we expect (because all the filter parameters resolve to `null` rather than what the programmer set them to). I have tested this in both CouchDB 1.6 and 2.0, and both behave the same way (no error, but bad filter logic).

This bug is particularly difficult to detect, precisely because it does not produce an obvious error. Instead it produces odd behavior with results that don't match the intent of the app logic. My fix gets around this by using GET for all `_changes` queries except for filtering by Couchbase channels or CouchDB doc_ids. It's also pretty simple  ;)

Thanks again!

**Comment by llisas** [comment]
Sorry I know it is not the best place for this questions, but I can not find info about.  I have to change also the usePOST variable in ChangeTracker to false, but the ChangeTracker  code is bloqueck because is compiled by gradle, so please how Can I import couchbase Lite 1.4 (android) not using gradle ? I have tried a lot of things but I am absolutely  stuck

**Comment by hideki** [comment]
@philmay 
You could download 1.4 jar files from download site: https://www.couchbase.com/downloads .
And you could add all required jar files into your project.

**Comment by philmay** [comment]
@llisas, I have an advantage of having an internal maven repo here on-site, so I configured my build to use that, and pushed my fixed CBL 1.4 artifacts there. What @hideki suggested also works, which is how I did it before moving to our internal maven repo. I do recall it being tricky to get the build to work with just the jars.

It's been a while, but here's the part of my old build.gradle for including the locally built jars in my Android build:

```
// Configs for including CBL explicitly via local aar/jar files
    compile(name: 'couchbase-lite-android-release', ext: 'aar')
    compile(name: 'couchbase-lite-java-core', ext: 'jar')
    compile(name: 'couchbase-lite-java-forestdb-release', ext: 'aar')
    compile(name: 'couchbase-lite-android-sqlite-custom', ext: 'aar')
    compile(name: 'couchbase-lite-java-native-sqlcipher', ext: 'aar')

// Configs for the other libs (required for both of above CBL configs
    compile 'com.squareup.okhttp3:okhttp:3.3.1'
    compile 'com.fasterxml.jackson.core:jackson-core:2.5.0'
    compile 'com.fasterxml.jackson.core:jackson-annotations:2.5.0'
    compile 'com.fasterxml.jackson.core:jackson-databind:2.5.0'
    compile 'com.github.oxo42:stateless4j:2.4.0'
```
Hope this helps.

**Comment by llisas** [comment]
@philmay  does not work on my site : ( 
 ¿Could  anyone, please,please, describe the steps I have to do in order to import CBL to my proyect? . I have tried all that I have read without success

**Comment by philmay** [comment]
Is it failing to compile or failing to run? Do you have the CBL .jar and .aar files in lib directories in your project that are being searched during build? I have the following in my top-level build.gradle file, specifying that dependencies may be found in my app libs directory and the top-level libs directory for my project. The .jar and .aar files go in these dirs. Again, we've been on internal maven for so long now, I don't do it this way anymore, and I doubt I could reproduce it. It did work at one time, however.
```
allprojects {
    repositories {
        jcenter()
        flatDir {
            dirs '../libs'
            dirs 'libs'
        }
    }
}
```

**Comment by Fenil15** [comment]
Usign filter params in query string is not a correct way to implement at query string has its own limitation. Instead one should use selector instead of filter if you are using CouchDB Server 2.0 and above. Only thing you need to make sure at your client side is, set the filter name = _selector and in filter params, pass params in following format -

    {
      "selector": {
        "key_name_to_filter": "key_value_to_filter",
        "$or": [
          {
            "$and": [
              {
                "key_1": "value_1"
              },
              {
                "key_2": "value2"
              }
            ]
          },
          {
            "$and": [
              {
                "key_3": "value_3"
              },
              {
                "key_4": "value_4"
              }
            ]
          }
        ]
      }
    }

Above format is just an example illustrating you can create complex queries in selector filter.

**Comment by skyred** [comment]
If filter parameters are set and sent via POST, then it will trigger a CouchDB timeout bug https://github.com/apache/couchdb/issues/1606. 

With respect to Couchbase team, I suggest we starting a folk (from @philmay https://github.com/couchbase/couchbase-lite-android/issues/942#issuecomment-295879313 ) of this library, until CouchDB would support filter parameters in POST in their future release. 

@philmay Will you be willing publish a fork, and other android developers can use your fork as depedency in gradle? Or, can you please make a pull request against latest 1.4.4 release? I can help publish a fork.
