### ISSUE TITLE
_changes, longpoll, timeout with 1.3.0-45

### ISSUE THREAD

**Issue by npomfret** [couchbase/couchbase-lite-android#951]
I've noticed on a few occasions that changes aren't appearing in my app.  I can see the document changes arriving in the logs (`Database: INSERT` appears 5 times, and `addToInbox() called, rev` appears 6 times for each document change) and I can the changes if I query the `_changes` feed from my web browser.    But occasionally my app doesn't display them.

I'm using the REST API and the `_changes` feed with `feed=longpoll` and `timeout=5000`.  In iOS this query returns as soon as the system detects any changes.  But in Android it doesn't seem to, at least not all of the time.  Also it seems that that the `timeout` parameter seems to be ignored and so the query is never repeated.  So I think maybe there are 2 issues here.

1.  The `_changes` feed with `longpoll` doesn't always return when there are new changes.
2. The `timeout` parameter in the changes feed is ignored.

Here's a thread dump https://gist.github.com/npomfret/99d34c3ddf06d5b2a3f1abb12cec6ccb

**Comment by hideki** [comment]
Hi @npomfret,

Thank you for bug report

As you wrote, `timeout` is not implemented for Android. We will implement this as soon as possible.
http://developer.couchbase.com/documentation/mobile/1.2/develop/references/couchbase-lite/rest-api/database/get-changes/index.html

About `longpoll`, could you please provide more details about the condition that could reproduce this? Can you find any insight from logcat?

From thread-dump, I can observe 5 `ChangeTracker ` instance. `ChangeTracker ` is per a pull replicator.  Is this intentionally?

Also from thread-dump, it seems you are not using latest build. Following is expected formatting for ChangeTracker instance.
https://github.com/couchbase/couchbase-lite-java-core/blob/master/src/main/java/com/couchbase/lite/replicator/ChangeTracker.java#L634-L640

Thanks!

**Comment by npomfret** [comment]
> timeout is not implemented for Android

I can't tell you how many hours I've wasted over the last 6 months trying to following incorrect documentation from Couchbase.  Its incredibly frustrating.  Can you please put them into github so that a the community can maintain them?

>  it seems you are not using latest build

I'm using 1.3.0-45 which is the latest build available on [here](http://latestbuilds.hq.couchbase.com/couchbase-lite-android/1.3.0/).

I'll update this when I have the steps to reproduce it.

**Comment by hideki** [comment]
ref for `timeout`: https://github.com/couchbase/couchbase-lite-java-core/issues/1376

**Comment by jamiltz** [comment]
@npomfret the documentation repo for cb mobile is at https://github.com/couchbaselabs/couchbase-mobile-portal. We're in the process of moving from XML to markdown to make it easier to contribute to docs. For REST API documentation we're switching to using [swagger](https://github.com/couchbaselabs/couchbase-mobile-portal/tree/master/swagger). We can add a note about the timeout param on android for the /_changes endpoint.

**Comment by hideki** [comment]
`timeout` parameter is implemented in [PR](https://github.com/couchbase/couchbase-lite-java-core/pull/1384).
