### ISSUE TITLE
ForestDB: db.getExistingView(viewName) returns null for views created in previous app launch

### ISSUE THREAD

**Issue by vbenso** [couchbase/couchbase-lite-android#952]
As the title says, 
Database.getExistingView() returns null for views that were created in previous launches of the app.
The view's files exist on storage, but forestDB doesn't retrieve them in future launches, so I'm forced to recreate all views at every launch. 
Am I missing something here?
Is this the expected behavior? 
Should I re-create the views at every launch?

I'm using:
    compile 'com.couchbase.lite:couchbase-lite-android:1.3.0-45'
    compile 'com.couchbase.lite:couchbase-lite-android-forestdb:1.3.0-45'

**Comment by hideki** [comment]
Hi @vbenso,
If you can compile from source codes, can you add `Log.e(TAG, "<message>", e)` in `catch` block. And check where error comes from?

```java
    @InterfaceAudience.Public
    public View getExistingView(String name) {
        synchronized (lockViews) {
            View view = views != null ? views.get(name) : null;
            if (view != null)
                return view;

            try {
                return registerView(new View(this, name, false));
            } catch (CouchbaseLiteException e) {
                // View is not exist.
                return null;
            }
        }
    }
```

**Comment by vbenso** [comment]
Hi @hideki, 
Couldn't compile from sources, using the following submodules:
```
 8ab623904639f27575c715b03ca9597b88ed59a2 libraries/couchbase-lite-java-core (1.3.0-3-g8ab6239)
 edd741e46adc9779f8a6702869e8450b9880cc0c libraries/couchbase-lite-java-forestdb (1.3.0-7-gedd741e)
 501be320fea1396e5922c1ddbde08af4d2e87664 libraries/couchbase-lite-java-native (1.3.0)
```
NDK doesn't want do compile some file:
```
:libraries:couchbase-lite-java-native:sqlcipher:transformNative_libsWithSyncJniLibsForRelease UP-TO-DATE
:libraries:couchbase-lite-java-native:sqlcipher:bundleRelease
In file included from /home/victor/Documents/software/couchbase-lite-android/libraries/couchbase-lite-java-forestdb/jni/../vendor/cbforest/vendor/forestdb/src/blockcache.cc:31:
In file included from ../vendor/cbforest/vendor/forestdb/src/blockcache.h:21:
In file included from ../vendor/cbforest/vendor/forestdb/src/filemgr.h:35:
In file included from ../vendor/cbforest/vendor/forestdb/src/atomic.h:30:
In file included from /home/victor/android-sdks/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/include/atomic:41:
/home/victor/android-sdks/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/atomic_base.h:443:16: error: cannot compile this atomic library call yet
      { return __atomic_and_fetch(&_M_i, __i, memory_order_seq_cst); }
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/victor/android-sdks/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/atomic_base.h:451:16: error: cannot compile this atomic library call yet
      { return __atomic_or_fetch(&_M_i, __i, memory_order_seq_cst); }
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2 errors generated.

/home/victor/android-sdks/ndk-bundle/build/core/build-binary.mk:462: recipe for target '/home/victor/Documents/software/couchbase-lite-android/libraries/couchbase-lite-java-forestdb/obj/local/armeabi/objs/CouchbaseLiteJavaForestDB/__/vendor/cbforest/vendor/forestdb/src/blockcache.o' failed

make: *** [/home/victor/Documents/software/couchbase-lite-android/libraries/couchbase-lite-java-forestdb/obj/local/armeabi/objs/CouchbaseLiteJavaForestDB/__/vendor/cbforest/vendor/forestdb/src/blockcache.o] Error 1

make: Leaving directory '/home/victor/Documents/software/couchbase-lite-android/libraries/couchbase-lite-java-forestdb/jni'
:libraries:couchbase-lite-java-forestdb:buildNative FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':libraries:couchbase-lite-java-forestdb:buildNative'.
> Process 'command '/home/victor/android-sdks/ndk-bundle/ndk-build'' finished with non-zero exit value 2

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 8.779 secs

```

Anyway I looked deeper into ForestDBViewStore and have some interesting findings,

![screenshot from 2016-07-31 07 50 59](https://cloud.githubusercontent.com/assets/8295627/17276072/d88993be-56f3-11e6-9a88-0ec8d17009d8.png)
In this case, it is trying to open the file:
`/storage/emulated/0/Android/data/com.precisagro.agcampofree/files/dbfc3bdb2e3cb5826a46305d08baafe044.cblite2/users%2Famostragens5.viewindex`
However, inspecting the application's path, the file that actually exists is `users%2Famostragens5.viewindex.2`,
In fact for every viewname there is a .meta file and a .x file (x being an integer from 0 to 5).
By not finding the file, the method throws CouchbaseLiteException(404).
Looks like viewNameToFileName is computing the proper filename, but is still missing that last integer, that I've no idea from where it comes and what is means.

Thanks a lot,

**Comment by pasin** [comment]
> Database.getExistingView() returns null for views that were created in previous launches of the app.
The view's files exist on storage, but forestDB doesn't retrieve them in future launches, so I'm forced to recreate all views at every launch. 

CBL doesn't store the map and reduce fn. So the view needs to be recreated with the map and reduce fn (if having one) every time that the app starts. If map / reduce fn is changed, the version number should be increased so that the view storage can know the change and re-index the view.

**Comment by vbenso** [comment]
Did some extra digging about this issue,
using 
```
compile 'com.couchbase.lite:couchbase-lite-android:0.0.0-673'
compile 'com.couchbase.lite:couchbase-lite-android-forestdb:0.0.0-673'
```
the .viewindex files don't have that number on filename, and views are properly recalled and view.getMapVersion() returns the expected value (the version of the map function that the view was using)

**Comment by hideki** [comment]
Hi @vbenso,

> Database.getExistingView() returns null for views that were created in previous launches of the app.

I misunderstood the your issue before. As @pasin wrote, Every app launches, the app needs to create/set view.  Please confirm this point first?

Thanks!

**Comment by vbenso** [comment]
It all started with:
> Database.getExistingView() returns null for views that were created in previous launches of the app.
> The view's files exist on storage, but forestDB doesn't retrieve them in future launches, so I'm forced to recreate all views at every launch. 
> Am I missing something here?
> Is this the expected behavior? 

lite/View.java(line 136) agrees with @pasin:

>  Since the function itself is obviously not stored in the database (only a unique
>  string idenfitying it), you must re-define the view on every launch of the app!
>  If the database needs to rebuild the view but the function hasn't been defined yet,
>  it will fail and the view will be empty, causing weird problems later on.
So I'll call setMap for all my views at launch time, but then:
the problem I'm struggling with and I wanted to report is that in the following scenario:

1. App is launched
2. All docs are synced with SG (takes time)
3. All views are properly indexed (takes time)
4. App is closed and relaunched
5. Replicator tries to sync but there are no changes (fast)
6. All views are indexed again, using the same mapFunctions from the previous launch (takes the same time as step 3) 

Is the expected behavior to index everything again given that the views where previously computed and there were no changes to the Database?

**Comment by hideki** [comment]
Theoretically, reindexing from beginning should not happen. Please check if you are using same view name and same view version number? If the issue still occurs, I guess there is bug in some where. Please write detailed steps to reproduce?

**Comment by pasin** [comment]
From https://github.com/couchbase/couchbase-lite-android/pull/958, there is an issue getting an existing view with ForestDB Storage engine. SQLiteStorage works fine.

**Comment by pasin** [comment]
@vbenso I believe a workaround is always call database.getView("viewname") when you setup the view first time after launching the app. Please try that and let us know if that works.

**Comment by pasin** [comment]
Umm, with calling database.getView("viewname"), the view gets reindexed.

**Comment by pasin** [comment]
@hideki knows forestDB more that I do so I will need to have @hideki look into this.

**Comment by vbenso** [comment]
@pasin @hideki 
When using database.getView("viewname") the test fails on the next assert (the view shouldn't be indexed at every launch)

```
junit.framework.AssertionFailedError: expected:<304> but was:<200>
at com.couchbase.lite.ViewsTest.testViewCreationAndRecall(ViewsTest.java:132)
at java.lang.reflect.Method.invokeNative(Native Method)
at com.couchbase.lite.LiteTestCase.runBare(LiteTestCase.java:33)
at com.couchbase.lite.LiteTestCaseWithDB.runBare(LiteTestCaseWithDB.java:106)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:191)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:176)
at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:554)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1729)
```


```
    public void testViewCreationAndRecall() {
        try {
            String expectedVersion = "1.0";
            String viewName = "testview";
            Database db1 = startDatabase();
            putDocs(db1);
            View view1 = db1.getView(viewName);
            view1.setMap(new Mapper() {
                @Override
                public void map(Map<String, Object> document, Emitter emitter) {
                    if (document.get("key") != null) {
                        emitter.emit(document.get("key"), null);
                    }
                }
            }, expectedVersion);
            view1.updateIndex();
            db1.close();

            Database db2 = manager.getExistingDatabase(DEFAULT_TEST_DB);
            View view2 = db2.getView(viewName);
            Assert.assertNotNull(view2);
            view2.setMap(new Mapper() {
                @Override
                public void map(Map<String, Object> document, Emitter emitter) {
                    if (document.get("key") != null) {
                        emitter.emit(document.get("key"), null);
                    }
                }
            }, expectedVersion);
            assertEquals(Status.NOT_MODIFIED,view2.updateIndex().getCode());    <------ FAILS HERE
            db2.close();
        } catch (CouchbaseLiteException e) {
            e.printStackTrace();
        }
```

**Comment by vbenso** [comment]
In [couchbase-lite-java-forestdb/src/main/java/com/couchbase/lite/store/ForestDBStore.java](https://github.com/couchbaselabs/couchbase-lite-java-forestdb/commit/57ebb05afb909f29f914235314a31b810797c19a)
```
      @Override
      public void open() throws CouchbaseLiteException {
// Commenting these lines out, works around the problem, getExistingView() doesn't return null anymore
//        if(autoCompact) 
//            flags |= Database.AutoCompact;
```
