### ISSUE TITLE
How can we get latest changes document id's

### ISSUE THREAD

**Issue by iCRG** [couchbase/couchbase-lite-android#953]
Hi All,

I would like to get latest changes documents information(like ids or etc...), i currently I'm able to getting document changes count but those information is not enough to make my UI update due to i do not know the which document has been updated.

```
pullReplication.addChangeListener(new Replication.ChangeListener() {
                @Override
                public void changed(Replication.ChangeEvent event) {
                    mProgressDialog.setMax(event.getChangeCount());
                    mProgressDialog.setProgress(event.getCompletedChangeCount());
                    if (event.getSource().getStatus().equals(Replication.ReplicationStatus.REPLICATION_IDLE)
                            || event.getSource().getStatus().equals(Replication.ReplicationStatus.REPLICATION_STOPPED)
                            || event.getSource().getStatus().equals(Replication.ReplicationStatus.REPLICATION_OFFLINE)) {
                        mProgressDialog.dismiss();
                    }
                  
                }
            });
```
using event.getChangeCount() we can able to get changes count but i would like know with change ids also so that i can update UI where i want. Please let me know i can solve this problem, I'm using 1.3..0-37 version of CBL.

Please let me know if need any clarification or information.

Thank's
Prasanna

**Comment by hideki** [comment]
Hi @iCRG,

To obtain indivisual document change, please use Database Change notification instead of replicator notification. Note: Replicator does not track indivisual document changes.
http://developer.couchbase.com/documentation/mobile/1.2/develop/guides/couchbase-lite/native-api/database/index.html

Thanks!

**Comment by pasin** [comment]
I'm closing this issue now. @iCRG if you found there is an issue about this, we could reopen or create a new issue. For non-issues questions, I would suggest to use https://forums.couchbase.com/c/mobile.
