### ISSUE TITLE
Does the livequery observe the pull replication changes ?

### ISSUE THREAD

**Issue by mseshachalam** [couchbase/couchbase-lite-android#954]
I have a livequery adapter which lists out the keys from a view. I don't have any pull replication listener in my app.
When I add a document to the couch base server via sync gateway, I don't see this document in the list view.

**Comment by hideki** [comment]
LiveQuery is triggered by database change event, and pull replication could cause database change event if new document or changes are available. So LiveQuery should work as you expected.

Please check followings:
Please make sure if new document is already pulled to local database?
Please make sure if your map function matches your new document?

**Comment by pasin** [comment]
Basically yes, LiveQuery should update if there are new changes from pull replication.

**Comment by pasin** [comment]
> I don't have any pull replication listener in my app.

Do you mean you have a continuous pull replicator running but just do not have the change listener setup?

**Comment by mseshachalam** [comment]
@pasin yes, you are correct. My pull replicator is continuous. There is no change listener setup. I am guessing my pull replication is not happening in my case, thats why the live query is not reflecting changes. I have tried different changes in my sync gateway config file but I think the pull replication is not happening. How do I log only the pull replication logs on sync gateway ?

**Comment by pasin** [comment]
There isn't a way to log only a particular replication. You can try to log everything by putting `"log": ["*"]` in your sync gateway config file. 

On client side, you can enable some logging by:

```
// Replication logs:
Manager.enableLogging(Log.TAG_SYNC_ASYNC_TASK, Log.VERBOSE);
Manager.enableLogging(Log.TAG_SYNC, Log.VERBOSE);

// View and Query logs:
Manager.enableLogging(Log.TAG_VIEW, Log.VERBOSE);
Manager.enableLogging(Log.TAG_QUERY, Log.VERBOSE);
```

**Comment by pasin** [comment]
Also if you have question about Sync Gateway, you can post your question here: https://forums.couchbase.com/c/mobile.

I'm closing the issue now. If you think, there is an issue on Couchbase Lite Android, we can reopen issue anytime.
