### ISSUE TITLE
With the REST API, POST _bulk_docs does not return generated document IDs (v1.3.0)

### ISSUE THREAD

**Issue by lasselaakkonen** [couchbase/couchbase-lite-android#959]
I am using CouchBase Lite for Android with https://github.com/couchbaselabs/Couchbase-Lite-PhoneGap-Plugin. I assume this issue is with the Android version, since iOS and OSX work as expected.

**Version 1.2.1 - works as expected**
POST ../db1/_bulk_docs
`{"docs":[{"foobar":123}]}`

Gets the response
`[{"rev":"1-72c061e6c4562c4e6f7e1f9aa9110e43","id":"d31db298-8a4d-4454-a043-97ce462df28f","ok":true}]`

**Version 1.3.0 - ID missing in response**
POST ../db1/_bulk_docs
`{"docs":[{"foobar":123}]}`

Gets the response
`[{"rev":"1-72c061e6c4562c4e6f7e1f9aa9110e43","id":null,"ok":true}]`

Reproduced on Android 4.4.2 and Android 6.0.

Am I missing something?

**Comment by pasin** [comment]
Look like there is a regression from this commit https://github.com/couchbase/couchbase-lite-java-core/commit/de7afd4d02a98d19ab9ffdb2be7bebc4f38b8e92. 

Basically the new doc may not have '_id' property.

**Comment by lasselaakkonen** [comment]
When can the 1.3.1 release be expected, few days/weeks/months?
