### ISSUE TITLE
SQL schema reference

### ISSUE THREAD

**Issue by Takhion** [couchbase/couchbase-lite-android#964]
Is there a reference for each SQL schema that CBL has used under the hood in the various versions?

**Comment by pasin** [comment]
Please use https://forums.couchbase.com to ask questions. Close as not an issue.

For your question, you can find the schema info from https://github.com/couchbase/couchbase-lite-java-core/blob/master/src/main/java/com/couchbase/lite/store/SQLiteStore.java.
