### ISSUE TITLE
Cloudant could not handle POST /_changes request, and it returns 401, 403, or 405

### ISSUE THREAD

**Issue by Aksi0m** [couchbase/couchbase-lite-android#978]
Hi dev team,

Currently the 1.3 has a default POST method for pulling the data, while on pre releases it was GET. As I saw in the ChangeTracker class there is a retry policy if the POST request fails. Unfortunately for me if I do a POST request I get a 403 response because for some reason the API allows only GET requests. This 403 response code does not go through your retryIfFailedPost() and so it does not fallback to GET.

On the pre releases of the lib it works fine, but I need to use 1.3.0 because of the fix for Android N. So my question is, can we get an option to edit the flag usePost when we initially set up the Replication object or in some other way. I offer also my help to do a PR if you are interested. This is quite urgent (because Android N is already here!) and I want to avoid to fork the whole project if I can.

Thank you for your time!

**Comment by reisub** [comment]
It would be great if we could configure this option from outside the library, especially since cloud providers since cloudant charge more for POST requests.

See pricing here:
https://cloudant.com/product/pricing/

**Comment by hideki** [comment]
@Aksi0m what server are you using? CouchDB 1.6, Sync Gateway, or something else?

**Comment by hideki** [comment]
Note to self:
Http 403 Forbidden (https://en.wikipedia.org/wiki/HTTP_403) could be correct error response. Might need to fallback to `GET` if error is 403.

**Comment by hideki** [comment]
iOS already handle this issue with 

```
// Cloudant returns 401 or 403 if we send it a POST to _changes for a write-protected database.
// (See issues #1020, #1267.)
- (BOOL) isCloudantAuthError: (NSError*)error {
    if ([_serverName rangeOfString: @"CouchDB/1.0.2"].length == 0)     // (Accurate as of 5/2016)
        return NO;
    return [error my_hasDomain: NSURLErrorDomain code: NSURLErrorUserAuthenticationRequired]
        || [error my_hasDomain: CBLHTTPErrorDomain code: kCBLStatusForbidden];
}
```
https://github.com/couchbase/couchbase-lite-ios/blob/e667f38e5280b7f5442d70cf34c1f95ce029affd/Source/ChangeTracker/CBLSocketChangeTracker.m#L309-L316


iOS tickets: 
- https://github.com/couchbase/couchbase-lite-ios/issues/1020
- https://github.com/couchbase/couchbase-lite-ios/issues/1267

**Comment by Aksi0m** [comment]
@hideki Thanks for the quick response. This fix in iOS is exactly what we need, because we are using Cloudant. Is it possible to have this fix in the master branch as soon as possible? 

And also, ass reisub mentioned, it would be great for a later release to have access to the request setup so that we can configure it if needed.

Thank you very much for your time and effort.

**Comment by hideki** [comment]
We will port the fix in CBL iOS to CBL Java/Android as soon as possible.

About making `usePost` flag editable,  I created new ticket, https://github.com/couchbase/couchbase-lite-java-core/issues/1403 .

**Comment by hideki** [comment]
Hi @Aksi0m and @reisub,
In my PR (https://github.com/couchbase/couchbase-lite-java-core/pull/1405), I did not handle 401  HTTP Error (UNAUTHORIZED). Because 401 could be returned for true authentication error. If you will face to 401 issue, please create new ticket?
Thanks!

**Comment by hideki** [comment]
Hi @Aksi0m and @reisub,

I don't have Cloudant test environment. If you have time, could you please verify the fix?
You could install latest dev build from Couchbase custom maven repo. Version number is `1.3.1-26`.
http://files.couchbase.com/maven2/com/couchbase/lite/couchbase-lite-android/1.3.1-26/

How to setup custom maven repo.
https://github.com/couchbase/couchbase-lite-android#using-latest-official-release

Thanks!

**Comment by Aksi0m** [comment]
Hey @hideki I tried your fix but it does not work. I mean the logic for checking the forbidden response is good but the if statement before the forbidden check

`if (server == null || server.indexOf("CouchDB/1.0.2") == -1)// (Accurate as of 5/2016)
            return false;`

in my case is always true because my server string value from the response header is this 

> CouchDB/ad97a06 (Erlang OTP/17)

That is why I never get to the `response.code() == Status.FORBIDDEN`

**Comment by hideki** [comment]
Hi @Aksi0m,
Thank you for testing dev build. I will check with `CouchDB` instead of `CouchDB/1.0.2`.

**Comment by Aksi0m** [comment]
No problem @hideki 

Let me know when you merge it in your latest dev build.

**Comment by Aksi0m** [comment]
@hideki any news about merging the latest code into the dev branch?

**Comment by borrrden** [comment]
> especially since cloud providers since cloudant charge more for POST requests.

That's sneaky of them...

**Comment by hideki** [comment]
@Aksi0m 
Could you please retest with `1.3.1-28`?
http://files.couchbase.com/maven2/com/couchbase/lite/couchbase-lite-android/1.3.1-28/
Thanks!

**Comment by Aksi0m** [comment]
Hey @hideki it is working now! Thnx for the time, we apriciate it!

**Comment by hideki** [comment]
@Aksi0m Thank you for verifying the fix.

**Comment by AfzalivE** [comment]
Now POST requests time out with 500 instead of 401 or 405 or 403, and of course takes a while to timeout. Not sure if this change affects only the Cloudant version on Bluemix or normal Cloudant as well but I'm going to push a PR for #1403 anyway since I have to fix this to continue with fetching an existing user (instead of creating a new account) for our app.
