### ISSUE TITLE
CBLJava: unit tests fail on Windows: ManagerTest > testUpgradeDatabaseFrom110WithFakeTempDb

### ISSUE THREAD

**Issue by hideki** [couchbase/couchbase-lite-android#980]
```
com.couchbase.lite.ManagerTest > testUpgradeDatabaseFrom110WithFakeTempDb FAILED
    java.lang.RuntimeException at ManagerTest.java:808
```

**Comment by pasin** [comment]
I couldn't build forestDB storage engine on windows with VS 2013. Do I need VS 2015?

**Comment by pasin** [comment]
I can run the tests after I removed ForestDB dependencies and disabled forestDB tests. A couple of things:

- I could reproduce `testUpgradeDatabaseFrom110WithFakeTempDb` failed, but not `testDeleteView` failed. Probably`testDeleteView` might fail on ForestDB storage engine not SQLite storage engine.

- The reason that testUpgradeDatabaseFrom110WithFakeTempDb failed is that the tmp db doesn't get closed. I can submit a PR to fix the test.

**Comment by hideki** [comment]
To build forest db, you need latest Visual Studio which is downloadable from Microsoft web site.

**Comment by hideki** [comment]
`testDeleteView()` test failure is forestdb issue.

**Comment by hideki** [comment]
I will change this Ticket for `testUpgradeDatabaseFrom110WithFakeTempDb()` test failure. And I will create new ticket for `testDeleteView()` test failure.

**Comment by hideki** [comment]
Ticket for `testDeleteView()` test failure: https://github.com/couchbase/couchbase-lite-java-core/issues/1411
