### ISSUE TITLE
Gradle download error with 1.3.1-31

### ISSUE THREAD

**Issue by npomfret** [couchbase/couchbase-lite-android#995]
I tried upgrading to use http://latestbuilds.hq.couchbase.com/couchbase-lite-android/1.3.1/1.3.1-31/, but I'm just getting download errors from gradle:

`Could not find com.couchbase.lite:couchbase-lite-java-javascript:1.3.1-31.
`

Here's my deps:

    compile 'com.couchbase.lite:couchbase-lite-android:1.3.1-31'
    compile 'com.couchbase.lite:couchbase-lite-java-listener:1.3.1-31'
    compile 'com.couchbase.lite:couchbase-lite-java-javascript:1.3.1-31'

**Comment by hideki** [comment]
Hi @npomfret,
Build 1.3.1-31 is built for final release of 1.3.1.  Historically we don't add build number for release build. Instead of `1.3.1-31`, please use `1.3.1`. This is release build for 1.3.1. 
Thanks!
